#--------------------------------------------------
# SETUP
#--------------------------------------------------

include:
#  # Sanity pipeline
#  - project: tools/py/dev/package-tools
#    ref: v0.6.4
#    file: .gitlab/ci/pipelines/sanity.yml

  # Release pipeline
  - project: tools/py/dev/package-tools
    ref: v0.6.4
    file: .gitlab/ci/pipelines/release.yml

  # Package pipeline
  - project: tools/py/dev/package-tools
    ref: v0.6.4
    file: .gitlab/ci/pipelines/package.yml

  # Container pipeline
  - project: tools/py/dev/package-tools
    ref: v0.6.4
    file: .gitlab/ci/pipelines/container.yml

  # Local pipelines
  - local: .gitlab/ci/pipelines/*

variables:
  PYTHON: python3.10
  PACKAGE_TOOLS_VERSION: 0.6.4
  GITLAB_REPOSITORY_PASSWORD: "$CI_JOB_TOKEN"
  SILVERLIGHT_REPOSITORY_PASSWORD: "$SILVERLIGHT_PYPI_PASSWORD"
  NEXUS_REPOSITORY_PASSWORD: "$NEXUS_PYPI_PASSWORD"
  GITLAB_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"

stages:
  - validate
  - build
  - test
  - release
  - publish
