[project]
repo_url = "https://git.axelera.ai/ai-hw-team/pipewatch/pipewatch-server"
docs_url = "https://doc.axelera.ai/ai-hw-team/pipewatch/pipewatch-server"

[package]
version= "0.3.7"
package_name = "pipewatch-server"

[package.repositories.gitlab]
url = "https://git.axelera.ai/api/v4/projects/238/packages/pypi/"
username = "gitlab-ci-token"

[package.repositories.nexus]
url = "http://10.1.5.124/repository/pypi-axe/"
username = "pypi-axe"

[package.repositories.silverlight]
url = "http://silverlight-host-0-zrh:4532/"
username = "gitlab-runner"

[container.registries.gitlab]
url = "https://git.axelera.ai:5050/ai-hw-team/pipewatch/"
username = "gitlab-ci-token"

[release]
version_variables = [
    "pipewatch_server/api.py:__version__",
]

[docs]
landing_page = "user_guide"
macros_modules = [
    "mkdocs_macros_lib",
    "mkdocs_macros_local",
]

[envs.docs]
extra_dependencies = [
    "mkdocs-macros-lib >= 0.1, <= 0.2",
    "mkdocs-macros-helper >= 0.1, <= 0.2",
    "-e scripts/mkdocs-macros-local",
]

[envs.test]
extra_dependencies = [
    "-e ../pipewatch-lib",
]
