#!/usr/bin/env tclsh
#
# send tcl_cmd to velrun's TCL cmd server,
# requires ./run --server to be run beforehand

set tcl_cmd [lindex $argv 0]

proc tcl_cmd_send {host port tcl_cmd} {
  set s [socket $host $port]
  fconfigure $s -buffering line
  puts $s "$tcl_cmd"
  gets $s server_response
}

set grep_output [exec grep tcl_cmd_server run_tcl_server.tcl]
set tcl_cmd_server_port [lindex $grep_output  1]

tcl_cmd_send "localhost" $tcl_cmd_server_port $tcl_cmd
