# Configuration
IP_NAME            = iau
TOP_LEVEL_MODULES  = hdl_top
BENDER_MANI_LOC    = $(MAKEFILE_DIR)/../rtl

TESTNAME     ?= iau_standard_test
SEED         ?= 1
UVM          ?= 1
GUI          ?= 0
## Setting compilation time-out
SIM_COMPILE_TIME_MINUTES ?= 20

GLOBAL_DEFINES += +define+UVM_DISABLE_AUTO_ITEM_RECORDING
GLOBAL_DEFINES += +define+AXI_VIP
GLOBAL_DEFINES += +define+SYNOPSYS_SV
GLOBAL_DEFINES += +define+ASSERTIONS_ON
GLOBAL_DEFINES += +define+UVM
GLOBAL_DEFINES += +define+UVM_NO_DPI

# New for bender, as svt.uvm.pkg includes uvm pkg definition
GLOBAL_DEFINES += +define+SVT_EXCLUDE_METHODOLOGY_PKG_INCLUDE
GLOBAL_DEFINES += +define+SVT_UVM_12_OR_HIGHER
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ADDR_WIDTH=36
GLOBAL_DEFINES += +define+SVT_AXI_MAX_DATA_WIDTH=512
GLOBAL_DEFINES += +define+SVT_AXI_MAX_TDATA_WIDTH=2048
GLOBAL_DEFINES += +define+SVT_AXI_MAX_BURST_LENGTH_WIDTH=8
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ID_WIDTH=9
GLOBAL_DEFINES += +define+SVT_AXI_RESP_WIDTH=2
GLOBAL_DEFINES += +define+SVT_AXI_MAX_WRITE_RESP_REORDERING_DEPTH=8
GLOBAL_DEFINES += +define+SVT_AXI_MAX_STREAM_BURST_LENGTH=9999 #change because of tready_delay>10000; Its performanace degration
GLOBAL_DEFINES += +define+SVT_UVM_TECHNOLOGY

GLOBAL_DEFINES += +define+IAU_CSR_RAL

GLOBAL_DEFINES += +define+AIC_DP_CMD_GEN_COMMAND_DEPTH=1024
