#!/bin/bash

DIR=/scratch/workspace/ferguson/dwc_ap_lpddr5x_phy_sssf5a/ss3/phy/firmware/Latest/ate

declare -a arr=(
                "ddr_ate_dmem_bank0_ecc.txt"
                "ddr_ate_dmem_bank1_ecc.txt"
                "ddr_ate_dmem_bank2_ecc.txt"
                "ddr_ate_dmem_bank3_ecc.txt"
                "ddr_ate_imem_bank0_ecc.txt"
                "ddr_ate_imem_bank1_ecc.txt"
                )     

SZ=1536
rm -f ddr_ate_*
for i in "${arr[@]}"; do
    basename=${i%.*}
    echo "$basename is $(wc -l ${DIR}/${i}) long"
    cp ${DIR}/${i} .
    #imem images are not big enough for memories so pad out with random data
    if [[ "$i" =~ imem ]]; then
        python3 pad_file.py  $i
    else
        python3 convert_file.py  $i --type DCCM
    fi
    split -a 1 -d -l "$SZ" ${i} ${basename}_mem
    rm $i
    
done




