#RTL_NAME#
IP_NAME            = noc_top
#TB_NAME#
TOP_LEVEL_MODULES  = hdl_top
#TB_YML#
BENDER_MANI_LOC    = $(MAKEFILE_DIR)/../tb
#UVM_TESTNAME#
TESTNAME     ?= enoc_smoke_test
#UVM_SEED#
SEED         ?= 1
#UVM_EN#
UVM          ?= 1

#UVM#
GLOBAL_DEFINES += +define+UVM
GLOBAL_DEFINES += +define+AXI_VIP
GLOBAL_DEFINES += +define+UVM_NO_DPI
GLOBAL_DEFINES += +define+SYNOPSYS_SV
GLOBAL_DEFINES += +define+ASSERTIONS_ON
GLOBAL_DEFINES += +define+UVM_DISABLE_AUTO_ITEM_RECORDING
GLOBAL_DEFINES += +define+SVT_EXCLUDE_METHODOLOGY_PKG_INCLUDE
GLOBAL_DEFINES += +define+SVT_UVM_12_OR_HIGHER
#SNPS_AXI_VIP#
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ADDR_WIDTH=40
GLOBAL_DEFINES += +define+SVT_AXI_MAX_DATA_WIDTH=512
GLOBAL_DEFINES += +define+SVT_AXI_MAX_BURST_LENGTH_WIDTH=8
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ID_WIDTH=11
GLOBAL_DEFINES += +define+SVT_AXI_MAX_CACHE_WIDTH=4
GLOBAL_DEFINES += +define+SVT_AXI_CACHE_WIDTH=4
GLOBAL_DEFINES += +define+SVT_AXI_LOCK_WIDTH=1
GLOBAL_DEFINES += +define+SVT_AXI_MAX_PROT_WIDTH=3
GLOBAL_DEFINES += +define+SVT_AXI_RESP_WIDTH=2
GLOBAL_DEFINES += +define+SVT_AXI_MAX_WRITE_RESP_REORDERING_DEPTH=8
GLOBAL_DEFINES += +define+SVT_UVM_TECHNOLOGY
GLOBAL_DEFINES += +define+SVT_AXI_MAX_NUM_MASTERS_35
GLOBAL_DEFINES += +define+SVT_AXI_MAX_NUM_SLAVES_34
GLOBAL_DEFINES += +define+SVT_AXI_MAX_NUM_OUTSTANDING_XACT=512
#GLOBAL_DEFINES += +define+SVT_APB_PADDR_WIDTH=16
GLOBAL_DEFINES += +define+SVT_APB_MAX_ADDR_WIDTH=20
GLOBAL_DEFINES += +define+SVT_APB_MAX_DATA_WIDTH=32
GLOBAL_DEFINES += +define+SVT_APB_PWDATA_WIDTH=32
GLOBAL_DEFINES += +define+SVT_APB_MAX_NUM_SLAVES_1
GLOBAL_DEFINES += +define+SVT_APB_DISCONNECT_TOP_LEVEL_APB_IF_SIGNALS

