ifeq ($(DEBUG),1)
  export VERDI_ENHANCE_DYNAMIC_OBJECT
  export FSDB_ENABLE_CLASS=1
  export FSDB_ENABLE_EXPAND_CLASS=1
  export FSDB_VARIANT_SIZE_ARRAY=1
  VCS_ELAB_OPTS_EXT += -debug_access+all
  VCS_VLOGAN_OPTS_EXT += +define+UVM_VERDI_COMPWAVE
  VCS_RUN_OPTS_EXT += +UVM_VERDI_TRACE=" HIER+COMPWAVE"
endif

