
# Configuration
IP_NAME            = l2_p
TOP_LEVEL_MODULES  = hdl_top
BENDER_MANI_LOC    = $(REPO_ROOT)/hw/ip/l2/default/dv/rtl
BENDER_TARGETS_EXT  = asic
BENDER_TARGETS_EXT += sf5a

TESTNAME     ?= l2_axi_sanity_test
SEED         ?= 1
UVM          ?= 1

GLOBAL_DEFINES += +define+UVM_DISABLE_AUTO_ITEM_RECORDING
GLOBAL_DEFINES += +define+AXI_VIP
GLOBAL_DEFINES += +define+APB_VIP
GLOBAL_DEFINES += +define+SYNOPSYS_SV
GLOBAL_DEFINES += +define+UVM

GLOBAL_DEFINES += +define+SVT_APB_MAX_ADDR_WIDTH=40
GLOBAL_DEFINES += +define+SVT_APB_MAX_DATA_WIDTH=32
GLOBAL_DEFINES += +define+SVT_APB_MAX_NUM_SLAVES_1
GLOBAL_DEFINES += +define+SVT_APB_PWDATA_WIDTH=32

# New for bender, as svt.uvm.pkg includes uvm pkg definition
GLOBAL_DEFINES += +define+SVT_EXCLUDE_METHODOLOGY_PKG_INCLUDE
GLOBAL_DEFINES += +define+SVT_UVM_12_OR_HIGHER
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ADDR_WIDTH=40
GLOBAL_DEFINES += +define+SVT_AXI_MAX_DATA_WIDTH=512
GLOBAL_DEFINES += +define+SVT_AXI_MAX_BURST_LENGTH_WIDTH=8
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ID_WIDTH=9 #TODO CHECK
GLOBAL_DEFINES += +define+SVT_AXI_RESP_WIDTH=2
GLOBAL_DEFINES += +define+SVT_AXI_MAX_WRITE_RESP_REORDERING_DEPTH=8
GLOBAL_DEFINES += +define+SVT_AXI_MAX_SLAVES=1
GLOBAL_DEFINES += +define+SVT_UVM_TECHNOLOGY
GLOBAL_DEFINES += +define+SVT_AXI_ACE_SNPS_INTERNAL_SYSTEM_MONITOR_USE_MASTER_SLAVE_AGENT_CONNECTION
GLOBAL_DEFINES += +define+UVM_NO_DPI

# reduces verbosity in sf5a mem cells
GLOBAL_DEFINES += +define+BACKDOOR_DISPLAY_OFF
