#ifndef EMMC_COMMANDS_H
#define EMMC_COMMANDS_H

#include <std/std_bit.h>

#define CMD6_ACCESS_CMD_SET 0
#define CMD6_ACCESS_BITS_SET 1
#define CMD6_ACCESS_BITS_CLEAR 2
#define CMD6_ACCESS_BYTE_WRITE 3
#define CMD6_ACCESS_OFFSET 24
#define CMD6_ACCESS_WIDTH 2
#define CMD6_INDEX_OFFSET 16
#define CMD6_INDEX_WIDTH 8
#define CMD6_VALUE_OFFSET 8
#define CMD6_VALUE_WIDTH 8

#endif
