#ifndef EMMC_PHY_H
#define EMMC_PHY_H

#include <std/std_bit.h>

#define PHY_DQ_TIMING_REG 0x2000
#define DATA_SELECT_OE_END_OFFSET 0
#define DATA_SELECT_OE_END_WIDTH 3
#define IO_MASK_END_OFFSET 27
#define IO_MASK_END_WIDTH 3
#define IO_MASK_START_OFFSET 24
#define IO_MASK_START_WIDTH 3
#define IO_MASK_ALWAYS_ON STD_BIT32(31)

#define PHY_DQS_TIMING_REG 0x2004
#define USE_PHONY_DQS_CMD STD_BIT32(19)
#define USE_PHONY_DQS STD_BIT32(20)
#define USE_LPBK_DQS STD_BIT32(21)
#define USE_EXT_LPBK_DQS STD_BIT32(22)

#define PHY_GATE_LPBK_CTRL_REG 0x2008
#define GATE_CFG_ALWAYS_ON STD_BIT32(6)
#define UNDERRUN_SUPPRESS STD_BIT32(18)
#define SYNC_METHOD STD_BIT32(31)
#define RD_DEL_SEL_OFFSET 19
#define RD_DEL_SEL_WIDTH 5

#define PHY_DLL_MASTER_CTRL_REG 0x200C
#define PARAM_DLL_BYPASS_MODE STD_BIT32(23)
#define PARAM_DLL_START_POINT_OFFSET 0
#define PARAM_DLL_START_POINT_WIDTH 8
#define PARAM_PHASE_DETECT_SEL_OFFSET 20
#define PARAM_PHASE_DETECT_SEL_WIDTH 3

#define PHY_DLL_SLAVE_CTRL_REG 0x2010
#define READ_DQS_CMD_DELAY_OFFSET 24
#define READ_DQS_CMD_DELAY_WIDTH 8
#define CLK_WR_DELAY_OFFSET 8
#define CLK_WR_DELAY_WIDTH 8
#define READ_DQS_DELAY_OFFSET 0
#define READ_DQS_DELAY_WIDTH 8

#define PHY_OBS_REG_0 0x2018

#define PHY_DLL_OBS_REG_0 0x201C
#define DLL_LOCKED_MODE 1

#define PHY_DLL_CTRL_REG 0x2080
#define LOW_FREQ_SEL 20
#define SDR_DQS_VALUE 14
#define PHONY_DQS_TIMING_OFFSET 4
#define PHONY_DQS_TIMING_WIDTH 5
#define CTRL_CLKPERIOD_DELAY 0

#define PHY_DLL_TSEL_REG 0x2084
#define TSEL_OFF_VALUE_DATA 20
#define TSEL_RD_VALUE_DATA 16
#define TSEL_OFF_VALUE_DQS 12
#define TSEL_RD_VALUE_DQS 8

#endif
