#ifndef EMMC_CARD_REGS_H
#define EMMC_CARD_REGS_H

#include <std/std_bit.h>

#define OCR_2_7_3_6_V_OFFSET 15
#define OCR_2_7_3_6_V_WIDTH 9
#define OCR_1_7_1_95_V STD_BIT32(7)
#define OCR_ACCESS_MODE_OFFSET 29
#define OCR_ACCESS_MODE_WIDTH 2
#define OCR_CARD_POWER_UP STD_BIT32(31)

#define STATUS_ADDRESS_OUT_OF_RANGE STD_BIT32(31)
#define STATUS_ADDRESS_MISALIGN STD_BIT32(30)
#define STATUS_ADDRESS_BLOCK_EN_ERROR STD_BIT32(29)
#define STATUS_ERASE_SEQ_ERROR STD_BIT32(28)
#define STATUS_ERASE_PARAM STD_BIT32(27)
#define STATUS_WP_VIOLATION STD_BIT32(26)
#define STATUS_CARD_IS_LOCKED STD_BIT32(25)
#define STATUS_LOCK_UNLOCK_FAILED STD_BIT32(24)
#define STATUS_COM_CRC_ERROR STD_BIT32(23)
#define STATUS_ILLEGAL_COMMAND STD_BIT32(22)
#define STATUS_CARD_ECC_FAILED STD_BIT32(21)
#define STATUS_CC_ERROR STD_BIT32(20)
#define STATUS_ERROR STD_BIT32(19)
#define STATUS_UNDERRUN STD_BIT32(18)
#define STATUS_OVERRUN STD_BIT32(17)
#define STATUS_CID_CSD_OVERWITE STD_BIT32(16)
#define STATUS_SWITCH_ERROR STD_BIT32(7)

#define STATUS_ERRORS                                                          \
  (STATUS_ADDRESS_OUT_OF_RANGE | STATUS_ADDRESS_MISALIGN |                     \
   STATUS_ADDRESS_BLOCK_EN_ERROR | STATUS_ERASE_SEQ_ERROR |                    \
   STATUS_ERASE_PARAM | STATUS_WP_VIOLATION | STATUS_CARD_IS_LOCKED |          \
   STATUS_LOCK_UNLOCK_FAILED | STATUS_COM_CRC_ERROR | STATUS_ILLEGAL_COMMAND | \
   STATUS_CARD_ECC_FAILED | STATUS_CC_ERROR | STATUS_ERROR | STATUS_UNDERRUN | \
   STATUS_OVERRUN | STATUS_CID_CSD_OVERWITE | STATUS_SWITCH_ERROR)

#define EXT_CSD_BUS_WIDTH_OFFSET 183
#define EXT_CSD_BUS_WIDTH_1_BIT 0
#define EXT_CSD_BUS_WIDTH_4_BIT 1
#define EXT_CSD_BUS_WIDTH_8_BIT 2
#define EXT_CSD_BUS_WIDTH_4_BIT_DDR 5
#define EXT_CSD_BUS_WIDTH_8_BIT_DDR 6
#define EXT_CSD_BUS_WIDTH_ENHANCED_STROBE 0x80

#define EXT_CSD_HS_TIMING_OFFSET 185
#define EXT_CSD_HS_TIMING_SDR 0
#define EXT_CSD_HS_TIMING_HS 1
#define EXT_CSD_HS_TIMING_HS200 2
#define EXT_CSD_HS_TIMING_HS400 3

#define EXT_CSD_SIZE_BYTE 512 // bytes
#define EXT_CSD_SIZE_UI32 64

#endif
