#*****************************************************************************
#
# This file was automatically generated by coreAssembler (version V-2023.12-1).
#
# FILENAME : soc_periph_dw_peripherals_simple.tcl
# DATE :     May 30, 2024
# ABSTRACT : 
#            Script generated by write_batch_script.  This script
#            was used to capture the coreAssembler workspace 'soc_periph_dw_peripherals'.
#            The command line was:
#                 write_batch_script -include -create_workspace -assembly -activities soc_periph_dw_peripherals_simple.tcl
#
# LICENSES AUTHORIZED: coreAssembler DesignWare-Foundation DWC-AMBA-Fabric-Source DWC-APB-Advanced-Source DWC-APB-Periph-Source
#
#
#*****************************************************************************


create_workspace -design soc_periph_dw_peripherals -name soc_periph_dw_peripherals
set_design_attribute SpiritName design_soc_dw_peripherals
set_design_attribute SpiritVendor ThirdParty
set_design_attribute SpiritLibrary ThirdParty
set_design_attribute SpiritVersion 1.0
set_workspace_options -batch

set_activity_parameter SpecifySubsystem SearchPath "/home/projects/dware/DESIGNWARE_HOME/iip/latest $::synopsys_root/auxx/dware/glue"
set_current_component

instantiate_component {Synopsys DesignWareLibrary DW_apb_ssi 4.03a} -name soc_periph_dw_ssi -noauto
   set_configuration_parameter -component soc_periph_dw_ssi SSI_INTR_POL 1

instantiate_component {Synopsys DesignWareLibrary DW_apb_gpio 2.14a} -name soc_periph_dw_gpio -noauto -noexport
   set_configuration_parameter -component soc_periph_dw_gpio GPIO_INTR_IO 1
   set_configuration_parameter -component soc_periph_dw_gpio GPIO_INT_POL 1
   set_configuration_parameter -component soc_periph_dw_gpio GPIO_PWIDTH_A 16

instantiate_component {Synopsys DesignWareLibrary DW_apb_i2c 2.03a} -name soc_periph_dw_i2c_0 -noauto

instantiate_component {Synopsys DesignWareLibrary DW_apb_uart 4.03a} -name soc_periph_dw_uart -noauto -noexport

instantiate_component {Synopsys DesignWareLibrary DW_axi_x2p 2.04a} -name soc_periph_dw_axi -noauto -noexport

instantiate_component {Synopsys DesignWareLibrary DW_apb_i2c 2.03a} -name soc_periph_dw_i2c_1 -noauto

instantiate_component {Synopsys DesignWareLibrary DW_apb_timers 2.13a} -name soc_periph_dw_timers -noauto
set_current_component /

set instance [export_interface -noauto -name PRESETn -component soc_periph_dw_gpio -interface PRESETn -format %e_%p]

set instance [export_interface -noauto -name apb_gpio_api -component soc_periph_dw_gpio -interface DW_apb_gpio-API -format %e_%p]

set instance [export_interface -noauto -name SIO -component soc_periph_dw_uart -interface SIO -format %e_%p]

set instance [export_interface -noauto -name PCLK -component soc_periph_dw_uart -interface PCLK -format %e_%p]

set instance [export_interface -noauto -name slave0_soc_periph_dw_axi_ACLK -component soc_periph_dw_axi -interface ACLK -format %e_%p]

set instance [export_interface -noauto -name slave0_soc_periph_dw_axi_ARESETn -component soc_periph_dw_axi -interface ARESETn -format %e_%p]

set instance [export_interface -noauto -name lt_axi_s -component soc_periph_dw_axi -interface AXI_Slave -format %e_%p]
set_interface_attribute $instance MinConsumers 1

set instance [export_interface -noauto -name apb_cfg_padctrl -component soc_periph_dw_axi -interface APB_Slave -format %e_%p]
set_interface_port_attribute $instance \
    paddr BusAlignment right
set_interface_port_attribute $instance \
    pprot InterfaceLink <open>
set_interface_port_attribute $instance \
    pstrb InterfaceLink <open>

set instance [export_interface -noauto -name apb_cfg_emmc -component soc_periph_dw_axi -interface APB_Slave -format %e_%p]
set_interface_port_attribute $instance \
    paddr BusAlignment right
set_interface_port_attribute $instance \
    pprot InterfaceLink <open>
set_interface_port_attribute $instance \
    pstrb InterfaceLink <open>

connect_interface -from_interface PCLK -to_component soc_periph_dw_axi -to_interface PCLK
connect_interface -from_interface PCLK -to_component soc_periph_dw_gpio -to_interface PCLK
connect_interface -from_interface PCLK -to_component soc_periph_dw_i2c_0 -to_interface PCLK
connect_interface -from_interface PCLK -to_component soc_periph_dw_i2c_1 -to_interface PCLK
connect_interface -from_interface PCLK -to_component soc_periph_dw_ssi -to_interface PCLK
connect_interface -from_interface PCLK -to_component soc_periph_dw_timers -to_interface PCLK
connect_interface -from_interface PRESETn -to_component soc_periph_dw_axi -to_interface PRESETn
connect_interface -from_interface PRESETn -to_component soc_periph_dw_i2c_0 -to_interface PRESETn
connect_interface -from_interface PRESETn -to_component soc_periph_dw_i2c_1 -to_interface PRESETn
connect_interface -from_interface PRESETn -to_component soc_periph_dw_ssi -to_interface PRESETn
connect_interface -from_interface PRESETn -to_component soc_periph_dw_timers -to_interface PRESETn
connect_interface -from_interface PRESETn -to_component soc_periph_dw_uart -to_interface PRESETn
connect_interface -from_component soc_periph_dw_axi -from_interface APB_Slave -to_component soc_periph_dw_gpio -to_interface APB_Slave
connect_interface -from_component soc_periph_dw_axi -from_interface APB_Slave -to_component soc_periph_dw_i2c_0 -to_interface APB_Slave
connect_interface -from_component soc_periph_dw_axi -from_interface APB_Slave -to_component soc_periph_dw_i2c_1 -to_interface APB_Slave
connect_interface -from_component soc_periph_dw_axi -from_interface APB_Slave -to_component soc_periph_dw_ssi -to_interface APB_Slave
connect_interface -from_component soc_periph_dw_axi -from_interface APB_Slave -to_component soc_periph_dw_timers -to_interface APB_Slave
connect_interface -from_component soc_periph_dw_axi -from_interface APB_Slave -to_component soc_periph_dw_uart -to_interface APB_Slave

set_interface_parameter apb_cfg_emmc APB3 1 -instance
set_interface_parameter apb_cfg_padctrl APB3 1 -instance
set_interface_parameter lt_axi_s axi_interface_type 1 -instance
set_interface_parameter lt_axi_s axi_dw 64 -instance
set_interface_parameter lt_axi_s axi_blw 8 -instance
set_interface_parameter soc_periph_dw_i2c_0/APB_Slave APB4 1 -instance
set_interface_parameter soc_periph_dw_i2c_1/APB_Slave APB4 1 -instance
set_interface_parameter soc_periph_dw_ssi/APB_Slave APB4 1 -instance
set_interface_parameter soc_periph_dw_timers/APB_Slave APB4 1 -instance
set_interface_parameter soc_periph_dw_uart/APB_Slave APB4 1 -instance

autoconnect_interfaces
set_interface_attribute soc_periph_dw_gpio/APB_Slave SlotOrder 0
set_interface_attribute soc_periph_dw_i2c_0/APB_Slave SlotOrder 1
set_interface_attribute soc_periph_dw_ssi/APB_Slave SlotOrder 2
set_interface_attribute soc_periph_dw_i2c_1/APB_Slave SlotOrder 3
set_interface_attribute soc_periph_dw_uart/APB_Slave SlotOrder 4
set_interface_attribute soc_periph_dw_timers/APB_Slave SlotOrder 5
set_interface_attribute apb_cfg_padctrl SlotOrder 6
set_interface_attribute apb_cfg_emmc SlotOrder 7

set_slave_base_address -component soc_periph_dw_gpio -interface APB_Slave -range 0x10000
set_slave_base_address -component soc_periph_dw_gpio -interface APB_Slave -address 0x3030000 
set_slave_base_address -component soc_periph_dw_i2c_0 -interface APB_Slave -range 0x10000
set_slave_base_address -component soc_periph_dw_i2c_0 -interface APB_Slave -address 0x3010000 
set_slave_base_address -component soc_periph_dw_ssi -interface APB_Slave -range 0x10000
set_slave_base_address -component soc_periph_dw_ssi -interface APB_Slave -address 0x3040000 
set_slave_base_address -component soc_periph_dw_i2c_1 -interface APB_Slave -range 0x10000
set_slave_base_address -component soc_periph_dw_i2c_1 -interface APB_Slave -address 0x3020000 
set_slave_base_address -component soc_periph_dw_uart -interface APB_Slave -range 0x10000
set_slave_base_address -component soc_periph_dw_uart -interface APB_Slave -address 0x3060000 
set_slave_base_address -component soc_periph_dw_timers -interface APB_Slave -range 0x10000
set_slave_base_address -component soc_periph_dw_timers -interface APB_Slave -address 0x3070000 
set_slave_base_address -interface apb_cfg_padctrl -range 0x10000
set_slave_base_address -interface apb_cfg_padctrl -address 0x3000000 
set_slave_base_address -interface apb_cfg_emmc -range 0x10000
set_slave_base_address -interface apb_cfg_emmc -address 0x3050000 


set_configuration_parameter -component soc_periph_dw_ssi SSI_NUM_SLAVES 4
set_configuration_parameter -component soc_periph_dw_ssi SSI_SPI_MODE 2
set_configuration_parameter -component soc_periph_dw_gpio GPIO_NUM_PORTS 1
set_configuration_parameter -component soc_periph_dw_i2c_0 IC_SMBUS 0x1
set_configuration_parameter -component soc_periph_dw_uart AFCE_MODE 0x1
set_configuration_parameter -component soc_periph_dw_i2c_1 IC_SMBUS 0x1
autocomplete_activity SpecifySubsystem
set_current_component /
create_connection -constant open soc_periph_dw_i2c_0/debug_wr
create_connection -constant open {{soc_periph_dw_i2c_0/debug_slv_cstate[3:0]} soc_periph_dw_i2c_0/debug_slave_act soc_periph_dw_i2c_0/debug_s_gen soc_periph_dw_i2c_0/debug_rd soc_periph_dw_i2c_0/debug_p_gen {soc_periph_dw_i2c_0/debug_mst_cstate[4:0]} soc_periph_dw_i2c_0/debug_master_act soc_periph_dw_i2c_0/debug_data soc_periph_dw_i2c_0/debug_hs soc_periph_dw_i2c_0/debug_addr_10bit soc_periph_dw_i2c_0/debug_addr}
create_connection -constant open soc_periph_dw_i2c_0/ic_en
create_connection -constant open {soc_periph_dw_i2c_1/debug_wr {soc_periph_dw_i2c_1/debug_slv_cstate[3:0]} soc_periph_dw_i2c_1/debug_slave_act soc_periph_dw_i2c_1/debug_s_gen soc_periph_dw_i2c_1/debug_rd soc_periph_dw_i2c_1/debug_p_gen {soc_periph_dw_i2c_1/debug_mst_cstate[4:0]} soc_periph_dw_i2c_1/debug_master_act soc_periph_dw_i2c_1/debug_hs soc_periph_dw_i2c_1/debug_data soc_periph_dw_i2c_1/debug_addr_10bit soc_periph_dw_i2c_1/debug_addr soc_periph_dw_i2c_1/ic_en}
create_connection -constant open soc_periph_dw_ssi/ssi_busy
create_connection -constant open soc_periph_dw_ssi/ssi_sleep
create_connection -constant open {soc_periph_dw_uart/out2_n soc_periph_dw_uart/out1_n soc_periph_dw_uart/dma_tx_req_n soc_periph_dw_uart/dma_rx_req_n soc_periph_dw_uart/dtr_n soc_periph_dw_uart/baudout_n}
create_connection -constant open {soc_periph_dw_uart/rxrdy_n soc_periph_dw_uart/txrdy_n}
autocomplete_activity CompleteConnections

autocomplete_activity  GenerateSubsystemRTL
set_tool_root rtl_shell -root /opt/synopsys/rtla/V-2023.12 -64bit
set_tool_root verdi -root /opt/synopsys/verdi/S-2021.09-SP1-1 -64bit
set_tool_root fm_shell -root /opt/synopsys/fm/Q-2019.12-SP2 -64bit
set_tool_root tmax -root /opt/synopsys/testmax/S-2021.06-SP4 -64bit
set_tool_root vcs -root /opt/synopsys/vcs/S-2021.09-SP1-1
set_tool_root dc_shell -root /opt/synopsys/syn2/S-2021.06-SP1 -64bit
set_tool_root vsim -root /opt/mentor/questa_sim-2023.2_1/questasim
set_tool_root vcstatic -root /opt/synopsys/vc_static/S-2021.09-SP2-4 -64bit
set_tool_root vcsi -root /opt/synopsys/vcs/S-2021.09-SP1-1


set_current_component /soc_periph_dw_axi
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.81
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /soc_periph_dw_gpio
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.675
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /soc_periph_dw_i2c_0
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.675
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /soc_periph_dw_i2c_1
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.675
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /soc_periph_dw_ssi
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.675
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /soc_periph_dw_timers
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.675
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /soc_periph_dw_uart
set_upf_voltage -state SINGLE_DOMAIN_ON -supply SINGLE_DOMAIN.primary {0.81}
set_upf_voltage -state SINGLE_DOMAIN_GND -supply SINGLE_DOMAIN.primary {0}
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.power -mode max 0.675
set_upf_supply_voltage -supply SINGLE_DOMAIN.primary.ground -mode max 0
set_current_component /

set_strategy_parameter Design_Compiler_Reference_Methodology WriteSDF 1

set_activity_parameter Synthesize DcThroughPathReport 0
set_activity_parameter Synthesize DcRegisteredIOReport 0
set_activity_parameter Synthesize DcSetupReport 0
set_activity_parameter Synthesize DcConstraintReport 0
set_activity_parameter Synthesize DcShortIoTimingReport 0
set_activity_parameter Synthesize DcLongIoTimingReport 0
set_activity_parameter Synthesize DcHierarchyReport 0
set_activity_parameter Synthesize DcResourcesReport 0





























