####################
# Common Setup.

export SIM_DIR ?= $(shell pwd)
export WORK_DIR ?= $(shell pwd)/work
export TOP_DIR ?= $(shell pwd)/../../verification_ip/top_env_pkg
export BASE_DIR ?= $(shell pwd)/../../../lpddr_blk

####################
# Questa support.

include $(SIM_DIR)/script/lpddr_subsystem_defines.make
include $(SIM_DIR)/script/lpddr_subsystem_cond_defines.make
include $(SIM_DIR)/script/lpddr_subsystem_targets.make
