#!/usr/bin/env bash

set -e

VENV=.venv/memorybist_spec

make -C $REPO_ROOT/bin venv VENV=$VENV FILE=$REPO_ROOT/hw/impl/europa/blocks/pve_l1/dft/insertion/memory_test/scripts/python-requirements.txt > /dev/null 2>&1

source $REPO_ROOT/bin/$VENV/bin/activate
python3.10 $REPO_ROOT/hw/impl/europa/blocks/pve_l1/dft/insertion/memory_test/scripts/gen_memorybist_spec.py $@
deactivate
