# Configuration
IP_NAME            = aicore_infra
TOP_LEVEL_MODULES  = hdl_top
BENDER_MANI_LOC    = $(MAKEFILE_DIR)/../rtl

TESTNAME     ?= ai_core_infra_base_test
SEED         ?= 1
UVM          ?= 1

## Setting compilation time-out
SIM_COMPILE_TIME_MINUTES ?= 20

# UVM options
GLOBAL_DEFINES += +define+UVM_NO_DPI
GLOBAL_DEFINES += +define+UVM_NO_DEPRECATED
GLOBAL_DEFINES += +define+UVM_DISABLE_AUTO_ITEM_RECORDING

# Include the AXI_VIP defines
GLOBAL_DEFINES += +define+AXI_VIP
GLOBAL_DEFINES += +define+SYNOPSYS_SV


# New for bender, as svt.uvm.pkg includes uvm pkg definition
GLOBAL_DEFINES += +define+SVT_EXCLUDE_METHODOLOGY_PKG_INCLUDE
GLOBAL_DEFINES += +define+SVT_UVM_12_OR_HIGHER
GLOBAL_DEFINES += +define+SVT_UVM_TECHNOLOGY
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ADDR_WIDTH=40
GLOBAL_DEFINES += +define+SVT_AXI_MAX_DATA_WIDTH=512
GLOBAL_DEFINES += +define+SVT_AXI_MAX_BURST_LENGTH_WIDTH=8
GLOBAL_DEFINES += +define+SVT_AXI_SIZE_WIDTH=4
GLOBAL_DEFINES += +define+SVT_AXI_MAX_ID_WIDTH=9
GLOBAL_DEFINES += +define+SVT_AXI_BURST_WIDTH=2

GLOBAL_DEFINES += +define+SVT_AXI_CACHE_WIDTH=4
GLOBAL_DEFINES += +define+SVT_AXI_QOS_WIDTH=4
GLOBAL_DEFINES += +define+SVT_AXI_LOCK_WIDTH=1
GLOBAL_DEFINES += +define+SVT_MEM_ENABLE_INTERNAL_MESSAGING

GLOBAL_DEFINES += +define+SVT_AXI_RESP_WIDTH=2
GLOBAL_DEFINES += +define+SVT_AXI_MAX_WRITE_RESP_REORDERING_DEPTH=8
GLOBAL_DEFINES += +define+SVT_AXI_MAX_SLAVES=0
GLOBAL_DEFINES += +define+SVT_AXI_ACE_SNPS_INTERNAL_SYSTEM_MONITOR_USE_MASTER_SLAVE_AGENT_CONNECTION

GLOBAL_DEFINES += +define+ASSERTIONS_ON
