/*****************************************************************************
 *
 *
 *                    (C) COPYRIGHT 2022 SYNOPSYS, INC.
 *                            ALL RIGHTS RESERVED
 *
 * This software and the associated  documentation are proprietary to 
 * Synopsys, Inc. This software may only be used in accordance with the terms 
 * and conditions of a written license agreement with Synopsys, Inc. All other
 * use, reproduction, or distribution of this software is strictly prohibited.
 *
 * The entire notice above must be reproduced on all authorized copies.
 *
 *****************************************************************************/

#ifndef SNPSDDRDEFINES_DWC_DDRPHY_VDEFINES_H
#define SNPSDDRDEFINES_DWC_DDRPHY_VDEFINES_H

#ifdef	__cplusplus
extern "C" {
#endif

/*************************************************************************
 * T Y P E D E F S    &    D E F I N E S
 *************************************************************************/


//Autogenerated from /home/rodrigo.borges/workspace/hw/europa_cinit_ss4/sw/scripts/lpddr/synopsys/sim/testbench/macros/dwc_ddrphy_VDEFINES.v
#define DWC_PUB_RID_GE230
#define DWC_PUB_RID_GE210
#define DWC_PUB_RID_GE0090
#define DWC_PUB_RID_GT101
#define DWC_PHYINIT_RID_GE101
#define DWC_PHYINIT_RID_GE103
#define DWC_PHYINIT_RID_GE111
#define DWC_PHYINIT_RID_GE121
#define DWC_PHYINIT_RID_GE200
#define DWC_PHYINIT_RID_GE122
#define DWC_PHYINIT_RID_GT201707
#define DWC_PHYINIT_RID_GE201707
#define DWC_PHYINIT_RID_GE201705
#define DWC_PHYINIT_RID_GE201709
#define DWC_PHYINIT_RID_GE201711
#define DWC_PHYINIT_RID_GT201807
#define DWC_PHYINIT_RID_GE201904
#define DWC_PHYINIT_RID_GE202001
#define DWC_PHYINIT_RID_GE202009
#define DWC_PHYINIT_RID_GE202212
#define DWC_PHYINIT_RID_GE202307
#define DWC_PHYINIT_RID_GE202310
#define DWC_LPDDR5XPHY_TOP_PG_PINS
#define DWC_LPDDR5XPHY_TOP_PG_PINS
#define DWC_LPDDR5XPHY_PG_PINS
#define DWC_LPDDR5XPHY_PG_PINS
#define LPDDR5X4_PHY
#define DWC_LPDDR5XPHY_NUM_CHANNELS  2
#define DWC_LPDDR5XPHY_NUM_CHANNELS_2
#define DWC_LPDDR5XPHY_NUM_CHANNELS_2
#define DWC_LPDDR5XPHY_EXISTS_AC0
#define DWC_LPDDR5XPHY_EXISTS_AC1
#define DWC_LPDDR5XPHY_NUM_RANKS  2
#define DWC_LPDDR5XPHY_NUM_RANKS_2
#define DWC_LPDDR5XPHY_NUM_DBYTES_PER_CHANNEL  2
#define DWC_LPDDR5XPHY_NUM_DBYTES_PER_CHANNEL_2
#define DWC_LPDDR5XPHY_NUM_DBYTES  4
#define DWC_LPDDR5XPHY_NUM_DBYTES_4
#define DWC_LPDDR5XPHY_EXISTS_DB0
#define DWC_LPDDR5XPHY_EXISTS_DB1
#define DWC_LPDDR5XPHY_EXISTS_DB2
#define DWC_LPDDR5XPHY_EXISTS_DB3
#define DWC_LPDDR5XPHY_DBYTE_DMI_ENABLED
#define DWC_LPDDR5XPHY_LPDDR5_ENABLED
#define DWC_LPDDR5XPHY__LPDDR5_ENABLE  1
#define DWC_LPDDR5XPHY__DTO_ENABLE  0
#define DWC_LPDDR5XPHY_NUM_TOP_SCAN_CHAINS  1368
#define DWC_LPDDR5XPHY_PIPE_DFI_WR  1
#define DWC_LPDDR5XPHY_PIPE_DFI_RD  1
#define DWC_LPDDR5XPHY_PIPE_DFI_MISC  1
#define DWC_LPDDR5XPHY_TOP_PG_PINS
#define DWC_LPDDR5XPHY_PG_PINS
#define DWC_LPDDR5XPHY_CUST_PHYREV  0x0
#define DWC_LPDDR5XPHY_CUST_PUBREV  0x0
#define DWC_LPDDR5XPHY_PUB_RID  0x230
#define DWC_LPDDR5XPHY_PUB_VAR  0xffff
#ifdef DWC_LPDDR5XPHY_TECH__CDCBUF__DISABLE_BEHAVIORAL_VERILOG
#define DWC_LPDDR5XPHY_TECH__CDCBUF__DISABLE_DSTCLK
#endif
#define DWC_LPDDR5XPHY_DERIVED_DEFINES

/*************************************************************************
 * G L O B A L    V A R I A B L E S
 *************************************************************************/

/*************************************************************************
 * F U N C T I O N    P R O T O T Y P E S
 *************************************************************************/


#ifdef	__cplusplus
}
#endif

#endif	/* SNPSDDRDEFINES_DWC_DDRPHY_VDEFINES_H */
