databases:
  - name: top_light_veloce
    location: hw/impl/europa/emulation/output_top_light/coverage_veloce/tcl_server.ucdb
    inst_path: hdl_top/i_europa/u_aipu/u_soc_periph_p
    move_inside: /top
    delete: 
      - hdl_top
      - /top/u_soc_periph_p/u_pctl
      - /top/u_soc_periph_p/u_ao_csr_padctrl
      - /top/u_soc_periph_p/u_soc_periph/u_emmc
      - /top/u_soc_periph_p/u_soc_periph/u_sram_cfg
      - /top/u_soc_periph_p/u_soc_periph/u_uart_tx_ram
      - /top/u_soc_periph_p/u_soc_periph/u_uart_rx_ram

  - name: top_light_sim
    location: hw/impl/europa/dv/top_light/build_vsim_europa_top/coverage_vsim/coverage.ucdb
    inst_path: sim_top/i_hdl_top/i_europa/u_aipu/u_soc_periph_p
    move_inside: /top
    delete:
      - sim_top
      - /top/u_soc_periph_p/u_pctl
      - /top/u_soc_periph_p/u_ao_csr_padctrl

  - name: soc_periph_spike
    location: hw/impl/europa/blocks/soc_periph/dv/spike_tb/sim/build_vsim_spike_top_test/coverage_vsim/coverage.ucdb
    inst_path: spike_top_tb/th/u_soc_periph_p
    move_inside: /top
    delete:
      - spike_top_tb
      - /top/u_soc_periph_p/u_pctl
      - /top/u_soc_periph_p/u_ao_csr_padctrl
      - /top/u_soc_periph_p/u_soc_periph/u_emmc
      - /top/u_soc_periph_p/u_soc_periph/u_sram_cfg
      - /top/u_soc_periph_p/u_soc_periph/u_uart_tx_ram
      - /top/u_soc_periph_p/u_soc_periph/u_uart_rx_ram

  - name: soc_periph_axi
    location: hw/impl/europa/blocks/soc_periph/dv/axi_tb/sim/build_vsim_axi_stress_top_test/coverage_vsim/coverage.ucdb
    inst_path: axi_stress_top_tb/th/u_soc_periph_p
    move_inside: /top
    delete:
      - axi_stress_top_tb
      - /top/u_soc_periph_p/u_pctl
      - /top/u_soc_periph_p/u_ao_csr_padctrl
      - /top/u_soc_periph_p/u_soc_periph/u_emmc
      - /top/u_soc_periph_p/u_soc_periph/u_sram_cfg
      - /top/u_soc_periph_p/u_soc_periph/u_uart_tx_ram
      - /top/u_soc_periph_p/u_soc_periph/u_uart_rx_ram
      - /top/u_soc_periph_p/u_soc_periph/u_peripherals/soc_periph_dw_gpio/gpio_apb_if
      - /top/u_soc_periph_p/u_soc_periph/u_peripherals/soc_periph_dw_i2c_0/i2c_0_apb_if
      - /top/u_soc_periph_p/u_soc_periph/u_peripherals/soc_periph_dw_i2c_1/i2c_1_apb_if
      - /top/u_soc_periph_p/u_soc_periph/u_peripherals/soc_periph_dw_ssi/ssi_apb_if
      - /top/u_soc_periph_p/u_soc_periph/u_peripherals/soc_periph_dw_timers/timers_apb_if
      - /top/u_soc_periph_p/u_soc_periph/u_peripherals/soc_periph_dw_uart/uart_apb_if

excludes:

  #########################################################################
  # soc_periph excludes
  #########################################################################

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: EMMC sideband signals, controlled by CSRs. Should not change
    signals:
      - emmc_inreg_cfg
      - emmc_outreg_cfg

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Card inserted signal, tied at 1 by tb
    signals:
      - i_mem_ctrl_0_ipad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Loopback Signal used when internal clock source is used for data sampling. Not connected to anything in the mini_top + from the emmc driver, we choose to use an external clock source instead.
    signals:
      - i_mem_rebar_ipad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Write protect signal, should be tied to high as per cadence emmc spec (Table 14)
    signals:
      - i_mem_wpbar_ipad
      - o_mem_wpbar_iepad
      - o_mem_wpbar_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Sideband signals
    signals:
      - i_pde
      - i_ret
      - o_obs[0:15]
      - o_prn
      - scan_en
      - test_mode

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment:  Pull-up / pull-down resistor control for LVS Identification (SD mode)
    signals:
      - o_mem_ale_iepad
      - o_mem_ale_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Card inserted signal input/output config, at the correct config by default (input enabled)
    signals:
      - o_mem_ctrl_0_iepad
      - o_mem_ctrl_0_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Bus power signal input/output config, correct config by default (output enabled)
    signals:
      - o_mem_ctrl_1_iepad
      - o_mem_ctrl_1_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: lpbk_dqs output enable signal, not used since o_mem_lpbk_dqs_opad does not exist
    signals:
      - o_mem_lpbk_dqs_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment:  Loopback output enable, on by default -> no need to toggle it
    signals:
      - o_mem_rebar_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Device reset signal input/output config, correct config by default (output enable)
    signals:
      - o_mem_rstbar_iepad
      - o_mem_rstbar_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: Clock from host to card signal input/output config, correct config by default (output enable)
    signals:
      - o_mem_webar_iepad
      - o_mem_webar_oepad

  - scope: /top/u_soc_periph_p/u_soc_periph
    comment: UART CTS handshake signals, will remain unused as per SW team needs
    signals:
      - i_uart_cst_n 


  #########################################################################
  # soc_periph_p excludes
  #########################################################################

  - scope: /top/u_soc_periph_p
    comment: PADTRCL signals
    signals:
      - o_ref_clk_sel_freq
      - o_jtag_drive
      - o_uart_drive
      - o_spi_drive
      - o_i2c_drive
      - o_gpio_drive
      - o_obs_drive
      - o_dft_drive
      - o_emmc_drive
      - o_clk_schmitt
      - o_rst_schmitt
      - o_spi_schmitt
      - o_uart_schmitt
      - o_i2c_schmitt
      - o_gpio_schmitt
      - o_emmc_schmitt
      - o_dft_schmitt

  - scope: /top/u_soc_periph_p
    comment: DFT signals
    signals:
      - bisr_clk
      - bisr_reset
      - bisr_shift_en
      - bisr_si
      - bisr_so
      - edt_update

  - scope: /top/u_soc_periph_p
    comment: Unconnected wires within soc_periph
    signals:
      - i_lt_axi_s_arqos[0:3]
      - i_lt_axi_s_arregion[0:3]
      - i_lt_axi_s_aruser[0]
      - i_lt_axi_s_awqos[0:3]
      - i_lt_axi_s_awregion[0:3]
      - i_lt_axi_s_awuser[0]
      - i_lt_axi_s_wuser[0]
      - o_lt_axi_s_buser[0]
      - o_lt_axi_s_ruser[0]
      - ijtag_ce
      - ijtag_reset
      - ijtag_se
      - ijtag_sel
      - ijtag_si
      - ijtag_so
      - ijtag_tck
      - ijtag_ue

  - scope: /top/u_soc_periph_p
    comment: PCTL signals
    signals:
      - o_noc_async_idle_req

  - scope: /top/u_soc_periph_p
    comment: Sideband signals
    signals:
      - scan_en
      - scan_in
      - scan_out
      - test_clk
      - test_mode
