# Variables TCL synth_variables 
set FREQ_MARGIN "1.15"
set PMA_NAME "c20"
set SYNTH_UPF_FLOW "0"
set dwc_dpalt_phy "0"
set flow "syn"
set hdmi_2p1_ctrl "0"
set hdmi_54b_support "0"
set jtag_mphy_support "1"
set jtag_phy_res_ext "0"
set jtag_phy_scan_rx_dword "1"
set jtag_pma_bit_blasted "0"
set jtag_pma_new_timing_arcs "1"
set jtag_rx_ana_dword_xf "1"
set max_pclk_div_ratio "0,0,0,0"
set msg2apb_pdos_reg "0"
set noextrom "0"
set norom "0"
set nphys "1"

set pclk_as_phy_input "0"
set pcs_scan_nonsds_pclk "1"
set pcs_scan_rx_clk "0"
set pipe_clksrc_perlink "0x"
set pipe_lanes_perlink "4x"
set pipe_nlanes "4"
set pipe_nlinks "1"
set pipe_width "8,8,16,16"
set pma_inst_name "pma"
set protocol "pcie4"
set ref_freq_val "100"
set separate_vp_vdd_support "0"
set serdes_mode "0"
set sync_apb0_fw "0"

set remove_upcs_scan_constraints "1"
set post_synth "0"
#############################################################################################
