// AUTO GENERATED, DO NOT MANUALLY EDIT!!
//
// Description: Interrupt connectivity module gathering external interrupt
//
// external_irqs --> module --> external_irqs_struct
//
// Owner: hw/scripts/interrupt_map

module apu_interrupt_connectivity_external (

    input logic i_irq__soc_mgmt__thermal_throttle,
    input logic i_irq__soc_mgmt__thermal_warning,
    input logic i_irq__soc_mgmt__thermal_shutdown,
    input logic i_irq__lpddr_graph_0__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_graph_1__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_graph_2__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_graph_3__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_ppp_0__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_ppp_1__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_ppp_2__ctrl_derate_temp_limit,
    input logic i_irq__lpddr_ppp_3__ctrl_derate_temp_limit,
    input logic i_irq__soc_mgmt__dlm_warning,
    input logic i_irq__soc_mgmt__dlm_critical,
    input logic i_irq__lpddr_graph_0__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_graph_0__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_graph_0__phy_pie_prog_err,
    input logic i_irq__lpddr_graph_0__phy_ecc_err,
    input logic i_irq__lpddr_graph_0__phy_rdfptrchk_err,
    input logic i_irq__lpddr_graph_0__phy_pie_parity_err,
    input logic i_irq__lpddr_graph_0__phy_acsm_parity_err,
    input logic i_irq__lpddr_graph_1__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_graph_1__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_graph_1__phy_pie_prog_err,
    input logic i_irq__lpddr_graph_1__phy_ecc_err,
    input logic i_irq__lpddr_graph_1__phy_rdfptrchk_err,
    input logic i_irq__lpddr_graph_1__phy_pie_parity_err,
    input logic i_irq__lpddr_graph_1__phy_acsm_parity_err,
    input logic i_irq__lpddr_graph_2__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_graph_2__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_graph_2__phy_pie_prog_err,
    input logic i_irq__lpddr_graph_2__phy_ecc_err,
    input logic i_irq__lpddr_graph_2__phy_rdfptrchk_err,
    input logic i_irq__lpddr_graph_2__phy_pie_parity_err,
    input logic i_irq__lpddr_graph_2__phy_acsm_parity_err,
    input logic i_irq__lpddr_graph_3__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_graph_3__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_graph_3__phy_pie_prog_err,
    input logic i_irq__lpddr_graph_3__phy_ecc_err,
    input logic i_irq__lpddr_graph_3__phy_rdfptrchk_err,
    input logic i_irq__lpddr_graph_3__phy_pie_parity_err,
    input logic i_irq__lpddr_graph_3__phy_acsm_parity_err,
    input logic i_irq__lpddr_ppp_0__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_ppp_0__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_ppp_0__phy_pie_prog_err,
    input logic i_irq__lpddr_ppp_0__phy_ecc_err,
    input logic i_irq__lpddr_ppp_0__phy_rdfptrchk_err,
    input logic i_irq__lpddr_ppp_0__phy_pie_parity_err,
    input logic i_irq__lpddr_ppp_0__phy_acsm_parity_err,
    input logic i_irq__lpddr_ppp_1__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_ppp_1__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_ppp_1__phy_pie_prog_err,
    input logic i_irq__lpddr_ppp_1__phy_ecc_err,
    input logic i_irq__lpddr_ppp_1__phy_rdfptrchk_err,
    input logic i_irq__lpddr_ppp_1__phy_pie_parity_err,
    input logic i_irq__lpddr_ppp_1__phy_acsm_parity_err,
    input logic i_irq__lpddr_ppp_2__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_ppp_2__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_ppp_2__phy_pie_prog_err,
    input logic i_irq__lpddr_ppp_2__phy_ecc_err,
    input logic i_irq__lpddr_ppp_2__phy_rdfptrchk_err,
    input logic i_irq__lpddr_ppp_2__phy_pie_parity_err,
    input logic i_irq__lpddr_ppp_2__phy_acsm_parity_err,
    input logic i_irq__lpddr_ppp_3__ctrl_ecc_uncorrected_err,
    input logic i_irq__lpddr_ppp_3__ctrl_rd_linkecc_uncorr_err,
    input logic i_irq__lpddr_ppp_3__phy_pie_prog_err,
    input logic i_irq__lpddr_ppp_3__phy_ecc_err,
    input logic i_irq__lpddr_ppp_3__phy_rdfptrchk_err,
    input logic i_irq__lpddr_ppp_3__phy_pie_parity_err,
    input logic i_irq__lpddr_ppp_3__phy_acsm_parity_err,
    input logic i_irq__pcie__perst_n,
    input logic i_irq__sys_spm__error,
    input logic i_irq__lpddr_graph_0__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_graph_0__phy_trng_fail,
    input logic i_irq__lpddr_graph_1__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_graph_1__phy_trng_fail,
    input logic i_irq__lpddr_graph_2__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_graph_2__phy_trng_fail,
    input logic i_irq__lpddr_graph_3__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_graph_3__phy_trng_fail,
    input logic i_irq__lpddr_ppp_0__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_ppp_0__phy_trng_fail,
    input logic i_irq__lpddr_ppp_1__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_ppp_1__phy_trng_fail,
    input logic i_irq__lpddr_ppp_2__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_ppp_2__phy_trng_fail,
    input logic i_irq__lpddr_ppp_3__ctrl_ecc_ap_err,
    input logic i_irq__lpddr_ppp_3__phy_trng_fail,
    input logic i_irq__soc_mgmt__rtc,
    input logic i_irq__soc_mgmt__wdt,
    input logic i_irq__soc_periph__timer,
    input logic i_irq__lpddr_graph_0__ctrl_sbr_done,
    input logic i_irq__lpddr_graph_0__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_graph_0__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_graph_0__phy_init_cmplt,
    input logic i_irq__lpddr_graph_0__phy_trng_cmplt,
    input logic i_irq__lpddr_graph_1__ctrl_sbr_done,
    input logic i_irq__lpddr_graph_1__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_graph_1__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_graph_1__phy_init_cmplt,
    input logic i_irq__lpddr_graph_1__phy_trng_cmplt,
    input logic i_irq__lpddr_graph_2__ctrl_sbr_done,
    input logic i_irq__lpddr_graph_2__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_graph_2__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_graph_2__phy_init_cmplt,
    input logic i_irq__lpddr_graph_2__phy_trng_cmplt,
    input logic i_irq__lpddr_graph_3__ctrl_sbr_done,
    input logic i_irq__lpddr_graph_3__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_graph_3__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_graph_3__phy_init_cmplt,
    input logic i_irq__lpddr_graph_3__phy_trng_cmplt,
    input logic i_irq__lpddr_ppp_0__ctrl_sbr_done,
    input logic i_irq__lpddr_ppp_0__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_ppp_0__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_ppp_0__phy_init_cmplt,
    input logic i_irq__lpddr_ppp_0__phy_trng_cmplt,
    input logic i_irq__lpddr_ppp_1__ctrl_sbr_done,
    input logic i_irq__lpddr_ppp_1__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_ppp_1__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_ppp_1__phy_init_cmplt,
    input logic i_irq__lpddr_ppp_1__phy_trng_cmplt,
    input logic i_irq__lpddr_ppp_2__ctrl_sbr_done,
    input logic i_irq__lpddr_ppp_2__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_ppp_2__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_ppp_2__phy_init_cmplt,
    input logic i_irq__lpddr_ppp_2__phy_trng_cmplt,
    input logic i_irq__lpddr_ppp_3__ctrl_sbr_done,
    input logic i_irq__lpddr_ppp_3__ctrl_ecc_corrected_err,
    input logic i_irq__lpddr_ppp_3__ctrl_rd_linkecc_corr_err,
    input logic i_irq__lpddr_ppp_3__phy_init_cmplt,
    input logic i_irq__lpddr_ppp_3__phy_trng_cmplt,
    input logic i_irq__soc_mgmt__security,
    input logic i_irq__soc_periph__emmc,
    input logic i_irq__dcd__int,
    input logic i_irq__noc__int,
    input logic i_irq__noc__sdma_0_int_0,
    input logic i_irq__noc__sdma_0_int_1,
    input logic i_irq__noc__sdma_0_int_2,
    input logic i_irq__noc__sdma_0_int_3,
    input logic i_irq__noc__sdma_1_int_0,
    input logic i_irq__noc__sdma_1_int_1,
    input logic i_irq__noc__sdma_1_int_2,
    input logic i_irq__noc__sdma_1_int_3,
    input logic i_irq__soc_periph__uart,
    input logic i_irq__soc_periph__gpio,
    input logic i_irq__soc_periph__i2c_0,
    input logic i_irq__soc_periph__i2c_1,
    input logic i_irq__soc_periph__spi,
    input logic i_irq__pcie__int,
    output apu_interrupt_map_pkg::apu_external_irqs_t o_external_irqs
);

  always_comb begin

    o_external_irqs.soc_mgmt__thermal_throttle = i_irq__soc_mgmt__thermal_throttle;
    o_external_irqs.soc_mgmt__thermal_warning = i_irq__soc_mgmt__thermal_warning;
    o_external_irqs.soc_mgmt__thermal_shutdown = i_irq__soc_mgmt__thermal_shutdown;
    o_external_irqs.lpddr_graph_0__ctrl_derate_temp_limit = i_irq__lpddr_graph_0__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_graph_1__ctrl_derate_temp_limit = i_irq__lpddr_graph_1__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_graph_2__ctrl_derate_temp_limit = i_irq__lpddr_graph_2__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_graph_3__ctrl_derate_temp_limit = i_irq__lpddr_graph_3__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_ppp_0__ctrl_derate_temp_limit = i_irq__lpddr_ppp_0__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_ppp_1__ctrl_derate_temp_limit = i_irq__lpddr_ppp_1__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_ppp_2__ctrl_derate_temp_limit = i_irq__lpddr_ppp_2__ctrl_derate_temp_limit;
    o_external_irqs.lpddr_ppp_3__ctrl_derate_temp_limit = i_irq__lpddr_ppp_3__ctrl_derate_temp_limit;
    o_external_irqs.soc_mgmt__dlm_warning = i_irq__soc_mgmt__dlm_warning;
    o_external_irqs.soc_mgmt__dlm_critical = i_irq__soc_mgmt__dlm_critical;
    o_external_irqs.lpddr_graph_0__ctrl_ecc_uncorrected_err = i_irq__lpddr_graph_0__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_graph_0__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_graph_0__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_graph_0__phy_pie_prog_err = i_irq__lpddr_graph_0__phy_pie_prog_err;
    o_external_irqs.lpddr_graph_0__phy_ecc_err = i_irq__lpddr_graph_0__phy_ecc_err;
    o_external_irqs.lpddr_graph_0__phy_rdfptrchk_err = i_irq__lpddr_graph_0__phy_rdfptrchk_err;
    o_external_irqs.lpddr_graph_0__phy_pie_parity_err = i_irq__lpddr_graph_0__phy_pie_parity_err;
    o_external_irqs.lpddr_graph_0__phy_acsm_parity_err = i_irq__lpddr_graph_0__phy_acsm_parity_err;
    o_external_irqs.lpddr_graph_1__ctrl_ecc_uncorrected_err = i_irq__lpddr_graph_1__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_graph_1__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_graph_1__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_graph_1__phy_pie_prog_err = i_irq__lpddr_graph_1__phy_pie_prog_err;
    o_external_irqs.lpddr_graph_1__phy_ecc_err = i_irq__lpddr_graph_1__phy_ecc_err;
    o_external_irqs.lpddr_graph_1__phy_rdfptrchk_err = i_irq__lpddr_graph_1__phy_rdfptrchk_err;
    o_external_irqs.lpddr_graph_1__phy_pie_parity_err = i_irq__lpddr_graph_1__phy_pie_parity_err;
    o_external_irqs.lpddr_graph_1__phy_acsm_parity_err = i_irq__lpddr_graph_1__phy_acsm_parity_err;
    o_external_irqs.lpddr_graph_2__ctrl_ecc_uncorrected_err = i_irq__lpddr_graph_2__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_graph_2__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_graph_2__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_graph_2__phy_pie_prog_err = i_irq__lpddr_graph_2__phy_pie_prog_err;
    o_external_irqs.lpddr_graph_2__phy_ecc_err = i_irq__lpddr_graph_2__phy_ecc_err;
    o_external_irqs.lpddr_graph_2__phy_rdfptrchk_err = i_irq__lpddr_graph_2__phy_rdfptrchk_err;
    o_external_irqs.lpddr_graph_2__phy_pie_parity_err = i_irq__lpddr_graph_2__phy_pie_parity_err;
    o_external_irqs.lpddr_graph_2__phy_acsm_parity_err = i_irq__lpddr_graph_2__phy_acsm_parity_err;
    o_external_irqs.lpddr_graph_3__ctrl_ecc_uncorrected_err = i_irq__lpddr_graph_3__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_graph_3__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_graph_3__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_graph_3__phy_pie_prog_err = i_irq__lpddr_graph_3__phy_pie_prog_err;
    o_external_irqs.lpddr_graph_3__phy_ecc_err = i_irq__lpddr_graph_3__phy_ecc_err;
    o_external_irqs.lpddr_graph_3__phy_rdfptrchk_err = i_irq__lpddr_graph_3__phy_rdfptrchk_err;
    o_external_irqs.lpddr_graph_3__phy_pie_parity_err = i_irq__lpddr_graph_3__phy_pie_parity_err;
    o_external_irqs.lpddr_graph_3__phy_acsm_parity_err = i_irq__lpddr_graph_3__phy_acsm_parity_err;
    o_external_irqs.lpddr_ppp_0__ctrl_ecc_uncorrected_err = i_irq__lpddr_ppp_0__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_ppp_0__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_ppp_0__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_ppp_0__phy_pie_prog_err = i_irq__lpddr_ppp_0__phy_pie_prog_err;
    o_external_irqs.lpddr_ppp_0__phy_ecc_err = i_irq__lpddr_ppp_0__phy_ecc_err;
    o_external_irqs.lpddr_ppp_0__phy_rdfptrchk_err = i_irq__lpddr_ppp_0__phy_rdfptrchk_err;
    o_external_irqs.lpddr_ppp_0__phy_pie_parity_err = i_irq__lpddr_ppp_0__phy_pie_parity_err;
    o_external_irqs.lpddr_ppp_0__phy_acsm_parity_err = i_irq__lpddr_ppp_0__phy_acsm_parity_err;
    o_external_irqs.lpddr_ppp_1__ctrl_ecc_uncorrected_err = i_irq__lpddr_ppp_1__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_ppp_1__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_ppp_1__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_ppp_1__phy_pie_prog_err = i_irq__lpddr_ppp_1__phy_pie_prog_err;
    o_external_irqs.lpddr_ppp_1__phy_ecc_err = i_irq__lpddr_ppp_1__phy_ecc_err;
    o_external_irqs.lpddr_ppp_1__phy_rdfptrchk_err = i_irq__lpddr_ppp_1__phy_rdfptrchk_err;
    o_external_irqs.lpddr_ppp_1__phy_pie_parity_err = i_irq__lpddr_ppp_1__phy_pie_parity_err;
    o_external_irqs.lpddr_ppp_1__phy_acsm_parity_err = i_irq__lpddr_ppp_1__phy_acsm_parity_err;
    o_external_irqs.lpddr_ppp_2__ctrl_ecc_uncorrected_err = i_irq__lpddr_ppp_2__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_ppp_2__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_ppp_2__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_ppp_2__phy_pie_prog_err = i_irq__lpddr_ppp_2__phy_pie_prog_err;
    o_external_irqs.lpddr_ppp_2__phy_ecc_err = i_irq__lpddr_ppp_2__phy_ecc_err;
    o_external_irqs.lpddr_ppp_2__phy_rdfptrchk_err = i_irq__lpddr_ppp_2__phy_rdfptrchk_err;
    o_external_irqs.lpddr_ppp_2__phy_pie_parity_err = i_irq__lpddr_ppp_2__phy_pie_parity_err;
    o_external_irqs.lpddr_ppp_2__phy_acsm_parity_err = i_irq__lpddr_ppp_2__phy_acsm_parity_err;
    o_external_irqs.lpddr_ppp_3__ctrl_ecc_uncorrected_err = i_irq__lpddr_ppp_3__ctrl_ecc_uncorrected_err;
    o_external_irqs.lpddr_ppp_3__ctrl_rd_linkecc_uncorr_err = i_irq__lpddr_ppp_3__ctrl_rd_linkecc_uncorr_err;
    o_external_irqs.lpddr_ppp_3__phy_pie_prog_err = i_irq__lpddr_ppp_3__phy_pie_prog_err;
    o_external_irqs.lpddr_ppp_3__phy_ecc_err = i_irq__lpddr_ppp_3__phy_ecc_err;
    o_external_irqs.lpddr_ppp_3__phy_rdfptrchk_err = i_irq__lpddr_ppp_3__phy_rdfptrchk_err;
    o_external_irqs.lpddr_ppp_3__phy_pie_parity_err = i_irq__lpddr_ppp_3__phy_pie_parity_err;
    o_external_irqs.lpddr_ppp_3__phy_acsm_parity_err = i_irq__lpddr_ppp_3__phy_acsm_parity_err;
    o_external_irqs.pcie__perst_n = i_irq__pcie__perst_n;
    o_external_irqs.sys_spm__error = i_irq__sys_spm__error;
    o_external_irqs.lpddr_graph_0__ctrl_ecc_ap_err = i_irq__lpddr_graph_0__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_graph_0__phy_trng_fail = i_irq__lpddr_graph_0__phy_trng_fail;
    o_external_irqs.lpddr_graph_1__ctrl_ecc_ap_err = i_irq__lpddr_graph_1__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_graph_1__phy_trng_fail = i_irq__lpddr_graph_1__phy_trng_fail;
    o_external_irqs.lpddr_graph_2__ctrl_ecc_ap_err = i_irq__lpddr_graph_2__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_graph_2__phy_trng_fail = i_irq__lpddr_graph_2__phy_trng_fail;
    o_external_irqs.lpddr_graph_3__ctrl_ecc_ap_err = i_irq__lpddr_graph_3__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_graph_3__phy_trng_fail = i_irq__lpddr_graph_3__phy_trng_fail;
    o_external_irqs.lpddr_ppp_0__ctrl_ecc_ap_err = i_irq__lpddr_ppp_0__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_ppp_0__phy_trng_fail = i_irq__lpddr_ppp_0__phy_trng_fail;
    o_external_irqs.lpddr_ppp_1__ctrl_ecc_ap_err = i_irq__lpddr_ppp_1__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_ppp_1__phy_trng_fail = i_irq__lpddr_ppp_1__phy_trng_fail;
    o_external_irqs.lpddr_ppp_2__ctrl_ecc_ap_err = i_irq__lpddr_ppp_2__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_ppp_2__phy_trng_fail = i_irq__lpddr_ppp_2__phy_trng_fail;
    o_external_irqs.lpddr_ppp_3__ctrl_ecc_ap_err = i_irq__lpddr_ppp_3__ctrl_ecc_ap_err;
    o_external_irqs.lpddr_ppp_3__phy_trng_fail = i_irq__lpddr_ppp_3__phy_trng_fail;
    o_external_irqs.soc_mgmt__rtc = i_irq__soc_mgmt__rtc;
    o_external_irqs.soc_mgmt__wdt = i_irq__soc_mgmt__wdt;
    o_external_irqs.soc_periph__timer = i_irq__soc_periph__timer;
    o_external_irqs.lpddr_graph_0__ctrl_sbr_done = i_irq__lpddr_graph_0__ctrl_sbr_done;
    o_external_irqs.lpddr_graph_0__ctrl_ecc_corrected_err = i_irq__lpddr_graph_0__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_graph_0__ctrl_rd_linkecc_corr_err = i_irq__lpddr_graph_0__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_graph_0__phy_init_cmplt = i_irq__lpddr_graph_0__phy_init_cmplt;
    o_external_irqs.lpddr_graph_0__phy_trng_cmplt = i_irq__lpddr_graph_0__phy_trng_cmplt;
    o_external_irqs.lpddr_graph_1__ctrl_sbr_done = i_irq__lpddr_graph_1__ctrl_sbr_done;
    o_external_irqs.lpddr_graph_1__ctrl_ecc_corrected_err = i_irq__lpddr_graph_1__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_graph_1__ctrl_rd_linkecc_corr_err = i_irq__lpddr_graph_1__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_graph_1__phy_init_cmplt = i_irq__lpddr_graph_1__phy_init_cmplt;
    o_external_irqs.lpddr_graph_1__phy_trng_cmplt = i_irq__lpddr_graph_1__phy_trng_cmplt;
    o_external_irqs.lpddr_graph_2__ctrl_sbr_done = i_irq__lpddr_graph_2__ctrl_sbr_done;
    o_external_irqs.lpddr_graph_2__ctrl_ecc_corrected_err = i_irq__lpddr_graph_2__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_graph_2__ctrl_rd_linkecc_corr_err = i_irq__lpddr_graph_2__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_graph_2__phy_init_cmplt = i_irq__lpddr_graph_2__phy_init_cmplt;
    o_external_irqs.lpddr_graph_2__phy_trng_cmplt = i_irq__lpddr_graph_2__phy_trng_cmplt;
    o_external_irqs.lpddr_graph_3__ctrl_sbr_done = i_irq__lpddr_graph_3__ctrl_sbr_done;
    o_external_irqs.lpddr_graph_3__ctrl_ecc_corrected_err = i_irq__lpddr_graph_3__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_graph_3__ctrl_rd_linkecc_corr_err = i_irq__lpddr_graph_3__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_graph_3__phy_init_cmplt = i_irq__lpddr_graph_3__phy_init_cmplt;
    o_external_irqs.lpddr_graph_3__phy_trng_cmplt = i_irq__lpddr_graph_3__phy_trng_cmplt;
    o_external_irqs.lpddr_ppp_0__ctrl_sbr_done = i_irq__lpddr_ppp_0__ctrl_sbr_done;
    o_external_irqs.lpddr_ppp_0__ctrl_ecc_corrected_err = i_irq__lpddr_ppp_0__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_ppp_0__ctrl_rd_linkecc_corr_err = i_irq__lpddr_ppp_0__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_ppp_0__phy_init_cmplt = i_irq__lpddr_ppp_0__phy_init_cmplt;
    o_external_irqs.lpddr_ppp_0__phy_trng_cmplt = i_irq__lpddr_ppp_0__phy_trng_cmplt;
    o_external_irqs.lpddr_ppp_1__ctrl_sbr_done = i_irq__lpddr_ppp_1__ctrl_sbr_done;
    o_external_irqs.lpddr_ppp_1__ctrl_ecc_corrected_err = i_irq__lpddr_ppp_1__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_ppp_1__ctrl_rd_linkecc_corr_err = i_irq__lpddr_ppp_1__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_ppp_1__phy_init_cmplt = i_irq__lpddr_ppp_1__phy_init_cmplt;
    o_external_irqs.lpddr_ppp_1__phy_trng_cmplt = i_irq__lpddr_ppp_1__phy_trng_cmplt;
    o_external_irqs.lpddr_ppp_2__ctrl_sbr_done = i_irq__lpddr_ppp_2__ctrl_sbr_done;
    o_external_irqs.lpddr_ppp_2__ctrl_ecc_corrected_err = i_irq__lpddr_ppp_2__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_ppp_2__ctrl_rd_linkecc_corr_err = i_irq__lpddr_ppp_2__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_ppp_2__phy_init_cmplt = i_irq__lpddr_ppp_2__phy_init_cmplt;
    o_external_irqs.lpddr_ppp_2__phy_trng_cmplt = i_irq__lpddr_ppp_2__phy_trng_cmplt;
    o_external_irqs.lpddr_ppp_3__ctrl_sbr_done = i_irq__lpddr_ppp_3__ctrl_sbr_done;
    o_external_irqs.lpddr_ppp_3__ctrl_ecc_corrected_err = i_irq__lpddr_ppp_3__ctrl_ecc_corrected_err;
    o_external_irqs.lpddr_ppp_3__ctrl_rd_linkecc_corr_err = i_irq__lpddr_ppp_3__ctrl_rd_linkecc_corr_err;
    o_external_irqs.lpddr_ppp_3__phy_init_cmplt = i_irq__lpddr_ppp_3__phy_init_cmplt;
    o_external_irqs.lpddr_ppp_3__phy_trng_cmplt = i_irq__lpddr_ppp_3__phy_trng_cmplt;
    o_external_irqs.soc_mgmt__security = i_irq__soc_mgmt__security;
    o_external_irqs.soc_periph__emmc = i_irq__soc_periph__emmc;
    o_external_irqs.dcd__int = i_irq__dcd__int;
    o_external_irqs.noc__int = i_irq__noc__int;
    o_external_irqs.noc__sdma_0_int_0 = i_irq__noc__sdma_0_int_0;
    o_external_irqs.noc__sdma_0_int_1 = i_irq__noc__sdma_0_int_1;
    o_external_irqs.noc__sdma_0_int_2 = i_irq__noc__sdma_0_int_2;
    o_external_irqs.noc__sdma_0_int_3 = i_irq__noc__sdma_0_int_3;
    o_external_irqs.noc__sdma_1_int_0 = i_irq__noc__sdma_1_int_0;
    o_external_irqs.noc__sdma_1_int_1 = i_irq__noc__sdma_1_int_1;
    o_external_irqs.noc__sdma_1_int_2 = i_irq__noc__sdma_1_int_2;
    o_external_irqs.noc__sdma_1_int_3 = i_irq__noc__sdma_1_int_3;
    o_external_irqs.soc_periph__uart = i_irq__soc_periph__uart;
    o_external_irqs.soc_periph__gpio = i_irq__soc_periph__gpio;
    o_external_irqs.soc_periph__i2c_0 = i_irq__soc_periph__i2c_0;
    o_external_irqs.soc_periph__i2c_1 = i_irq__soc_periph__i2c_1;
    o_external_irqs.soc_periph__spi = i_irq__soc_periph__spi;
    o_external_irqs.pcie__int = i_irq__pcie__int;
  end

endmodule
