// AUTO GENERATED, DO NOT MANUALLY EDIT!!
//
// Description: Interrupt connectivity module before interrupt_controller
//
// external_irqs_struc --> module --> interrupt_controller
// internal_irqs --------/
//
// Owner: hw/scripts/interrupt_map

module apu_interrupt_connectivity_internal (

    input logic i_irq__apu__l2c_err,
    input logic i_irq__apu__dma_channel_1,
    input logic i_irq__apu__dma_channel_2,
    input logic i_irq__apu__dma_common,
    input logic i_irq__apu__mailbox,
    input logic i_irq__apu__token_manager,
    input apu_interrupt_map_pkg::apu_external_irqs_t i_external_irqs,
    output apu_interrupt_map_pkg::apu_all_irqs_t o_all_irqs
);

  always_comb begin

    o_all_irqs.apu__l2c_err = i_irq__apu__l2c_err;
    o_all_irqs.apu__dma_channel_1 = i_irq__apu__dma_channel_1;
    o_all_irqs.apu__dma_channel_2 = i_irq__apu__dma_channel_2;
    o_all_irqs.apu__dma_common = i_irq__apu__dma_common;
    o_all_irqs.apu__mailbox = i_irq__apu__mailbox;
    o_all_irqs.apu__token_manager = i_irq__apu__token_manager;

    o_all_irqs.soc_mgmt__thermal_throttle = i_external_irqs.soc_mgmt__thermal_throttle;
    o_all_irqs.soc_mgmt__thermal_warning = i_external_irqs.soc_mgmt__thermal_warning;
    o_all_irqs.soc_mgmt__thermal_shutdown = i_external_irqs.soc_mgmt__thermal_shutdown;
    o_all_irqs.lpddr_graph_0__ctrl_derate_temp_limit = i_external_irqs.lpddr_graph_0__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_graph_1__ctrl_derate_temp_limit = i_external_irqs.lpddr_graph_1__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_graph_2__ctrl_derate_temp_limit = i_external_irqs.lpddr_graph_2__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_graph_3__ctrl_derate_temp_limit = i_external_irqs.lpddr_graph_3__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_ppp_0__ctrl_derate_temp_limit = i_external_irqs.lpddr_ppp_0__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_ppp_1__ctrl_derate_temp_limit = i_external_irqs.lpddr_ppp_1__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_ppp_2__ctrl_derate_temp_limit = i_external_irqs.lpddr_ppp_2__ctrl_derate_temp_limit;
    o_all_irqs.lpddr_ppp_3__ctrl_derate_temp_limit = i_external_irqs.lpddr_ppp_3__ctrl_derate_temp_limit;
    o_all_irqs.soc_mgmt__dlm_warning = i_external_irqs.soc_mgmt__dlm_warning;
    o_all_irqs.soc_mgmt__dlm_critical = i_external_irqs.soc_mgmt__dlm_critical;
    o_all_irqs.lpddr_graph_0__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_graph_0__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_graph_0__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_graph_0__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_graph_0__phy_pie_prog_err = i_external_irqs.lpddr_graph_0__phy_pie_prog_err;
    o_all_irqs.lpddr_graph_0__phy_ecc_err = i_external_irqs.lpddr_graph_0__phy_ecc_err;
    o_all_irqs.lpddr_graph_0__phy_rdfptrchk_err = i_external_irqs.lpddr_graph_0__phy_rdfptrchk_err;
    o_all_irqs.lpddr_graph_0__phy_pie_parity_err = i_external_irqs.lpddr_graph_0__phy_pie_parity_err;
    o_all_irqs.lpddr_graph_0__phy_acsm_parity_err = i_external_irqs.lpddr_graph_0__phy_acsm_parity_err;
    o_all_irqs.lpddr_graph_1__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_graph_1__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_graph_1__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_graph_1__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_graph_1__phy_pie_prog_err = i_external_irqs.lpddr_graph_1__phy_pie_prog_err;
    o_all_irqs.lpddr_graph_1__phy_ecc_err = i_external_irqs.lpddr_graph_1__phy_ecc_err;
    o_all_irqs.lpddr_graph_1__phy_rdfptrchk_err = i_external_irqs.lpddr_graph_1__phy_rdfptrchk_err;
    o_all_irqs.lpddr_graph_1__phy_pie_parity_err = i_external_irqs.lpddr_graph_1__phy_pie_parity_err;
    o_all_irqs.lpddr_graph_1__phy_acsm_parity_err = i_external_irqs.lpddr_graph_1__phy_acsm_parity_err;
    o_all_irqs.lpddr_graph_2__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_graph_2__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_graph_2__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_graph_2__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_graph_2__phy_pie_prog_err = i_external_irqs.lpddr_graph_2__phy_pie_prog_err;
    o_all_irqs.lpddr_graph_2__phy_ecc_err = i_external_irqs.lpddr_graph_2__phy_ecc_err;
    o_all_irqs.lpddr_graph_2__phy_rdfptrchk_err = i_external_irqs.lpddr_graph_2__phy_rdfptrchk_err;
    o_all_irqs.lpddr_graph_2__phy_pie_parity_err = i_external_irqs.lpddr_graph_2__phy_pie_parity_err;
    o_all_irqs.lpddr_graph_2__phy_acsm_parity_err = i_external_irqs.lpddr_graph_2__phy_acsm_parity_err;
    o_all_irqs.lpddr_graph_3__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_graph_3__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_graph_3__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_graph_3__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_graph_3__phy_pie_prog_err = i_external_irqs.lpddr_graph_3__phy_pie_prog_err;
    o_all_irqs.lpddr_graph_3__phy_ecc_err = i_external_irqs.lpddr_graph_3__phy_ecc_err;
    o_all_irqs.lpddr_graph_3__phy_rdfptrchk_err = i_external_irqs.lpddr_graph_3__phy_rdfptrchk_err;
    o_all_irqs.lpddr_graph_3__phy_pie_parity_err = i_external_irqs.lpddr_graph_3__phy_pie_parity_err;
    o_all_irqs.lpddr_graph_3__phy_acsm_parity_err = i_external_irqs.lpddr_graph_3__phy_acsm_parity_err;
    o_all_irqs.lpddr_ppp_0__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_ppp_0__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_ppp_0__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_ppp_0__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_ppp_0__phy_pie_prog_err = i_external_irqs.lpddr_ppp_0__phy_pie_prog_err;
    o_all_irqs.lpddr_ppp_0__phy_ecc_err = i_external_irqs.lpddr_ppp_0__phy_ecc_err;
    o_all_irqs.lpddr_ppp_0__phy_rdfptrchk_err = i_external_irqs.lpddr_ppp_0__phy_rdfptrchk_err;
    o_all_irqs.lpddr_ppp_0__phy_pie_parity_err = i_external_irqs.lpddr_ppp_0__phy_pie_parity_err;
    o_all_irqs.lpddr_ppp_0__phy_acsm_parity_err = i_external_irqs.lpddr_ppp_0__phy_acsm_parity_err;
    o_all_irqs.lpddr_ppp_1__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_ppp_1__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_ppp_1__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_ppp_1__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_ppp_1__phy_pie_prog_err = i_external_irqs.lpddr_ppp_1__phy_pie_prog_err;
    o_all_irqs.lpddr_ppp_1__phy_ecc_err = i_external_irqs.lpddr_ppp_1__phy_ecc_err;
    o_all_irqs.lpddr_ppp_1__phy_rdfptrchk_err = i_external_irqs.lpddr_ppp_1__phy_rdfptrchk_err;
    o_all_irqs.lpddr_ppp_1__phy_pie_parity_err = i_external_irqs.lpddr_ppp_1__phy_pie_parity_err;
    o_all_irqs.lpddr_ppp_1__phy_acsm_parity_err = i_external_irqs.lpddr_ppp_1__phy_acsm_parity_err;
    o_all_irqs.lpddr_ppp_2__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_ppp_2__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_ppp_2__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_ppp_2__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_ppp_2__phy_pie_prog_err = i_external_irqs.lpddr_ppp_2__phy_pie_prog_err;
    o_all_irqs.lpddr_ppp_2__phy_ecc_err = i_external_irqs.lpddr_ppp_2__phy_ecc_err;
    o_all_irqs.lpddr_ppp_2__phy_rdfptrchk_err = i_external_irqs.lpddr_ppp_2__phy_rdfptrchk_err;
    o_all_irqs.lpddr_ppp_2__phy_pie_parity_err = i_external_irqs.lpddr_ppp_2__phy_pie_parity_err;
    o_all_irqs.lpddr_ppp_2__phy_acsm_parity_err = i_external_irqs.lpddr_ppp_2__phy_acsm_parity_err;
    o_all_irqs.lpddr_ppp_3__ctrl_ecc_uncorrected_err = i_external_irqs.lpddr_ppp_3__ctrl_ecc_uncorrected_err;
    o_all_irqs.lpddr_ppp_3__ctrl_rd_linkecc_uncorr_err = i_external_irqs.lpddr_ppp_3__ctrl_rd_linkecc_uncorr_err;
    o_all_irqs.lpddr_ppp_3__phy_pie_prog_err = i_external_irqs.lpddr_ppp_3__phy_pie_prog_err;
    o_all_irqs.lpddr_ppp_3__phy_ecc_err = i_external_irqs.lpddr_ppp_3__phy_ecc_err;
    o_all_irqs.lpddr_ppp_3__phy_rdfptrchk_err = i_external_irqs.lpddr_ppp_3__phy_rdfptrchk_err;
    o_all_irqs.lpddr_ppp_3__phy_pie_parity_err = i_external_irqs.lpddr_ppp_3__phy_pie_parity_err;
    o_all_irqs.lpddr_ppp_3__phy_acsm_parity_err = i_external_irqs.lpddr_ppp_3__phy_acsm_parity_err;
    o_all_irqs.pcie__perst_n = i_external_irqs.pcie__perst_n;
    o_all_irqs.sys_spm__error = i_external_irqs.sys_spm__error;
    o_all_irqs.lpddr_graph_0__ctrl_ecc_ap_err = i_external_irqs.lpddr_graph_0__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_graph_0__phy_trng_fail = i_external_irqs.lpddr_graph_0__phy_trng_fail;
    o_all_irqs.lpddr_graph_1__ctrl_ecc_ap_err = i_external_irqs.lpddr_graph_1__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_graph_1__phy_trng_fail = i_external_irqs.lpddr_graph_1__phy_trng_fail;
    o_all_irqs.lpddr_graph_2__ctrl_ecc_ap_err = i_external_irqs.lpddr_graph_2__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_graph_2__phy_trng_fail = i_external_irqs.lpddr_graph_2__phy_trng_fail;
    o_all_irqs.lpddr_graph_3__ctrl_ecc_ap_err = i_external_irqs.lpddr_graph_3__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_graph_3__phy_trng_fail = i_external_irqs.lpddr_graph_3__phy_trng_fail;
    o_all_irqs.lpddr_ppp_0__ctrl_ecc_ap_err = i_external_irqs.lpddr_ppp_0__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_ppp_0__phy_trng_fail = i_external_irqs.lpddr_ppp_0__phy_trng_fail;
    o_all_irqs.lpddr_ppp_1__ctrl_ecc_ap_err = i_external_irqs.lpddr_ppp_1__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_ppp_1__phy_trng_fail = i_external_irqs.lpddr_ppp_1__phy_trng_fail;
    o_all_irqs.lpddr_ppp_2__ctrl_ecc_ap_err = i_external_irqs.lpddr_ppp_2__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_ppp_2__phy_trng_fail = i_external_irqs.lpddr_ppp_2__phy_trng_fail;
    o_all_irqs.lpddr_ppp_3__ctrl_ecc_ap_err = i_external_irqs.lpddr_ppp_3__ctrl_ecc_ap_err;
    o_all_irqs.lpddr_ppp_3__phy_trng_fail = i_external_irqs.lpddr_ppp_3__phy_trng_fail;
    o_all_irqs.soc_mgmt__rtc = i_external_irqs.soc_mgmt__rtc;
    o_all_irqs.soc_mgmt__wdt = i_external_irqs.soc_mgmt__wdt;
    o_all_irqs.soc_periph__timer = i_external_irqs.soc_periph__timer;
    o_all_irqs.lpddr_graph_0__ctrl_sbr_done = i_external_irqs.lpddr_graph_0__ctrl_sbr_done;
    o_all_irqs.lpddr_graph_0__ctrl_ecc_corrected_err = i_external_irqs.lpddr_graph_0__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_graph_0__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_graph_0__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_graph_0__phy_init_cmplt = i_external_irqs.lpddr_graph_0__phy_init_cmplt;
    o_all_irqs.lpddr_graph_0__phy_trng_cmplt = i_external_irqs.lpddr_graph_0__phy_trng_cmplt;
    o_all_irqs.lpddr_graph_1__ctrl_sbr_done = i_external_irqs.lpddr_graph_1__ctrl_sbr_done;
    o_all_irqs.lpddr_graph_1__ctrl_ecc_corrected_err = i_external_irqs.lpddr_graph_1__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_graph_1__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_graph_1__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_graph_1__phy_init_cmplt = i_external_irqs.lpddr_graph_1__phy_init_cmplt;
    o_all_irqs.lpddr_graph_1__phy_trng_cmplt = i_external_irqs.lpddr_graph_1__phy_trng_cmplt;
    o_all_irqs.lpddr_graph_2__ctrl_sbr_done = i_external_irqs.lpddr_graph_2__ctrl_sbr_done;
    o_all_irqs.lpddr_graph_2__ctrl_ecc_corrected_err = i_external_irqs.lpddr_graph_2__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_graph_2__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_graph_2__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_graph_2__phy_init_cmplt = i_external_irqs.lpddr_graph_2__phy_init_cmplt;
    o_all_irqs.lpddr_graph_2__phy_trng_cmplt = i_external_irqs.lpddr_graph_2__phy_trng_cmplt;
    o_all_irqs.lpddr_graph_3__ctrl_sbr_done = i_external_irqs.lpddr_graph_3__ctrl_sbr_done;
    o_all_irqs.lpddr_graph_3__ctrl_ecc_corrected_err = i_external_irqs.lpddr_graph_3__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_graph_3__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_graph_3__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_graph_3__phy_init_cmplt = i_external_irqs.lpddr_graph_3__phy_init_cmplt;
    o_all_irqs.lpddr_graph_3__phy_trng_cmplt = i_external_irqs.lpddr_graph_3__phy_trng_cmplt;
    o_all_irqs.lpddr_ppp_0__ctrl_sbr_done = i_external_irqs.lpddr_ppp_0__ctrl_sbr_done;
    o_all_irqs.lpddr_ppp_0__ctrl_ecc_corrected_err = i_external_irqs.lpddr_ppp_0__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_ppp_0__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_ppp_0__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_ppp_0__phy_init_cmplt = i_external_irqs.lpddr_ppp_0__phy_init_cmplt;
    o_all_irqs.lpddr_ppp_0__phy_trng_cmplt = i_external_irqs.lpddr_ppp_0__phy_trng_cmplt;
    o_all_irqs.lpddr_ppp_1__ctrl_sbr_done = i_external_irqs.lpddr_ppp_1__ctrl_sbr_done;
    o_all_irqs.lpddr_ppp_1__ctrl_ecc_corrected_err = i_external_irqs.lpddr_ppp_1__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_ppp_1__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_ppp_1__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_ppp_1__phy_init_cmplt = i_external_irqs.lpddr_ppp_1__phy_init_cmplt;
    o_all_irqs.lpddr_ppp_1__phy_trng_cmplt = i_external_irqs.lpddr_ppp_1__phy_trng_cmplt;
    o_all_irqs.lpddr_ppp_2__ctrl_sbr_done = i_external_irqs.lpddr_ppp_2__ctrl_sbr_done;
    o_all_irqs.lpddr_ppp_2__ctrl_ecc_corrected_err = i_external_irqs.lpddr_ppp_2__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_ppp_2__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_ppp_2__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_ppp_2__phy_init_cmplt = i_external_irqs.lpddr_ppp_2__phy_init_cmplt;
    o_all_irqs.lpddr_ppp_2__phy_trng_cmplt = i_external_irqs.lpddr_ppp_2__phy_trng_cmplt;
    o_all_irqs.lpddr_ppp_3__ctrl_sbr_done = i_external_irqs.lpddr_ppp_3__ctrl_sbr_done;
    o_all_irqs.lpddr_ppp_3__ctrl_ecc_corrected_err = i_external_irqs.lpddr_ppp_3__ctrl_ecc_corrected_err;
    o_all_irqs.lpddr_ppp_3__ctrl_rd_linkecc_corr_err = i_external_irqs.lpddr_ppp_3__ctrl_rd_linkecc_corr_err;
    o_all_irqs.lpddr_ppp_3__phy_init_cmplt = i_external_irqs.lpddr_ppp_3__phy_init_cmplt;
    o_all_irqs.lpddr_ppp_3__phy_trng_cmplt = i_external_irqs.lpddr_ppp_3__phy_trng_cmplt;
    o_all_irqs.soc_mgmt__security = i_external_irqs.soc_mgmt__security;
    o_all_irqs.soc_periph__emmc = i_external_irqs.soc_periph__emmc;
    o_all_irqs.dcd__int = i_external_irqs.dcd__int;
    o_all_irqs.noc__int = i_external_irqs.noc__int;
    o_all_irqs.noc__sdma_0_int_0 = i_external_irqs.noc__sdma_0_int_0;
    o_all_irqs.noc__sdma_0_int_1 = i_external_irqs.noc__sdma_0_int_1;
    o_all_irqs.noc__sdma_0_int_2 = i_external_irqs.noc__sdma_0_int_2;
    o_all_irqs.noc__sdma_0_int_3 = i_external_irqs.noc__sdma_0_int_3;
    o_all_irqs.noc__sdma_1_int_0 = i_external_irqs.noc__sdma_1_int_0;
    o_all_irqs.noc__sdma_1_int_1 = i_external_irqs.noc__sdma_1_int_1;
    o_all_irqs.noc__sdma_1_int_2 = i_external_irqs.noc__sdma_1_int_2;
    o_all_irqs.noc__sdma_1_int_3 = i_external_irqs.noc__sdma_1_int_3;
    o_all_irqs.soc_periph__uart = i_external_irqs.soc_periph__uart;
    o_all_irqs.soc_periph__gpio = i_external_irqs.soc_periph__gpio;
    o_all_irqs.soc_periph__i2c_0 = i_external_irqs.soc_periph__i2c_0;
    o_all_irqs.soc_periph__i2c_1 = i_external_irqs.soc_periph__i2c_1;
    o_all_irqs.soc_periph__spi = i_external_irqs.soc_periph__spi;
    o_all_irqs.pcie__int = i_external_irqs.pcie__int;
  end

endmodule
