// auto generated file with https://git.axelera.ai/vincent.morillon/ax65_wrapper

module ax65_bridge_wrapper #(
    parameter int unsigned CORE_WIDTH = 6,
    parameter int unsigned MAX_CORE_WIDTH = 8,
    parameter int unsigned SINK_WIDTH = 6,
    parameter int unsigned SOURCE_WIDTH = 5
) (
    input wire i_aclk,
    input logic i_test_mode,
    input wire [CORE_WIDTH - 1:0] i_us_cores_clk,
    input wire [CORE_WIDTH - 1:0] i_us_cores_rst_n,
    input wire [CORE_WIDTH - 1:0] i_us_cores_dcu_clk,
    input wire [CORE_WIDTH - 1:0] i_us_cores_l2_clk,
    input wire [CORE_WIDTH - 1:0] i_us_cores_l2_rst_n,
    input logic [CORE_WIDTH - 1:0] i_us_cores_coherent_enable,
    output logic [CORE_WIDTH - 1:0] o_us_cores_coherent_state,
    input logic [CORE_WIDTH - 1:0][39:0] i_us_cores_dcu_a_address,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_a_corrupt,
    input logic [CORE_WIDTH - 1:0][255:0] i_us_cores_dcu_a_data,
    input logic [CORE_WIDTH - 1:0][31:0] i_us_cores_dcu_a_mask,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_dcu_a_opcode,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_dcu_a_param,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_dcu_a_size,
    input logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_us_cores_dcu_a_source,
    input logic [CORE_WIDTH - 1:0][11:0] i_us_cores_dcu_a_user,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_a_ready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_a_valid,
    output logic [CORE_WIDTH - 1:0][39:0] o_us_cores_dcu_b_address,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_b_corrupt,
    output logic [CORE_WIDTH - 1:0][255:0] o_us_cores_dcu_b_data,
    output logic [CORE_WIDTH - 1:0][31:0] o_us_cores_dcu_b_mask,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_dcu_b_opcode,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_dcu_b_param,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_dcu_b_size,
    output logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_us_cores_dcu_b_source,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_b_ready,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_b_valid,
    input logic [CORE_WIDTH - 1:0][39:0] i_us_cores_dcu_c_address,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_c_corrupt,
    input logic [CORE_WIDTH - 1:0][255:0] i_us_cores_dcu_c_data,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_dcu_c_opcode,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_dcu_c_param,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_dcu_c_size,
    input logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_us_cores_dcu_c_source,
    input logic [CORE_WIDTH - 1:0][7:0] i_us_cores_dcu_c_user,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_c_ready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_c_valid,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_d_corrupt,
    output logic [CORE_WIDTH - 1:0][255:0] o_us_cores_dcu_d_data,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_d_denied,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_dcu_d_opcode,
    output logic [CORE_WIDTH - 1:0][1:0] o_us_cores_dcu_d_param,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_dcu_d_size,
    output logic [CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] o_us_cores_dcu_d_sink,
    output logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_us_cores_dcu_d_source,
    output logic [CORE_WIDTH - 1:0][5:0] o_us_cores_dcu_d_user,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_d_ready,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_d_valid,
    input logic [CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] i_us_cores_dcu_e_sink,
    output logic [CORE_WIDTH - 1:0] o_us_cores_dcu_e_ready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_dcu_e_valid,
    input logic [CORE_WIDTH - 1:0][39:0] i_us_cores_icu_a_address,
    input logic [CORE_WIDTH - 1:0] i_us_cores_icu_a_corrupt,
    input logic [CORE_WIDTH - 1:0][255:0] i_us_cores_icu_a_data,
    input logic [CORE_WIDTH - 1:0][31:0] i_us_cores_icu_a_mask,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_icu_a_opcode,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_icu_a_param,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_icu_a_size,
    input logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_us_cores_icu_a_source,
    input logic [CORE_WIDTH - 1:0][11:0] i_us_cores_icu_a_user,
    output logic [CORE_WIDTH - 1:0] o_us_cores_icu_a_ready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_icu_a_valid,
    output logic [CORE_WIDTH - 1:0] o_us_cores_icu_d_corrupt,
    output logic [CORE_WIDTH - 1:0][255:0] o_us_cores_icu_d_data,
    output logic [CORE_WIDTH - 1:0] o_us_cores_icu_d_denied,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_icu_d_opcode,
    output logic [CORE_WIDTH - 1:0][1:0] o_us_cores_icu_d_param,
    output logic [CORE_WIDTH - 1:0][2:0] o_us_cores_icu_d_size,
    output logic [CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] o_us_cores_icu_d_sink,
    output logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_us_cores_icu_d_source,
    output logic [CORE_WIDTH - 1:0][5:0] o_us_cores_icu_d_user,
    input logic [CORE_WIDTH - 1:0] i_us_cores_icu_d_ready,
    output logic [CORE_WIDTH - 1:0] o_us_cores_icu_d_valid,
    input logic [CORE_WIDTH - 1:0][39:0] i_us_cores_mpipe_axi_s_araddr,
    input logic [CORE_WIDTH - 1:0][1:0] i_us_cores_mpipe_axi_s_arburst,
    input logic [CORE_WIDTH - 1:0][3:0] i_us_cores_mpipe_axi_s_arcache,
    input logic [CORE_WIDTH - 1:0][4:0] i_us_cores_mpipe_axi_s_arid,
    input logic [CORE_WIDTH - 1:0][7:0] i_us_cores_mpipe_axi_s_arlen,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_arlock,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_mpipe_axi_s_arprot,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_mpipe_axi_s_arsize,
    output logic [CORE_WIDTH - 1:0] o_us_cores_mpipe_axi_s_arready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_arvalid,
    input logic [CORE_WIDTH - 1:0][39:0] i_us_cores_mpipe_axi_s_awaddr,
    input logic [CORE_WIDTH - 1:0][1:0] i_us_cores_mpipe_axi_s_awburst,
    input logic [CORE_WIDTH - 1:0][3:0] i_us_cores_mpipe_axi_s_awcache,
    input logic [CORE_WIDTH - 1:0][4:0] i_us_cores_mpipe_axi_s_awid,
    input logic [CORE_WIDTH - 1:0][7:0] i_us_cores_mpipe_axi_s_awlen,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_awlock,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_mpipe_axi_s_awprot,
    input logic [CORE_WIDTH - 1:0][2:0] i_us_cores_mpipe_axi_s_awsize,
    output logic [CORE_WIDTH - 1:0] o_us_cores_mpipe_axi_s_awready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_awvalid,
    output logic [CORE_WIDTH - 1:0][4:0] o_us_cores_mpipe_axi_s_bid,
    output logic [CORE_WIDTH - 1:0][1:0] o_us_cores_mpipe_axi_s_bresp,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_bready,
    output logic [CORE_WIDTH - 1:0] o_us_cores_mpipe_axi_s_bvalid,
    output logic [CORE_WIDTH - 1:0][63:0] o_us_cores_mpipe_axi_s_rdata,
    output logic [CORE_WIDTH - 1:0][4:0] o_us_cores_mpipe_axi_s_rid,
    output logic [CORE_WIDTH - 1:0] o_us_cores_mpipe_axi_s_rlast,
    output logic [CORE_WIDTH - 1:0][1:0] o_us_cores_mpipe_axi_s_rresp,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_rready,
    output logic [CORE_WIDTH - 1:0] o_us_cores_mpipe_axi_s_rvalid,
    input logic [CORE_WIDTH - 1:0][63:0] i_us_cores_mpipe_axi_s_wdata,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_wlast,
    input logic [CORE_WIDTH - 1:0][(64 / 8) -1:0] i_us_cores_mpipe_axi_s_wstrb,
    output logic [CORE_WIDTH - 1:0] o_us_cores_mpipe_axi_s_wready,
    input logic [CORE_WIDTH - 1:0] i_us_cores_mpipe_axi_s_wvalid,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_coherent_enable,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_coherent_state,
    output logic [MAX_CORE_WIDTH - 1:0][39:0] o_ds_cores_m0_a_address,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_a_corrupt,
    output logic [MAX_CORE_WIDTH - 1:0][255:0] o_ds_cores_m0_a_data,
    output logic [MAX_CORE_WIDTH - 1:0][31:0] o_ds_cores_m0_a_mask,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m0_a_opcode,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m0_a_param,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m0_a_size,
    output logic [MAX_CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_ds_cores_m0_a_source,
    output logic [MAX_CORE_WIDTH - 1:0][11:0] o_ds_cores_m0_a_user,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_a_ready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_a_valid,
    input logic [MAX_CORE_WIDTH - 1:0][39:0] i_ds_cores_m0_b_address,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_b_corrupt,
    input logic [MAX_CORE_WIDTH - 1:0][255:0] i_ds_cores_m0_b_data,
    input logic [MAX_CORE_WIDTH - 1:0][31:0] i_ds_cores_m0_b_mask,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m0_b_opcode,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m0_b_param,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m0_b_size,
    input logic [MAX_CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_ds_cores_m0_b_source,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_b_ready,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_b_valid,
    output logic [MAX_CORE_WIDTH - 1:0][39:0] o_ds_cores_m0_c_address,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_c_corrupt,
    output logic [MAX_CORE_WIDTH - 1:0][255:0] o_ds_cores_m0_c_data,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m0_c_opcode,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m0_c_param,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m0_c_size,
    output logic [MAX_CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_ds_cores_m0_c_source,
    output logic [MAX_CORE_WIDTH - 1:0][7:0] o_ds_cores_m0_c_user,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_c_ready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_c_valid,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_d_corrupt,
    input logic [MAX_CORE_WIDTH - 1:0][255:0] i_ds_cores_m0_d_data,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_d_denied,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m0_d_opcode,
    input logic [MAX_CORE_WIDTH - 1:0][1:0] i_ds_cores_m0_d_param,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m0_d_size,
    input logic [MAX_CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] i_ds_cores_m0_d_sink,
    input logic [MAX_CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_ds_cores_m0_d_source,
    input logic [MAX_CORE_WIDTH - 1:0][5:0] i_ds_cores_m0_d_user,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_d_ready,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_d_valid,
    output logic [MAX_CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] o_ds_cores_m0_e_sink,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m0_e_ready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m0_e_valid,
    output logic [MAX_CORE_WIDTH - 1:0][39:0] o_ds_cores_m1_axi_m_araddr,
    output logic [MAX_CORE_WIDTH - 1:0][1:0] o_ds_cores_m1_axi_m_arburst,
    output logic [MAX_CORE_WIDTH - 1:0][3:0] o_ds_cores_m1_axi_m_arcache,
    output logic [MAX_CORE_WIDTH - 1:0][4:0] o_ds_cores_m1_axi_m_arid,
    output logic [MAX_CORE_WIDTH - 1:0][7:0] o_ds_cores_m1_axi_m_arlen,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_arlock,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m1_axi_m_arprot,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m1_axi_m_arsize,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m1_axi_m_arready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_arvalid,
    output logic [MAX_CORE_WIDTH - 1:0][39:0] o_ds_cores_m1_axi_m_awaddr,
    output logic [MAX_CORE_WIDTH - 1:0][1:0] o_ds_cores_m1_axi_m_awburst,
    output logic [MAX_CORE_WIDTH - 1:0][3:0] o_ds_cores_m1_axi_m_awcache,
    output logic [MAX_CORE_WIDTH - 1:0][4:0] o_ds_cores_m1_axi_m_awid,
    output logic [MAX_CORE_WIDTH - 1:0][7:0] o_ds_cores_m1_axi_m_awlen,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_awlock,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m1_axi_m_awprot,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m1_axi_m_awsize,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m1_axi_m_awready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_awvalid,
    input logic [MAX_CORE_WIDTH - 1:0][4:0] i_ds_cores_m1_axi_m_bid,
    input logic [MAX_CORE_WIDTH - 1:0][1:0] i_ds_cores_m1_axi_m_bresp,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_bready,
    input logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_bvalid,
    input logic [MAX_CORE_WIDTH - 1:0][63:0] i_ds_cores_m1_axi_m_rdata,
    input logic [MAX_CORE_WIDTH - 1:0][4:0] i_ds_cores_m1_axi_m_rid,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m1_axi_m_rlast,
    input logic [MAX_CORE_WIDTH - 1:0][1:0] i_ds_cores_m1_axi_m_rresp,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_rready,
    input logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_rvalid,
    output logic [MAX_CORE_WIDTH - 1:0][63:0] o_ds_cores_m1_axi_m_wdata,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_wlast,
    output logic [MAX_CORE_WIDTH - 1:0][(64 / 8) -1:0] o_ds_cores_m1_axi_m_wstrb,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m1_axi_m_wready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m1_axi_m_wvalid,
    output logic [MAX_CORE_WIDTH - 1:0][39:0] o_ds_cores_m2_a_address,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m2_a_corrupt,
    output logic [MAX_CORE_WIDTH - 1:0][255:0] o_ds_cores_m2_a_data,
    output logic [MAX_CORE_WIDTH - 1:0][31:0] o_ds_cores_m2_a_mask,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m2_a_opcode,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m2_a_param,
    output logic [MAX_CORE_WIDTH - 1:0][2:0] o_ds_cores_m2_a_size,
    output logic [MAX_CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_ds_cores_m2_a_source,
    output logic [MAX_CORE_WIDTH - 1:0][11:0] o_ds_cores_m2_a_user,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m2_a_ready,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m2_a_valid,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m2_d_corrupt,
    input logic [MAX_CORE_WIDTH - 1:0][255:0] i_ds_cores_m2_d_data,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m2_d_denied,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m2_d_opcode,
    input logic [MAX_CORE_WIDTH - 1:0][1:0] i_ds_cores_m2_d_param,
    input logic [MAX_CORE_WIDTH - 1:0][2:0] i_ds_cores_m2_d_size,
    input logic [MAX_CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] i_ds_cores_m2_d_sink,
    input logic [MAX_CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_ds_cores_m2_d_source,
    input logic [MAX_CORE_WIDTH - 1:0][5:0] i_ds_cores_m2_d_user,
    output logic [MAX_CORE_WIDTH - 1:0] o_ds_cores_m2_d_ready,
    input logic [MAX_CORE_WIDTH - 1:0] i_ds_cores_m2_d_valid
);

  ax65_brg_top u_ax65_brg_top (
      .us_core0_clk(i_us_cores_clk[0]),
      .us_core0_reset_n(i_us_cores_rst_n[0]),
      .us_core0_dcu_clk(i_us_cores_dcu_clk[0]),
      .us_core0_l2_clk(i_us_cores_l2_clk[0]),
      .us_core0_l2_reset_n(i_us_cores_l2_rst_n[0]),
      .us_core0_csr_brg_core_coherent_enable(i_us_cores_coherent_enable[0]),
      .us_core0_brg_csr_core_coherent_state(o_us_cores_coherent_state[0]),
      .us_core0_dcu_a_address(i_us_cores_dcu_a_address[0]),
      .us_core0_dcu_a_corrupt(i_us_cores_dcu_a_corrupt[0]),
      .us_core0_dcu_a_data(i_us_cores_dcu_a_data[0]),
      .us_core0_dcu_a_mask(i_us_cores_dcu_a_mask[0]),
      .us_core0_dcu_a_opcode(i_us_cores_dcu_a_opcode[0]),
      .us_core0_dcu_a_param(i_us_cores_dcu_a_param[0]),
      .us_core0_dcu_a_size(i_us_cores_dcu_a_size[0]),
      .us_core0_dcu_a_source(i_us_cores_dcu_a_source[0]),
      .us_core0_dcu_a_user(i_us_cores_dcu_a_user[0]),
      .us_core0_dcu_a_ready(o_us_cores_dcu_a_ready[0]),
      .us_core0_dcu_a_valid(i_us_cores_dcu_a_valid[0]),
      .us_core0_dcu_b_address(o_us_cores_dcu_b_address[0]),
      .us_core0_dcu_b_corrupt(o_us_cores_dcu_b_corrupt[0]),
      .us_core0_dcu_b_data(o_us_cores_dcu_b_data[0]),
      .us_core0_dcu_b_mask(o_us_cores_dcu_b_mask[0]),
      .us_core0_dcu_b_opcode(o_us_cores_dcu_b_opcode[0]),
      .us_core0_dcu_b_param(o_us_cores_dcu_b_param[0]),
      .us_core0_dcu_b_size(o_us_cores_dcu_b_size[0]),
      .us_core0_dcu_b_source(o_us_cores_dcu_b_source[0]),
      .us_core0_dcu_b_ready(i_us_cores_dcu_b_ready[0]),
      .us_core0_dcu_b_valid(o_us_cores_dcu_b_valid[0]),
      .us_core0_dcu_c_address(i_us_cores_dcu_c_address[0]),
      .us_core0_dcu_c_corrupt(i_us_cores_dcu_c_corrupt[0]),
      .us_core0_dcu_c_data(i_us_cores_dcu_c_data[0]),
      .us_core0_dcu_c_opcode(i_us_cores_dcu_c_opcode[0]),
      .us_core0_dcu_c_param(i_us_cores_dcu_c_param[0]),
      .us_core0_dcu_c_size(i_us_cores_dcu_c_size[0]),
      .us_core0_dcu_c_source(i_us_cores_dcu_c_source[0]),
      .us_core0_dcu_c_user(i_us_cores_dcu_c_user[0]),
      .us_core0_dcu_c_ready(o_us_cores_dcu_c_ready[0]),
      .us_core0_dcu_c_valid(i_us_cores_dcu_c_valid[0]),
      .us_core0_dcu_d_corrupt(o_us_cores_dcu_d_corrupt[0]),
      .us_core0_dcu_d_data(o_us_cores_dcu_d_data[0]),
      .us_core0_dcu_d_denied(o_us_cores_dcu_d_denied[0]),
      .us_core0_dcu_d_opcode(o_us_cores_dcu_d_opcode[0]),
      .us_core0_dcu_d_param(o_us_cores_dcu_d_param[0]),
      .us_core0_dcu_d_size(o_us_cores_dcu_d_size[0]),
      .us_core0_dcu_d_sink(o_us_cores_dcu_d_sink[0]),
      .us_core0_dcu_d_source(o_us_cores_dcu_d_source[0]),
      .us_core0_dcu_d_user(o_us_cores_dcu_d_user[0]),
      .us_core0_dcu_d_ready(i_us_cores_dcu_d_ready[0]),
      .us_core0_dcu_d_valid(o_us_cores_dcu_d_valid[0]),
      .us_core0_dcu_e_sink(i_us_cores_dcu_e_sink[0]),
      .us_core0_dcu_e_ready(o_us_cores_dcu_e_ready[0]),
      .us_core0_dcu_e_valid(i_us_cores_dcu_e_valid[0]),
      .us_core0_icu_a_address(i_us_cores_icu_a_address[0]),
      .us_core0_icu_a_corrupt(i_us_cores_icu_a_corrupt[0]),
      .us_core0_icu_a_data(i_us_cores_icu_a_data[0]),
      .us_core0_icu_a_mask(i_us_cores_icu_a_mask[0]),
      .us_core0_icu_a_opcode(i_us_cores_icu_a_opcode[0]),
      .us_core0_icu_a_param(i_us_cores_icu_a_param[0]),
      .us_core0_icu_a_size(i_us_cores_icu_a_size[0]),
      .us_core0_icu_a_source(i_us_cores_icu_a_source[0]),
      .us_core0_icu_a_user(i_us_cores_icu_a_user[0]),
      .us_core0_icu_a_ready(o_us_cores_icu_a_ready[0]),
      .us_core0_icu_a_valid(i_us_cores_icu_a_valid[0]),
      .us_core0_icu_d_corrupt(o_us_cores_icu_d_corrupt[0]),
      .us_core0_icu_d_data(o_us_cores_icu_d_data[0]),
      .us_core0_icu_d_denied(o_us_cores_icu_d_denied[0]),
      .us_core0_icu_d_opcode(o_us_cores_icu_d_opcode[0]),
      .us_core0_icu_d_param(o_us_cores_icu_d_param[0]),
      .us_core0_icu_d_size(o_us_cores_icu_d_size[0]),
      .us_core0_icu_d_sink(o_us_cores_icu_d_sink[0]),
      .us_core0_icu_d_source(o_us_cores_icu_d_source[0]),
      .us_core0_icu_d_user(o_us_cores_icu_d_user[0]),
      .us_core0_icu_d_ready(i_us_cores_icu_d_ready[0]),
      .us_core0_icu_d_valid(o_us_cores_icu_d_valid[0]),
      .us_core0_mpipe_araddr(i_us_cores_mpipe_axi_s_araddr[0]),
      .us_core0_mpipe_arburst(i_us_cores_mpipe_axi_s_arburst[0]),
      .us_core0_mpipe_arcache(i_us_cores_mpipe_axi_s_arcache[0]),
      .us_core0_mpipe_arid(i_us_cores_mpipe_axi_s_arid[0]),
      .us_core0_mpipe_arlen(i_us_cores_mpipe_axi_s_arlen[0]),
      .us_core0_mpipe_arlock(i_us_cores_mpipe_axi_s_arlock[0]),
      .us_core0_mpipe_arprot(i_us_cores_mpipe_axi_s_arprot[0]),
      .us_core0_mpipe_arsize(i_us_cores_mpipe_axi_s_arsize[0]),
      .us_core0_mpipe_arready(o_us_cores_mpipe_axi_s_arready[0]),
      .us_core0_mpipe_arvalid(i_us_cores_mpipe_axi_s_arvalid[0]),
      .us_core0_mpipe_awaddr(i_us_cores_mpipe_axi_s_awaddr[0]),
      .us_core0_mpipe_awburst(i_us_cores_mpipe_axi_s_awburst[0]),
      .us_core0_mpipe_awcache(i_us_cores_mpipe_axi_s_awcache[0]),
      .us_core0_mpipe_awid(i_us_cores_mpipe_axi_s_awid[0]),
      .us_core0_mpipe_awlen(i_us_cores_mpipe_axi_s_awlen[0]),
      .us_core0_mpipe_awlock(i_us_cores_mpipe_axi_s_awlock[0]),
      .us_core0_mpipe_awprot(i_us_cores_mpipe_axi_s_awprot[0]),
      .us_core0_mpipe_awsize(i_us_cores_mpipe_axi_s_awsize[0]),
      .us_core0_mpipe_awready(o_us_cores_mpipe_axi_s_awready[0]),
      .us_core0_mpipe_awvalid(i_us_cores_mpipe_axi_s_awvalid[0]),
      .us_core0_mpipe_bid(o_us_cores_mpipe_axi_s_bid[0]),
      .us_core0_mpipe_bresp(o_us_cores_mpipe_axi_s_bresp[0]),
      .us_core0_mpipe_bready(i_us_cores_mpipe_axi_s_bready[0]),
      .us_core0_mpipe_bvalid(o_us_cores_mpipe_axi_s_bvalid[0]),
      .us_core0_mpipe_rdata(o_us_cores_mpipe_axi_s_rdata[0]),
      .us_core0_mpipe_rid(o_us_cores_mpipe_axi_s_rid[0]),
      .us_core0_mpipe_rlast(o_us_cores_mpipe_axi_s_rlast[0]),
      .us_core0_mpipe_rresp(o_us_cores_mpipe_axi_s_rresp[0]),
      .us_core0_mpipe_rready(i_us_cores_mpipe_axi_s_rready[0]),
      .us_core0_mpipe_rvalid(o_us_cores_mpipe_axi_s_rvalid[0]),
      .us_core0_mpipe_wdata(i_us_cores_mpipe_axi_s_wdata[0]),
      .us_core0_mpipe_wlast(i_us_cores_mpipe_axi_s_wlast[0]),
      .us_core0_mpipe_wstrb(i_us_cores_mpipe_axi_s_wstrb[0]),
      .us_core0_mpipe_wready(o_us_cores_mpipe_axi_s_wready[0]),
      .us_core0_mpipe_wvalid(i_us_cores_mpipe_axi_s_wvalid[0]),
      .us_core1_clk(i_us_cores_clk[1]),
      .us_core1_reset_n(i_us_cores_rst_n[1]),
      .us_core1_dcu_clk(i_us_cores_dcu_clk[1]),
      .us_core1_l2_clk(i_us_cores_l2_clk[1]),
      .us_core1_l2_reset_n(i_us_cores_l2_rst_n[1]),
      .us_core1_csr_brg_core_coherent_enable(i_us_cores_coherent_enable[1]),
      .us_core1_brg_csr_core_coherent_state(o_us_cores_coherent_state[1]),
      .us_core1_dcu_a_address(i_us_cores_dcu_a_address[1]),
      .us_core1_dcu_a_corrupt(i_us_cores_dcu_a_corrupt[1]),
      .us_core1_dcu_a_data(i_us_cores_dcu_a_data[1]),
      .us_core1_dcu_a_mask(i_us_cores_dcu_a_mask[1]),
      .us_core1_dcu_a_opcode(i_us_cores_dcu_a_opcode[1]),
      .us_core1_dcu_a_param(i_us_cores_dcu_a_param[1]),
      .us_core1_dcu_a_size(i_us_cores_dcu_a_size[1]),
      .us_core1_dcu_a_source(i_us_cores_dcu_a_source[1]),
      .us_core1_dcu_a_user(i_us_cores_dcu_a_user[1]),
      .us_core1_dcu_a_ready(o_us_cores_dcu_a_ready[1]),
      .us_core1_dcu_a_valid(i_us_cores_dcu_a_valid[1]),
      .us_core1_dcu_b_address(o_us_cores_dcu_b_address[1]),
      .us_core1_dcu_b_corrupt(o_us_cores_dcu_b_corrupt[1]),
      .us_core1_dcu_b_data(o_us_cores_dcu_b_data[1]),
      .us_core1_dcu_b_mask(o_us_cores_dcu_b_mask[1]),
      .us_core1_dcu_b_opcode(o_us_cores_dcu_b_opcode[1]),
      .us_core1_dcu_b_param(o_us_cores_dcu_b_param[1]),
      .us_core1_dcu_b_size(o_us_cores_dcu_b_size[1]),
      .us_core1_dcu_b_source(o_us_cores_dcu_b_source[1]),
      .us_core1_dcu_b_ready(i_us_cores_dcu_b_ready[1]),
      .us_core1_dcu_b_valid(o_us_cores_dcu_b_valid[1]),
      .us_core1_dcu_c_address(i_us_cores_dcu_c_address[1]),
      .us_core1_dcu_c_corrupt(i_us_cores_dcu_c_corrupt[1]),
      .us_core1_dcu_c_data(i_us_cores_dcu_c_data[1]),
      .us_core1_dcu_c_opcode(i_us_cores_dcu_c_opcode[1]),
      .us_core1_dcu_c_param(i_us_cores_dcu_c_param[1]),
      .us_core1_dcu_c_size(i_us_cores_dcu_c_size[1]),
      .us_core1_dcu_c_source(i_us_cores_dcu_c_source[1]),
      .us_core1_dcu_c_user(i_us_cores_dcu_c_user[1]),
      .us_core1_dcu_c_ready(o_us_cores_dcu_c_ready[1]),
      .us_core1_dcu_c_valid(i_us_cores_dcu_c_valid[1]),
      .us_core1_dcu_d_corrupt(o_us_cores_dcu_d_corrupt[1]),
      .us_core1_dcu_d_data(o_us_cores_dcu_d_data[1]),
      .us_core1_dcu_d_denied(o_us_cores_dcu_d_denied[1]),
      .us_core1_dcu_d_opcode(o_us_cores_dcu_d_opcode[1]),
      .us_core1_dcu_d_param(o_us_cores_dcu_d_param[1]),
      .us_core1_dcu_d_size(o_us_cores_dcu_d_size[1]),
      .us_core1_dcu_d_sink(o_us_cores_dcu_d_sink[1]),
      .us_core1_dcu_d_source(o_us_cores_dcu_d_source[1]),
      .us_core1_dcu_d_user(o_us_cores_dcu_d_user[1]),
      .us_core1_dcu_d_ready(i_us_cores_dcu_d_ready[1]),
      .us_core1_dcu_d_valid(o_us_cores_dcu_d_valid[1]),
      .us_core1_dcu_e_sink(i_us_cores_dcu_e_sink[1]),
      .us_core1_dcu_e_ready(o_us_cores_dcu_e_ready[1]),
      .us_core1_dcu_e_valid(i_us_cores_dcu_e_valid[1]),
      .us_core1_icu_a_address(i_us_cores_icu_a_address[1]),
      .us_core1_icu_a_corrupt(i_us_cores_icu_a_corrupt[1]),
      .us_core1_icu_a_data(i_us_cores_icu_a_data[1]),
      .us_core1_icu_a_mask(i_us_cores_icu_a_mask[1]),
      .us_core1_icu_a_opcode(i_us_cores_icu_a_opcode[1]),
      .us_core1_icu_a_param(i_us_cores_icu_a_param[1]),
      .us_core1_icu_a_size(i_us_cores_icu_a_size[1]),
      .us_core1_icu_a_source(i_us_cores_icu_a_source[1]),
      .us_core1_icu_a_user(i_us_cores_icu_a_user[1]),
      .us_core1_icu_a_ready(o_us_cores_icu_a_ready[1]),
      .us_core1_icu_a_valid(i_us_cores_icu_a_valid[1]),
      .us_core1_icu_d_corrupt(o_us_cores_icu_d_corrupt[1]),
      .us_core1_icu_d_data(o_us_cores_icu_d_data[1]),
      .us_core1_icu_d_denied(o_us_cores_icu_d_denied[1]),
      .us_core1_icu_d_opcode(o_us_cores_icu_d_opcode[1]),
      .us_core1_icu_d_param(o_us_cores_icu_d_param[1]),
      .us_core1_icu_d_size(o_us_cores_icu_d_size[1]),
      .us_core1_icu_d_sink(o_us_cores_icu_d_sink[1]),
      .us_core1_icu_d_source(o_us_cores_icu_d_source[1]),
      .us_core1_icu_d_user(o_us_cores_icu_d_user[1]),
      .us_core1_icu_d_ready(i_us_cores_icu_d_ready[1]),
      .us_core1_icu_d_valid(o_us_cores_icu_d_valid[1]),
      .us_core1_mpipe_araddr(i_us_cores_mpipe_axi_s_araddr[1]),
      .us_core1_mpipe_arburst(i_us_cores_mpipe_axi_s_arburst[1]),
      .us_core1_mpipe_arcache(i_us_cores_mpipe_axi_s_arcache[1]),
      .us_core1_mpipe_arid(i_us_cores_mpipe_axi_s_arid[1]),
      .us_core1_mpipe_arlen(i_us_cores_mpipe_axi_s_arlen[1]),
      .us_core1_mpipe_arlock(i_us_cores_mpipe_axi_s_arlock[1]),
      .us_core1_mpipe_arprot(i_us_cores_mpipe_axi_s_arprot[1]),
      .us_core1_mpipe_arsize(i_us_cores_mpipe_axi_s_arsize[1]),
      .us_core1_mpipe_arready(o_us_cores_mpipe_axi_s_arready[1]),
      .us_core1_mpipe_arvalid(i_us_cores_mpipe_axi_s_arvalid[1]),
      .us_core1_mpipe_awaddr(i_us_cores_mpipe_axi_s_awaddr[1]),
      .us_core1_mpipe_awburst(i_us_cores_mpipe_axi_s_awburst[1]),
      .us_core1_mpipe_awcache(i_us_cores_mpipe_axi_s_awcache[1]),
      .us_core1_mpipe_awid(i_us_cores_mpipe_axi_s_awid[1]),
      .us_core1_mpipe_awlen(i_us_cores_mpipe_axi_s_awlen[1]),
      .us_core1_mpipe_awlock(i_us_cores_mpipe_axi_s_awlock[1]),
      .us_core1_mpipe_awprot(i_us_cores_mpipe_axi_s_awprot[1]),
      .us_core1_mpipe_awsize(i_us_cores_mpipe_axi_s_awsize[1]),
      .us_core1_mpipe_awready(o_us_cores_mpipe_axi_s_awready[1]),
      .us_core1_mpipe_awvalid(i_us_cores_mpipe_axi_s_awvalid[1]),
      .us_core1_mpipe_bid(o_us_cores_mpipe_axi_s_bid[1]),
      .us_core1_mpipe_bresp(o_us_cores_mpipe_axi_s_bresp[1]),
      .us_core1_mpipe_bready(i_us_cores_mpipe_axi_s_bready[1]),
      .us_core1_mpipe_bvalid(o_us_cores_mpipe_axi_s_bvalid[1]),
      .us_core1_mpipe_rdata(o_us_cores_mpipe_axi_s_rdata[1]),
      .us_core1_mpipe_rid(o_us_cores_mpipe_axi_s_rid[1]),
      .us_core1_mpipe_rlast(o_us_cores_mpipe_axi_s_rlast[1]),
      .us_core1_mpipe_rresp(o_us_cores_mpipe_axi_s_rresp[1]),
      .us_core1_mpipe_rready(i_us_cores_mpipe_axi_s_rready[1]),
      .us_core1_mpipe_rvalid(o_us_cores_mpipe_axi_s_rvalid[1]),
      .us_core1_mpipe_wdata(i_us_cores_mpipe_axi_s_wdata[1]),
      .us_core1_mpipe_wlast(i_us_cores_mpipe_axi_s_wlast[1]),
      .us_core1_mpipe_wstrb(i_us_cores_mpipe_axi_s_wstrb[1]),
      .us_core1_mpipe_wready(o_us_cores_mpipe_axi_s_wready[1]),
      .us_core1_mpipe_wvalid(i_us_cores_mpipe_axi_s_wvalid[1]),
      .us_core2_clk(i_us_cores_clk[2]),
      .us_core2_reset_n(i_us_cores_rst_n[2]),
      .us_core2_dcu_clk(i_us_cores_dcu_clk[2]),
      .us_core2_l2_clk(i_us_cores_l2_clk[2]),
      .us_core2_l2_reset_n(i_us_cores_l2_rst_n[2]),
      .us_core2_csr_brg_core_coherent_enable(i_us_cores_coherent_enable[2]),
      .us_core2_brg_csr_core_coherent_state(o_us_cores_coherent_state[2]),
      .us_core2_dcu_a_address(i_us_cores_dcu_a_address[2]),
      .us_core2_dcu_a_corrupt(i_us_cores_dcu_a_corrupt[2]),
      .us_core2_dcu_a_data(i_us_cores_dcu_a_data[2]),
      .us_core2_dcu_a_mask(i_us_cores_dcu_a_mask[2]),
      .us_core2_dcu_a_opcode(i_us_cores_dcu_a_opcode[2]),
      .us_core2_dcu_a_param(i_us_cores_dcu_a_param[2]),
      .us_core2_dcu_a_size(i_us_cores_dcu_a_size[2]),
      .us_core2_dcu_a_source(i_us_cores_dcu_a_source[2]),
      .us_core2_dcu_a_user(i_us_cores_dcu_a_user[2]),
      .us_core2_dcu_a_ready(o_us_cores_dcu_a_ready[2]),
      .us_core2_dcu_a_valid(i_us_cores_dcu_a_valid[2]),
      .us_core2_dcu_b_address(o_us_cores_dcu_b_address[2]),
      .us_core2_dcu_b_corrupt(o_us_cores_dcu_b_corrupt[2]),
      .us_core2_dcu_b_data(o_us_cores_dcu_b_data[2]),
      .us_core2_dcu_b_mask(o_us_cores_dcu_b_mask[2]),
      .us_core2_dcu_b_opcode(o_us_cores_dcu_b_opcode[2]),
      .us_core2_dcu_b_param(o_us_cores_dcu_b_param[2]),
      .us_core2_dcu_b_size(o_us_cores_dcu_b_size[2]),
      .us_core2_dcu_b_source(o_us_cores_dcu_b_source[2]),
      .us_core2_dcu_b_ready(i_us_cores_dcu_b_ready[2]),
      .us_core2_dcu_b_valid(o_us_cores_dcu_b_valid[2]),
      .us_core2_dcu_c_address(i_us_cores_dcu_c_address[2]),
      .us_core2_dcu_c_corrupt(i_us_cores_dcu_c_corrupt[2]),
      .us_core2_dcu_c_data(i_us_cores_dcu_c_data[2]),
      .us_core2_dcu_c_opcode(i_us_cores_dcu_c_opcode[2]),
      .us_core2_dcu_c_param(i_us_cores_dcu_c_param[2]),
      .us_core2_dcu_c_size(i_us_cores_dcu_c_size[2]),
      .us_core2_dcu_c_source(i_us_cores_dcu_c_source[2]),
      .us_core2_dcu_c_user(i_us_cores_dcu_c_user[2]),
      .us_core2_dcu_c_ready(o_us_cores_dcu_c_ready[2]),
      .us_core2_dcu_c_valid(i_us_cores_dcu_c_valid[2]),
      .us_core2_dcu_d_corrupt(o_us_cores_dcu_d_corrupt[2]),
      .us_core2_dcu_d_data(o_us_cores_dcu_d_data[2]),
      .us_core2_dcu_d_denied(o_us_cores_dcu_d_denied[2]),
      .us_core2_dcu_d_opcode(o_us_cores_dcu_d_opcode[2]),
      .us_core2_dcu_d_param(o_us_cores_dcu_d_param[2]),
      .us_core2_dcu_d_size(o_us_cores_dcu_d_size[2]),
      .us_core2_dcu_d_sink(o_us_cores_dcu_d_sink[2]),
      .us_core2_dcu_d_source(o_us_cores_dcu_d_source[2]),
      .us_core2_dcu_d_user(o_us_cores_dcu_d_user[2]),
      .us_core2_dcu_d_ready(i_us_cores_dcu_d_ready[2]),
      .us_core2_dcu_d_valid(o_us_cores_dcu_d_valid[2]),
      .us_core2_dcu_e_sink(i_us_cores_dcu_e_sink[2]),
      .us_core2_dcu_e_ready(o_us_cores_dcu_e_ready[2]),
      .us_core2_dcu_e_valid(i_us_cores_dcu_e_valid[2]),
      .us_core2_icu_a_address(i_us_cores_icu_a_address[2]),
      .us_core2_icu_a_corrupt(i_us_cores_icu_a_corrupt[2]),
      .us_core2_icu_a_data(i_us_cores_icu_a_data[2]),
      .us_core2_icu_a_mask(i_us_cores_icu_a_mask[2]),
      .us_core2_icu_a_opcode(i_us_cores_icu_a_opcode[2]),
      .us_core2_icu_a_param(i_us_cores_icu_a_param[2]),
      .us_core2_icu_a_size(i_us_cores_icu_a_size[2]),
      .us_core2_icu_a_source(i_us_cores_icu_a_source[2]),
      .us_core2_icu_a_user(i_us_cores_icu_a_user[2]),
      .us_core2_icu_a_ready(o_us_cores_icu_a_ready[2]),
      .us_core2_icu_a_valid(i_us_cores_icu_a_valid[2]),
      .us_core2_icu_d_corrupt(o_us_cores_icu_d_corrupt[2]),
      .us_core2_icu_d_data(o_us_cores_icu_d_data[2]),
      .us_core2_icu_d_denied(o_us_cores_icu_d_denied[2]),
      .us_core2_icu_d_opcode(o_us_cores_icu_d_opcode[2]),
      .us_core2_icu_d_param(o_us_cores_icu_d_param[2]),
      .us_core2_icu_d_size(o_us_cores_icu_d_size[2]),
      .us_core2_icu_d_sink(o_us_cores_icu_d_sink[2]),
      .us_core2_icu_d_source(o_us_cores_icu_d_source[2]),
      .us_core2_icu_d_user(o_us_cores_icu_d_user[2]),
      .us_core2_icu_d_ready(i_us_cores_icu_d_ready[2]),
      .us_core2_icu_d_valid(o_us_cores_icu_d_valid[2]),
      .us_core2_mpipe_araddr(i_us_cores_mpipe_axi_s_araddr[2]),
      .us_core2_mpipe_arburst(i_us_cores_mpipe_axi_s_arburst[2]),
      .us_core2_mpipe_arcache(i_us_cores_mpipe_axi_s_arcache[2]),
      .us_core2_mpipe_arid(i_us_cores_mpipe_axi_s_arid[2]),
      .us_core2_mpipe_arlen(i_us_cores_mpipe_axi_s_arlen[2]),
      .us_core2_mpipe_arlock(i_us_cores_mpipe_axi_s_arlock[2]),
      .us_core2_mpipe_arprot(i_us_cores_mpipe_axi_s_arprot[2]),
      .us_core2_mpipe_arsize(i_us_cores_mpipe_axi_s_arsize[2]),
      .us_core2_mpipe_arready(o_us_cores_mpipe_axi_s_arready[2]),
      .us_core2_mpipe_arvalid(i_us_cores_mpipe_axi_s_arvalid[2]),
      .us_core2_mpipe_awaddr(i_us_cores_mpipe_axi_s_awaddr[2]),
      .us_core2_mpipe_awburst(i_us_cores_mpipe_axi_s_awburst[2]),
      .us_core2_mpipe_awcache(i_us_cores_mpipe_axi_s_awcache[2]),
      .us_core2_mpipe_awid(i_us_cores_mpipe_axi_s_awid[2]),
      .us_core2_mpipe_awlen(i_us_cores_mpipe_axi_s_awlen[2]),
      .us_core2_mpipe_awlock(i_us_cores_mpipe_axi_s_awlock[2]),
      .us_core2_mpipe_awprot(i_us_cores_mpipe_axi_s_awprot[2]),
      .us_core2_mpipe_awsize(i_us_cores_mpipe_axi_s_awsize[2]),
      .us_core2_mpipe_awready(o_us_cores_mpipe_axi_s_awready[2]),
      .us_core2_mpipe_awvalid(i_us_cores_mpipe_axi_s_awvalid[2]),
      .us_core2_mpipe_bid(o_us_cores_mpipe_axi_s_bid[2]),
      .us_core2_mpipe_bresp(o_us_cores_mpipe_axi_s_bresp[2]),
      .us_core2_mpipe_bready(i_us_cores_mpipe_axi_s_bready[2]),
      .us_core2_mpipe_bvalid(o_us_cores_mpipe_axi_s_bvalid[2]),
      .us_core2_mpipe_rdata(o_us_cores_mpipe_axi_s_rdata[2]),
      .us_core2_mpipe_rid(o_us_cores_mpipe_axi_s_rid[2]),
      .us_core2_mpipe_rlast(o_us_cores_mpipe_axi_s_rlast[2]),
      .us_core2_mpipe_rresp(o_us_cores_mpipe_axi_s_rresp[2]),
      .us_core2_mpipe_rready(i_us_cores_mpipe_axi_s_rready[2]),
      .us_core2_mpipe_rvalid(o_us_cores_mpipe_axi_s_rvalid[2]),
      .us_core2_mpipe_wdata(i_us_cores_mpipe_axi_s_wdata[2]),
      .us_core2_mpipe_wlast(i_us_cores_mpipe_axi_s_wlast[2]),
      .us_core2_mpipe_wstrb(i_us_cores_mpipe_axi_s_wstrb[2]),
      .us_core2_mpipe_wready(o_us_cores_mpipe_axi_s_wready[2]),
      .us_core2_mpipe_wvalid(i_us_cores_mpipe_axi_s_wvalid[2]),
      .us_core3_clk(i_us_cores_clk[3]),
      .us_core3_reset_n(i_us_cores_rst_n[3]),
      .us_core3_dcu_clk(i_us_cores_dcu_clk[3]),
      .us_core3_l2_clk(i_us_cores_l2_clk[3]),
      .us_core3_l2_reset_n(i_us_cores_l2_rst_n[3]),
      .us_core3_csr_brg_core_coherent_enable(i_us_cores_coherent_enable[3]),
      .us_core3_brg_csr_core_coherent_state(o_us_cores_coherent_state[3]),
      .us_core3_dcu_a_address(i_us_cores_dcu_a_address[3]),
      .us_core3_dcu_a_corrupt(i_us_cores_dcu_a_corrupt[3]),
      .us_core3_dcu_a_data(i_us_cores_dcu_a_data[3]),
      .us_core3_dcu_a_mask(i_us_cores_dcu_a_mask[3]),
      .us_core3_dcu_a_opcode(i_us_cores_dcu_a_opcode[3]),
      .us_core3_dcu_a_param(i_us_cores_dcu_a_param[3]),
      .us_core3_dcu_a_size(i_us_cores_dcu_a_size[3]),
      .us_core3_dcu_a_source(i_us_cores_dcu_a_source[3]),
      .us_core3_dcu_a_user(i_us_cores_dcu_a_user[3]),
      .us_core3_dcu_a_ready(o_us_cores_dcu_a_ready[3]),
      .us_core3_dcu_a_valid(i_us_cores_dcu_a_valid[3]),
      .us_core3_dcu_b_address(o_us_cores_dcu_b_address[3]),
      .us_core3_dcu_b_corrupt(o_us_cores_dcu_b_corrupt[3]),
      .us_core3_dcu_b_data(o_us_cores_dcu_b_data[3]),
      .us_core3_dcu_b_mask(o_us_cores_dcu_b_mask[3]),
      .us_core3_dcu_b_opcode(o_us_cores_dcu_b_opcode[3]),
      .us_core3_dcu_b_param(o_us_cores_dcu_b_param[3]),
      .us_core3_dcu_b_size(o_us_cores_dcu_b_size[3]),
      .us_core3_dcu_b_source(o_us_cores_dcu_b_source[3]),
      .us_core3_dcu_b_ready(i_us_cores_dcu_b_ready[3]),
      .us_core3_dcu_b_valid(o_us_cores_dcu_b_valid[3]),
      .us_core3_dcu_c_address(i_us_cores_dcu_c_address[3]),
      .us_core3_dcu_c_corrupt(i_us_cores_dcu_c_corrupt[3]),
      .us_core3_dcu_c_data(i_us_cores_dcu_c_data[3]),
      .us_core3_dcu_c_opcode(i_us_cores_dcu_c_opcode[3]),
      .us_core3_dcu_c_param(i_us_cores_dcu_c_param[3]),
      .us_core3_dcu_c_size(i_us_cores_dcu_c_size[3]),
      .us_core3_dcu_c_source(i_us_cores_dcu_c_source[3]),
      .us_core3_dcu_c_user(i_us_cores_dcu_c_user[3]),
      .us_core3_dcu_c_ready(o_us_cores_dcu_c_ready[3]),
      .us_core3_dcu_c_valid(i_us_cores_dcu_c_valid[3]),
      .us_core3_dcu_d_corrupt(o_us_cores_dcu_d_corrupt[3]),
      .us_core3_dcu_d_data(o_us_cores_dcu_d_data[3]),
      .us_core3_dcu_d_denied(o_us_cores_dcu_d_denied[3]),
      .us_core3_dcu_d_opcode(o_us_cores_dcu_d_opcode[3]),
      .us_core3_dcu_d_param(o_us_cores_dcu_d_param[3]),
      .us_core3_dcu_d_size(o_us_cores_dcu_d_size[3]),
      .us_core3_dcu_d_sink(o_us_cores_dcu_d_sink[3]),
      .us_core3_dcu_d_source(o_us_cores_dcu_d_source[3]),
      .us_core3_dcu_d_user(o_us_cores_dcu_d_user[3]),
      .us_core3_dcu_d_ready(i_us_cores_dcu_d_ready[3]),
      .us_core3_dcu_d_valid(o_us_cores_dcu_d_valid[3]),
      .us_core3_dcu_e_sink(i_us_cores_dcu_e_sink[3]),
      .us_core3_dcu_e_ready(o_us_cores_dcu_e_ready[3]),
      .us_core3_dcu_e_valid(i_us_cores_dcu_e_valid[3]),
      .us_core3_icu_a_address(i_us_cores_icu_a_address[3]),
      .us_core3_icu_a_corrupt(i_us_cores_icu_a_corrupt[3]),
      .us_core3_icu_a_data(i_us_cores_icu_a_data[3]),
      .us_core3_icu_a_mask(i_us_cores_icu_a_mask[3]),
      .us_core3_icu_a_opcode(i_us_cores_icu_a_opcode[3]),
      .us_core3_icu_a_param(i_us_cores_icu_a_param[3]),
      .us_core3_icu_a_size(i_us_cores_icu_a_size[3]),
      .us_core3_icu_a_source(i_us_cores_icu_a_source[3]),
      .us_core3_icu_a_user(i_us_cores_icu_a_user[3]),
      .us_core3_icu_a_ready(o_us_cores_icu_a_ready[3]),
      .us_core3_icu_a_valid(i_us_cores_icu_a_valid[3]),
      .us_core3_icu_d_corrupt(o_us_cores_icu_d_corrupt[3]),
      .us_core3_icu_d_data(o_us_cores_icu_d_data[3]),
      .us_core3_icu_d_denied(o_us_cores_icu_d_denied[3]),
      .us_core3_icu_d_opcode(o_us_cores_icu_d_opcode[3]),
      .us_core3_icu_d_param(o_us_cores_icu_d_param[3]),
      .us_core3_icu_d_size(o_us_cores_icu_d_size[3]),
      .us_core3_icu_d_sink(o_us_cores_icu_d_sink[3]),
      .us_core3_icu_d_source(o_us_cores_icu_d_source[3]),
      .us_core3_icu_d_user(o_us_cores_icu_d_user[3]),
      .us_core3_icu_d_ready(i_us_cores_icu_d_ready[3]),
      .us_core3_icu_d_valid(o_us_cores_icu_d_valid[3]),
      .us_core3_mpipe_araddr(i_us_cores_mpipe_axi_s_araddr[3]),
      .us_core3_mpipe_arburst(i_us_cores_mpipe_axi_s_arburst[3]),
      .us_core3_mpipe_arcache(i_us_cores_mpipe_axi_s_arcache[3]),
      .us_core3_mpipe_arid(i_us_cores_mpipe_axi_s_arid[3]),
      .us_core3_mpipe_arlen(i_us_cores_mpipe_axi_s_arlen[3]),
      .us_core3_mpipe_arlock(i_us_cores_mpipe_axi_s_arlock[3]),
      .us_core3_mpipe_arprot(i_us_cores_mpipe_axi_s_arprot[3]),
      .us_core3_mpipe_arsize(i_us_cores_mpipe_axi_s_arsize[3]),
      .us_core3_mpipe_arready(o_us_cores_mpipe_axi_s_arready[3]),
      .us_core3_mpipe_arvalid(i_us_cores_mpipe_axi_s_arvalid[3]),
      .us_core3_mpipe_awaddr(i_us_cores_mpipe_axi_s_awaddr[3]),
      .us_core3_mpipe_awburst(i_us_cores_mpipe_axi_s_awburst[3]),
      .us_core3_mpipe_awcache(i_us_cores_mpipe_axi_s_awcache[3]),
      .us_core3_mpipe_awid(i_us_cores_mpipe_axi_s_awid[3]),
      .us_core3_mpipe_awlen(i_us_cores_mpipe_axi_s_awlen[3]),
      .us_core3_mpipe_awlock(i_us_cores_mpipe_axi_s_awlock[3]),
      .us_core3_mpipe_awprot(i_us_cores_mpipe_axi_s_awprot[3]),
      .us_core3_mpipe_awsize(i_us_cores_mpipe_axi_s_awsize[3]),
      .us_core3_mpipe_awready(o_us_cores_mpipe_axi_s_awready[3]),
      .us_core3_mpipe_awvalid(i_us_cores_mpipe_axi_s_awvalid[3]),
      .us_core3_mpipe_bid(o_us_cores_mpipe_axi_s_bid[3]),
      .us_core3_mpipe_bresp(o_us_cores_mpipe_axi_s_bresp[3]),
      .us_core3_mpipe_bready(i_us_cores_mpipe_axi_s_bready[3]),
      .us_core3_mpipe_bvalid(o_us_cores_mpipe_axi_s_bvalid[3]),
      .us_core3_mpipe_rdata(o_us_cores_mpipe_axi_s_rdata[3]),
      .us_core3_mpipe_rid(o_us_cores_mpipe_axi_s_rid[3]),
      .us_core3_mpipe_rlast(o_us_cores_mpipe_axi_s_rlast[3]),
      .us_core3_mpipe_rresp(o_us_cores_mpipe_axi_s_rresp[3]),
      .us_core3_mpipe_rready(i_us_cores_mpipe_axi_s_rready[3]),
      .us_core3_mpipe_rvalid(o_us_cores_mpipe_axi_s_rvalid[3]),
      .us_core3_mpipe_wdata(i_us_cores_mpipe_axi_s_wdata[3]),
      .us_core3_mpipe_wlast(i_us_cores_mpipe_axi_s_wlast[3]),
      .us_core3_mpipe_wstrb(i_us_cores_mpipe_axi_s_wstrb[3]),
      .us_core3_mpipe_wready(o_us_cores_mpipe_axi_s_wready[3]),
      .us_core3_mpipe_wvalid(i_us_cores_mpipe_axi_s_wvalid[3]),
      .us_core4_clk(i_us_cores_clk[4]),
      .us_core4_reset_n(i_us_cores_rst_n[4]),
      .us_core4_dcu_clk(i_us_cores_dcu_clk[4]),
      .us_core4_l2_clk(i_us_cores_l2_clk[4]),
      .us_core4_l2_reset_n(i_us_cores_l2_rst_n[4]),
      .us_core4_csr_brg_core_coherent_enable(i_us_cores_coherent_enable[4]),
      .us_core4_brg_csr_core_coherent_state(o_us_cores_coherent_state[4]),
      .us_core4_dcu_a_address(i_us_cores_dcu_a_address[4]),
      .us_core4_dcu_a_corrupt(i_us_cores_dcu_a_corrupt[4]),
      .us_core4_dcu_a_data(i_us_cores_dcu_a_data[4]),
      .us_core4_dcu_a_mask(i_us_cores_dcu_a_mask[4]),
      .us_core4_dcu_a_opcode(i_us_cores_dcu_a_opcode[4]),
      .us_core4_dcu_a_param(i_us_cores_dcu_a_param[4]),
      .us_core4_dcu_a_size(i_us_cores_dcu_a_size[4]),
      .us_core4_dcu_a_source(i_us_cores_dcu_a_source[4]),
      .us_core4_dcu_a_user(i_us_cores_dcu_a_user[4]),
      .us_core4_dcu_a_ready(o_us_cores_dcu_a_ready[4]),
      .us_core4_dcu_a_valid(i_us_cores_dcu_a_valid[4]),
      .us_core4_dcu_b_address(o_us_cores_dcu_b_address[4]),
      .us_core4_dcu_b_corrupt(o_us_cores_dcu_b_corrupt[4]),
      .us_core4_dcu_b_data(o_us_cores_dcu_b_data[4]),
      .us_core4_dcu_b_mask(o_us_cores_dcu_b_mask[4]),
      .us_core4_dcu_b_opcode(o_us_cores_dcu_b_opcode[4]),
      .us_core4_dcu_b_param(o_us_cores_dcu_b_param[4]),
      .us_core4_dcu_b_size(o_us_cores_dcu_b_size[4]),
      .us_core4_dcu_b_source(o_us_cores_dcu_b_source[4]),
      .us_core4_dcu_b_ready(i_us_cores_dcu_b_ready[4]),
      .us_core4_dcu_b_valid(o_us_cores_dcu_b_valid[4]),
      .us_core4_dcu_c_address(i_us_cores_dcu_c_address[4]),
      .us_core4_dcu_c_corrupt(i_us_cores_dcu_c_corrupt[4]),
      .us_core4_dcu_c_data(i_us_cores_dcu_c_data[4]),
      .us_core4_dcu_c_opcode(i_us_cores_dcu_c_opcode[4]),
      .us_core4_dcu_c_param(i_us_cores_dcu_c_param[4]),
      .us_core4_dcu_c_size(i_us_cores_dcu_c_size[4]),
      .us_core4_dcu_c_source(i_us_cores_dcu_c_source[4]),
      .us_core4_dcu_c_user(i_us_cores_dcu_c_user[4]),
      .us_core4_dcu_c_ready(o_us_cores_dcu_c_ready[4]),
      .us_core4_dcu_c_valid(i_us_cores_dcu_c_valid[4]),
      .us_core4_dcu_d_corrupt(o_us_cores_dcu_d_corrupt[4]),
      .us_core4_dcu_d_data(o_us_cores_dcu_d_data[4]),
      .us_core4_dcu_d_denied(o_us_cores_dcu_d_denied[4]),
      .us_core4_dcu_d_opcode(o_us_cores_dcu_d_opcode[4]),
      .us_core4_dcu_d_param(o_us_cores_dcu_d_param[4]),
      .us_core4_dcu_d_size(o_us_cores_dcu_d_size[4]),
      .us_core4_dcu_d_sink(o_us_cores_dcu_d_sink[4]),
      .us_core4_dcu_d_source(o_us_cores_dcu_d_source[4]),
      .us_core4_dcu_d_user(o_us_cores_dcu_d_user[4]),
      .us_core4_dcu_d_ready(i_us_cores_dcu_d_ready[4]),
      .us_core4_dcu_d_valid(o_us_cores_dcu_d_valid[4]),
      .us_core4_dcu_e_sink(i_us_cores_dcu_e_sink[4]),
      .us_core4_dcu_e_ready(o_us_cores_dcu_e_ready[4]),
      .us_core4_dcu_e_valid(i_us_cores_dcu_e_valid[4]),
      .us_core4_icu_a_address(i_us_cores_icu_a_address[4]),
      .us_core4_icu_a_corrupt(i_us_cores_icu_a_corrupt[4]),
      .us_core4_icu_a_data(i_us_cores_icu_a_data[4]),
      .us_core4_icu_a_mask(i_us_cores_icu_a_mask[4]),
      .us_core4_icu_a_opcode(i_us_cores_icu_a_opcode[4]),
      .us_core4_icu_a_param(i_us_cores_icu_a_param[4]),
      .us_core4_icu_a_size(i_us_cores_icu_a_size[4]),
      .us_core4_icu_a_source(i_us_cores_icu_a_source[4]),
      .us_core4_icu_a_user(i_us_cores_icu_a_user[4]),
      .us_core4_icu_a_ready(o_us_cores_icu_a_ready[4]),
      .us_core4_icu_a_valid(i_us_cores_icu_a_valid[4]),
      .us_core4_icu_d_corrupt(o_us_cores_icu_d_corrupt[4]),
      .us_core4_icu_d_data(o_us_cores_icu_d_data[4]),
      .us_core4_icu_d_denied(o_us_cores_icu_d_denied[4]),
      .us_core4_icu_d_opcode(o_us_cores_icu_d_opcode[4]),
      .us_core4_icu_d_param(o_us_cores_icu_d_param[4]),
      .us_core4_icu_d_size(o_us_cores_icu_d_size[4]),
      .us_core4_icu_d_sink(o_us_cores_icu_d_sink[4]),
      .us_core4_icu_d_source(o_us_cores_icu_d_source[4]),
      .us_core4_icu_d_user(o_us_cores_icu_d_user[4]),
      .us_core4_icu_d_ready(i_us_cores_icu_d_ready[4]),
      .us_core4_icu_d_valid(o_us_cores_icu_d_valid[4]),
      .us_core4_mpipe_araddr(i_us_cores_mpipe_axi_s_araddr[4]),
      .us_core4_mpipe_arburst(i_us_cores_mpipe_axi_s_arburst[4]),
      .us_core4_mpipe_arcache(i_us_cores_mpipe_axi_s_arcache[4]),
      .us_core4_mpipe_arid(i_us_cores_mpipe_axi_s_arid[4]),
      .us_core4_mpipe_arlen(i_us_cores_mpipe_axi_s_arlen[4]),
      .us_core4_mpipe_arlock(i_us_cores_mpipe_axi_s_arlock[4]),
      .us_core4_mpipe_arprot(i_us_cores_mpipe_axi_s_arprot[4]),
      .us_core4_mpipe_arsize(i_us_cores_mpipe_axi_s_arsize[4]),
      .us_core4_mpipe_arready(o_us_cores_mpipe_axi_s_arready[4]),
      .us_core4_mpipe_arvalid(i_us_cores_mpipe_axi_s_arvalid[4]),
      .us_core4_mpipe_awaddr(i_us_cores_mpipe_axi_s_awaddr[4]),
      .us_core4_mpipe_awburst(i_us_cores_mpipe_axi_s_awburst[4]),
      .us_core4_mpipe_awcache(i_us_cores_mpipe_axi_s_awcache[4]),
      .us_core4_mpipe_awid(i_us_cores_mpipe_axi_s_awid[4]),
      .us_core4_mpipe_awlen(i_us_cores_mpipe_axi_s_awlen[4]),
      .us_core4_mpipe_awlock(i_us_cores_mpipe_axi_s_awlock[4]),
      .us_core4_mpipe_awprot(i_us_cores_mpipe_axi_s_awprot[4]),
      .us_core4_mpipe_awsize(i_us_cores_mpipe_axi_s_awsize[4]),
      .us_core4_mpipe_awready(o_us_cores_mpipe_axi_s_awready[4]),
      .us_core4_mpipe_awvalid(i_us_cores_mpipe_axi_s_awvalid[4]),
      .us_core4_mpipe_bid(o_us_cores_mpipe_axi_s_bid[4]),
      .us_core4_mpipe_bresp(o_us_cores_mpipe_axi_s_bresp[4]),
      .us_core4_mpipe_bready(i_us_cores_mpipe_axi_s_bready[4]),
      .us_core4_mpipe_bvalid(o_us_cores_mpipe_axi_s_bvalid[4]),
      .us_core4_mpipe_rdata(o_us_cores_mpipe_axi_s_rdata[4]),
      .us_core4_mpipe_rid(o_us_cores_mpipe_axi_s_rid[4]),
      .us_core4_mpipe_rlast(o_us_cores_mpipe_axi_s_rlast[4]),
      .us_core4_mpipe_rresp(o_us_cores_mpipe_axi_s_rresp[4]),
      .us_core4_mpipe_rready(i_us_cores_mpipe_axi_s_rready[4]),
      .us_core4_mpipe_rvalid(o_us_cores_mpipe_axi_s_rvalid[4]),
      .us_core4_mpipe_wdata(i_us_cores_mpipe_axi_s_wdata[4]),
      .us_core4_mpipe_wlast(i_us_cores_mpipe_axi_s_wlast[4]),
      .us_core4_mpipe_wstrb(i_us_cores_mpipe_axi_s_wstrb[4]),
      .us_core4_mpipe_wready(o_us_cores_mpipe_axi_s_wready[4]),
      .us_core4_mpipe_wvalid(i_us_cores_mpipe_axi_s_wvalid[4]),
      .us_core5_clk(i_us_cores_clk[5]),
      .us_core5_reset_n(i_us_cores_rst_n[5]),
      .us_core5_dcu_clk(i_us_cores_dcu_clk[5]),
      .us_core5_l2_clk(i_us_cores_l2_clk[5]),
      .us_core5_l2_reset_n(i_us_cores_l2_rst_n[5]),
      .us_core5_csr_brg_core_coherent_enable(i_us_cores_coherent_enable[5]),
      .us_core5_brg_csr_core_coherent_state(o_us_cores_coherent_state[5]),
      .us_core5_dcu_a_address(i_us_cores_dcu_a_address[5]),
      .us_core5_dcu_a_corrupt(i_us_cores_dcu_a_corrupt[5]),
      .us_core5_dcu_a_data(i_us_cores_dcu_a_data[5]),
      .us_core5_dcu_a_mask(i_us_cores_dcu_a_mask[5]),
      .us_core5_dcu_a_opcode(i_us_cores_dcu_a_opcode[5]),
      .us_core5_dcu_a_param(i_us_cores_dcu_a_param[5]),
      .us_core5_dcu_a_size(i_us_cores_dcu_a_size[5]),
      .us_core5_dcu_a_source(i_us_cores_dcu_a_source[5]),
      .us_core5_dcu_a_user(i_us_cores_dcu_a_user[5]),
      .us_core5_dcu_a_ready(o_us_cores_dcu_a_ready[5]),
      .us_core5_dcu_a_valid(i_us_cores_dcu_a_valid[5]),
      .us_core5_dcu_b_address(o_us_cores_dcu_b_address[5]),
      .us_core5_dcu_b_corrupt(o_us_cores_dcu_b_corrupt[5]),
      .us_core5_dcu_b_data(o_us_cores_dcu_b_data[5]),
      .us_core5_dcu_b_mask(o_us_cores_dcu_b_mask[5]),
      .us_core5_dcu_b_opcode(o_us_cores_dcu_b_opcode[5]),
      .us_core5_dcu_b_param(o_us_cores_dcu_b_param[5]),
      .us_core5_dcu_b_size(o_us_cores_dcu_b_size[5]),
      .us_core5_dcu_b_source(o_us_cores_dcu_b_source[5]),
      .us_core5_dcu_b_ready(i_us_cores_dcu_b_ready[5]),
      .us_core5_dcu_b_valid(o_us_cores_dcu_b_valid[5]),
      .us_core5_dcu_c_address(i_us_cores_dcu_c_address[5]),
      .us_core5_dcu_c_corrupt(i_us_cores_dcu_c_corrupt[5]),
      .us_core5_dcu_c_data(i_us_cores_dcu_c_data[5]),
      .us_core5_dcu_c_opcode(i_us_cores_dcu_c_opcode[5]),
      .us_core5_dcu_c_param(i_us_cores_dcu_c_param[5]),
      .us_core5_dcu_c_size(i_us_cores_dcu_c_size[5]),
      .us_core5_dcu_c_source(i_us_cores_dcu_c_source[5]),
      .us_core5_dcu_c_user(i_us_cores_dcu_c_user[5]),
      .us_core5_dcu_c_ready(o_us_cores_dcu_c_ready[5]),
      .us_core5_dcu_c_valid(i_us_cores_dcu_c_valid[5]),
      .us_core5_dcu_d_corrupt(o_us_cores_dcu_d_corrupt[5]),
      .us_core5_dcu_d_data(o_us_cores_dcu_d_data[5]),
      .us_core5_dcu_d_denied(o_us_cores_dcu_d_denied[5]),
      .us_core5_dcu_d_opcode(o_us_cores_dcu_d_opcode[5]),
      .us_core5_dcu_d_param(o_us_cores_dcu_d_param[5]),
      .us_core5_dcu_d_size(o_us_cores_dcu_d_size[5]),
      .us_core5_dcu_d_sink(o_us_cores_dcu_d_sink[5]),
      .us_core5_dcu_d_source(o_us_cores_dcu_d_source[5]),
      .us_core5_dcu_d_user(o_us_cores_dcu_d_user[5]),
      .us_core5_dcu_d_ready(i_us_cores_dcu_d_ready[5]),
      .us_core5_dcu_d_valid(o_us_cores_dcu_d_valid[5]),
      .us_core5_dcu_e_sink(i_us_cores_dcu_e_sink[5]),
      .us_core5_dcu_e_ready(o_us_cores_dcu_e_ready[5]),
      .us_core5_dcu_e_valid(i_us_cores_dcu_e_valid[5]),
      .us_core5_icu_a_address(i_us_cores_icu_a_address[5]),
      .us_core5_icu_a_corrupt(i_us_cores_icu_a_corrupt[5]),
      .us_core5_icu_a_data(i_us_cores_icu_a_data[5]),
      .us_core5_icu_a_mask(i_us_cores_icu_a_mask[5]),
      .us_core5_icu_a_opcode(i_us_cores_icu_a_opcode[5]),
      .us_core5_icu_a_param(i_us_cores_icu_a_param[5]),
      .us_core5_icu_a_size(i_us_cores_icu_a_size[5]),
      .us_core5_icu_a_source(i_us_cores_icu_a_source[5]),
      .us_core5_icu_a_user(i_us_cores_icu_a_user[5]),
      .us_core5_icu_a_ready(o_us_cores_icu_a_ready[5]),
      .us_core5_icu_a_valid(i_us_cores_icu_a_valid[5]),
      .us_core5_icu_d_corrupt(o_us_cores_icu_d_corrupt[5]),
      .us_core5_icu_d_data(o_us_cores_icu_d_data[5]),
      .us_core5_icu_d_denied(o_us_cores_icu_d_denied[5]),
      .us_core5_icu_d_opcode(o_us_cores_icu_d_opcode[5]),
      .us_core5_icu_d_param(o_us_cores_icu_d_param[5]),
      .us_core5_icu_d_size(o_us_cores_icu_d_size[5]),
      .us_core5_icu_d_sink(o_us_cores_icu_d_sink[5]),
      .us_core5_icu_d_source(o_us_cores_icu_d_source[5]),
      .us_core5_icu_d_user(o_us_cores_icu_d_user[5]),
      .us_core5_icu_d_ready(i_us_cores_icu_d_ready[5]),
      .us_core5_icu_d_valid(o_us_cores_icu_d_valid[5]),
      .us_core5_mpipe_araddr(i_us_cores_mpipe_axi_s_araddr[5]),
      .us_core5_mpipe_arburst(i_us_cores_mpipe_axi_s_arburst[5]),
      .us_core5_mpipe_arcache(i_us_cores_mpipe_axi_s_arcache[5]),
      .us_core5_mpipe_arid(i_us_cores_mpipe_axi_s_arid[5]),
      .us_core5_mpipe_arlen(i_us_cores_mpipe_axi_s_arlen[5]),
      .us_core5_mpipe_arlock(i_us_cores_mpipe_axi_s_arlock[5]),
      .us_core5_mpipe_arprot(i_us_cores_mpipe_axi_s_arprot[5]),
      .us_core5_mpipe_arsize(i_us_cores_mpipe_axi_s_arsize[5]),
      .us_core5_mpipe_arready(o_us_cores_mpipe_axi_s_arready[5]),
      .us_core5_mpipe_arvalid(i_us_cores_mpipe_axi_s_arvalid[5]),
      .us_core5_mpipe_awaddr(i_us_cores_mpipe_axi_s_awaddr[5]),
      .us_core5_mpipe_awburst(i_us_cores_mpipe_axi_s_awburst[5]),
      .us_core5_mpipe_awcache(i_us_cores_mpipe_axi_s_awcache[5]),
      .us_core5_mpipe_awid(i_us_cores_mpipe_axi_s_awid[5]),
      .us_core5_mpipe_awlen(i_us_cores_mpipe_axi_s_awlen[5]),
      .us_core5_mpipe_awlock(i_us_cores_mpipe_axi_s_awlock[5]),
      .us_core5_mpipe_awprot(i_us_cores_mpipe_axi_s_awprot[5]),
      .us_core5_mpipe_awsize(i_us_cores_mpipe_axi_s_awsize[5]),
      .us_core5_mpipe_awready(o_us_cores_mpipe_axi_s_awready[5]),
      .us_core5_mpipe_awvalid(i_us_cores_mpipe_axi_s_awvalid[5]),
      .us_core5_mpipe_bid(o_us_cores_mpipe_axi_s_bid[5]),
      .us_core5_mpipe_bresp(o_us_cores_mpipe_axi_s_bresp[5]),
      .us_core5_mpipe_bready(i_us_cores_mpipe_axi_s_bready[5]),
      .us_core5_mpipe_bvalid(o_us_cores_mpipe_axi_s_bvalid[5]),
      .us_core5_mpipe_rdata(o_us_cores_mpipe_axi_s_rdata[5]),
      .us_core5_mpipe_rid(o_us_cores_mpipe_axi_s_rid[5]),
      .us_core5_mpipe_rlast(o_us_cores_mpipe_axi_s_rlast[5]),
      .us_core5_mpipe_rresp(o_us_cores_mpipe_axi_s_rresp[5]),
      .us_core5_mpipe_rready(i_us_cores_mpipe_axi_s_rready[5]),
      .us_core5_mpipe_rvalid(o_us_cores_mpipe_axi_s_rvalid[5]),
      .us_core5_mpipe_wdata(i_us_cores_mpipe_axi_s_wdata[5]),
      .us_core5_mpipe_wlast(i_us_cores_mpipe_axi_s_wlast[5]),
      .us_core5_mpipe_wstrb(i_us_cores_mpipe_axi_s_wstrb[5]),
      .us_core5_mpipe_wready(o_us_cores_mpipe_axi_s_wready[5]),
      .us_core5_mpipe_wvalid(i_us_cores_mpipe_axi_s_wvalid[5]),
      .aclk(i_aclk),
      .i_test_mode(i_test_mode),
      .ds_core0_coherent_enable(o_ds_cores_coherent_enable[0]),
      .ds_core1_coherent_enable(o_ds_cores_coherent_enable[1]),
      .ds_core2_coherent_enable(o_ds_cores_coherent_enable[2]),
      .ds_core3_coherent_enable(o_ds_cores_coherent_enable[3]),
      .ds_core4_coherent_enable(o_ds_cores_coherent_enable[4]),
      .ds_core5_coherent_enable(o_ds_cores_coherent_enable[5]),
      .ds_core6_coherent_enable(o_ds_cores_coherent_enable[6]),
      .ds_core7_coherent_enable(o_ds_cores_coherent_enable[7]),
      .ds_core0_coherent_state(i_ds_cores_coherent_state[0]),
      .ds_core1_coherent_state(i_ds_cores_coherent_state[1]),
      .ds_core2_coherent_state(i_ds_cores_coherent_state[2]),
      .ds_core3_coherent_state(i_ds_cores_coherent_state[3]),
      .ds_core4_coherent_state(i_ds_cores_coherent_state[4]),
      .ds_core5_coherent_state(i_ds_cores_coherent_state[5]),
      .ds_core6_coherent_state(i_ds_cores_coherent_state[6]),
      .ds_core7_coherent_state(i_ds_cores_coherent_state[7]),
      .ds_core0_m0_a_address(o_ds_cores_m0_a_address[0]),
      .ds_core1_m0_a_address(o_ds_cores_m0_a_address[1]),
      .ds_core2_m0_a_address(o_ds_cores_m0_a_address[2]),
      .ds_core3_m0_a_address(o_ds_cores_m0_a_address[3]),
      .ds_core4_m0_a_address(o_ds_cores_m0_a_address[4]),
      .ds_core5_m0_a_address(o_ds_cores_m0_a_address[5]),
      .ds_core6_m0_a_address(o_ds_cores_m0_a_address[6]),
      .ds_core7_m0_a_address(o_ds_cores_m0_a_address[7]),
      .ds_core0_m0_a_corrupt(o_ds_cores_m0_a_corrupt[0]),
      .ds_core1_m0_a_corrupt(o_ds_cores_m0_a_corrupt[1]),
      .ds_core2_m0_a_corrupt(o_ds_cores_m0_a_corrupt[2]),
      .ds_core3_m0_a_corrupt(o_ds_cores_m0_a_corrupt[3]),
      .ds_core4_m0_a_corrupt(o_ds_cores_m0_a_corrupt[4]),
      .ds_core5_m0_a_corrupt(o_ds_cores_m0_a_corrupt[5]),
      .ds_core6_m0_a_corrupt(o_ds_cores_m0_a_corrupt[6]),
      .ds_core7_m0_a_corrupt(o_ds_cores_m0_a_corrupt[7]),
      .ds_core0_m0_a_data(o_ds_cores_m0_a_data[0]),
      .ds_core1_m0_a_data(o_ds_cores_m0_a_data[1]),
      .ds_core2_m0_a_data(o_ds_cores_m0_a_data[2]),
      .ds_core3_m0_a_data(o_ds_cores_m0_a_data[3]),
      .ds_core4_m0_a_data(o_ds_cores_m0_a_data[4]),
      .ds_core5_m0_a_data(o_ds_cores_m0_a_data[5]),
      .ds_core6_m0_a_data(o_ds_cores_m0_a_data[6]),
      .ds_core7_m0_a_data(o_ds_cores_m0_a_data[7]),
      .ds_core0_m0_a_mask(o_ds_cores_m0_a_mask[0]),
      .ds_core1_m0_a_mask(o_ds_cores_m0_a_mask[1]),
      .ds_core2_m0_a_mask(o_ds_cores_m0_a_mask[2]),
      .ds_core3_m0_a_mask(o_ds_cores_m0_a_mask[3]),
      .ds_core4_m0_a_mask(o_ds_cores_m0_a_mask[4]),
      .ds_core5_m0_a_mask(o_ds_cores_m0_a_mask[5]),
      .ds_core6_m0_a_mask(o_ds_cores_m0_a_mask[6]),
      .ds_core7_m0_a_mask(o_ds_cores_m0_a_mask[7]),
      .ds_core0_m0_a_opcode(o_ds_cores_m0_a_opcode[0]),
      .ds_core1_m0_a_opcode(o_ds_cores_m0_a_opcode[1]),
      .ds_core2_m0_a_opcode(o_ds_cores_m0_a_opcode[2]),
      .ds_core3_m0_a_opcode(o_ds_cores_m0_a_opcode[3]),
      .ds_core4_m0_a_opcode(o_ds_cores_m0_a_opcode[4]),
      .ds_core5_m0_a_opcode(o_ds_cores_m0_a_opcode[5]),
      .ds_core6_m0_a_opcode(o_ds_cores_m0_a_opcode[6]),
      .ds_core7_m0_a_opcode(o_ds_cores_m0_a_opcode[7]),
      .ds_core0_m0_a_param(o_ds_cores_m0_a_param[0]),
      .ds_core1_m0_a_param(o_ds_cores_m0_a_param[1]),
      .ds_core2_m0_a_param(o_ds_cores_m0_a_param[2]),
      .ds_core3_m0_a_param(o_ds_cores_m0_a_param[3]),
      .ds_core4_m0_a_param(o_ds_cores_m0_a_param[4]),
      .ds_core5_m0_a_param(o_ds_cores_m0_a_param[5]),
      .ds_core6_m0_a_param(o_ds_cores_m0_a_param[6]),
      .ds_core7_m0_a_param(o_ds_cores_m0_a_param[7]),
      .ds_core0_m0_a_size(o_ds_cores_m0_a_size[0]),
      .ds_core1_m0_a_size(o_ds_cores_m0_a_size[1]),
      .ds_core2_m0_a_size(o_ds_cores_m0_a_size[2]),
      .ds_core3_m0_a_size(o_ds_cores_m0_a_size[3]),
      .ds_core4_m0_a_size(o_ds_cores_m0_a_size[4]),
      .ds_core5_m0_a_size(o_ds_cores_m0_a_size[5]),
      .ds_core6_m0_a_size(o_ds_cores_m0_a_size[6]),
      .ds_core7_m0_a_size(o_ds_cores_m0_a_size[7]),
      .ds_core0_m0_a_source(o_ds_cores_m0_a_source[0]),
      .ds_core1_m0_a_source(o_ds_cores_m0_a_source[1]),
      .ds_core2_m0_a_source(o_ds_cores_m0_a_source[2]),
      .ds_core3_m0_a_source(o_ds_cores_m0_a_source[3]),
      .ds_core4_m0_a_source(o_ds_cores_m0_a_source[4]),
      .ds_core5_m0_a_source(o_ds_cores_m0_a_source[5]),
      .ds_core6_m0_a_source(o_ds_cores_m0_a_source[6]),
      .ds_core7_m0_a_source(o_ds_cores_m0_a_source[7]),
      .ds_core0_m0_a_user(o_ds_cores_m0_a_user[0]),
      .ds_core1_m0_a_user(o_ds_cores_m0_a_user[1]),
      .ds_core2_m0_a_user(o_ds_cores_m0_a_user[2]),
      .ds_core3_m0_a_user(o_ds_cores_m0_a_user[3]),
      .ds_core4_m0_a_user(o_ds_cores_m0_a_user[4]),
      .ds_core5_m0_a_user(o_ds_cores_m0_a_user[5]),
      .ds_core6_m0_a_user(o_ds_cores_m0_a_user[6]),
      .ds_core7_m0_a_user(o_ds_cores_m0_a_user[7]),
      .ds_core0_m0_a_ready(i_ds_cores_m0_a_ready[0]),
      .ds_core1_m0_a_ready(i_ds_cores_m0_a_ready[1]),
      .ds_core2_m0_a_ready(i_ds_cores_m0_a_ready[2]),
      .ds_core3_m0_a_ready(i_ds_cores_m0_a_ready[3]),
      .ds_core4_m0_a_ready(i_ds_cores_m0_a_ready[4]),
      .ds_core5_m0_a_ready(i_ds_cores_m0_a_ready[5]),
      .ds_core6_m0_a_ready(i_ds_cores_m0_a_ready[6]),
      .ds_core7_m0_a_ready(i_ds_cores_m0_a_ready[7]),
      .ds_core0_m0_a_valid(o_ds_cores_m0_a_valid[0]),
      .ds_core1_m0_a_valid(o_ds_cores_m0_a_valid[1]),
      .ds_core2_m0_a_valid(o_ds_cores_m0_a_valid[2]),
      .ds_core3_m0_a_valid(o_ds_cores_m0_a_valid[3]),
      .ds_core4_m0_a_valid(o_ds_cores_m0_a_valid[4]),
      .ds_core5_m0_a_valid(o_ds_cores_m0_a_valid[5]),
      .ds_core6_m0_a_valid(o_ds_cores_m0_a_valid[6]),
      .ds_core7_m0_a_valid(o_ds_cores_m0_a_valid[7]),
      .ds_core0_m0_b_address(i_ds_cores_m0_b_address[0]),
      .ds_core1_m0_b_address(i_ds_cores_m0_b_address[1]),
      .ds_core2_m0_b_address(i_ds_cores_m0_b_address[2]),
      .ds_core3_m0_b_address(i_ds_cores_m0_b_address[3]),
      .ds_core4_m0_b_address(i_ds_cores_m0_b_address[4]),
      .ds_core5_m0_b_address(i_ds_cores_m0_b_address[5]),
      .ds_core6_m0_b_address(i_ds_cores_m0_b_address[6]),
      .ds_core7_m0_b_address(i_ds_cores_m0_b_address[7]),
      .ds_core0_m0_b_corrupt(i_ds_cores_m0_b_corrupt[0]),
      .ds_core1_m0_b_corrupt(i_ds_cores_m0_b_corrupt[1]),
      .ds_core2_m0_b_corrupt(i_ds_cores_m0_b_corrupt[2]),
      .ds_core3_m0_b_corrupt(i_ds_cores_m0_b_corrupt[3]),
      .ds_core4_m0_b_corrupt(i_ds_cores_m0_b_corrupt[4]),
      .ds_core5_m0_b_corrupt(i_ds_cores_m0_b_corrupt[5]),
      .ds_core6_m0_b_corrupt(i_ds_cores_m0_b_corrupt[6]),
      .ds_core7_m0_b_corrupt(i_ds_cores_m0_b_corrupt[7]),
      .ds_core0_m0_b_data(i_ds_cores_m0_b_data[0]),
      .ds_core1_m0_b_data(i_ds_cores_m0_b_data[1]),
      .ds_core2_m0_b_data(i_ds_cores_m0_b_data[2]),
      .ds_core3_m0_b_data(i_ds_cores_m0_b_data[3]),
      .ds_core4_m0_b_data(i_ds_cores_m0_b_data[4]),
      .ds_core5_m0_b_data(i_ds_cores_m0_b_data[5]),
      .ds_core6_m0_b_data(i_ds_cores_m0_b_data[6]),
      .ds_core7_m0_b_data(i_ds_cores_m0_b_data[7]),
      .ds_core0_m0_b_mask(i_ds_cores_m0_b_mask[0]),
      .ds_core1_m0_b_mask(i_ds_cores_m0_b_mask[1]),
      .ds_core2_m0_b_mask(i_ds_cores_m0_b_mask[2]),
      .ds_core3_m0_b_mask(i_ds_cores_m0_b_mask[3]),
      .ds_core4_m0_b_mask(i_ds_cores_m0_b_mask[4]),
      .ds_core5_m0_b_mask(i_ds_cores_m0_b_mask[5]),
      .ds_core6_m0_b_mask(i_ds_cores_m0_b_mask[6]),
      .ds_core7_m0_b_mask(i_ds_cores_m0_b_mask[7]),
      .ds_core0_m0_b_opcode(i_ds_cores_m0_b_opcode[0]),
      .ds_core1_m0_b_opcode(i_ds_cores_m0_b_opcode[1]),
      .ds_core2_m0_b_opcode(i_ds_cores_m0_b_opcode[2]),
      .ds_core3_m0_b_opcode(i_ds_cores_m0_b_opcode[3]),
      .ds_core4_m0_b_opcode(i_ds_cores_m0_b_opcode[4]),
      .ds_core5_m0_b_opcode(i_ds_cores_m0_b_opcode[5]),
      .ds_core6_m0_b_opcode(i_ds_cores_m0_b_opcode[6]),
      .ds_core7_m0_b_opcode(i_ds_cores_m0_b_opcode[7]),
      .ds_core0_m0_b_param(i_ds_cores_m0_b_param[0]),
      .ds_core1_m0_b_param(i_ds_cores_m0_b_param[1]),
      .ds_core2_m0_b_param(i_ds_cores_m0_b_param[2]),
      .ds_core3_m0_b_param(i_ds_cores_m0_b_param[3]),
      .ds_core4_m0_b_param(i_ds_cores_m0_b_param[4]),
      .ds_core5_m0_b_param(i_ds_cores_m0_b_param[5]),
      .ds_core6_m0_b_param(i_ds_cores_m0_b_param[6]),
      .ds_core7_m0_b_param(i_ds_cores_m0_b_param[7]),
      .ds_core0_m0_b_size(i_ds_cores_m0_b_size[0]),
      .ds_core1_m0_b_size(i_ds_cores_m0_b_size[1]),
      .ds_core2_m0_b_size(i_ds_cores_m0_b_size[2]),
      .ds_core3_m0_b_size(i_ds_cores_m0_b_size[3]),
      .ds_core4_m0_b_size(i_ds_cores_m0_b_size[4]),
      .ds_core5_m0_b_size(i_ds_cores_m0_b_size[5]),
      .ds_core6_m0_b_size(i_ds_cores_m0_b_size[6]),
      .ds_core7_m0_b_size(i_ds_cores_m0_b_size[7]),
      .ds_core0_m0_b_source(i_ds_cores_m0_b_source[0]),
      .ds_core1_m0_b_source(i_ds_cores_m0_b_source[1]),
      .ds_core2_m0_b_source(i_ds_cores_m0_b_source[2]),
      .ds_core3_m0_b_source(i_ds_cores_m0_b_source[3]),
      .ds_core4_m0_b_source(i_ds_cores_m0_b_source[4]),
      .ds_core5_m0_b_source(i_ds_cores_m0_b_source[5]),
      .ds_core6_m0_b_source(i_ds_cores_m0_b_source[6]),
      .ds_core7_m0_b_source(i_ds_cores_m0_b_source[7]),
      .ds_core0_m0_b_ready(o_ds_cores_m0_b_ready[0]),
      .ds_core1_m0_b_ready(o_ds_cores_m0_b_ready[1]),
      .ds_core2_m0_b_ready(o_ds_cores_m0_b_ready[2]),
      .ds_core3_m0_b_ready(o_ds_cores_m0_b_ready[3]),
      .ds_core4_m0_b_ready(o_ds_cores_m0_b_ready[4]),
      .ds_core5_m0_b_ready(o_ds_cores_m0_b_ready[5]),
      .ds_core6_m0_b_ready(o_ds_cores_m0_b_ready[6]),
      .ds_core7_m0_b_ready(o_ds_cores_m0_b_ready[7]),
      .ds_core0_m0_b_valid(i_ds_cores_m0_b_valid[0]),
      .ds_core1_m0_b_valid(i_ds_cores_m0_b_valid[1]),
      .ds_core2_m0_b_valid(i_ds_cores_m0_b_valid[2]),
      .ds_core3_m0_b_valid(i_ds_cores_m0_b_valid[3]),
      .ds_core4_m0_b_valid(i_ds_cores_m0_b_valid[4]),
      .ds_core5_m0_b_valid(i_ds_cores_m0_b_valid[5]),
      .ds_core6_m0_b_valid(i_ds_cores_m0_b_valid[6]),
      .ds_core7_m0_b_valid(i_ds_cores_m0_b_valid[7]),
      .ds_core0_m0_c_address(o_ds_cores_m0_c_address[0]),
      .ds_core1_m0_c_address(o_ds_cores_m0_c_address[1]),
      .ds_core2_m0_c_address(o_ds_cores_m0_c_address[2]),
      .ds_core3_m0_c_address(o_ds_cores_m0_c_address[3]),
      .ds_core4_m0_c_address(o_ds_cores_m0_c_address[4]),
      .ds_core5_m0_c_address(o_ds_cores_m0_c_address[5]),
      .ds_core6_m0_c_address(o_ds_cores_m0_c_address[6]),
      .ds_core7_m0_c_address(o_ds_cores_m0_c_address[7]),
      .ds_core0_m0_c_corrupt(o_ds_cores_m0_c_corrupt[0]),
      .ds_core1_m0_c_corrupt(o_ds_cores_m0_c_corrupt[1]),
      .ds_core2_m0_c_corrupt(o_ds_cores_m0_c_corrupt[2]),
      .ds_core3_m0_c_corrupt(o_ds_cores_m0_c_corrupt[3]),
      .ds_core4_m0_c_corrupt(o_ds_cores_m0_c_corrupt[4]),
      .ds_core5_m0_c_corrupt(o_ds_cores_m0_c_corrupt[5]),
      .ds_core6_m0_c_corrupt(o_ds_cores_m0_c_corrupt[6]),
      .ds_core7_m0_c_corrupt(o_ds_cores_m0_c_corrupt[7]),
      .ds_core0_m0_c_data(o_ds_cores_m0_c_data[0]),
      .ds_core1_m0_c_data(o_ds_cores_m0_c_data[1]),
      .ds_core2_m0_c_data(o_ds_cores_m0_c_data[2]),
      .ds_core3_m0_c_data(o_ds_cores_m0_c_data[3]),
      .ds_core4_m0_c_data(o_ds_cores_m0_c_data[4]),
      .ds_core5_m0_c_data(o_ds_cores_m0_c_data[5]),
      .ds_core6_m0_c_data(o_ds_cores_m0_c_data[6]),
      .ds_core7_m0_c_data(o_ds_cores_m0_c_data[7]),
      .ds_core0_m0_c_opcode(o_ds_cores_m0_c_opcode[0]),
      .ds_core1_m0_c_opcode(o_ds_cores_m0_c_opcode[1]),
      .ds_core2_m0_c_opcode(o_ds_cores_m0_c_opcode[2]),
      .ds_core3_m0_c_opcode(o_ds_cores_m0_c_opcode[3]),
      .ds_core4_m0_c_opcode(o_ds_cores_m0_c_opcode[4]),
      .ds_core5_m0_c_opcode(o_ds_cores_m0_c_opcode[5]),
      .ds_core6_m0_c_opcode(o_ds_cores_m0_c_opcode[6]),
      .ds_core7_m0_c_opcode(o_ds_cores_m0_c_opcode[7]),
      .ds_core0_m0_c_param(o_ds_cores_m0_c_param[0]),
      .ds_core1_m0_c_param(o_ds_cores_m0_c_param[1]),
      .ds_core2_m0_c_param(o_ds_cores_m0_c_param[2]),
      .ds_core3_m0_c_param(o_ds_cores_m0_c_param[3]),
      .ds_core4_m0_c_param(o_ds_cores_m0_c_param[4]),
      .ds_core5_m0_c_param(o_ds_cores_m0_c_param[5]),
      .ds_core6_m0_c_param(o_ds_cores_m0_c_param[6]),
      .ds_core7_m0_c_param(o_ds_cores_m0_c_param[7]),
      .ds_core0_m0_c_size(o_ds_cores_m0_c_size[0]),
      .ds_core1_m0_c_size(o_ds_cores_m0_c_size[1]),
      .ds_core2_m0_c_size(o_ds_cores_m0_c_size[2]),
      .ds_core3_m0_c_size(o_ds_cores_m0_c_size[3]),
      .ds_core4_m0_c_size(o_ds_cores_m0_c_size[4]),
      .ds_core5_m0_c_size(o_ds_cores_m0_c_size[5]),
      .ds_core6_m0_c_size(o_ds_cores_m0_c_size[6]),
      .ds_core7_m0_c_size(o_ds_cores_m0_c_size[7]),
      .ds_core0_m0_c_source(o_ds_cores_m0_c_source[0]),
      .ds_core1_m0_c_source(o_ds_cores_m0_c_source[1]),
      .ds_core2_m0_c_source(o_ds_cores_m0_c_source[2]),
      .ds_core3_m0_c_source(o_ds_cores_m0_c_source[3]),
      .ds_core4_m0_c_source(o_ds_cores_m0_c_source[4]),
      .ds_core5_m0_c_source(o_ds_cores_m0_c_source[5]),
      .ds_core6_m0_c_source(o_ds_cores_m0_c_source[6]),
      .ds_core7_m0_c_source(o_ds_cores_m0_c_source[7]),
      .ds_core0_m0_c_user(o_ds_cores_m0_c_user[0]),
      .ds_core1_m0_c_user(o_ds_cores_m0_c_user[1]),
      .ds_core2_m0_c_user(o_ds_cores_m0_c_user[2]),
      .ds_core3_m0_c_user(o_ds_cores_m0_c_user[3]),
      .ds_core4_m0_c_user(o_ds_cores_m0_c_user[4]),
      .ds_core5_m0_c_user(o_ds_cores_m0_c_user[5]),
      .ds_core6_m0_c_user(o_ds_cores_m0_c_user[6]),
      .ds_core7_m0_c_user(o_ds_cores_m0_c_user[7]),
      .ds_core0_m0_c_ready(i_ds_cores_m0_c_ready[0]),
      .ds_core1_m0_c_ready(i_ds_cores_m0_c_ready[1]),
      .ds_core2_m0_c_ready(i_ds_cores_m0_c_ready[2]),
      .ds_core3_m0_c_ready(i_ds_cores_m0_c_ready[3]),
      .ds_core4_m0_c_ready(i_ds_cores_m0_c_ready[4]),
      .ds_core5_m0_c_ready(i_ds_cores_m0_c_ready[5]),
      .ds_core6_m0_c_ready(i_ds_cores_m0_c_ready[6]),
      .ds_core7_m0_c_ready(i_ds_cores_m0_c_ready[7]),
      .ds_core0_m0_c_valid(o_ds_cores_m0_c_valid[0]),
      .ds_core1_m0_c_valid(o_ds_cores_m0_c_valid[1]),
      .ds_core2_m0_c_valid(o_ds_cores_m0_c_valid[2]),
      .ds_core3_m0_c_valid(o_ds_cores_m0_c_valid[3]),
      .ds_core4_m0_c_valid(o_ds_cores_m0_c_valid[4]),
      .ds_core5_m0_c_valid(o_ds_cores_m0_c_valid[5]),
      .ds_core6_m0_c_valid(o_ds_cores_m0_c_valid[6]),
      .ds_core7_m0_c_valid(o_ds_cores_m0_c_valid[7]),
      .ds_core0_m0_d_corrupt(i_ds_cores_m0_d_corrupt[0]),
      .ds_core1_m0_d_corrupt(i_ds_cores_m0_d_corrupt[1]),
      .ds_core2_m0_d_corrupt(i_ds_cores_m0_d_corrupt[2]),
      .ds_core3_m0_d_corrupt(i_ds_cores_m0_d_corrupt[3]),
      .ds_core4_m0_d_corrupt(i_ds_cores_m0_d_corrupt[4]),
      .ds_core5_m0_d_corrupt(i_ds_cores_m0_d_corrupt[5]),
      .ds_core6_m0_d_corrupt(i_ds_cores_m0_d_corrupt[6]),
      .ds_core7_m0_d_corrupt(i_ds_cores_m0_d_corrupt[7]),
      .ds_core0_m0_d_data(i_ds_cores_m0_d_data[0]),
      .ds_core1_m0_d_data(i_ds_cores_m0_d_data[1]),
      .ds_core2_m0_d_data(i_ds_cores_m0_d_data[2]),
      .ds_core3_m0_d_data(i_ds_cores_m0_d_data[3]),
      .ds_core4_m0_d_data(i_ds_cores_m0_d_data[4]),
      .ds_core5_m0_d_data(i_ds_cores_m0_d_data[5]),
      .ds_core6_m0_d_data(i_ds_cores_m0_d_data[6]),
      .ds_core7_m0_d_data(i_ds_cores_m0_d_data[7]),
      .ds_core0_m0_d_denied(i_ds_cores_m0_d_denied[0]),
      .ds_core1_m0_d_denied(i_ds_cores_m0_d_denied[1]),
      .ds_core2_m0_d_denied(i_ds_cores_m0_d_denied[2]),
      .ds_core3_m0_d_denied(i_ds_cores_m0_d_denied[3]),
      .ds_core4_m0_d_denied(i_ds_cores_m0_d_denied[4]),
      .ds_core5_m0_d_denied(i_ds_cores_m0_d_denied[5]),
      .ds_core6_m0_d_denied(i_ds_cores_m0_d_denied[6]),
      .ds_core7_m0_d_denied(i_ds_cores_m0_d_denied[7]),
      .ds_core0_m0_d_opcode(i_ds_cores_m0_d_opcode[0]),
      .ds_core1_m0_d_opcode(i_ds_cores_m0_d_opcode[1]),
      .ds_core2_m0_d_opcode(i_ds_cores_m0_d_opcode[2]),
      .ds_core3_m0_d_opcode(i_ds_cores_m0_d_opcode[3]),
      .ds_core4_m0_d_opcode(i_ds_cores_m0_d_opcode[4]),
      .ds_core5_m0_d_opcode(i_ds_cores_m0_d_opcode[5]),
      .ds_core6_m0_d_opcode(i_ds_cores_m0_d_opcode[6]),
      .ds_core7_m0_d_opcode(i_ds_cores_m0_d_opcode[7]),
      .ds_core0_m0_d_param(i_ds_cores_m0_d_param[0]),
      .ds_core1_m0_d_param(i_ds_cores_m0_d_param[1]),
      .ds_core2_m0_d_param(i_ds_cores_m0_d_param[2]),
      .ds_core3_m0_d_param(i_ds_cores_m0_d_param[3]),
      .ds_core4_m0_d_param(i_ds_cores_m0_d_param[4]),
      .ds_core5_m0_d_param(i_ds_cores_m0_d_param[5]),
      .ds_core6_m0_d_param(i_ds_cores_m0_d_param[6]),
      .ds_core7_m0_d_param(i_ds_cores_m0_d_param[7]),
      .ds_core0_m0_d_size(i_ds_cores_m0_d_size[0]),
      .ds_core1_m0_d_size(i_ds_cores_m0_d_size[1]),
      .ds_core2_m0_d_size(i_ds_cores_m0_d_size[2]),
      .ds_core3_m0_d_size(i_ds_cores_m0_d_size[3]),
      .ds_core4_m0_d_size(i_ds_cores_m0_d_size[4]),
      .ds_core5_m0_d_size(i_ds_cores_m0_d_size[5]),
      .ds_core6_m0_d_size(i_ds_cores_m0_d_size[6]),
      .ds_core7_m0_d_size(i_ds_cores_m0_d_size[7]),
      .ds_core0_m0_d_sink(i_ds_cores_m0_d_sink[0]),
      .ds_core1_m0_d_sink(i_ds_cores_m0_d_sink[1]),
      .ds_core2_m0_d_sink(i_ds_cores_m0_d_sink[2]),
      .ds_core3_m0_d_sink(i_ds_cores_m0_d_sink[3]),
      .ds_core4_m0_d_sink(i_ds_cores_m0_d_sink[4]),
      .ds_core5_m0_d_sink(i_ds_cores_m0_d_sink[5]),
      .ds_core6_m0_d_sink(i_ds_cores_m0_d_sink[6]),
      .ds_core7_m0_d_sink(i_ds_cores_m0_d_sink[7]),
      .ds_core0_m0_d_source(i_ds_cores_m0_d_source[0]),
      .ds_core1_m0_d_source(i_ds_cores_m0_d_source[1]),
      .ds_core2_m0_d_source(i_ds_cores_m0_d_source[2]),
      .ds_core3_m0_d_source(i_ds_cores_m0_d_source[3]),
      .ds_core4_m0_d_source(i_ds_cores_m0_d_source[4]),
      .ds_core5_m0_d_source(i_ds_cores_m0_d_source[5]),
      .ds_core6_m0_d_source(i_ds_cores_m0_d_source[6]),
      .ds_core7_m0_d_source(i_ds_cores_m0_d_source[7]),
      .ds_core0_m0_d_user(i_ds_cores_m0_d_user[0]),
      .ds_core1_m0_d_user(i_ds_cores_m0_d_user[1]),
      .ds_core2_m0_d_user(i_ds_cores_m0_d_user[2]),
      .ds_core3_m0_d_user(i_ds_cores_m0_d_user[3]),
      .ds_core4_m0_d_user(i_ds_cores_m0_d_user[4]),
      .ds_core5_m0_d_user(i_ds_cores_m0_d_user[5]),
      .ds_core6_m0_d_user(i_ds_cores_m0_d_user[6]),
      .ds_core7_m0_d_user(i_ds_cores_m0_d_user[7]),
      .ds_core0_m0_d_ready(o_ds_cores_m0_d_ready[0]),
      .ds_core1_m0_d_ready(o_ds_cores_m0_d_ready[1]),
      .ds_core2_m0_d_ready(o_ds_cores_m0_d_ready[2]),
      .ds_core3_m0_d_ready(o_ds_cores_m0_d_ready[3]),
      .ds_core4_m0_d_ready(o_ds_cores_m0_d_ready[4]),
      .ds_core5_m0_d_ready(o_ds_cores_m0_d_ready[5]),
      .ds_core6_m0_d_ready(o_ds_cores_m0_d_ready[6]),
      .ds_core7_m0_d_ready(o_ds_cores_m0_d_ready[7]),
      .ds_core0_m0_d_valid(i_ds_cores_m0_d_valid[0]),
      .ds_core1_m0_d_valid(i_ds_cores_m0_d_valid[1]),
      .ds_core2_m0_d_valid(i_ds_cores_m0_d_valid[2]),
      .ds_core3_m0_d_valid(i_ds_cores_m0_d_valid[3]),
      .ds_core4_m0_d_valid(i_ds_cores_m0_d_valid[4]),
      .ds_core5_m0_d_valid(i_ds_cores_m0_d_valid[5]),
      .ds_core6_m0_d_valid(i_ds_cores_m0_d_valid[6]),
      .ds_core7_m0_d_valid(i_ds_cores_m0_d_valid[7]),
      .ds_core0_m0_e_sink(o_ds_cores_m0_e_sink[0]),
      .ds_core1_m0_e_sink(o_ds_cores_m0_e_sink[1]),
      .ds_core2_m0_e_sink(o_ds_cores_m0_e_sink[2]),
      .ds_core3_m0_e_sink(o_ds_cores_m0_e_sink[3]),
      .ds_core4_m0_e_sink(o_ds_cores_m0_e_sink[4]),
      .ds_core5_m0_e_sink(o_ds_cores_m0_e_sink[5]),
      .ds_core6_m0_e_sink(o_ds_cores_m0_e_sink[6]),
      .ds_core7_m0_e_sink(o_ds_cores_m0_e_sink[7]),
      .ds_core0_m0_e_ready(i_ds_cores_m0_e_ready[0]),
      .ds_core1_m0_e_ready(i_ds_cores_m0_e_ready[1]),
      .ds_core2_m0_e_ready(i_ds_cores_m0_e_ready[2]),
      .ds_core3_m0_e_ready(i_ds_cores_m0_e_ready[3]),
      .ds_core4_m0_e_ready(i_ds_cores_m0_e_ready[4]),
      .ds_core5_m0_e_ready(i_ds_cores_m0_e_ready[5]),
      .ds_core6_m0_e_ready(i_ds_cores_m0_e_ready[6]),
      .ds_core7_m0_e_ready(i_ds_cores_m0_e_ready[7]),
      .ds_core0_m0_e_valid(o_ds_cores_m0_e_valid[0]),
      .ds_core1_m0_e_valid(o_ds_cores_m0_e_valid[1]),
      .ds_core2_m0_e_valid(o_ds_cores_m0_e_valid[2]),
      .ds_core3_m0_e_valid(o_ds_cores_m0_e_valid[3]),
      .ds_core4_m0_e_valid(o_ds_cores_m0_e_valid[4]),
      .ds_core5_m0_e_valid(o_ds_cores_m0_e_valid[5]),
      .ds_core6_m0_e_valid(o_ds_cores_m0_e_valid[6]),
      .ds_core7_m0_e_valid(o_ds_cores_m0_e_valid[7]),
      .ds_core0_m1_araddr(o_ds_cores_m1_axi_m_araddr[0]),
      .ds_core1_m1_araddr(o_ds_cores_m1_axi_m_araddr[1]),
      .ds_core2_m1_araddr(o_ds_cores_m1_axi_m_araddr[2]),
      .ds_core3_m1_araddr(o_ds_cores_m1_axi_m_araddr[3]),
      .ds_core4_m1_araddr(o_ds_cores_m1_axi_m_araddr[4]),
      .ds_core5_m1_araddr(o_ds_cores_m1_axi_m_araddr[5]),
      .ds_core6_m1_araddr(o_ds_cores_m1_axi_m_araddr[6]),
      .ds_core7_m1_araddr(o_ds_cores_m1_axi_m_araddr[7]),
      .ds_core0_m1_arburst(o_ds_cores_m1_axi_m_arburst[0]),
      .ds_core1_m1_arburst(o_ds_cores_m1_axi_m_arburst[1]),
      .ds_core2_m1_arburst(o_ds_cores_m1_axi_m_arburst[2]),
      .ds_core3_m1_arburst(o_ds_cores_m1_axi_m_arburst[3]),
      .ds_core4_m1_arburst(o_ds_cores_m1_axi_m_arburst[4]),
      .ds_core5_m1_arburst(o_ds_cores_m1_axi_m_arburst[5]),
      .ds_core6_m1_arburst(o_ds_cores_m1_axi_m_arburst[6]),
      .ds_core7_m1_arburst(o_ds_cores_m1_axi_m_arburst[7]),
      .ds_core0_m1_arcache(o_ds_cores_m1_axi_m_arcache[0]),
      .ds_core1_m1_arcache(o_ds_cores_m1_axi_m_arcache[1]),
      .ds_core2_m1_arcache(o_ds_cores_m1_axi_m_arcache[2]),
      .ds_core3_m1_arcache(o_ds_cores_m1_axi_m_arcache[3]),
      .ds_core4_m1_arcache(o_ds_cores_m1_axi_m_arcache[4]),
      .ds_core5_m1_arcache(o_ds_cores_m1_axi_m_arcache[5]),
      .ds_core6_m1_arcache(o_ds_cores_m1_axi_m_arcache[6]),
      .ds_core7_m1_arcache(o_ds_cores_m1_axi_m_arcache[7]),
      .ds_core0_m1_arid(o_ds_cores_m1_axi_m_arid[0]),
      .ds_core1_m1_arid(o_ds_cores_m1_axi_m_arid[1]),
      .ds_core2_m1_arid(o_ds_cores_m1_axi_m_arid[2]),
      .ds_core3_m1_arid(o_ds_cores_m1_axi_m_arid[3]),
      .ds_core4_m1_arid(o_ds_cores_m1_axi_m_arid[4]),
      .ds_core5_m1_arid(o_ds_cores_m1_axi_m_arid[5]),
      .ds_core6_m1_arid(o_ds_cores_m1_axi_m_arid[6]),
      .ds_core7_m1_arid(o_ds_cores_m1_axi_m_arid[7]),
      .ds_core0_m1_arlen(o_ds_cores_m1_axi_m_arlen[0]),
      .ds_core1_m1_arlen(o_ds_cores_m1_axi_m_arlen[1]),
      .ds_core2_m1_arlen(o_ds_cores_m1_axi_m_arlen[2]),
      .ds_core3_m1_arlen(o_ds_cores_m1_axi_m_arlen[3]),
      .ds_core4_m1_arlen(o_ds_cores_m1_axi_m_arlen[4]),
      .ds_core5_m1_arlen(o_ds_cores_m1_axi_m_arlen[5]),
      .ds_core6_m1_arlen(o_ds_cores_m1_axi_m_arlen[6]),
      .ds_core7_m1_arlen(o_ds_cores_m1_axi_m_arlen[7]),
      .ds_core0_m1_arlock(o_ds_cores_m1_axi_m_arlock[0]),
      .ds_core1_m1_arlock(o_ds_cores_m1_axi_m_arlock[1]),
      .ds_core2_m1_arlock(o_ds_cores_m1_axi_m_arlock[2]),
      .ds_core3_m1_arlock(o_ds_cores_m1_axi_m_arlock[3]),
      .ds_core4_m1_arlock(o_ds_cores_m1_axi_m_arlock[4]),
      .ds_core5_m1_arlock(o_ds_cores_m1_axi_m_arlock[5]),
      .ds_core6_m1_arlock(o_ds_cores_m1_axi_m_arlock[6]),
      .ds_core7_m1_arlock(o_ds_cores_m1_axi_m_arlock[7]),
      .ds_core0_m1_arprot(o_ds_cores_m1_axi_m_arprot[0]),
      .ds_core1_m1_arprot(o_ds_cores_m1_axi_m_arprot[1]),
      .ds_core2_m1_arprot(o_ds_cores_m1_axi_m_arprot[2]),
      .ds_core3_m1_arprot(o_ds_cores_m1_axi_m_arprot[3]),
      .ds_core4_m1_arprot(o_ds_cores_m1_axi_m_arprot[4]),
      .ds_core5_m1_arprot(o_ds_cores_m1_axi_m_arprot[5]),
      .ds_core6_m1_arprot(o_ds_cores_m1_axi_m_arprot[6]),
      .ds_core7_m1_arprot(o_ds_cores_m1_axi_m_arprot[7]),
      .ds_core0_m1_arsize(o_ds_cores_m1_axi_m_arsize[0]),
      .ds_core1_m1_arsize(o_ds_cores_m1_axi_m_arsize[1]),
      .ds_core2_m1_arsize(o_ds_cores_m1_axi_m_arsize[2]),
      .ds_core3_m1_arsize(o_ds_cores_m1_axi_m_arsize[3]),
      .ds_core4_m1_arsize(o_ds_cores_m1_axi_m_arsize[4]),
      .ds_core5_m1_arsize(o_ds_cores_m1_axi_m_arsize[5]),
      .ds_core6_m1_arsize(o_ds_cores_m1_axi_m_arsize[6]),
      .ds_core7_m1_arsize(o_ds_cores_m1_axi_m_arsize[7]),
      .ds_core0_m1_arready(i_ds_cores_m1_axi_m_arready[0]),
      .ds_core1_m1_arready(i_ds_cores_m1_axi_m_arready[1]),
      .ds_core2_m1_arready(i_ds_cores_m1_axi_m_arready[2]),
      .ds_core3_m1_arready(i_ds_cores_m1_axi_m_arready[3]),
      .ds_core4_m1_arready(i_ds_cores_m1_axi_m_arready[4]),
      .ds_core5_m1_arready(i_ds_cores_m1_axi_m_arready[5]),
      .ds_core6_m1_arready(i_ds_cores_m1_axi_m_arready[6]),
      .ds_core7_m1_arready(i_ds_cores_m1_axi_m_arready[7]),
      .ds_core0_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[0]),
      .ds_core1_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[1]),
      .ds_core2_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[2]),
      .ds_core3_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[3]),
      .ds_core4_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[4]),
      .ds_core5_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[5]),
      .ds_core6_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[6]),
      .ds_core7_m1_arvalid(o_ds_cores_m1_axi_m_arvalid[7]),
      .ds_core0_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[0]),
      .ds_core1_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[1]),
      .ds_core2_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[2]),
      .ds_core3_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[3]),
      .ds_core4_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[4]),
      .ds_core5_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[5]),
      .ds_core6_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[6]),
      .ds_core7_m1_awaddr(o_ds_cores_m1_axi_m_awaddr[7]),
      .ds_core0_m1_awburst(o_ds_cores_m1_axi_m_awburst[0]),
      .ds_core1_m1_awburst(o_ds_cores_m1_axi_m_awburst[1]),
      .ds_core2_m1_awburst(o_ds_cores_m1_axi_m_awburst[2]),
      .ds_core3_m1_awburst(o_ds_cores_m1_axi_m_awburst[3]),
      .ds_core4_m1_awburst(o_ds_cores_m1_axi_m_awburst[4]),
      .ds_core5_m1_awburst(o_ds_cores_m1_axi_m_awburst[5]),
      .ds_core6_m1_awburst(o_ds_cores_m1_axi_m_awburst[6]),
      .ds_core7_m1_awburst(o_ds_cores_m1_axi_m_awburst[7]),
      .ds_core0_m1_awcache(o_ds_cores_m1_axi_m_awcache[0]),
      .ds_core1_m1_awcache(o_ds_cores_m1_axi_m_awcache[1]),
      .ds_core2_m1_awcache(o_ds_cores_m1_axi_m_awcache[2]),
      .ds_core3_m1_awcache(o_ds_cores_m1_axi_m_awcache[3]),
      .ds_core4_m1_awcache(o_ds_cores_m1_axi_m_awcache[4]),
      .ds_core5_m1_awcache(o_ds_cores_m1_axi_m_awcache[5]),
      .ds_core6_m1_awcache(o_ds_cores_m1_axi_m_awcache[6]),
      .ds_core7_m1_awcache(o_ds_cores_m1_axi_m_awcache[7]),
      .ds_core0_m1_awid(o_ds_cores_m1_axi_m_awid[0]),
      .ds_core1_m1_awid(o_ds_cores_m1_axi_m_awid[1]),
      .ds_core2_m1_awid(o_ds_cores_m1_axi_m_awid[2]),
      .ds_core3_m1_awid(o_ds_cores_m1_axi_m_awid[3]),
      .ds_core4_m1_awid(o_ds_cores_m1_axi_m_awid[4]),
      .ds_core5_m1_awid(o_ds_cores_m1_axi_m_awid[5]),
      .ds_core6_m1_awid(o_ds_cores_m1_axi_m_awid[6]),
      .ds_core7_m1_awid(o_ds_cores_m1_axi_m_awid[7]),
      .ds_core0_m1_awlen(o_ds_cores_m1_axi_m_awlen[0]),
      .ds_core1_m1_awlen(o_ds_cores_m1_axi_m_awlen[1]),
      .ds_core2_m1_awlen(o_ds_cores_m1_axi_m_awlen[2]),
      .ds_core3_m1_awlen(o_ds_cores_m1_axi_m_awlen[3]),
      .ds_core4_m1_awlen(o_ds_cores_m1_axi_m_awlen[4]),
      .ds_core5_m1_awlen(o_ds_cores_m1_axi_m_awlen[5]),
      .ds_core6_m1_awlen(o_ds_cores_m1_axi_m_awlen[6]),
      .ds_core7_m1_awlen(o_ds_cores_m1_axi_m_awlen[7]),
      .ds_core0_m1_awlock(o_ds_cores_m1_axi_m_awlock[0]),
      .ds_core1_m1_awlock(o_ds_cores_m1_axi_m_awlock[1]),
      .ds_core2_m1_awlock(o_ds_cores_m1_axi_m_awlock[2]),
      .ds_core3_m1_awlock(o_ds_cores_m1_axi_m_awlock[3]),
      .ds_core4_m1_awlock(o_ds_cores_m1_axi_m_awlock[4]),
      .ds_core5_m1_awlock(o_ds_cores_m1_axi_m_awlock[5]),
      .ds_core6_m1_awlock(o_ds_cores_m1_axi_m_awlock[6]),
      .ds_core7_m1_awlock(o_ds_cores_m1_axi_m_awlock[7]),
      .ds_core0_m1_awprot(o_ds_cores_m1_axi_m_awprot[0]),
      .ds_core1_m1_awprot(o_ds_cores_m1_axi_m_awprot[1]),
      .ds_core2_m1_awprot(o_ds_cores_m1_axi_m_awprot[2]),
      .ds_core3_m1_awprot(o_ds_cores_m1_axi_m_awprot[3]),
      .ds_core4_m1_awprot(o_ds_cores_m1_axi_m_awprot[4]),
      .ds_core5_m1_awprot(o_ds_cores_m1_axi_m_awprot[5]),
      .ds_core6_m1_awprot(o_ds_cores_m1_axi_m_awprot[6]),
      .ds_core7_m1_awprot(o_ds_cores_m1_axi_m_awprot[7]),
      .ds_core0_m1_awsize(o_ds_cores_m1_axi_m_awsize[0]),
      .ds_core1_m1_awsize(o_ds_cores_m1_axi_m_awsize[1]),
      .ds_core2_m1_awsize(o_ds_cores_m1_axi_m_awsize[2]),
      .ds_core3_m1_awsize(o_ds_cores_m1_axi_m_awsize[3]),
      .ds_core4_m1_awsize(o_ds_cores_m1_axi_m_awsize[4]),
      .ds_core5_m1_awsize(o_ds_cores_m1_axi_m_awsize[5]),
      .ds_core6_m1_awsize(o_ds_cores_m1_axi_m_awsize[6]),
      .ds_core7_m1_awsize(o_ds_cores_m1_axi_m_awsize[7]),
      .ds_core0_m1_awready(i_ds_cores_m1_axi_m_awready[0]),
      .ds_core1_m1_awready(i_ds_cores_m1_axi_m_awready[1]),
      .ds_core2_m1_awready(i_ds_cores_m1_axi_m_awready[2]),
      .ds_core3_m1_awready(i_ds_cores_m1_axi_m_awready[3]),
      .ds_core4_m1_awready(i_ds_cores_m1_axi_m_awready[4]),
      .ds_core5_m1_awready(i_ds_cores_m1_axi_m_awready[5]),
      .ds_core6_m1_awready(i_ds_cores_m1_axi_m_awready[6]),
      .ds_core7_m1_awready(i_ds_cores_m1_axi_m_awready[7]),
      .ds_core0_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[0]),
      .ds_core1_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[1]),
      .ds_core2_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[2]),
      .ds_core3_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[3]),
      .ds_core4_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[4]),
      .ds_core5_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[5]),
      .ds_core6_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[6]),
      .ds_core7_m1_awvalid(o_ds_cores_m1_axi_m_awvalid[7]),
      .ds_core0_m1_bid(i_ds_cores_m1_axi_m_bid[0]),
      .ds_core1_m1_bid(i_ds_cores_m1_axi_m_bid[1]),
      .ds_core2_m1_bid(i_ds_cores_m1_axi_m_bid[2]),
      .ds_core3_m1_bid(i_ds_cores_m1_axi_m_bid[3]),
      .ds_core4_m1_bid(i_ds_cores_m1_axi_m_bid[4]),
      .ds_core5_m1_bid(i_ds_cores_m1_axi_m_bid[5]),
      .ds_core6_m1_bid(i_ds_cores_m1_axi_m_bid[6]),
      .ds_core7_m1_bid(i_ds_cores_m1_axi_m_bid[7]),
      .ds_core0_m1_bresp(i_ds_cores_m1_axi_m_bresp[0]),
      .ds_core1_m1_bresp(i_ds_cores_m1_axi_m_bresp[1]),
      .ds_core2_m1_bresp(i_ds_cores_m1_axi_m_bresp[2]),
      .ds_core3_m1_bresp(i_ds_cores_m1_axi_m_bresp[3]),
      .ds_core4_m1_bresp(i_ds_cores_m1_axi_m_bresp[4]),
      .ds_core5_m1_bresp(i_ds_cores_m1_axi_m_bresp[5]),
      .ds_core6_m1_bresp(i_ds_cores_m1_axi_m_bresp[6]),
      .ds_core7_m1_bresp(i_ds_cores_m1_axi_m_bresp[7]),
      .ds_core0_m1_bready(o_ds_cores_m1_axi_m_bready[0]),
      .ds_core1_m1_bready(o_ds_cores_m1_axi_m_bready[1]),
      .ds_core2_m1_bready(o_ds_cores_m1_axi_m_bready[2]),
      .ds_core3_m1_bready(o_ds_cores_m1_axi_m_bready[3]),
      .ds_core4_m1_bready(o_ds_cores_m1_axi_m_bready[4]),
      .ds_core5_m1_bready(o_ds_cores_m1_axi_m_bready[5]),
      .ds_core6_m1_bready(o_ds_cores_m1_axi_m_bready[6]),
      .ds_core7_m1_bready(o_ds_cores_m1_axi_m_bready[7]),
      .ds_core0_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[0]),
      .ds_core1_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[1]),
      .ds_core2_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[2]),
      .ds_core3_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[3]),
      .ds_core4_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[4]),
      .ds_core5_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[5]),
      .ds_core6_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[6]),
      .ds_core7_m1_bvalid(o_ds_cores_m1_axi_m_bvalid[7]),
      .ds_core0_m1_rdata(i_ds_cores_m1_axi_m_rdata[0]),
      .ds_core1_m1_rdata(i_ds_cores_m1_axi_m_rdata[1]),
      .ds_core2_m1_rdata(i_ds_cores_m1_axi_m_rdata[2]),
      .ds_core3_m1_rdata(i_ds_cores_m1_axi_m_rdata[3]),
      .ds_core4_m1_rdata(i_ds_cores_m1_axi_m_rdata[4]),
      .ds_core5_m1_rdata(i_ds_cores_m1_axi_m_rdata[5]),
      .ds_core6_m1_rdata(i_ds_cores_m1_axi_m_rdata[6]),
      .ds_core7_m1_rdata(i_ds_cores_m1_axi_m_rdata[7]),
      .ds_core0_m1_rid(i_ds_cores_m1_axi_m_rid[0]),
      .ds_core1_m1_rid(i_ds_cores_m1_axi_m_rid[1]),
      .ds_core2_m1_rid(i_ds_cores_m1_axi_m_rid[2]),
      .ds_core3_m1_rid(i_ds_cores_m1_axi_m_rid[3]),
      .ds_core4_m1_rid(i_ds_cores_m1_axi_m_rid[4]),
      .ds_core5_m1_rid(i_ds_cores_m1_axi_m_rid[5]),
      .ds_core6_m1_rid(i_ds_cores_m1_axi_m_rid[6]),
      .ds_core7_m1_rid(i_ds_cores_m1_axi_m_rid[7]),
      .ds_core0_m1_rlast(i_ds_cores_m1_axi_m_rlast[0]),
      .ds_core1_m1_rlast(i_ds_cores_m1_axi_m_rlast[1]),
      .ds_core2_m1_rlast(i_ds_cores_m1_axi_m_rlast[2]),
      .ds_core3_m1_rlast(i_ds_cores_m1_axi_m_rlast[3]),
      .ds_core4_m1_rlast(i_ds_cores_m1_axi_m_rlast[4]),
      .ds_core5_m1_rlast(i_ds_cores_m1_axi_m_rlast[5]),
      .ds_core6_m1_rlast(i_ds_cores_m1_axi_m_rlast[6]),
      .ds_core7_m1_rlast(i_ds_cores_m1_axi_m_rlast[7]),
      .ds_core0_m1_rresp(i_ds_cores_m1_axi_m_rresp[0]),
      .ds_core1_m1_rresp(i_ds_cores_m1_axi_m_rresp[1]),
      .ds_core2_m1_rresp(i_ds_cores_m1_axi_m_rresp[2]),
      .ds_core3_m1_rresp(i_ds_cores_m1_axi_m_rresp[3]),
      .ds_core4_m1_rresp(i_ds_cores_m1_axi_m_rresp[4]),
      .ds_core5_m1_rresp(i_ds_cores_m1_axi_m_rresp[5]),
      .ds_core6_m1_rresp(i_ds_cores_m1_axi_m_rresp[6]),
      .ds_core7_m1_rresp(i_ds_cores_m1_axi_m_rresp[7]),
      .ds_core0_m1_rready(o_ds_cores_m1_axi_m_rready[0]),
      .ds_core1_m1_rready(o_ds_cores_m1_axi_m_rready[1]),
      .ds_core2_m1_rready(o_ds_cores_m1_axi_m_rready[2]),
      .ds_core3_m1_rready(o_ds_cores_m1_axi_m_rready[3]),
      .ds_core4_m1_rready(o_ds_cores_m1_axi_m_rready[4]),
      .ds_core5_m1_rready(o_ds_cores_m1_axi_m_rready[5]),
      .ds_core6_m1_rready(o_ds_cores_m1_axi_m_rready[6]),
      .ds_core7_m1_rready(o_ds_cores_m1_axi_m_rready[7]),
      .ds_core0_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[0]),
      .ds_core1_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[1]),
      .ds_core2_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[2]),
      .ds_core3_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[3]),
      .ds_core4_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[4]),
      .ds_core5_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[5]),
      .ds_core6_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[6]),
      .ds_core7_m1_rvalid(o_ds_cores_m1_axi_m_rvalid[7]),
      .ds_core0_m1_wdata(o_ds_cores_m1_axi_m_wdata[0]),
      .ds_core1_m1_wdata(o_ds_cores_m1_axi_m_wdata[1]),
      .ds_core2_m1_wdata(o_ds_cores_m1_axi_m_wdata[2]),
      .ds_core3_m1_wdata(o_ds_cores_m1_axi_m_wdata[3]),
      .ds_core4_m1_wdata(o_ds_cores_m1_axi_m_wdata[4]),
      .ds_core5_m1_wdata(o_ds_cores_m1_axi_m_wdata[5]),
      .ds_core6_m1_wdata(o_ds_cores_m1_axi_m_wdata[6]),
      .ds_core7_m1_wdata(o_ds_cores_m1_axi_m_wdata[7]),
      .ds_core0_m1_wlast(o_ds_cores_m1_axi_m_wlast[0]),
      .ds_core1_m1_wlast(o_ds_cores_m1_axi_m_wlast[1]),
      .ds_core2_m1_wlast(o_ds_cores_m1_axi_m_wlast[2]),
      .ds_core3_m1_wlast(o_ds_cores_m1_axi_m_wlast[3]),
      .ds_core4_m1_wlast(o_ds_cores_m1_axi_m_wlast[4]),
      .ds_core5_m1_wlast(o_ds_cores_m1_axi_m_wlast[5]),
      .ds_core6_m1_wlast(o_ds_cores_m1_axi_m_wlast[6]),
      .ds_core7_m1_wlast(o_ds_cores_m1_axi_m_wlast[7]),
      .ds_core0_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[0]),
      .ds_core1_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[1]),
      .ds_core2_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[2]),
      .ds_core3_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[3]),
      .ds_core4_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[4]),
      .ds_core5_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[5]),
      .ds_core6_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[6]),
      .ds_core7_m1_wstrb(o_ds_cores_m1_axi_m_wstrb[7]),
      .ds_core0_m1_wready(i_ds_cores_m1_axi_m_wready[0]),
      .ds_core1_m1_wready(i_ds_cores_m1_axi_m_wready[1]),
      .ds_core2_m1_wready(i_ds_cores_m1_axi_m_wready[2]),
      .ds_core3_m1_wready(i_ds_cores_m1_axi_m_wready[3]),
      .ds_core4_m1_wready(i_ds_cores_m1_axi_m_wready[4]),
      .ds_core5_m1_wready(i_ds_cores_m1_axi_m_wready[5]),
      .ds_core6_m1_wready(i_ds_cores_m1_axi_m_wready[6]),
      .ds_core7_m1_wready(i_ds_cores_m1_axi_m_wready[7]),
      .ds_core0_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[0]),
      .ds_core1_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[1]),
      .ds_core2_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[2]),
      .ds_core3_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[3]),
      .ds_core4_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[4]),
      .ds_core5_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[5]),
      .ds_core6_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[6]),
      .ds_core7_m1_wvalid(o_ds_cores_m1_axi_m_wvalid[7]),
      .ds_core0_m2_a_address(o_ds_cores_m2_a_address[0]),
      .ds_core1_m2_a_address(o_ds_cores_m2_a_address[1]),
      .ds_core2_m2_a_address(o_ds_cores_m2_a_address[2]),
      .ds_core3_m2_a_address(o_ds_cores_m2_a_address[3]),
      .ds_core4_m2_a_address(o_ds_cores_m2_a_address[4]),
      .ds_core5_m2_a_address(o_ds_cores_m2_a_address[5]),
      .ds_core6_m2_a_address(o_ds_cores_m2_a_address[6]),
      .ds_core7_m2_a_address(o_ds_cores_m2_a_address[7]),
      .ds_core0_m2_a_corrupt(o_ds_cores_m2_a_corrupt[0]),
      .ds_core1_m2_a_corrupt(o_ds_cores_m2_a_corrupt[1]),
      .ds_core2_m2_a_corrupt(o_ds_cores_m2_a_corrupt[2]),
      .ds_core3_m2_a_corrupt(o_ds_cores_m2_a_corrupt[3]),
      .ds_core4_m2_a_corrupt(o_ds_cores_m2_a_corrupt[4]),
      .ds_core5_m2_a_corrupt(o_ds_cores_m2_a_corrupt[5]),
      .ds_core6_m2_a_corrupt(o_ds_cores_m2_a_corrupt[6]),
      .ds_core7_m2_a_corrupt(o_ds_cores_m2_a_corrupt[7]),
      .ds_core0_m2_a_data(o_ds_cores_m2_a_data[0]),
      .ds_core1_m2_a_data(o_ds_cores_m2_a_data[1]),
      .ds_core2_m2_a_data(o_ds_cores_m2_a_data[2]),
      .ds_core3_m2_a_data(o_ds_cores_m2_a_data[3]),
      .ds_core4_m2_a_data(o_ds_cores_m2_a_data[4]),
      .ds_core5_m2_a_data(o_ds_cores_m2_a_data[5]),
      .ds_core6_m2_a_data(o_ds_cores_m2_a_data[6]),
      .ds_core7_m2_a_data(o_ds_cores_m2_a_data[7]),
      .ds_core0_m2_a_mask(o_ds_cores_m2_a_mask[0]),
      .ds_core1_m2_a_mask(o_ds_cores_m2_a_mask[1]),
      .ds_core2_m2_a_mask(o_ds_cores_m2_a_mask[2]),
      .ds_core3_m2_a_mask(o_ds_cores_m2_a_mask[3]),
      .ds_core4_m2_a_mask(o_ds_cores_m2_a_mask[4]),
      .ds_core5_m2_a_mask(o_ds_cores_m2_a_mask[5]),
      .ds_core6_m2_a_mask(o_ds_cores_m2_a_mask[6]),
      .ds_core7_m2_a_mask(o_ds_cores_m2_a_mask[7]),
      .ds_core0_m2_a_opcode(o_ds_cores_m2_a_opcode[0]),
      .ds_core1_m2_a_opcode(o_ds_cores_m2_a_opcode[1]),
      .ds_core2_m2_a_opcode(o_ds_cores_m2_a_opcode[2]),
      .ds_core3_m2_a_opcode(o_ds_cores_m2_a_opcode[3]),
      .ds_core4_m2_a_opcode(o_ds_cores_m2_a_opcode[4]),
      .ds_core5_m2_a_opcode(o_ds_cores_m2_a_opcode[5]),
      .ds_core6_m2_a_opcode(o_ds_cores_m2_a_opcode[6]),
      .ds_core7_m2_a_opcode(o_ds_cores_m2_a_opcode[7]),
      .ds_core0_m2_a_param(o_ds_cores_m2_a_param[0]),
      .ds_core1_m2_a_param(o_ds_cores_m2_a_param[1]),
      .ds_core2_m2_a_param(o_ds_cores_m2_a_param[2]),
      .ds_core3_m2_a_param(o_ds_cores_m2_a_param[3]),
      .ds_core4_m2_a_param(o_ds_cores_m2_a_param[4]),
      .ds_core5_m2_a_param(o_ds_cores_m2_a_param[5]),
      .ds_core6_m2_a_param(o_ds_cores_m2_a_param[6]),
      .ds_core7_m2_a_param(o_ds_cores_m2_a_param[7]),
      .ds_core0_m2_a_size(o_ds_cores_m2_a_size[0]),
      .ds_core1_m2_a_size(o_ds_cores_m2_a_size[1]),
      .ds_core2_m2_a_size(o_ds_cores_m2_a_size[2]),
      .ds_core3_m2_a_size(o_ds_cores_m2_a_size[3]),
      .ds_core4_m2_a_size(o_ds_cores_m2_a_size[4]),
      .ds_core5_m2_a_size(o_ds_cores_m2_a_size[5]),
      .ds_core6_m2_a_size(o_ds_cores_m2_a_size[6]),
      .ds_core7_m2_a_size(o_ds_cores_m2_a_size[7]),
      .ds_core0_m2_a_source(o_ds_cores_m2_a_source[0]),
      .ds_core1_m2_a_source(o_ds_cores_m2_a_source[1]),
      .ds_core2_m2_a_source(o_ds_cores_m2_a_source[2]),
      .ds_core3_m2_a_source(o_ds_cores_m2_a_source[3]),
      .ds_core4_m2_a_source(o_ds_cores_m2_a_source[4]),
      .ds_core5_m2_a_source(o_ds_cores_m2_a_source[5]),
      .ds_core6_m2_a_source(o_ds_cores_m2_a_source[6]),
      .ds_core7_m2_a_source(o_ds_cores_m2_a_source[7]),
      .ds_core0_m2_a_user(o_ds_cores_m2_a_user[0]),
      .ds_core1_m2_a_user(o_ds_cores_m2_a_user[1]),
      .ds_core2_m2_a_user(o_ds_cores_m2_a_user[2]),
      .ds_core3_m2_a_user(o_ds_cores_m2_a_user[3]),
      .ds_core4_m2_a_user(o_ds_cores_m2_a_user[4]),
      .ds_core5_m2_a_user(o_ds_cores_m2_a_user[5]),
      .ds_core6_m2_a_user(o_ds_cores_m2_a_user[6]),
      .ds_core7_m2_a_user(o_ds_cores_m2_a_user[7]),
      .ds_core0_m2_a_ready(i_ds_cores_m2_a_ready[0]),
      .ds_core1_m2_a_ready(i_ds_cores_m2_a_ready[1]),
      .ds_core2_m2_a_ready(i_ds_cores_m2_a_ready[2]),
      .ds_core3_m2_a_ready(i_ds_cores_m2_a_ready[3]),
      .ds_core4_m2_a_ready(i_ds_cores_m2_a_ready[4]),
      .ds_core5_m2_a_ready(i_ds_cores_m2_a_ready[5]),
      .ds_core6_m2_a_ready(i_ds_cores_m2_a_ready[6]),
      .ds_core7_m2_a_ready(i_ds_cores_m2_a_ready[7]),
      .ds_core0_m2_a_valid(o_ds_cores_m2_a_valid[0]),
      .ds_core1_m2_a_valid(o_ds_cores_m2_a_valid[1]),
      .ds_core2_m2_a_valid(o_ds_cores_m2_a_valid[2]),
      .ds_core3_m2_a_valid(o_ds_cores_m2_a_valid[3]),
      .ds_core4_m2_a_valid(o_ds_cores_m2_a_valid[4]),
      .ds_core5_m2_a_valid(o_ds_cores_m2_a_valid[5]),
      .ds_core6_m2_a_valid(o_ds_cores_m2_a_valid[6]),
      .ds_core7_m2_a_valid(o_ds_cores_m2_a_valid[7]),
      .ds_core0_m2_d_corrupt(i_ds_cores_m2_d_corrupt[0]),
      .ds_core1_m2_d_corrupt(i_ds_cores_m2_d_corrupt[1]),
      .ds_core2_m2_d_corrupt(i_ds_cores_m2_d_corrupt[2]),
      .ds_core3_m2_d_corrupt(i_ds_cores_m2_d_corrupt[3]),
      .ds_core4_m2_d_corrupt(i_ds_cores_m2_d_corrupt[4]),
      .ds_core5_m2_d_corrupt(i_ds_cores_m2_d_corrupt[5]),
      .ds_core6_m2_d_corrupt(i_ds_cores_m2_d_corrupt[6]),
      .ds_core7_m2_d_corrupt(i_ds_cores_m2_d_corrupt[7]),
      .ds_core0_m2_d_data(i_ds_cores_m2_d_data[0]),
      .ds_core1_m2_d_data(i_ds_cores_m2_d_data[1]),
      .ds_core2_m2_d_data(i_ds_cores_m2_d_data[2]),
      .ds_core3_m2_d_data(i_ds_cores_m2_d_data[3]),
      .ds_core4_m2_d_data(i_ds_cores_m2_d_data[4]),
      .ds_core5_m2_d_data(i_ds_cores_m2_d_data[5]),
      .ds_core6_m2_d_data(i_ds_cores_m2_d_data[6]),
      .ds_core7_m2_d_data(i_ds_cores_m2_d_data[7]),
      .ds_core0_m2_d_denied(i_ds_cores_m2_d_denied[0]),
      .ds_core1_m2_d_denied(i_ds_cores_m2_d_denied[1]),
      .ds_core2_m2_d_denied(i_ds_cores_m2_d_denied[2]),
      .ds_core3_m2_d_denied(i_ds_cores_m2_d_denied[3]),
      .ds_core4_m2_d_denied(i_ds_cores_m2_d_denied[4]),
      .ds_core5_m2_d_denied(i_ds_cores_m2_d_denied[5]),
      .ds_core6_m2_d_denied(i_ds_cores_m2_d_denied[6]),
      .ds_core7_m2_d_denied(i_ds_cores_m2_d_denied[7]),
      .ds_core0_m2_d_opcode(i_ds_cores_m2_d_opcode[0]),
      .ds_core1_m2_d_opcode(i_ds_cores_m2_d_opcode[1]),
      .ds_core2_m2_d_opcode(i_ds_cores_m2_d_opcode[2]),
      .ds_core3_m2_d_opcode(i_ds_cores_m2_d_opcode[3]),
      .ds_core4_m2_d_opcode(i_ds_cores_m2_d_opcode[4]),
      .ds_core5_m2_d_opcode(i_ds_cores_m2_d_opcode[5]),
      .ds_core6_m2_d_opcode(i_ds_cores_m2_d_opcode[6]),
      .ds_core7_m2_d_opcode(i_ds_cores_m2_d_opcode[7]),
      .ds_core0_m2_d_param(i_ds_cores_m2_d_param[0]),
      .ds_core1_m2_d_param(i_ds_cores_m2_d_param[1]),
      .ds_core2_m2_d_param(i_ds_cores_m2_d_param[2]),
      .ds_core3_m2_d_param(i_ds_cores_m2_d_param[3]),
      .ds_core4_m2_d_param(i_ds_cores_m2_d_param[4]),
      .ds_core5_m2_d_param(i_ds_cores_m2_d_param[5]),
      .ds_core6_m2_d_param(i_ds_cores_m2_d_param[6]),
      .ds_core7_m2_d_param(i_ds_cores_m2_d_param[7]),
      .ds_core0_m2_d_size(i_ds_cores_m2_d_size[0]),
      .ds_core1_m2_d_size(i_ds_cores_m2_d_size[1]),
      .ds_core2_m2_d_size(i_ds_cores_m2_d_size[2]),
      .ds_core3_m2_d_size(i_ds_cores_m2_d_size[3]),
      .ds_core4_m2_d_size(i_ds_cores_m2_d_size[4]),
      .ds_core5_m2_d_size(i_ds_cores_m2_d_size[5]),
      .ds_core6_m2_d_size(i_ds_cores_m2_d_size[6]),
      .ds_core7_m2_d_size(i_ds_cores_m2_d_size[7]),
      .ds_core0_m2_d_sink(i_ds_cores_m2_d_sink[0]),
      .ds_core1_m2_d_sink(i_ds_cores_m2_d_sink[1]),
      .ds_core2_m2_d_sink(i_ds_cores_m2_d_sink[2]),
      .ds_core3_m2_d_sink(i_ds_cores_m2_d_sink[3]),
      .ds_core4_m2_d_sink(i_ds_cores_m2_d_sink[4]),
      .ds_core5_m2_d_sink(i_ds_cores_m2_d_sink[5]),
      .ds_core6_m2_d_sink(i_ds_cores_m2_d_sink[6]),
      .ds_core7_m2_d_sink(i_ds_cores_m2_d_sink[7]),
      .ds_core0_m2_d_source(i_ds_cores_m2_d_source[0]),
      .ds_core1_m2_d_source(i_ds_cores_m2_d_source[1]),
      .ds_core2_m2_d_source(i_ds_cores_m2_d_source[2]),
      .ds_core3_m2_d_source(i_ds_cores_m2_d_source[3]),
      .ds_core4_m2_d_source(i_ds_cores_m2_d_source[4]),
      .ds_core5_m2_d_source(i_ds_cores_m2_d_source[5]),
      .ds_core6_m2_d_source(i_ds_cores_m2_d_source[6]),
      .ds_core7_m2_d_source(i_ds_cores_m2_d_source[7]),
      .ds_core0_m2_d_user(i_ds_cores_m2_d_user[0]),
      .ds_core1_m2_d_user(i_ds_cores_m2_d_user[1]),
      .ds_core2_m2_d_user(i_ds_cores_m2_d_user[2]),
      .ds_core3_m2_d_user(i_ds_cores_m2_d_user[3]),
      .ds_core4_m2_d_user(i_ds_cores_m2_d_user[4]),
      .ds_core5_m2_d_user(i_ds_cores_m2_d_user[5]),
      .ds_core6_m2_d_user(i_ds_cores_m2_d_user[6]),
      .ds_core7_m2_d_user(i_ds_cores_m2_d_user[7]),
      .ds_core0_m2_d_ready(o_ds_cores_m2_d_ready[0]),
      .ds_core1_m2_d_ready(o_ds_cores_m2_d_ready[1]),
      .ds_core2_m2_d_ready(o_ds_cores_m2_d_ready[2]),
      .ds_core3_m2_d_ready(o_ds_cores_m2_d_ready[3]),
      .ds_core4_m2_d_ready(o_ds_cores_m2_d_ready[4]),
      .ds_core5_m2_d_ready(o_ds_cores_m2_d_ready[5]),
      .ds_core6_m2_d_ready(o_ds_cores_m2_d_ready[6]),
      .ds_core7_m2_d_ready(o_ds_cores_m2_d_ready[7]),
      .ds_core0_m2_d_valid(i_ds_cores_m2_d_valid[0]),
      .ds_core1_m2_d_valid(i_ds_cores_m2_d_valid[1]),
      .ds_core2_m2_d_valid(i_ds_cores_m2_d_valid[2]),
      .ds_core3_m2_d_valid(i_ds_cores_m2_d_valid[3]),
      .ds_core4_m2_d_valid(i_ds_cores_m2_d_valid[4]),
      .ds_core5_m2_d_valid(i_ds_cores_m2_d_valid[5]),
      .ds_core6_m2_d_valid(i_ds_cores_m2_d_valid[6]),
      .ds_core7_m2_d_valid(i_ds_cores_m2_d_valid[7])
  );

endmodule
