// pctl tests
//
// test_soc_periph_pctl_rw:
//
// 1. Read the soc_periph pctl reset timing control register
// 2. Check that all its fields are at reset value
// 3. Modify one of its fields
// 4. Read it back and check that the value has been correctly updated
//
// test_soc_periph_csr_rw:
//
// 1. Read the soc_periph IO_DS_JTAG register
// 2. Check that it is at reset value
// 3. Write to it
// 4. Read it back and check that the value has been correctly updated

#include <testutils.h>
#include <pctl/drv_pctl.h>
#include <memorymap.h>
#include <timer.h>
#include <auto-generated/soc_periph_ao_csr.h>

#define SOC_PERIPH_RST_IDX 0

void test_soc_periph_pctl_rw(void) {
  pctl_regs* soc_periph_pctl = (pctl_regs*)SYS_CFG_SOC_PERIPH_AO_CSR_BASE;
  ppmu_timing_control timing_config;

  // Read PPMU_RESET_TIMING_CONTROL register
  pctlGetTiming(soc_periph_pctl, SOC_PERIPH_RST_IDX, &timing_config);
  CHECK_EQUAL_HEX(PRE_RST_0_CYCLES_RESET_VAL, timing_config.pre_rst_0_cycles);
  CHECK_EQUAL_HEX(PRE_RST_1_CYCLES_RESET_VAL, timing_config.pre_rst_1_cycles);
  CHECK_EQUAL_HEX(PRE_RST_2_CYCLES_RESET_VAL, timing_config.pre_rst_2_cycles);
  CHECK_EQUAL_HEX(PRE_REL_CYCLES_RESET_VAL, timing_config.pre_rel_cycles);

  // Write it back
  timing_config.pre_rst_2_cycles = ~PRE_RST_2_CYCLES_RESET_VAL;
  pctlSetTiming(soc_periph_pctl, SOC_PERIPH_RST_IDX, &timing_config);

  // Check again
  pctlGetTiming(soc_periph_pctl, SOC_PERIPH_RST_IDX, &timing_config);
  CHECK_EQUAL_HEX(PRE_RST_0_CYCLES_RESET_VAL, timing_config.pre_rst_0_cycles);
  CHECK_EQUAL_HEX(PRE_RST_1_CYCLES_RESET_VAL, timing_config.pre_rst_1_cycles);
  CHECK_EQUAL_HEX((uint8_t)(~PRE_RST_2_CYCLES_RESET_VAL), timing_config.pre_rst_2_cycles);
  CHECK_EQUAL_HEX(PRE_REL_CYCLES_RESET_VAL, timing_config.pre_rel_cycles);
}

void test_soc_periph_ao_csr_rw(void) {
  uint32_t reversed_val = (~SOC_PERIPH_AO_CSR_IO_DS_JTAG_REG_RESVAL & SOC_PERIPH_AO_CSR_IO_DS_JTAG_IO_DS_JTAG_MASK);
  HalSoc_Periph_Ao_CsrReg* soc_periph_ao_csr = (HalSoc_Periph_Ao_CsrReg*)SYS_CFG_SOC_PERIPH_AO_CSR_BASE;

  // Check IO_DS_JTAG register
  CHECK_EQUAL_HEX((uint32_t)SOC_PERIPH_AO_CSR_IO_DS_JTAG_REG_RESVAL, soc_periph_ao_csr->io_ds_jtag);

  // Change its value
  soc_periph_ao_csr->io_ds_jtag = reversed_val;

  // Read it back
  CHECK_EQUAL_HEX(reversed_val, soc_periph_ao_csr->io_ds_jtag);
}



int main(void) {
  testcase_init();
  test_soc_periph_pctl_rw();
  test_soc_periph_ao_csr_rw();

  return testcase_finalize();
}
