 /*
 * \file
 * \brief Contains defines for the features supported by Phyinit.
 * Defines can be used to differentiate from older Phyinit versions that don't
 * have the support.
 *
 */

#ifndef _DWC_DDRPHY_PHYINIT_FEATURE_DEFINES_H_
#define _DWC_DDRPHY_PHYINIT_FEATURE_DEFINES_H_

#define DWC_DDRPHY_PHYINIT_RUNTIME_COMMON_VAR_SUPPORT    1
#define DWC_DDRPHY_PHYINIT_READ_ONLY_FW_SUPPORT    1
#define DWC_DDRPHY_PHYINIT_DEASSERT_DRAM_RESET_FW_SUPPORT   1
#define DWC_DDRPHY_PHYINIT_RX_GAIN_CTRL_SUPPORT          1
#define CHECK_IMP_TX_RX_SUPPORT        1
#define CHECK_DVFSQ_DRAM_ODT_SUPPORT   1
#define DEPRECATED_RX_VREF_DAC_ENABLED 1
#define DWC_DDRPHY_PHYINIT_DEPRECATED_ENRXDQSTRACKING	1
#define DWC_DDRPHY_PHYINIT_DISABLEUNUSEDADDRLNS_DEPRECATED  1
#define CHECK_DISABLE_RXCLK_C_LCDL 	          1	
#define DWC_DDRPHY_PHYINIT_DISZCALONDATARATE_SUPPORT 1
#define DWC_DDRPHY_PHYINIT_ACDLYSCALEGATING_SUPPORT 1
#define DWC_DDRPHY_PHYINIT_DTO_ENABLE_SUPPORT            1

// DWC_DDRPHY_PHYINIT_FEATURE_TAG is reserved for verification.
#define DWC_DDRPHY_PHYINIT_FEATURE_TAG 0

#endif // _DWC_DDRPHY_PHYINIT_FEATURE_DEFINES_H_
