#pragma once

typedef uint64_t tid_t;

/* HARD_IDs per core */
typedef enum {
    APU_CORE_0 = 0,
    APU_CORE_1,
    APU_CORE_2,
    APU_CORE_3,
    APU_CORE_4,
    APU_CORE_5,
    AI_CORE_0,
    AI_CORE_1,
    AI_CORE_2,
    AI_CORE_3,
    AI_CORE_4,
    AI_CORE_5,
    AI_CORE_6,
    AI_CORE_7,
    PVE_0_CLUSTER_0_CORE_0,
    PVE_0_CLUSTER_0_CORE_1,
    PVE_0_CLUSTER_1_CORE_0,
    PVE_0_CLUSTER_1_CORE_1,
    PVE_0_CLUSTER_2_CORE_0,
    PVE_0_CLUSTER_2_CORE_1,
    PVE_0_CLUSTER_3_CORE_0,
    PVE_0_CLUSTER_3_CORE_1,
    PVE_1_CLUSTER_0_CORE_0,
    PVE_1_CLUSTER_0_CORE_1,
    PVE_1_CLUSTER_1_CORE_0,
    PVE_1_CLUSTER_1_CORE_1,
    PVE_1_CLUSTER_2_CORE_0,
    PVE_1_CLUSTER_2_CORE_1,
    PVE_1_CLUSTER_3_CORE_0,
    PVE_1_CLUSTER_3_CORE_1,
    NUM_CORES,
} HART_ID;

#define PVE_NUM_CORES_PER_CLUSTER 2
