// ------------------------------------------------------------------------------
// 
// Copyright 2024 Synopsys, INC.
// 
// This Synopsys IP and all associated documentation are proprietary to
// Synopsys, Inc. and may only be used pursuant to the terms and conditions of a
// written license agreement with Synopsys, Inc. All other use, reproduction,
// modification, or distribution of the Synopsys IP or the associated
// documentation is strictly prohibited.
// Inclusivity & Diversity - Visit SolvNetPlus to read the "Synopsys Statement on
//            Inclusivity and Diversity" (Refer to article 000036315 at
//                        https://solvnetplus.synopsys.com)
// 
// Component Name   : DWC_ddrctl_lpddr54
// Component Version: 1.60a-lca00
// Release Type     : LCA
// Build ID         : 0.0.0.0.TreMctl_302.DwsDdrChip_8.26.6.DwsDdrctlTop_5.12.7
// ------------------------------------------------------------------------------


#ifndef CINIT_MODULES_CORE_INCLUDE_DWC_DDRCTL_LUT_DEFINES_H_
#define CINIT_MODULES_CORE_INCLUDE_DWC_DDRCTL_LUT_DEFINES_H_

#include ".autoconf.h"


#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_0
#define DWC_DDRCTL_CINIT_LUT_ENTRY_0 ((1 << 7) + (DWC_DDRCTL_CINIT_CSN_0 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_0)
#endif

#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_0
#define DWC_DDRCTL_CINIT_LUT_ENTRY_0 (DWC_DDRCTL_CINIT_CSN_0 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_0
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_1
#define DWC_DDRCTL_CINIT_LUT_ENTRY_1 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_1 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_1
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_1
#define DWC_DDRCTL_CINIT_LUT_ENTRY_1 (DWC_DDRCTL_CINIT_CSN_1 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_1
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_2
#define DWC_DDRCTL_CINIT_LUT_ENTRY_2 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_2 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_2
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_2
#define DWC_DDRCTL_CINIT_LUT_ENTRY_2 (DWC_DDRCTL_CINIT_CSN_2 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_2
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_3
#define DWC_DDRCTL_CINIT_LUT_ENTRY_3 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_3 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_3
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_3
#define DWC_DDRCTL_CINIT_LUT_ENTRY_3 (DWC_DDRCTL_CINIT_CSN_3 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_3
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_4
#define DWC_DDRCTL_CINIT_LUT_ENTRY_4 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_4 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_4
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_4
#define DWC_DDRCTL_CINIT_LUT_ENTRY_4 (DWC_DDRCTL_CINIT_CSN_4 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_4
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_5
#define DWC_DDRCTL_CINIT_LUT_ENTRY_5 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_5 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_5
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_5
#define DWC_DDRCTL_CINIT_LUT_ENTRY_5 (DWC_DDRCTL_CINIT_CSN_5 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_5
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_6
#define DWC_DDRCTL_CINIT_LUT_ENTRY_6 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_6 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_6
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_6
#define DWC_DDRCTL_CINIT_LUT_ENTRY_6 (DWC_DDRCTL_CINIT_CSN_6 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_6
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_7
#define DWC_DDRCTL_CINIT_LUT_ENTRY_7 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_7 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_7
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_7
#define DWC_DDRCTL_CINIT_LUT_ENTRY_7 (DWC_DDRCTL_CINIT_CSN_7 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_7
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_8
#define DWC_DDRCTL_CINIT_LUT_ENTRY_8 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_8 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_8
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_8
#define DWC_DDRCTL_CINIT_LUT_ENTRY_8 (DWC_DDRCTL_CINIT_CSN_8 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_8
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_9
#define DWC_DDRCTL_CINIT_LUT_ENTRY_9 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_9 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_9
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_9
#define DWC_DDRCTL_CINIT_LUT_ENTRY_9 (DWC_DDRCTL_CINIT_CSN_9 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_9
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_10
#define DWC_DDRCTL_CINIT_LUT_ENTRY_10 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_10 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_10
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_10
#define DWC_DDRCTL_CINIT_LUT_ENTRY_10 (DWC_DDRCTL_CINIT_CSN_10 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_10
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_11
#define DWC_DDRCTL_CINIT_LUT_ENTRY_11 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_11 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_11
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_11
#define DWC_DDRCTL_CINIT_LUT_ENTRY_11 (DWC_DDRCTL_CINIT_CSN_11 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_11
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_12
#define DWC_DDRCTL_CINIT_LUT_ENTRY_12 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_12 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_12
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_12
#define DWC_DDRCTL_CINIT_LUT_ENTRY_12 (DWC_DDRCTL_CINIT_CSN_12 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_12
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_13
#define DWC_DDRCTL_CINIT_LUT_ENTRY_13 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_13 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_13
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_13
#define DWC_DDRCTL_CINIT_LUT_ENTRY_13 (DWC_DDRCTL_CINIT_CSN_13 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_13
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_14
#define DWC_DDRCTL_CINIT_LUT_ENTRY_14 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_14 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_14
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_14
#define DWC_DDRCTL_CINIT_LUT_ENTRY_14 (DWC_DDRCTL_CINIT_CSN_14 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_14
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_15
#define DWC_DDRCTL_CINIT_LUT_ENTRY_15 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_15 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_15
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_15
#define DWC_DDRCTL_CINIT_LUT_ENTRY_15 (DWC_DDRCTL_CINIT_CSN_15 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_15
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_16
#define DWC_DDRCTL_CINIT_LUT_ENTRY_16 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_16 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_16
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_16
#define DWC_DDRCTL_CINIT_LUT_ENTRY_16 (DWC_DDRCTL_CINIT_CSN_16 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_16
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_17
#define DWC_DDRCTL_CINIT_LUT_ENTRY_17 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_17 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_17
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_17
#define DWC_DDRCTL_CINIT_LUT_ENTRY_17 (DWC_DDRCTL_CINIT_CSN_17 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_17
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_18
#define DWC_DDRCTL_CINIT_LUT_ENTRY_18 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_18 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_18
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_18
#define DWC_DDRCTL_CINIT_LUT_ENTRY_18 (DWC_DDRCTL_CINIT_CSN_18 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_18
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_19
#define DWC_DDRCTL_CINIT_LUT_ENTRY_19 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_19 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_19
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_19
#define DWC_DDRCTL_CINIT_LUT_ENTRY_19 (DWC_DDRCTL_CINIT_CSN_19 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_19
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_20
#define DWC_DDRCTL_CINIT_LUT_ENTRY_20 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_20 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_20
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_20
#define DWC_DDRCTL_CINIT_LUT_ENTRY_20 (DWC_DDRCTL_CINIT_CSN_20 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_20
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_21
#define DWC_DDRCTL_CINIT_LUT_ENTRY_21 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_21 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_21
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_21
#define DWC_DDRCTL_CINIT_LUT_ENTRY_21 (DWC_DDRCTL_CINIT_CSN_21 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_21
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_22
#define DWC_DDRCTL_CINIT_LUT_ENTRY_22 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_22 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_22
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_22
#define DWC_DDRCTL_CINIT_LUT_ENTRY_22 (DWC_DDRCTL_CINIT_CSN_22 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_22
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_23
#define DWC_DDRCTL_CINIT_LUT_ENTRY_23 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_23 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_23
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_23
#define DWC_DDRCTL_CINIT_LUT_ENTRY_23 (DWC_DDRCTL_CINIT_CSN_23 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_23
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_24
#define DWC_DDRCTL_CINIT_LUT_ENTRY_24 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_24 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_24
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_24
#define DWC_DDRCTL_CINIT_LUT_ENTRY_24 (DWC_DDRCTL_CINIT_CSN_24 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_24
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_25
#define DWC_DDRCTL_CINIT_LUT_ENTRY_25 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_25 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_25
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_25
#define DWC_DDRCTL_CINIT_LUT_ENTRY_25 (DWC_DDRCTL_CINIT_CSN_25 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_25
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_26
#define DWC_DDRCTL_CINIT_LUT_ENTRY_26 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_26 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_26
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_26
#define DWC_DDRCTL_CINIT_LUT_ENTRY_26 (DWC_DDRCTL_CINIT_CSN_26 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_26
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_27
#define DWC_DDRCTL_CINIT_LUT_ENTRY_27 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_27 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_27
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_27
#define DWC_DDRCTL_CINIT_LUT_ENTRY_27 (DWC_DDRCTL_CINIT_CSN_27 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_27
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_28
#define DWC_DDRCTL_CINIT_LUT_ENTRY_28 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_28 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_28
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_28
#define DWC_DDRCTL_CINIT_LUT_ENTRY_28 (DWC_DDRCTL_CINIT_CSN_28 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_28
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_29
#define DWC_DDRCTL_CINIT_LUT_ENTRY_29 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_29 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_29
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_29
#define DWC_DDRCTL_CINIT_LUT_ENTRY_29 (DWC_DDRCTL_CINIT_CSN_29 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_29
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_30
#define DWC_DDRCTL_CINIT_LUT_ENTRY_30 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_30 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_30
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_30
#define DWC_DDRCTL_CINIT_LUT_ENTRY_30 (DWC_DDRCTL_CINIT_CSN_30 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_30
#endif

#ifdef DWC_DDRCTL_CINIT_VALID_ENTRY_31
#define DWC_DDRCTL_CINIT_LUT_ENTRY_31 (1 << 7) + (DWC_DDRCTL_CINIT_CSN_31 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_31
#endif
#ifdef DWC_DDRCTL_CINIT_INVALID_ENTRY_31
#define DWC_DDRCTL_CINIT_LUT_ENTRY_31 (DWC_DDRCTL_CINIT_CSN_31 << 5) + DWC_DDRCTL_CINIT_DATA_ADDRESS_31
#endif

#endif /* CINIT_MODULES_CORE_INCLUDE_DWC_DDRCTL_LUT_DEFINES_H_ */
