// auto generated file with https://git.axelera.ai/vincent.morillon/ax65_wrapper

module ax65_core_wrapper #(
    parameter int unsigned BHT_WIDTH = 7,
    parameter int unsigned DCACHE_WIDTH = 16,
    parameter int unsigned ICACHE_WIDTH = 8,
    parameter int unsigned L2_WIDTH = 4,
    parameter int unsigned SINK_WIDTH = 6,
    parameter int unsigned SOURCE_WIDTH = 5,
    parameter int unsigned CTRL_IN_WIDTH = 9,
    parameter int unsigned CTRL_OUT_WIDTH = 1
) (
    input wire i_clk,
    input wire i_rst_n,
    input wire i_dcu_clk,
    input logic i_coherent_state,
    output logic o_coherent_enable,
    output logic o_wfi_mode,
    output logic [39:0] o_dcu_a_address,
    output logic o_dcu_a_corrupt,
    output logic [255:0] o_dcu_a_data,
    output logic [31:0] o_dcu_a_mask,
    output logic [2:0] o_dcu_a_opcode,
    output logic [2:0] o_dcu_a_param,
    output logic [2:0] o_dcu_a_size,
    output logic [SOURCE_WIDTH - 1:0] o_dcu_a_source,
    output logic [11:0] o_dcu_a_user,
    input logic i_dcu_a_ready,
    output logic o_dcu_a_valid,
    input logic [39:0] i_dcu_b_address,
    input logic i_dcu_b_corrupt,
    input logic [255:0] i_dcu_b_data,
    input logic [31:0] i_dcu_b_mask,
    input logic [2:0] i_dcu_b_opcode,
    input logic [2:0] i_dcu_b_param,
    input logic [2:0] i_dcu_b_size,
    input logic [SOURCE_WIDTH - 1:0] i_dcu_b_source,
    output logic o_dcu_b_ready,
    input logic i_dcu_b_valid,
    output logic [39:0] o_dcu_c_address,
    output logic o_dcu_c_corrupt,
    output logic [255:0] o_dcu_c_data,
    output logic [2:0] o_dcu_c_opcode,
    output logic [2:0] o_dcu_c_param,
    output logic [2:0] o_dcu_c_size,
    output logic [SOURCE_WIDTH - 1:0] o_dcu_c_source,
    output logic [7:0] o_dcu_c_user,
    input logic i_dcu_c_ready,
    output logic o_dcu_c_valid,
    input logic i_dcu_d_corrupt,
    input logic [255:0] i_dcu_d_data,
    input logic i_dcu_d_denied,
    input logic [2:0] i_dcu_d_opcode,
    input logic [1:0] i_dcu_d_param,
    input logic [2:0] i_dcu_d_size,
    input logic [SINK_WIDTH - 1:0] i_dcu_d_sink,
    input logic [SOURCE_WIDTH - 1:0] i_dcu_d_source,
    input logic [5:0] i_dcu_d_user,
    output logic o_dcu_d_ready,
    input logic i_dcu_d_valid,
    output logic [SINK_WIDTH - 1:0] o_dcu_e_sink,
    input logic i_dcu_e_ready,
    output logic o_dcu_e_valid,
    output logic [39:0] o_icu_a_address,
    output logic o_icu_a_corrupt,
    output logic [255:0] o_icu_a_data,
    output logic [31:0] o_icu_a_mask,
    output logic [2:0] o_icu_a_opcode,
    output logic [2:0] o_icu_a_param,
    output logic [2:0] o_icu_a_size,
    output logic [SOURCE_WIDTH - 1:0] o_icu_a_source,
    output logic [11:0] o_icu_a_user,
    input logic i_icu_a_ready,
    output logic o_icu_a_valid,
    input logic i_icu_d_corrupt,
    input logic [255:0] i_icu_d_data,
    input logic i_icu_d_denied,
    input logic [2:0] i_icu_d_opcode,
    input logic [1:0] i_icu_d_param,
    input logic [2:0] i_icu_d_size,
    input logic [SINK_WIDTH - 1:0] i_icu_d_sink,
    input logic [SOURCE_WIDTH - 1:0] i_icu_d_source,
    input logic [5:0] i_icu_d_user,
    output logic o_icu_d_ready,
    input logic i_icu_d_valid,
    output logic [39:0] o_mpipe_axi_m_araddr,
    output logic [1:0] o_mpipe_axi_m_arburst,
    output logic [3:0] o_mpipe_axi_m_arcache,
    output logic [4:0] o_mpipe_axi_m_arid,
    output logic [7:0] o_mpipe_axi_m_arlen,
    output logic o_mpipe_axi_m_arlock,
    output logic [2:0] o_mpipe_axi_m_arprot,
    output logic [2:0] o_mpipe_axi_m_arsize,
    input logic i_mpipe_axi_m_arready,
    output logic o_mpipe_axi_m_arvalid,
    output logic [39:0] o_mpipe_axi_m_awaddr,
    output logic [1:0] o_mpipe_axi_m_awburst,
    output logic [3:0] o_mpipe_axi_m_awcache,
    output logic [4:0] o_mpipe_axi_m_awid,
    output logic [7:0] o_mpipe_axi_m_awlen,
    output logic o_mpipe_axi_m_awlock,
    output logic [2:0] o_mpipe_axi_m_awprot,
    output logic [2:0] o_mpipe_axi_m_awsize,
    input logic i_mpipe_axi_m_awready,
    output logic o_mpipe_axi_m_awvalid,
    input logic [4:0] i_mpipe_axi_m_bid,
    input logic [1:0] i_mpipe_axi_m_bresp,
    output logic o_mpipe_axi_m_bready,
    input logic i_mpipe_axi_m_bvalid,
    input logic [63:0] i_mpipe_axi_m_rdata,
    input logic [4:0] i_mpipe_axi_m_rid,
    input logic i_mpipe_axi_m_rlast,
    input logic [1:0] i_mpipe_axi_m_rresp,
    output logic o_mpipe_axi_m_rready,
    input logic i_mpipe_axi_m_rvalid,
    output logic [63:0] o_mpipe_axi_m_wdata,
    output logic o_mpipe_axi_m_wlast,
    output logic [(64 / 8) - 1:0] o_mpipe_axi_m_wstrb,
    input logic i_mpipe_axi_m_wready,
    output logic o_mpipe_axi_m_wvalid,
    input logic i_dcache_disable_init,
    input logic i_icache_disable_init,
    input logic i_debugint,
    output logic o_hart_halted,
    input logic [63:0] i_hart_id,
    output logic o_hart_unavail,
    output logic o_hart_under_reset,
    input logic [10:0] i_mbist_addr,
    input logic [31:0] i_mbist_bwe,
    input logic i_mbist_en,
    input logic [46:0] i_mbist_ramsel,
    output logic [143:0] o_mbist_rdata,
    input logic [143:0] i_mbist_wdata,
    input logic i_mbist_we,
    input logic i_meip,
    input logic i_msip,
    input logic i_mtip,
    input logic i_nmi,
    input logic [47:0] i_reset_vector,
    input logic i_resethaltreq,
    input logic i_scan_enable,
    input logic i_seip,
    output logic o_stoptime,
    input logic i_test_mode,
    output logic [9:0] o_trace_cause,
    output logic [63:0] o_trace_context,
    output logic [1:0] o_trace_ctype,
    input logic i_trace_enabled,
    output logic o_trace_halted,
    output logic [(48 * 4) - 1:0] o_trace_iaddr,
    output logic [4 - 1:0] o_trace_ilastsize,
    output logic [(2 * 4) - 1:0] o_trace_iretire,
    output logic [(4 * 4) - 1:0] o_trace_itype,
    output logic [2:0] o_trace_priv,
    output logic o_trace_reset,
    input logic i_trace_stall,
    output logic [4 + 1:0] o_trace_trigger,
    output logic [63:0] o_trace_tval,
    input logic [L2_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_l2btb_ctrl,
    output logic [L2_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_l2btb_ctrl,
    input logic [BHT_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_bht_ctrl,
    output logic [BHT_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_bht_ctrl,
    input logic [ICACHE_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_icache_data_ctrl,
    output logic [ICACHE_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_icache_data_ctrl,
    input logic [ICACHE_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_icache_tag_ctrl,
    output logic [ICACHE_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_icache_tag_ctrl,
    input logic [DCACHE_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_dcache_data_ctrl,
    output logic [DCACHE_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_dcache_data_ctrl,
    input logic [DCACHE_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_dcache_tag_ctrl,
    output logic [DCACHE_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_dcache_tag_ctrl,
    input logic [DCACHE_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_dcache_dtag_ctrl,
    output logic [DCACHE_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_dcache_dtag_ctrl,
    input logic [L2_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_l2itlb_tag_ctrl,
    output logic [L2_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_l2itlb_tag_ctrl,
    input logic [L2_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_l2itlb_data_ctrl,
    output logic [L2_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_l2itlb_data_ctrl,
    input logic [L2_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_l2dtlb_tag_ctrl,
    output logic [L2_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_l2dtlb_tag_ctrl,
    input logic [L2_WIDTH - 1:0][CTRL_IN_WIDTH - 1:0] i_l2dtlb_data_ctrl,
    output logic [L2_WIDTH - 1:0][CTRL_OUT_WIDTH - 1:0] o_l2dtlb_data_ctrl
);

  ax65_core_top u_ax65_core_top (
      .core_clk(i_clk),
      .core_reset_n(i_rst_n),
      .dcu_clk(i_dcu_clk),
      .brg_csr_core_coherent_state(i_coherent_state),
      .csr_brg_core_coherent_enable(o_coherent_enable),
      .core_wfi_mode(o_wfi_mode),
      .dcu_a_address(o_dcu_a_address),
      .dcu_a_corrupt(o_dcu_a_corrupt),
      .dcu_a_data(o_dcu_a_data),
      .dcu_a_mask(o_dcu_a_mask),
      .dcu_a_opcode(o_dcu_a_opcode),
      .dcu_a_param(o_dcu_a_param),
      .dcu_a_size(o_dcu_a_size),
      .dcu_a_source(o_dcu_a_source),
      .dcu_a_user(o_dcu_a_user),
      .dcu_a_ready(i_dcu_a_ready),
      .dcu_a_valid(o_dcu_a_valid),
      .dcu_b_address(i_dcu_b_address),
      .dcu_b_corrupt(i_dcu_b_corrupt),
      .dcu_b_data(i_dcu_b_data),
      .dcu_b_mask(i_dcu_b_mask),
      .dcu_b_opcode(i_dcu_b_opcode),
      .dcu_b_param(i_dcu_b_param),
      .dcu_b_size(i_dcu_b_size),
      .dcu_b_source(i_dcu_b_source),
      .dcu_b_ready(o_dcu_b_ready),
      .dcu_b_valid(i_dcu_b_valid),
      .dcu_c_address(o_dcu_c_address),
      .dcu_c_corrupt(o_dcu_c_corrupt),
      .dcu_c_data(o_dcu_c_data),
      .dcu_c_opcode(o_dcu_c_opcode),
      .dcu_c_param(o_dcu_c_param),
      .dcu_c_size(o_dcu_c_size),
      .dcu_c_source(o_dcu_c_source),
      .dcu_c_user(o_dcu_c_user),
      .dcu_c_ready(i_dcu_c_ready),
      .dcu_c_valid(o_dcu_c_valid),
      .dcu_d_corrupt(i_dcu_d_corrupt),
      .dcu_d_data(i_dcu_d_data),
      .dcu_d_denied(i_dcu_d_denied),
      .dcu_d_opcode(i_dcu_d_opcode),
      .dcu_d_param(i_dcu_d_param),
      .dcu_d_size(i_dcu_d_size),
      .dcu_d_sink(i_dcu_d_sink),
      .dcu_d_source(i_dcu_d_source),
      .dcu_d_user(i_dcu_d_user),
      .dcu_d_ready(o_dcu_d_ready),
      .dcu_d_valid(i_dcu_d_valid),
      .dcu_e_sink(o_dcu_e_sink),
      .dcu_e_ready(i_dcu_e_ready),
      .dcu_e_valid(o_dcu_e_valid),
      .icu_a_address(o_icu_a_address),
      .icu_a_corrupt(o_icu_a_corrupt),
      .icu_a_data(o_icu_a_data),
      .icu_a_mask(o_icu_a_mask),
      .icu_a_opcode(o_icu_a_opcode),
      .icu_a_param(o_icu_a_param),
      .icu_a_size(o_icu_a_size),
      .icu_a_source(o_icu_a_source),
      .icu_a_user(o_icu_a_user),
      .icu_a_ready(i_icu_a_ready),
      .icu_a_valid(o_icu_a_valid),
      .icu_d_corrupt(i_icu_d_corrupt),
      .icu_d_data(i_icu_d_data),
      .icu_d_denied(i_icu_d_denied),
      .icu_d_opcode(i_icu_d_opcode),
      .icu_d_param(i_icu_d_param),
      .icu_d_size(i_icu_d_size),
      .icu_d_sink(i_icu_d_sink),
      .icu_d_source(i_icu_d_source),
      .icu_d_user(i_icu_d_user),
      .icu_d_ready(o_icu_d_ready),
      .icu_d_valid(i_icu_d_valid),
      .mpipe_araddr(o_mpipe_axi_m_araddr),
      .mpipe_arburst(o_mpipe_axi_m_arburst),
      .mpipe_arcache(o_mpipe_axi_m_arcache),
      .mpipe_arid(o_mpipe_axi_m_arid),
      .mpipe_arlen(o_mpipe_axi_m_arlen),
      .mpipe_arlock(o_mpipe_axi_m_arlock),
      .mpipe_arprot(o_mpipe_axi_m_arprot),
      .mpipe_arsize(o_mpipe_axi_m_arsize),
      .mpipe_arready(i_mpipe_axi_m_arready),
      .mpipe_arvalid(o_mpipe_axi_m_arvalid),
      .mpipe_awaddr(o_mpipe_axi_m_awaddr),
      .mpipe_awburst(o_mpipe_axi_m_awburst),
      .mpipe_awcache(o_mpipe_axi_m_awcache),
      .mpipe_awid(o_mpipe_axi_m_awid),
      .mpipe_awlen(o_mpipe_axi_m_awlen),
      .mpipe_awlock(o_mpipe_axi_m_awlock),
      .mpipe_awprot(o_mpipe_axi_m_awprot),
      .mpipe_awsize(o_mpipe_axi_m_awsize),
      .mpipe_awready(i_mpipe_axi_m_awready),
      .mpipe_awvalid(o_mpipe_axi_m_awvalid),
      .mpipe_bid(i_mpipe_axi_m_bid),
      .mpipe_bresp(i_mpipe_axi_m_bresp),
      .mpipe_bready(o_mpipe_axi_m_bready),
      .mpipe_bvalid(i_mpipe_axi_m_bvalid),
      .mpipe_rdata(i_mpipe_axi_m_rdata),
      .mpipe_rid(i_mpipe_axi_m_rid),
      .mpipe_rlast(i_mpipe_axi_m_rlast),
      .mpipe_rresp(i_mpipe_axi_m_rresp),
      .mpipe_rready(o_mpipe_axi_m_rready),
      .mpipe_rvalid(i_mpipe_axi_m_rvalid),
      .mpipe_wdata(o_mpipe_axi_m_wdata),
      .mpipe_wlast(o_mpipe_axi_m_wlast),
      .mpipe_wstrb(o_mpipe_axi_m_wstrb),
      .mpipe_wready(i_mpipe_axi_m_wready),
      .mpipe_wvalid(o_mpipe_axi_m_wvalid),
      .dcache_disable_init(i_dcache_disable_init),
      .icache_disable_init(i_icache_disable_init),
      .debugint(i_debugint),
      .hart_halted(o_hart_halted),
      .hart_id(i_hart_id),
      .hart_unavail(o_hart_unavail),
      .hart_under_reset(o_hart_under_reset),
      .mbist_addr(i_mbist_addr),
      .mbist_bwe(i_mbist_bwe),
      .mbist_en(i_mbist_en),
      .mbist_ramsel(i_mbist_ramsel),
      .mbist_rdata(o_mbist_rdata),
      .mbist_wdata(i_mbist_wdata),
      .mbist_we(i_mbist_we),
      .meip(i_meip),
      .msip(i_msip),
      .mtip(i_mtip),
      .nmi(i_nmi),
      .reset_vector(i_reset_vector),
      .resethaltreq(i_resethaltreq),
      .scan_enable(i_scan_enable),
      .seip(i_seip),
      .stoptime(o_stoptime),
      .test_mode(i_test_mode),
      .trace_cause(o_trace_cause),
      .trace_context(o_trace_context),
      .trace_ctype(o_trace_ctype),
      .trace_enabled(i_trace_enabled),
      .trace_halted(o_trace_halted),
      .trace_iaddr(o_trace_iaddr),
      .trace_ilastsize(o_trace_ilastsize),
      .trace_iretire(o_trace_iretire),
      .trace_itype(o_trace_itype),
      .trace_priv(o_trace_priv),
      .trace_reset(o_trace_reset),
      .trace_stall(i_trace_stall),
      .trace_trigger(o_trace_trigger),
      .trace_tval(o_trace_tval),
      .l2btb0_ctrl_in(i_l2btb_ctrl[0]),
      .l2btb1_ctrl_in(i_l2btb_ctrl[1]),
      .l2btb2_ctrl_in(i_l2btb_ctrl[2]),
      .l2btb3_ctrl_in(i_l2btb_ctrl[3]),
      .l2btb0_ctrl_out(o_l2btb_ctrl[0]),
      .l2btb1_ctrl_out(o_l2btb_ctrl[1]),
      .l2btb2_ctrl_out(o_l2btb_ctrl[2]),
      .l2btb3_ctrl_out(o_l2btb_ctrl[3]),
      .bht0_ctrl_in(i_bht_ctrl[0]),
      .bht1_ctrl_in(i_bht_ctrl[1]),
      .bht2_ctrl_in(i_bht_ctrl[2]),
      .bht3_ctrl_in(i_bht_ctrl[3]),
      .bht4_ctrl_in(i_bht_ctrl[4]),
      .bht5_ctrl_in(i_bht_ctrl[5]),
      .bht6_ctrl_in(i_bht_ctrl[6]),
      .bht0_ctrl_out(o_bht_ctrl[0]),
      .bht1_ctrl_out(o_bht_ctrl[1]),
      .bht2_ctrl_out(o_bht_ctrl[2]),
      .bht3_ctrl_out(o_bht_ctrl[3]),
      .bht4_ctrl_out(o_bht_ctrl[4]),
      .bht5_ctrl_out(o_bht_ctrl[5]),
      .bht6_ctrl_out(o_bht_ctrl[6]),
      .icache_data0_ctrl_in(i_icache_data_ctrl[0]),
      .icache_data1_ctrl_in(i_icache_data_ctrl[1]),
      .icache_data2_ctrl_in(i_icache_data_ctrl[2]),
      .icache_data3_ctrl_in(i_icache_data_ctrl[3]),
      .icache_data4_ctrl_in(i_icache_data_ctrl[4]),
      .icache_data5_ctrl_in(i_icache_data_ctrl[5]),
      .icache_data6_ctrl_in(i_icache_data_ctrl[6]),
      .icache_data7_ctrl_in(i_icache_data_ctrl[7]),
      .icache_data0_ctrl_out(o_icache_data_ctrl[0]),
      .icache_data1_ctrl_out(o_icache_data_ctrl[1]),
      .icache_data2_ctrl_out(o_icache_data_ctrl[2]),
      .icache_data3_ctrl_out(o_icache_data_ctrl[3]),
      .icache_data4_ctrl_out(o_icache_data_ctrl[4]),
      .icache_data5_ctrl_out(o_icache_data_ctrl[5]),
      .icache_data6_ctrl_out(o_icache_data_ctrl[6]),
      .icache_data7_ctrl_out(o_icache_data_ctrl[7]),
      .icache_tag0_ctrl_in(i_icache_tag_ctrl[0]),
      .icache_tag1_ctrl_in(i_icache_tag_ctrl[1]),
      .icache_tag2_ctrl_in(i_icache_tag_ctrl[2]),
      .icache_tag3_ctrl_in(i_icache_tag_ctrl[3]),
      .icache_tag4_ctrl_in(i_icache_tag_ctrl[4]),
      .icache_tag5_ctrl_in(i_icache_tag_ctrl[5]),
      .icache_tag6_ctrl_in(i_icache_tag_ctrl[6]),
      .icache_tag7_ctrl_in(i_icache_tag_ctrl[7]),
      .icache_tag0_ctrl_out(o_icache_tag_ctrl[0]),
      .icache_tag1_ctrl_out(o_icache_tag_ctrl[1]),
      .icache_tag2_ctrl_out(o_icache_tag_ctrl[2]),
      .icache_tag3_ctrl_out(o_icache_tag_ctrl[3]),
      .icache_tag4_ctrl_out(o_icache_tag_ctrl[4]),
      .icache_tag5_ctrl_out(o_icache_tag_ctrl[5]),
      .icache_tag6_ctrl_out(o_icache_tag_ctrl[6]),
      .icache_tag7_ctrl_out(o_icache_tag_ctrl[7]),
      .dcache_data0_ctrl_in(i_dcache_data_ctrl[0]),
      .dcache_data1_ctrl_in(i_dcache_data_ctrl[1]),
      .dcache_data2_ctrl_in(i_dcache_data_ctrl[2]),
      .dcache_data3_ctrl_in(i_dcache_data_ctrl[3]),
      .dcache_data4_ctrl_in(i_dcache_data_ctrl[4]),
      .dcache_data5_ctrl_in(i_dcache_data_ctrl[5]),
      .dcache_data6_ctrl_in(i_dcache_data_ctrl[6]),
      .dcache_data7_ctrl_in(i_dcache_data_ctrl[7]),
      .dcache_data8_ctrl_in(i_dcache_data_ctrl[8]),
      .dcache_data9_ctrl_in(i_dcache_data_ctrl[9]),
      .dcache_data10_ctrl_in(i_dcache_data_ctrl[10]),
      .dcache_data11_ctrl_in(i_dcache_data_ctrl[11]),
      .dcache_data12_ctrl_in(i_dcache_data_ctrl[12]),
      .dcache_data13_ctrl_in(i_dcache_data_ctrl[13]),
      .dcache_data14_ctrl_in(i_dcache_data_ctrl[14]),
      .dcache_data15_ctrl_in(i_dcache_data_ctrl[15]),
      .dcache_data0_ctrl_out(o_dcache_data_ctrl[0]),
      .dcache_data1_ctrl_out(o_dcache_data_ctrl[1]),
      .dcache_data2_ctrl_out(o_dcache_data_ctrl[2]),
      .dcache_data3_ctrl_out(o_dcache_data_ctrl[3]),
      .dcache_data4_ctrl_out(o_dcache_data_ctrl[4]),
      .dcache_data5_ctrl_out(o_dcache_data_ctrl[5]),
      .dcache_data6_ctrl_out(o_dcache_data_ctrl[6]),
      .dcache_data7_ctrl_out(o_dcache_data_ctrl[7]),
      .dcache_data8_ctrl_out(o_dcache_data_ctrl[8]),
      .dcache_data9_ctrl_out(o_dcache_data_ctrl[9]),
      .dcache_data10_ctrl_out(o_dcache_data_ctrl[10]),
      .dcache_data11_ctrl_out(o_dcache_data_ctrl[11]),
      .dcache_data12_ctrl_out(o_dcache_data_ctrl[12]),
      .dcache_data13_ctrl_out(o_dcache_data_ctrl[13]),
      .dcache_data14_ctrl_out(o_dcache_data_ctrl[14]),
      .dcache_data15_ctrl_out(o_dcache_data_ctrl[15]),
      .dcache_tag0_ctrl_in(i_dcache_tag_ctrl[0]),
      .dcache_tag1_ctrl_in(i_dcache_tag_ctrl[1]),
      .dcache_tag2_ctrl_in(i_dcache_tag_ctrl[2]),
      .dcache_tag3_ctrl_in(i_dcache_tag_ctrl[3]),
      .dcache_tag4_ctrl_in(i_dcache_tag_ctrl[4]),
      .dcache_tag5_ctrl_in(i_dcache_tag_ctrl[5]),
      .dcache_tag6_ctrl_in(i_dcache_tag_ctrl[6]),
      .dcache_tag7_ctrl_in(i_dcache_tag_ctrl[7]),
      .dcache_tag8_ctrl_in(i_dcache_tag_ctrl[8]),
      .dcache_tag9_ctrl_in(i_dcache_tag_ctrl[9]),
      .dcache_tag10_ctrl_in(i_dcache_tag_ctrl[10]),
      .dcache_tag11_ctrl_in(i_dcache_tag_ctrl[11]),
      .dcache_tag12_ctrl_in(i_dcache_tag_ctrl[12]),
      .dcache_tag13_ctrl_in(i_dcache_tag_ctrl[13]),
      .dcache_tag14_ctrl_in(i_dcache_tag_ctrl[14]),
      .dcache_tag15_ctrl_in(i_dcache_tag_ctrl[15]),
      .dcache_tag0_ctrl_out(o_dcache_tag_ctrl[0]),
      .dcache_tag1_ctrl_out(o_dcache_tag_ctrl[1]),
      .dcache_tag2_ctrl_out(o_dcache_tag_ctrl[2]),
      .dcache_tag3_ctrl_out(o_dcache_tag_ctrl[3]),
      .dcache_tag4_ctrl_out(o_dcache_tag_ctrl[4]),
      .dcache_tag5_ctrl_out(o_dcache_tag_ctrl[5]),
      .dcache_tag6_ctrl_out(o_dcache_tag_ctrl[6]),
      .dcache_tag7_ctrl_out(o_dcache_tag_ctrl[7]),
      .dcache_tag8_ctrl_out(o_dcache_tag_ctrl[8]),
      .dcache_tag9_ctrl_out(o_dcache_tag_ctrl[9]),
      .dcache_tag10_ctrl_out(o_dcache_tag_ctrl[10]),
      .dcache_tag11_ctrl_out(o_dcache_tag_ctrl[11]),
      .dcache_tag12_ctrl_out(o_dcache_tag_ctrl[12]),
      .dcache_tag13_ctrl_out(o_dcache_tag_ctrl[13]),
      .dcache_tag14_ctrl_out(o_dcache_tag_ctrl[14]),
      .dcache_tag15_ctrl_out(o_dcache_tag_ctrl[15]),
      .dcache_dtag0_ctrl_in(i_dcache_dtag_ctrl[0]),
      .dcache_dtag1_ctrl_in(i_dcache_dtag_ctrl[1]),
      .dcache_dtag2_ctrl_in(i_dcache_dtag_ctrl[2]),
      .dcache_dtag3_ctrl_in(i_dcache_dtag_ctrl[3]),
      .dcache_dtag4_ctrl_in(i_dcache_dtag_ctrl[4]),
      .dcache_dtag5_ctrl_in(i_dcache_dtag_ctrl[5]),
      .dcache_dtag6_ctrl_in(i_dcache_dtag_ctrl[6]),
      .dcache_dtag7_ctrl_in(i_dcache_dtag_ctrl[7]),
      .dcache_dtag8_ctrl_in(i_dcache_dtag_ctrl[8]),
      .dcache_dtag9_ctrl_in(i_dcache_dtag_ctrl[9]),
      .dcache_dtag10_ctrl_in(i_dcache_dtag_ctrl[10]),
      .dcache_dtag11_ctrl_in(i_dcache_dtag_ctrl[11]),
      .dcache_dtag12_ctrl_in(i_dcache_dtag_ctrl[12]),
      .dcache_dtag13_ctrl_in(i_dcache_dtag_ctrl[13]),
      .dcache_dtag14_ctrl_in(i_dcache_dtag_ctrl[14]),
      .dcache_dtag15_ctrl_in(i_dcache_dtag_ctrl[15]),
      .dcache_dtag0_ctrl_out(o_dcache_dtag_ctrl[0]),
      .dcache_dtag1_ctrl_out(o_dcache_dtag_ctrl[1]),
      .dcache_dtag2_ctrl_out(o_dcache_dtag_ctrl[2]),
      .dcache_dtag3_ctrl_out(o_dcache_dtag_ctrl[3]),
      .dcache_dtag4_ctrl_out(o_dcache_dtag_ctrl[4]),
      .dcache_dtag5_ctrl_out(o_dcache_dtag_ctrl[5]),
      .dcache_dtag6_ctrl_out(o_dcache_dtag_ctrl[6]),
      .dcache_dtag7_ctrl_out(o_dcache_dtag_ctrl[7]),
      .dcache_dtag8_ctrl_out(o_dcache_dtag_ctrl[8]),
      .dcache_dtag9_ctrl_out(o_dcache_dtag_ctrl[9]),
      .dcache_dtag10_ctrl_out(o_dcache_dtag_ctrl[10]),
      .dcache_dtag11_ctrl_out(o_dcache_dtag_ctrl[11]),
      .dcache_dtag12_ctrl_out(o_dcache_dtag_ctrl[12]),
      .dcache_dtag13_ctrl_out(o_dcache_dtag_ctrl[13]),
      .dcache_dtag14_ctrl_out(o_dcache_dtag_ctrl[14]),
      .dcache_dtag15_ctrl_out(o_dcache_dtag_ctrl[15]),
      .l2itlb_tag0_ctrl_in(i_l2itlb_tag_ctrl[0]),
      .l2itlb_tag1_ctrl_in(i_l2itlb_tag_ctrl[1]),
      .l2itlb_tag2_ctrl_in(i_l2itlb_tag_ctrl[2]),
      .l2itlb_tag3_ctrl_in(i_l2itlb_tag_ctrl[3]),
      .l2itlb_tag0_ctrl_out(o_l2itlb_tag_ctrl[0]),
      .l2itlb_tag1_ctrl_out(o_l2itlb_tag_ctrl[1]),
      .l2itlb_tag2_ctrl_out(o_l2itlb_tag_ctrl[2]),
      .l2itlb_tag3_ctrl_out(o_l2itlb_tag_ctrl[3]),
      .l2itlb_data0_ctrl_in(i_l2itlb_data_ctrl[0]),
      .l2itlb_data1_ctrl_in(i_l2itlb_data_ctrl[1]),
      .l2itlb_data2_ctrl_in(i_l2itlb_data_ctrl[2]),
      .l2itlb_data3_ctrl_in(i_l2itlb_data_ctrl[3]),
      .l2itlb_data0_ctrl_out(o_l2itlb_data_ctrl[0]),
      .l2itlb_data1_ctrl_out(o_l2itlb_data_ctrl[1]),
      .l2itlb_data2_ctrl_out(o_l2itlb_data_ctrl[2]),
      .l2itlb_data3_ctrl_out(o_l2itlb_data_ctrl[3]),
      .l2dtlb_tag0_ctrl_in(i_l2dtlb_tag_ctrl[0]),
      .l2dtlb_tag1_ctrl_in(i_l2dtlb_tag_ctrl[1]),
      .l2dtlb_tag2_ctrl_in(i_l2dtlb_tag_ctrl[2]),
      .l2dtlb_tag3_ctrl_in(i_l2dtlb_tag_ctrl[3]),
      .l2dtlb_tag0_ctrl_out(o_l2dtlb_tag_ctrl[0]),
      .l2dtlb_tag1_ctrl_out(o_l2dtlb_tag_ctrl[1]),
      .l2dtlb_tag2_ctrl_out(o_l2dtlb_tag_ctrl[2]),
      .l2dtlb_tag3_ctrl_out(o_l2dtlb_tag_ctrl[3]),
      .l2dtlb_data0_ctrl_in(i_l2dtlb_data_ctrl[0]),
      .l2dtlb_data1_ctrl_in(i_l2dtlb_data_ctrl[1]),
      .l2dtlb_data2_ctrl_in(i_l2dtlb_data_ctrl[2]),
      .l2dtlb_data3_ctrl_in(i_l2dtlb_data_ctrl[3]),
      .l2dtlb_data0_ctrl_out(o_l2dtlb_data_ctrl[0]),
      .l2dtlb_data1_ctrl_out(o_l2dtlb_data_ctrl[1]),
      .l2dtlb_data2_ctrl_out(o_l2dtlb_data_ctrl[2]),
      .l2dtlb_data3_ctrl_out(o_l2dtlb_data_ctrl[3])
  );

endmodule
