// auto generated file with https://git.axelera.ai/vincent.morillon/ax65_wrapper

module ax65_l2_wrapper #(
    parameter int unsigned CORE_WIDTH = 8,
    parameter int unsigned L2C_BANK_WIDTH = 4,
    parameter int unsigned L2C_BANK_DATA_WIDTH = 8,
    parameter int unsigned L2C_BANK_TAG_WIDTH = 64,
    parameter int unsigned SINK_WIDTH = 6,
    parameter int unsigned SOURCE_WIDTH = 5,
    parameter int unsigned CTRL_IN_WIDTH = 9,
    parameter int unsigned CTRL_OUT_WIDTH = 1
) (
    input wire i_clk,
    input wire i_rst_n,
    input logic i_test_mode,
    input logic [CORE_WIDTH - 1:0] i_cores_coherent_enable,
    output logic [CORE_WIDTH - 1:0] o_cores_coherent_state,
    input logic [CORE_WIDTH - 1:0][39:0] i_cores_m0_a_address,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_a_corrupt,
    input logic [CORE_WIDTH - 1:0][255:0] i_cores_m0_a_data,
    input logic [CORE_WIDTH - 1:0][31:0] i_cores_m0_a_mask,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m0_a_opcode,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m0_a_param,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m0_a_size,
    input logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_cores_m0_a_source,
    input logic [CORE_WIDTH - 1:0][11:0] i_cores_m0_a_user,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_a_ready,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_a_valid,
    output logic [CORE_WIDTH - 1:0][39:0] o_cores_m0_b_address,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_b_corrupt,
    output logic [CORE_WIDTH - 1:0][255:0] o_cores_m0_b_data,
    output logic [CORE_WIDTH - 1:0][31:0] o_cores_m0_b_mask,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m0_b_opcode,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m0_b_param,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m0_b_size,
    output logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_cores_m0_b_source,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_b_ready,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_b_valid,
    input logic [CORE_WIDTH - 1:0][39:0] i_cores_m0_c_address,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_c_corrupt,
    input logic [CORE_WIDTH - 1:0][255:0] i_cores_m0_c_data,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m0_c_opcode,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m0_c_param,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m0_c_size,
    input logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_cores_m0_c_source,
    input logic [CORE_WIDTH - 1:0][7:0] i_cores_m0_c_user,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_c_ready,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_c_valid,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_d_corrupt,
    output logic [CORE_WIDTH - 1:0][255:0] o_cores_m0_d_data,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_d_denied,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m0_d_opcode,
    output logic [CORE_WIDTH - 1:0][1:0] o_cores_m0_d_param,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m0_d_size,
    output logic [CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] o_cores_m0_d_sink,
    output logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_cores_m0_d_source,
    output logic [CORE_WIDTH - 1:0][5:0] o_cores_m0_d_user,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_d_ready,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_d_valid,
    input logic [CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] i_cores_m0_e_sink,
    output logic [CORE_WIDTH - 1:0] o_cores_m0_e_ready,
    input logic [CORE_WIDTH - 1:0] i_cores_m0_e_valid,
    input logic [CORE_WIDTH - 1:0][39:0] i_cores_m1_axi_s_araddr,
    input logic [CORE_WIDTH - 1:0][1:0] i_cores_m1_axi_s_arburst,
    input logic [CORE_WIDTH - 1:0][3:0] i_cores_m1_axi_s_arcache,
    input logic [CORE_WIDTH - 1:0][4:0] i_cores_m1_axi_s_arid,
    input logic [CORE_WIDTH - 1:0][7:0] i_cores_m1_axi_s_arlen,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_arlock,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m1_axi_s_arprot,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m1_axi_s_arsize,
    output logic [CORE_WIDTH - 1:0] o_cores_m1_axi_s_arready,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_arvalid,
    input logic [CORE_WIDTH - 1:0][39:0] i_cores_m1_axi_s_awaddr,
    input logic [CORE_WIDTH - 1:0][1:0] i_cores_m1_axi_s_awburst,
    input logic [CORE_WIDTH - 1:0][3:0] i_cores_m1_axi_s_awcache,
    input logic [CORE_WIDTH - 1:0][4:0] i_cores_m1_axi_s_awid,
    input logic [CORE_WIDTH - 1:0][7:0] i_cores_m1_axi_s_awlen,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_awlock,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m1_axi_s_awprot,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m1_axi_s_awsize,
    output logic [CORE_WIDTH - 1:0] o_cores_m1_axi_s_awready,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_awvalid,
    output logic [CORE_WIDTH - 1:0][4:0] o_cores_m1_axi_s_bid,
    output logic [CORE_WIDTH - 1:0][1:0] o_cores_m1_axi_s_bresp,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_bready,
    output logic [CORE_WIDTH - 1:0] o_cores_m1_axi_s_bvalid,
    output logic [CORE_WIDTH - 1:0][63:0] o_cores_m1_axi_s_rdata,
    output logic [CORE_WIDTH - 1:0][4:0] o_cores_m1_axi_s_rid,
    output logic [CORE_WIDTH - 1:0] o_cores_m1_axi_s_rlast,
    output logic [CORE_WIDTH - 1:0][1:0] o_cores_m1_axi_s_rresp,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_rready,
    output logic [CORE_WIDTH - 1:0] o_cores_m1_axi_s_rvalid,
    input logic [CORE_WIDTH - 1:0][63:0] i_cores_m1_axi_s_wdata,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_wlast,
    input logic [CORE_WIDTH - 1:0][(64 / 8) -1:0] i_cores_m1_axi_s_wstrb,
    output logic [CORE_WIDTH - 1:0] o_cores_m1_axi_s_wready,
    input logic [CORE_WIDTH - 1:0] i_cores_m1_axi_s_wvalid,
    input logic [CORE_WIDTH - 1:0][39:0] i_cores_m2_a_address,
    input logic [CORE_WIDTH - 1:0] i_cores_m2_a_corrupt,
    input logic [CORE_WIDTH - 1:0][255:0] i_cores_m2_a_data,
    input logic [CORE_WIDTH - 1:0][31:0] i_cores_m2_a_mask,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m2_a_opcode,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m2_a_param,
    input logic [CORE_WIDTH - 1:0][2:0] i_cores_m2_a_size,
    input logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] i_cores_m2_a_source,
    input logic [CORE_WIDTH - 1:0][11:0] i_cores_m2_a_user,
    output logic [CORE_WIDTH - 1:0] o_cores_m2_a_ready,
    input logic [CORE_WIDTH - 1:0] i_cores_m2_a_valid,
    output logic [CORE_WIDTH - 1:0] o_cores_m2_d_corrupt,
    output logic [CORE_WIDTH - 1:0][255:0] o_cores_m2_d_data,
    output logic [CORE_WIDTH - 1:0] o_cores_m2_d_denied,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m2_d_opcode,
    output logic [CORE_WIDTH - 1:0][1:0] o_cores_m2_d_param,
    output logic [CORE_WIDTH - 1:0][2:0] o_cores_m2_d_size,
    output logic [CORE_WIDTH - 1:0][SINK_WIDTH - 1:0] o_cores_m2_d_sink,
    output logic [CORE_WIDTH - 1:0][SOURCE_WIDTH - 1:0] o_cores_m2_d_source,
    output logic [CORE_WIDTH - 1:0][5:0] o_cores_m2_d_user,
    input logic [CORE_WIDTH - 1:0] i_cores_m2_d_ready,
    output logic [CORE_WIDTH - 1:0] o_cores_m2_d_valid,
    input wire i_iocp_aclk,
    input logic [39:0] i_iocp_axi_s_araddr,
    input logic [1:0] i_iocp_axi_s_arburst,
    input logic [3:0] i_iocp_axi_s_arcache,
    input logic [12:0] i_iocp_axi_s_arid,
    input logic [7:0] i_iocp_axi_s_arlen,
    input logic i_iocp_axi_s_arlock,
    input logic [2:0] i_iocp_axi_s_arprot,
    input logic [2:0] i_iocp_axi_s_arsize,
    output logic o_iocp_axi_s_arready,
    input logic i_iocp_axi_s_arvalid,
    input logic [39:0] i_iocp_axi_s_awaddr,
    input logic [1:0] i_iocp_axi_s_awburst,
    input logic [3:0] i_iocp_axi_s_awcache,
    input logic [12:0] i_iocp_axi_s_awid,
    input logic [7:0] i_iocp_axi_s_awlen,
    input logic i_iocp_axi_s_awlock,
    input logic [2:0] i_iocp_axi_s_awprot,
    input logic [2:0] i_iocp_axi_s_awsize,
    output logic o_iocp_axi_s_awready,
    input logic i_iocp_axi_s_awvalid,
    output logic [12:0] o_iocp_axi_s_bid,
    output logic [1:0] o_iocp_axi_s_bresp,
    input logic i_iocp_axi_s_bready,
    output logic o_iocp_axi_s_bvalid,
    output logic [255:0] o_iocp_axi_s_rdata,
    output logic [12:0] o_iocp_axi_s_rid,
    output logic o_iocp_axi_s_rlast,
    output logic [1:0] o_iocp_axi_s_rresp,
    input logic i_iocp_axi_s_rready,
    output logic o_iocp_axi_s_rvalid,
    input logic [255:0] i_iocp_axi_s_wdata,
    input logic i_iocp_axi_s_wlast,
    input logic [(256 / 8) - 1:0] i_iocp_axi_s_wstrb,
    output logic o_iocp_axi_s_wready,
    input logic i_iocp_axi_s_wvalid,
    input wire i_mem_aclk,
    output logic [39:0] o_mem_axi_m_araddr,
    output logic [1:0] o_mem_axi_m_arburst,
    output logic [3:0] o_mem_axi_m_arcache,
    output logic [7:0] o_mem_axi_m_arid,
    output logic [7:0] o_mem_axi_m_arlen,
    output logic o_mem_axi_m_arlock,
    output logic [2:0] o_mem_axi_m_arprot,
    output logic [2:0] o_mem_axi_m_arsize,
    input logic i_mem_axi_m_arready,
    output logic o_mem_axi_m_arvalid,
    output logic [39:0] o_mem_axi_m_awaddr,
    output logic [1:0] o_mem_axi_m_awburst,
    output logic [3:0] o_mem_axi_m_awcache,
    output logic [7:0] o_mem_axi_m_awid,
    output logic [7:0] o_mem_axi_m_awlen,
    output logic o_mem_axi_m_awlock,
    output logic [2:0] o_mem_axi_m_awprot,
    output logic [2:0] o_mem_axi_m_awsize,
    input logic i_mem_axi_m_awready,
    output logic o_mem_axi_m_awvalid,
    input logic [7:0] i_mem_axi_m_bid,
    input logic [1:0] i_mem_axi_m_bresp,
    output logic o_mem_axi_m_bready,
    input logic i_mem_axi_m_bvalid,
    input logic [255:0] i_mem_axi_m_rdata,
    input logic [7:0] i_mem_axi_m_rid,
    input logic i_mem_axi_m_rlast,
    input logic [1:0] i_mem_axi_m_rresp,
    output logic o_mem_axi_m_rready,
    input logic i_mem_axi_m_rvalid,
    output logic [255:0] o_mem_axi_m_wdata,
    output logic o_mem_axi_m_wlast,
    output logic [(256 / 8) - 1:0] o_mem_axi_m_wstrb,
    input logic i_mem_axi_m_wready,
    output logic o_mem_axi_m_wvalid,
    input wire i_mmio_aclk,
    input wire i_mmio_arst_n,
    output logic [39:0] o_mmio_axi_m_araddr,
    output logic [1:0] o_mmio_axi_m_arburst,
    output logic [3:0] o_mmio_axi_m_arcache,
    output logic [7:0] o_mmio_axi_m_arid,
    output logic [7:0] o_mmio_axi_m_arlen,
    output logic o_mmio_axi_m_arlock,
    output logic [2:0] o_mmio_axi_m_arprot,
    output logic [2:0] o_mmio_axi_m_arsize,
    input logic i_mmio_axi_m_arready,
    output logic o_mmio_axi_m_arvalid,
    output logic [39:0] o_mmio_axi_m_awaddr,
    output logic [1:0] o_mmio_axi_m_awburst,
    output logic [3:0] o_mmio_axi_m_awcache,
    output logic [7:0] o_mmio_axi_m_awid,
    output logic [7:0] o_mmio_axi_m_awlen,
    output logic o_mmio_axi_m_awlock,
    output logic [2:0] o_mmio_axi_m_awprot,
    output logic [2:0] o_mmio_axi_m_awsize,
    input logic i_mmio_axi_m_awready,
    output logic o_mmio_axi_m_awvalid,
    input logic [7:0] i_mmio_axi_m_bid,
    input logic [1:0] i_mmio_axi_m_bresp,
    output logic o_mmio_axi_m_bready,
    input logic i_mmio_axi_m_bvalid,
    input logic [63:0] i_mmio_axi_m_rdata,
    input logic [7:0] i_mmio_axi_m_rid,
    input logic i_mmio_axi_m_rlast,
    input logic [1:0] i_mmio_axi_m_rresp,
    output logic o_mmio_axi_m_rready,
    input logic i_mmio_axi_m_rvalid,
    output logic [63:0] o_mmio_axi_m_wdata,
    output logic o_mmio_axi_m_wlast,
    output logic [(64 / 8) - 1:0] o_mmio_axi_m_wstrb,
    input logic i_mmio_axi_m_wready,
    output logic o_mmio_axi_m_wvalid,
    output logic [39:0] o_plmt_axi_m_araddr,
    output logic [1:0] o_plmt_axi_m_arburst,
    output logic [3:0] o_plmt_axi_m_arcache,
    output logic [7:0] o_plmt_axi_m_arid,
    output logic [7:0] o_plmt_axi_m_arlen,
    output logic o_plmt_axi_m_arlock,
    output logic [2:0] o_plmt_axi_m_arprot,
    output logic [2:0] o_plmt_axi_m_arsize,
    input logic i_plmt_axi_m_arready,
    output logic o_plmt_axi_m_arvalid,
    output logic [39:0] o_plmt_axi_m_awaddr,
    output logic [1:0] o_plmt_axi_m_awburst,
    output logic [3:0] o_plmt_axi_m_awcache,
    output logic [7:0] o_plmt_axi_m_awid,
    output logic [7:0] o_plmt_axi_m_awlen,
    output logic o_plmt_axi_m_awlock,
    output logic [2:0] o_plmt_axi_m_awprot,
    output logic [2:0] o_plmt_axi_m_awsize,
    input logic i_plmt_axi_m_awready,
    output logic o_plmt_axi_m_awvalid,
    input logic [7:0] i_plmt_axi_m_bid,
    input logic [1:0] i_plmt_axi_m_bresp,
    output logic o_plmt_axi_m_bready,
    input logic i_plmt_axi_m_bvalid,
    input logic [63:0] i_plmt_axi_m_rdata,
    input logic [7:0] i_plmt_axi_m_rid,
    input logic i_plmt_axi_m_rlast,
    input logic [1:0] i_plmt_axi_m_rresp,
    output logic o_plmt_axi_m_rready,
    input logic i_plmt_axi_m_rvalid,
    output logic [63:0] o_plmt_axi_m_wdata,
    output logic o_plmt_axi_m_wlast,
    output logic [(64 / 8) - 1:0] o_plmt_axi_m_wstrb,
    input logic i_plmt_axi_m_wready,
    output logic o_plmt_axi_m_wvalid,
    input wire [L2C_BANK_WIDTH - 1:0] i_l2c_banks_clk,
    input logic [L2C_BANK_WIDTH - 1:0] i_l2c_banks_clk_en,
    input logic [L2C_BANK_WIDTH - 1:0][(L2C_BANK_TAG_WIDTH * CTRL_IN_WIDTH) - 1:0] i_l2c_banks_tag_ctrl,
    output logic [L2C_BANK_WIDTH - 1:0][(L2C_BANK_TAG_WIDTH * CTRL_OUT_WIDTH) - 1:0] o_l2c_banks_tag_ctrl,
    input logic [L2C_BANK_WIDTH - 1:0][(L2C_BANK_DATA_WIDTH * CTRL_IN_WIDTH) - 1:0] i_l2c_banks_data_ctrl,
    output logic [L2C_BANK_WIDTH - 1:0][(L2C_BANK_DATA_WIDTH * CTRL_OUT_WIDTH) - 1:0] o_l2c_banks_data_ctrl,
    input logic i_l2c_disable_init,
    output logic o_l2c_err_int
);

  ax65_l2_top u_ax65_l2_top (
      .l2c_bank0_data_ram_clk(i_l2c_banks_clk[0]),
      .l2c_bank0_data_ram_clk_en(i_l2c_banks_clk_en[0]),
      .l2c_bank0_tag_ram_ctrl_in(i_l2c_banks_tag_ctrl[0]),
      .l2c_bank0_tag_ram_ctrl_out(o_l2c_banks_tag_ctrl[0]),
      .l2c_bank0_data_ram_ctrl_in(i_l2c_banks_data_ctrl[0]),
      .l2c_bank0_data_ram_ctrl_out(o_l2c_banks_data_ctrl[0]),
      .l2c_bank1_data_ram_clk(i_l2c_banks_clk[1]),
      .l2c_bank1_data_ram_clk_en(i_l2c_banks_clk_en[1]),
      .l2c_bank1_tag_ram_ctrl_in(i_l2c_banks_tag_ctrl[1]),
      .l2c_bank1_tag_ram_ctrl_out(o_l2c_banks_tag_ctrl[1]),
      .l2c_bank1_data_ram_ctrl_in(i_l2c_banks_data_ctrl[1]),
      .l2c_bank1_data_ram_ctrl_out(o_l2c_banks_data_ctrl[1]),
      .l2c_bank2_data_ram_clk(i_l2c_banks_clk[2]),
      .l2c_bank2_data_ram_clk_en(i_l2c_banks_clk_en[2]),
      .l2c_bank2_tag_ram_ctrl_in(i_l2c_banks_tag_ctrl[2]),
      .l2c_bank2_tag_ram_ctrl_out(o_l2c_banks_tag_ctrl[2]),
      .l2c_bank2_data_ram_ctrl_in(i_l2c_banks_data_ctrl[2]),
      .l2c_bank2_data_ram_ctrl_out(o_l2c_banks_data_ctrl[2]),
      .l2c_bank3_data_ram_clk(i_l2c_banks_clk[3]),
      .l2c_bank3_data_ram_clk_en(i_l2c_banks_clk_en[3]),
      .l2c_bank3_tag_ram_ctrl_in(i_l2c_banks_tag_ctrl[3]),
      .l2c_bank3_tag_ram_ctrl_out(o_l2c_banks_tag_ctrl[3]),
      .l2c_bank3_data_ram_ctrl_in(i_l2c_banks_data_ctrl[3]),
      .l2c_bank3_data_ram_ctrl_out(o_l2c_banks_data_ctrl[3]),
      .l2_clk(i_clk),
      .l2_resetn(i_rst_n),
      .i_test_mode(i_test_mode),
      .core0_coherent_enable(i_cores_coherent_enable[0]),
      .core1_coherent_enable(i_cores_coherent_enable[1]),
      .core2_coherent_enable(i_cores_coherent_enable[2]),
      .core3_coherent_enable(i_cores_coherent_enable[3]),
      .core4_coherent_enable(i_cores_coherent_enable[4]),
      .core5_coherent_enable(i_cores_coherent_enable[5]),
      .core6_coherent_enable(i_cores_coherent_enable[6]),
      .core7_coherent_enable(i_cores_coherent_enable[7]),
      .core0_coherent_state(o_cores_coherent_state[0]),
      .core1_coherent_state(o_cores_coherent_state[1]),
      .core2_coherent_state(o_cores_coherent_state[2]),
      .core3_coherent_state(o_cores_coherent_state[3]),
      .core4_coherent_state(o_cores_coherent_state[4]),
      .core5_coherent_state(o_cores_coherent_state[5]),
      .core6_coherent_state(o_cores_coherent_state[6]),
      .core7_coherent_state(o_cores_coherent_state[7]),
      .core0_m0_a_address(i_cores_m0_a_address[0]),
      .core1_m0_a_address(i_cores_m0_a_address[1]),
      .core2_m0_a_address(i_cores_m0_a_address[2]),
      .core3_m0_a_address(i_cores_m0_a_address[3]),
      .core4_m0_a_address(i_cores_m0_a_address[4]),
      .core5_m0_a_address(i_cores_m0_a_address[5]),
      .core6_m0_a_address(i_cores_m0_a_address[6]),
      .core7_m0_a_address(i_cores_m0_a_address[7]),
      .core0_m0_a_corrupt(i_cores_m0_a_corrupt[0]),
      .core1_m0_a_corrupt(i_cores_m0_a_corrupt[1]),
      .core2_m0_a_corrupt(i_cores_m0_a_corrupt[2]),
      .core3_m0_a_corrupt(i_cores_m0_a_corrupt[3]),
      .core4_m0_a_corrupt(i_cores_m0_a_corrupt[4]),
      .core5_m0_a_corrupt(i_cores_m0_a_corrupt[5]),
      .core6_m0_a_corrupt(i_cores_m0_a_corrupt[6]),
      .core7_m0_a_corrupt(i_cores_m0_a_corrupt[7]),
      .core0_m0_a_data(i_cores_m0_a_data[0]),
      .core1_m0_a_data(i_cores_m0_a_data[1]),
      .core2_m0_a_data(i_cores_m0_a_data[2]),
      .core3_m0_a_data(i_cores_m0_a_data[3]),
      .core4_m0_a_data(i_cores_m0_a_data[4]),
      .core5_m0_a_data(i_cores_m0_a_data[5]),
      .core6_m0_a_data(i_cores_m0_a_data[6]),
      .core7_m0_a_data(i_cores_m0_a_data[7]),
      .core0_m0_a_mask(i_cores_m0_a_mask[0]),
      .core1_m0_a_mask(i_cores_m0_a_mask[1]),
      .core2_m0_a_mask(i_cores_m0_a_mask[2]),
      .core3_m0_a_mask(i_cores_m0_a_mask[3]),
      .core4_m0_a_mask(i_cores_m0_a_mask[4]),
      .core5_m0_a_mask(i_cores_m0_a_mask[5]),
      .core6_m0_a_mask(i_cores_m0_a_mask[6]),
      .core7_m0_a_mask(i_cores_m0_a_mask[7]),
      .core0_m0_a_opcode(i_cores_m0_a_opcode[0]),
      .core1_m0_a_opcode(i_cores_m0_a_opcode[1]),
      .core2_m0_a_opcode(i_cores_m0_a_opcode[2]),
      .core3_m0_a_opcode(i_cores_m0_a_opcode[3]),
      .core4_m0_a_opcode(i_cores_m0_a_opcode[4]),
      .core5_m0_a_opcode(i_cores_m0_a_opcode[5]),
      .core6_m0_a_opcode(i_cores_m0_a_opcode[6]),
      .core7_m0_a_opcode(i_cores_m0_a_opcode[7]),
      .core0_m0_a_param(i_cores_m0_a_param[0]),
      .core1_m0_a_param(i_cores_m0_a_param[1]),
      .core2_m0_a_param(i_cores_m0_a_param[2]),
      .core3_m0_a_param(i_cores_m0_a_param[3]),
      .core4_m0_a_param(i_cores_m0_a_param[4]),
      .core5_m0_a_param(i_cores_m0_a_param[5]),
      .core6_m0_a_param(i_cores_m0_a_param[6]),
      .core7_m0_a_param(i_cores_m0_a_param[7]),
      .core0_m0_a_size(i_cores_m0_a_size[0]),
      .core1_m0_a_size(i_cores_m0_a_size[1]),
      .core2_m0_a_size(i_cores_m0_a_size[2]),
      .core3_m0_a_size(i_cores_m0_a_size[3]),
      .core4_m0_a_size(i_cores_m0_a_size[4]),
      .core5_m0_a_size(i_cores_m0_a_size[5]),
      .core6_m0_a_size(i_cores_m0_a_size[6]),
      .core7_m0_a_size(i_cores_m0_a_size[7]),
      .core0_m0_a_source(i_cores_m0_a_source[0]),
      .core1_m0_a_source(i_cores_m0_a_source[1]),
      .core2_m0_a_source(i_cores_m0_a_source[2]),
      .core3_m0_a_source(i_cores_m0_a_source[3]),
      .core4_m0_a_source(i_cores_m0_a_source[4]),
      .core5_m0_a_source(i_cores_m0_a_source[5]),
      .core6_m0_a_source(i_cores_m0_a_source[6]),
      .core7_m0_a_source(i_cores_m0_a_source[7]),
      .core0_m0_a_user(i_cores_m0_a_user[0]),
      .core1_m0_a_user(i_cores_m0_a_user[1]),
      .core2_m0_a_user(i_cores_m0_a_user[2]),
      .core3_m0_a_user(i_cores_m0_a_user[3]),
      .core4_m0_a_user(i_cores_m0_a_user[4]),
      .core5_m0_a_user(i_cores_m0_a_user[5]),
      .core6_m0_a_user(i_cores_m0_a_user[6]),
      .core7_m0_a_user(i_cores_m0_a_user[7]),
      .core0_m0_a_ready(o_cores_m0_a_ready[0]),
      .core1_m0_a_ready(o_cores_m0_a_ready[1]),
      .core2_m0_a_ready(o_cores_m0_a_ready[2]),
      .core3_m0_a_ready(o_cores_m0_a_ready[3]),
      .core4_m0_a_ready(o_cores_m0_a_ready[4]),
      .core5_m0_a_ready(o_cores_m0_a_ready[5]),
      .core6_m0_a_ready(o_cores_m0_a_ready[6]),
      .core7_m0_a_ready(o_cores_m0_a_ready[7]),
      .core0_m0_a_valid(i_cores_m0_a_valid[0]),
      .core1_m0_a_valid(i_cores_m0_a_valid[1]),
      .core2_m0_a_valid(i_cores_m0_a_valid[2]),
      .core3_m0_a_valid(i_cores_m0_a_valid[3]),
      .core4_m0_a_valid(i_cores_m0_a_valid[4]),
      .core5_m0_a_valid(i_cores_m0_a_valid[5]),
      .core6_m0_a_valid(i_cores_m0_a_valid[6]),
      .core7_m0_a_valid(i_cores_m0_a_valid[7]),
      .core0_m0_b_address(o_cores_m0_b_address[0]),
      .core1_m0_b_address(o_cores_m0_b_address[1]),
      .core2_m0_b_address(o_cores_m0_b_address[2]),
      .core3_m0_b_address(o_cores_m0_b_address[3]),
      .core4_m0_b_address(o_cores_m0_b_address[4]),
      .core5_m0_b_address(o_cores_m0_b_address[5]),
      .core6_m0_b_address(o_cores_m0_b_address[6]),
      .core7_m0_b_address(o_cores_m0_b_address[7]),
      .core0_m0_b_corrupt(o_cores_m0_b_corrupt[0]),
      .core1_m0_b_corrupt(o_cores_m0_b_corrupt[1]),
      .core2_m0_b_corrupt(o_cores_m0_b_corrupt[2]),
      .core3_m0_b_corrupt(o_cores_m0_b_corrupt[3]),
      .core4_m0_b_corrupt(o_cores_m0_b_corrupt[4]),
      .core5_m0_b_corrupt(o_cores_m0_b_corrupt[5]),
      .core6_m0_b_corrupt(o_cores_m0_b_corrupt[6]),
      .core7_m0_b_corrupt(o_cores_m0_b_corrupt[7]),
      .core0_m0_b_data(o_cores_m0_b_data[0]),
      .core1_m0_b_data(o_cores_m0_b_data[1]),
      .core2_m0_b_data(o_cores_m0_b_data[2]),
      .core3_m0_b_data(o_cores_m0_b_data[3]),
      .core4_m0_b_data(o_cores_m0_b_data[4]),
      .core5_m0_b_data(o_cores_m0_b_data[5]),
      .core6_m0_b_data(o_cores_m0_b_data[6]),
      .core7_m0_b_data(o_cores_m0_b_data[7]),
      .core0_m0_b_mask(o_cores_m0_b_mask[0]),
      .core1_m0_b_mask(o_cores_m0_b_mask[1]),
      .core2_m0_b_mask(o_cores_m0_b_mask[2]),
      .core3_m0_b_mask(o_cores_m0_b_mask[3]),
      .core4_m0_b_mask(o_cores_m0_b_mask[4]),
      .core5_m0_b_mask(o_cores_m0_b_mask[5]),
      .core6_m0_b_mask(o_cores_m0_b_mask[6]),
      .core7_m0_b_mask(o_cores_m0_b_mask[7]),
      .core0_m0_b_opcode(o_cores_m0_b_opcode[0]),
      .core1_m0_b_opcode(o_cores_m0_b_opcode[1]),
      .core2_m0_b_opcode(o_cores_m0_b_opcode[2]),
      .core3_m0_b_opcode(o_cores_m0_b_opcode[3]),
      .core4_m0_b_opcode(o_cores_m0_b_opcode[4]),
      .core5_m0_b_opcode(o_cores_m0_b_opcode[5]),
      .core6_m0_b_opcode(o_cores_m0_b_opcode[6]),
      .core7_m0_b_opcode(o_cores_m0_b_opcode[7]),
      .core0_m0_b_param(o_cores_m0_b_param[0]),
      .core1_m0_b_param(o_cores_m0_b_param[1]),
      .core2_m0_b_param(o_cores_m0_b_param[2]),
      .core3_m0_b_param(o_cores_m0_b_param[3]),
      .core4_m0_b_param(o_cores_m0_b_param[4]),
      .core5_m0_b_param(o_cores_m0_b_param[5]),
      .core6_m0_b_param(o_cores_m0_b_param[6]),
      .core7_m0_b_param(o_cores_m0_b_param[7]),
      .core0_m0_b_size(o_cores_m0_b_size[0]),
      .core1_m0_b_size(o_cores_m0_b_size[1]),
      .core2_m0_b_size(o_cores_m0_b_size[2]),
      .core3_m0_b_size(o_cores_m0_b_size[3]),
      .core4_m0_b_size(o_cores_m0_b_size[4]),
      .core5_m0_b_size(o_cores_m0_b_size[5]),
      .core6_m0_b_size(o_cores_m0_b_size[6]),
      .core7_m0_b_size(o_cores_m0_b_size[7]),
      .core0_m0_b_source(o_cores_m0_b_source[0]),
      .core1_m0_b_source(o_cores_m0_b_source[1]),
      .core2_m0_b_source(o_cores_m0_b_source[2]),
      .core3_m0_b_source(o_cores_m0_b_source[3]),
      .core4_m0_b_source(o_cores_m0_b_source[4]),
      .core5_m0_b_source(o_cores_m0_b_source[5]),
      .core6_m0_b_source(o_cores_m0_b_source[6]),
      .core7_m0_b_source(o_cores_m0_b_source[7]),
      .core0_m0_b_ready(i_cores_m0_b_ready[0]),
      .core1_m0_b_ready(i_cores_m0_b_ready[1]),
      .core2_m0_b_ready(i_cores_m0_b_ready[2]),
      .core3_m0_b_ready(i_cores_m0_b_ready[3]),
      .core4_m0_b_ready(i_cores_m0_b_ready[4]),
      .core5_m0_b_ready(i_cores_m0_b_ready[5]),
      .core6_m0_b_ready(i_cores_m0_b_ready[6]),
      .core7_m0_b_ready(i_cores_m0_b_ready[7]),
      .core0_m0_b_valid(o_cores_m0_b_valid[0]),
      .core1_m0_b_valid(o_cores_m0_b_valid[1]),
      .core2_m0_b_valid(o_cores_m0_b_valid[2]),
      .core3_m0_b_valid(o_cores_m0_b_valid[3]),
      .core4_m0_b_valid(o_cores_m0_b_valid[4]),
      .core5_m0_b_valid(o_cores_m0_b_valid[5]),
      .core6_m0_b_valid(o_cores_m0_b_valid[6]),
      .core7_m0_b_valid(o_cores_m0_b_valid[7]),
      .core0_m0_c_address(i_cores_m0_c_address[0]),
      .core1_m0_c_address(i_cores_m0_c_address[1]),
      .core2_m0_c_address(i_cores_m0_c_address[2]),
      .core3_m0_c_address(i_cores_m0_c_address[3]),
      .core4_m0_c_address(i_cores_m0_c_address[4]),
      .core5_m0_c_address(i_cores_m0_c_address[5]),
      .core6_m0_c_address(i_cores_m0_c_address[6]),
      .core7_m0_c_address(i_cores_m0_c_address[7]),
      .core0_m0_c_corrupt(i_cores_m0_c_corrupt[0]),
      .core1_m0_c_corrupt(i_cores_m0_c_corrupt[1]),
      .core2_m0_c_corrupt(i_cores_m0_c_corrupt[2]),
      .core3_m0_c_corrupt(i_cores_m0_c_corrupt[3]),
      .core4_m0_c_corrupt(i_cores_m0_c_corrupt[4]),
      .core5_m0_c_corrupt(i_cores_m0_c_corrupt[5]),
      .core6_m0_c_corrupt(i_cores_m0_c_corrupt[6]),
      .core7_m0_c_corrupt(i_cores_m0_c_corrupt[7]),
      .core0_m0_c_data(i_cores_m0_c_data[0]),
      .core1_m0_c_data(i_cores_m0_c_data[1]),
      .core2_m0_c_data(i_cores_m0_c_data[2]),
      .core3_m0_c_data(i_cores_m0_c_data[3]),
      .core4_m0_c_data(i_cores_m0_c_data[4]),
      .core5_m0_c_data(i_cores_m0_c_data[5]),
      .core6_m0_c_data(i_cores_m0_c_data[6]),
      .core7_m0_c_data(i_cores_m0_c_data[7]),
      .core0_m0_c_opcode(i_cores_m0_c_opcode[0]),
      .core1_m0_c_opcode(i_cores_m0_c_opcode[1]),
      .core2_m0_c_opcode(i_cores_m0_c_opcode[2]),
      .core3_m0_c_opcode(i_cores_m0_c_opcode[3]),
      .core4_m0_c_opcode(i_cores_m0_c_opcode[4]),
      .core5_m0_c_opcode(i_cores_m0_c_opcode[5]),
      .core6_m0_c_opcode(i_cores_m0_c_opcode[6]),
      .core7_m0_c_opcode(i_cores_m0_c_opcode[7]),
      .core0_m0_c_param(i_cores_m0_c_param[0]),
      .core1_m0_c_param(i_cores_m0_c_param[1]),
      .core2_m0_c_param(i_cores_m0_c_param[2]),
      .core3_m0_c_param(i_cores_m0_c_param[3]),
      .core4_m0_c_param(i_cores_m0_c_param[4]),
      .core5_m0_c_param(i_cores_m0_c_param[5]),
      .core6_m0_c_param(i_cores_m0_c_param[6]),
      .core7_m0_c_param(i_cores_m0_c_param[7]),
      .core0_m0_c_size(i_cores_m0_c_size[0]),
      .core1_m0_c_size(i_cores_m0_c_size[1]),
      .core2_m0_c_size(i_cores_m0_c_size[2]),
      .core3_m0_c_size(i_cores_m0_c_size[3]),
      .core4_m0_c_size(i_cores_m0_c_size[4]),
      .core5_m0_c_size(i_cores_m0_c_size[5]),
      .core6_m0_c_size(i_cores_m0_c_size[6]),
      .core7_m0_c_size(i_cores_m0_c_size[7]),
      .core0_m0_c_source(i_cores_m0_c_source[0]),
      .core1_m0_c_source(i_cores_m0_c_source[1]),
      .core2_m0_c_source(i_cores_m0_c_source[2]),
      .core3_m0_c_source(i_cores_m0_c_source[3]),
      .core4_m0_c_source(i_cores_m0_c_source[4]),
      .core5_m0_c_source(i_cores_m0_c_source[5]),
      .core6_m0_c_source(i_cores_m0_c_source[6]),
      .core7_m0_c_source(i_cores_m0_c_source[7]),
      .core0_m0_c_user(i_cores_m0_c_user[0]),
      .core1_m0_c_user(i_cores_m0_c_user[1]),
      .core2_m0_c_user(i_cores_m0_c_user[2]),
      .core3_m0_c_user(i_cores_m0_c_user[3]),
      .core4_m0_c_user(i_cores_m0_c_user[4]),
      .core5_m0_c_user(i_cores_m0_c_user[5]),
      .core6_m0_c_user(i_cores_m0_c_user[6]),
      .core7_m0_c_user(i_cores_m0_c_user[7]),
      .core0_m0_c_ready(o_cores_m0_c_ready[0]),
      .core1_m0_c_ready(o_cores_m0_c_ready[1]),
      .core2_m0_c_ready(o_cores_m0_c_ready[2]),
      .core3_m0_c_ready(o_cores_m0_c_ready[3]),
      .core4_m0_c_ready(o_cores_m0_c_ready[4]),
      .core5_m0_c_ready(o_cores_m0_c_ready[5]),
      .core6_m0_c_ready(o_cores_m0_c_ready[6]),
      .core7_m0_c_ready(o_cores_m0_c_ready[7]),
      .core0_m0_c_valid(i_cores_m0_c_valid[0]),
      .core1_m0_c_valid(i_cores_m0_c_valid[1]),
      .core2_m0_c_valid(i_cores_m0_c_valid[2]),
      .core3_m0_c_valid(i_cores_m0_c_valid[3]),
      .core4_m0_c_valid(i_cores_m0_c_valid[4]),
      .core5_m0_c_valid(i_cores_m0_c_valid[5]),
      .core6_m0_c_valid(i_cores_m0_c_valid[6]),
      .core7_m0_c_valid(i_cores_m0_c_valid[7]),
      .core0_m0_d_corrupt(o_cores_m0_d_corrupt[0]),
      .core1_m0_d_corrupt(o_cores_m0_d_corrupt[1]),
      .core2_m0_d_corrupt(o_cores_m0_d_corrupt[2]),
      .core3_m0_d_corrupt(o_cores_m0_d_corrupt[3]),
      .core4_m0_d_corrupt(o_cores_m0_d_corrupt[4]),
      .core5_m0_d_corrupt(o_cores_m0_d_corrupt[5]),
      .core6_m0_d_corrupt(o_cores_m0_d_corrupt[6]),
      .core7_m0_d_corrupt(o_cores_m0_d_corrupt[7]),
      .core0_m0_d_data(o_cores_m0_d_data[0]),
      .core1_m0_d_data(o_cores_m0_d_data[1]),
      .core2_m0_d_data(o_cores_m0_d_data[2]),
      .core3_m0_d_data(o_cores_m0_d_data[3]),
      .core4_m0_d_data(o_cores_m0_d_data[4]),
      .core5_m0_d_data(o_cores_m0_d_data[5]),
      .core6_m0_d_data(o_cores_m0_d_data[6]),
      .core7_m0_d_data(o_cores_m0_d_data[7]),
      .core0_m0_d_denied(o_cores_m0_d_denied[0]),
      .core1_m0_d_denied(o_cores_m0_d_denied[1]),
      .core2_m0_d_denied(o_cores_m0_d_denied[2]),
      .core3_m0_d_denied(o_cores_m0_d_denied[3]),
      .core4_m0_d_denied(o_cores_m0_d_denied[4]),
      .core5_m0_d_denied(o_cores_m0_d_denied[5]),
      .core6_m0_d_denied(o_cores_m0_d_denied[6]),
      .core7_m0_d_denied(o_cores_m0_d_denied[7]),
      .core0_m0_d_opcode(o_cores_m0_d_opcode[0]),
      .core1_m0_d_opcode(o_cores_m0_d_opcode[1]),
      .core2_m0_d_opcode(o_cores_m0_d_opcode[2]),
      .core3_m0_d_opcode(o_cores_m0_d_opcode[3]),
      .core4_m0_d_opcode(o_cores_m0_d_opcode[4]),
      .core5_m0_d_opcode(o_cores_m0_d_opcode[5]),
      .core6_m0_d_opcode(o_cores_m0_d_opcode[6]),
      .core7_m0_d_opcode(o_cores_m0_d_opcode[7]),
      .core0_m0_d_param(o_cores_m0_d_param[0]),
      .core1_m0_d_param(o_cores_m0_d_param[1]),
      .core2_m0_d_param(o_cores_m0_d_param[2]),
      .core3_m0_d_param(o_cores_m0_d_param[3]),
      .core4_m0_d_param(o_cores_m0_d_param[4]),
      .core5_m0_d_param(o_cores_m0_d_param[5]),
      .core6_m0_d_param(o_cores_m0_d_param[6]),
      .core7_m0_d_param(o_cores_m0_d_param[7]),
      .core0_m0_d_size(o_cores_m0_d_size[0]),
      .core1_m0_d_size(o_cores_m0_d_size[1]),
      .core2_m0_d_size(o_cores_m0_d_size[2]),
      .core3_m0_d_size(o_cores_m0_d_size[3]),
      .core4_m0_d_size(o_cores_m0_d_size[4]),
      .core5_m0_d_size(o_cores_m0_d_size[5]),
      .core6_m0_d_size(o_cores_m0_d_size[6]),
      .core7_m0_d_size(o_cores_m0_d_size[7]),
      .core0_m0_d_sink(o_cores_m0_d_sink[0]),
      .core1_m0_d_sink(o_cores_m0_d_sink[1]),
      .core2_m0_d_sink(o_cores_m0_d_sink[2]),
      .core3_m0_d_sink(o_cores_m0_d_sink[3]),
      .core4_m0_d_sink(o_cores_m0_d_sink[4]),
      .core5_m0_d_sink(o_cores_m0_d_sink[5]),
      .core6_m0_d_sink(o_cores_m0_d_sink[6]),
      .core7_m0_d_sink(o_cores_m0_d_sink[7]),
      .core0_m0_d_source(o_cores_m0_d_source[0]),
      .core1_m0_d_source(o_cores_m0_d_source[1]),
      .core2_m0_d_source(o_cores_m0_d_source[2]),
      .core3_m0_d_source(o_cores_m0_d_source[3]),
      .core4_m0_d_source(o_cores_m0_d_source[4]),
      .core5_m0_d_source(o_cores_m0_d_source[5]),
      .core6_m0_d_source(o_cores_m0_d_source[6]),
      .core7_m0_d_source(o_cores_m0_d_source[7]),
      .core0_m0_d_user(o_cores_m0_d_user[0]),
      .core1_m0_d_user(o_cores_m0_d_user[1]),
      .core2_m0_d_user(o_cores_m0_d_user[2]),
      .core3_m0_d_user(o_cores_m0_d_user[3]),
      .core4_m0_d_user(o_cores_m0_d_user[4]),
      .core5_m0_d_user(o_cores_m0_d_user[5]),
      .core6_m0_d_user(o_cores_m0_d_user[6]),
      .core7_m0_d_user(o_cores_m0_d_user[7]),
      .core0_m0_d_ready(i_cores_m0_d_ready[0]),
      .core1_m0_d_ready(i_cores_m0_d_ready[1]),
      .core2_m0_d_ready(i_cores_m0_d_ready[2]),
      .core3_m0_d_ready(i_cores_m0_d_ready[3]),
      .core4_m0_d_ready(i_cores_m0_d_ready[4]),
      .core5_m0_d_ready(i_cores_m0_d_ready[5]),
      .core6_m0_d_ready(i_cores_m0_d_ready[6]),
      .core7_m0_d_ready(i_cores_m0_d_ready[7]),
      .core0_m0_d_valid(o_cores_m0_d_valid[0]),
      .core1_m0_d_valid(o_cores_m0_d_valid[1]),
      .core2_m0_d_valid(o_cores_m0_d_valid[2]),
      .core3_m0_d_valid(o_cores_m0_d_valid[3]),
      .core4_m0_d_valid(o_cores_m0_d_valid[4]),
      .core5_m0_d_valid(o_cores_m0_d_valid[5]),
      .core6_m0_d_valid(o_cores_m0_d_valid[6]),
      .core7_m0_d_valid(o_cores_m0_d_valid[7]),
      .core0_m0_e_sink(i_cores_m0_e_sink[0]),
      .core1_m0_e_sink(i_cores_m0_e_sink[1]),
      .core2_m0_e_sink(i_cores_m0_e_sink[2]),
      .core3_m0_e_sink(i_cores_m0_e_sink[3]),
      .core4_m0_e_sink(i_cores_m0_e_sink[4]),
      .core5_m0_e_sink(i_cores_m0_e_sink[5]),
      .core6_m0_e_sink(i_cores_m0_e_sink[6]),
      .core7_m0_e_sink(i_cores_m0_e_sink[7]),
      .core0_m0_e_ready(o_cores_m0_e_ready[0]),
      .core1_m0_e_ready(o_cores_m0_e_ready[1]),
      .core2_m0_e_ready(o_cores_m0_e_ready[2]),
      .core3_m0_e_ready(o_cores_m0_e_ready[3]),
      .core4_m0_e_ready(o_cores_m0_e_ready[4]),
      .core5_m0_e_ready(o_cores_m0_e_ready[5]),
      .core6_m0_e_ready(o_cores_m0_e_ready[6]),
      .core7_m0_e_ready(o_cores_m0_e_ready[7]),
      .core0_m0_e_valid(i_cores_m0_e_valid[0]),
      .core1_m0_e_valid(i_cores_m0_e_valid[1]),
      .core2_m0_e_valid(i_cores_m0_e_valid[2]),
      .core3_m0_e_valid(i_cores_m0_e_valid[3]),
      .core4_m0_e_valid(i_cores_m0_e_valid[4]),
      .core5_m0_e_valid(i_cores_m0_e_valid[5]),
      .core6_m0_e_valid(i_cores_m0_e_valid[6]),
      .core7_m0_e_valid(i_cores_m0_e_valid[7]),
      .core0_m1_araddr(i_cores_m1_axi_s_araddr[0]),
      .core1_m1_araddr(i_cores_m1_axi_s_araddr[1]),
      .core2_m1_araddr(i_cores_m1_axi_s_araddr[2]),
      .core3_m1_araddr(i_cores_m1_axi_s_araddr[3]),
      .core4_m1_araddr(i_cores_m1_axi_s_araddr[4]),
      .core5_m1_araddr(i_cores_m1_axi_s_araddr[5]),
      .core6_m1_araddr(i_cores_m1_axi_s_araddr[6]),
      .core7_m1_araddr(i_cores_m1_axi_s_araddr[7]),
      .core0_m1_arburst(i_cores_m1_axi_s_arburst[0]),
      .core1_m1_arburst(i_cores_m1_axi_s_arburst[1]),
      .core2_m1_arburst(i_cores_m1_axi_s_arburst[2]),
      .core3_m1_arburst(i_cores_m1_axi_s_arburst[3]),
      .core4_m1_arburst(i_cores_m1_axi_s_arburst[4]),
      .core5_m1_arburst(i_cores_m1_axi_s_arburst[5]),
      .core6_m1_arburst(i_cores_m1_axi_s_arburst[6]),
      .core7_m1_arburst(i_cores_m1_axi_s_arburst[7]),
      .core0_m1_arcache(i_cores_m1_axi_s_arcache[0]),
      .core1_m1_arcache(i_cores_m1_axi_s_arcache[1]),
      .core2_m1_arcache(i_cores_m1_axi_s_arcache[2]),
      .core3_m1_arcache(i_cores_m1_axi_s_arcache[3]),
      .core4_m1_arcache(i_cores_m1_axi_s_arcache[4]),
      .core5_m1_arcache(i_cores_m1_axi_s_arcache[5]),
      .core6_m1_arcache(i_cores_m1_axi_s_arcache[6]),
      .core7_m1_arcache(i_cores_m1_axi_s_arcache[7]),
      .core0_m1_arid(i_cores_m1_axi_s_arid[0]),
      .core1_m1_arid(i_cores_m1_axi_s_arid[1]),
      .core2_m1_arid(i_cores_m1_axi_s_arid[2]),
      .core3_m1_arid(i_cores_m1_axi_s_arid[3]),
      .core4_m1_arid(i_cores_m1_axi_s_arid[4]),
      .core5_m1_arid(i_cores_m1_axi_s_arid[5]),
      .core6_m1_arid(i_cores_m1_axi_s_arid[6]),
      .core7_m1_arid(i_cores_m1_axi_s_arid[7]),
      .core0_m1_arlen(i_cores_m1_axi_s_arlen[0]),
      .core1_m1_arlen(i_cores_m1_axi_s_arlen[1]),
      .core2_m1_arlen(i_cores_m1_axi_s_arlen[2]),
      .core3_m1_arlen(i_cores_m1_axi_s_arlen[3]),
      .core4_m1_arlen(i_cores_m1_axi_s_arlen[4]),
      .core5_m1_arlen(i_cores_m1_axi_s_arlen[5]),
      .core6_m1_arlen(i_cores_m1_axi_s_arlen[6]),
      .core7_m1_arlen(i_cores_m1_axi_s_arlen[7]),
      .core0_m1_arlock(i_cores_m1_axi_s_arlock[0]),
      .core1_m1_arlock(i_cores_m1_axi_s_arlock[1]),
      .core2_m1_arlock(i_cores_m1_axi_s_arlock[2]),
      .core3_m1_arlock(i_cores_m1_axi_s_arlock[3]),
      .core4_m1_arlock(i_cores_m1_axi_s_arlock[4]),
      .core5_m1_arlock(i_cores_m1_axi_s_arlock[5]),
      .core6_m1_arlock(i_cores_m1_axi_s_arlock[6]),
      .core7_m1_arlock(i_cores_m1_axi_s_arlock[7]),
      .core0_m1_arprot(i_cores_m1_axi_s_arprot[0]),
      .core1_m1_arprot(i_cores_m1_axi_s_arprot[1]),
      .core2_m1_arprot(i_cores_m1_axi_s_arprot[2]),
      .core3_m1_arprot(i_cores_m1_axi_s_arprot[3]),
      .core4_m1_arprot(i_cores_m1_axi_s_arprot[4]),
      .core5_m1_arprot(i_cores_m1_axi_s_arprot[5]),
      .core6_m1_arprot(i_cores_m1_axi_s_arprot[6]),
      .core7_m1_arprot(i_cores_m1_axi_s_arprot[7]),
      .core0_m1_arsize(i_cores_m1_axi_s_arsize[0]),
      .core1_m1_arsize(i_cores_m1_axi_s_arsize[1]),
      .core2_m1_arsize(i_cores_m1_axi_s_arsize[2]),
      .core3_m1_arsize(i_cores_m1_axi_s_arsize[3]),
      .core4_m1_arsize(i_cores_m1_axi_s_arsize[4]),
      .core5_m1_arsize(i_cores_m1_axi_s_arsize[5]),
      .core6_m1_arsize(i_cores_m1_axi_s_arsize[6]),
      .core7_m1_arsize(i_cores_m1_axi_s_arsize[7]),
      .core0_m1_arready(o_cores_m1_axi_s_arready[0]),
      .core1_m1_arready(o_cores_m1_axi_s_arready[1]),
      .core2_m1_arready(o_cores_m1_axi_s_arready[2]),
      .core3_m1_arready(o_cores_m1_axi_s_arready[3]),
      .core4_m1_arready(o_cores_m1_axi_s_arready[4]),
      .core5_m1_arready(o_cores_m1_axi_s_arready[5]),
      .core6_m1_arready(o_cores_m1_axi_s_arready[6]),
      .core7_m1_arready(o_cores_m1_axi_s_arready[7]),
      .core0_m1_arvalid(i_cores_m1_axi_s_arvalid[0]),
      .core1_m1_arvalid(i_cores_m1_axi_s_arvalid[1]),
      .core2_m1_arvalid(i_cores_m1_axi_s_arvalid[2]),
      .core3_m1_arvalid(i_cores_m1_axi_s_arvalid[3]),
      .core4_m1_arvalid(i_cores_m1_axi_s_arvalid[4]),
      .core5_m1_arvalid(i_cores_m1_axi_s_arvalid[5]),
      .core6_m1_arvalid(i_cores_m1_axi_s_arvalid[6]),
      .core7_m1_arvalid(i_cores_m1_axi_s_arvalid[7]),
      .core0_m1_awaddr(i_cores_m1_axi_s_awaddr[0]),
      .core1_m1_awaddr(i_cores_m1_axi_s_awaddr[1]),
      .core2_m1_awaddr(i_cores_m1_axi_s_awaddr[2]),
      .core3_m1_awaddr(i_cores_m1_axi_s_awaddr[3]),
      .core4_m1_awaddr(i_cores_m1_axi_s_awaddr[4]),
      .core5_m1_awaddr(i_cores_m1_axi_s_awaddr[5]),
      .core6_m1_awaddr(i_cores_m1_axi_s_awaddr[6]),
      .core7_m1_awaddr(i_cores_m1_axi_s_awaddr[7]),
      .core0_m1_awburst(i_cores_m1_axi_s_awburst[0]),
      .core1_m1_awburst(i_cores_m1_axi_s_awburst[1]),
      .core2_m1_awburst(i_cores_m1_axi_s_awburst[2]),
      .core3_m1_awburst(i_cores_m1_axi_s_awburst[3]),
      .core4_m1_awburst(i_cores_m1_axi_s_awburst[4]),
      .core5_m1_awburst(i_cores_m1_axi_s_awburst[5]),
      .core6_m1_awburst(i_cores_m1_axi_s_awburst[6]),
      .core7_m1_awburst(i_cores_m1_axi_s_awburst[7]),
      .core0_m1_awcache(i_cores_m1_axi_s_awcache[0]),
      .core1_m1_awcache(i_cores_m1_axi_s_awcache[1]),
      .core2_m1_awcache(i_cores_m1_axi_s_awcache[2]),
      .core3_m1_awcache(i_cores_m1_axi_s_awcache[3]),
      .core4_m1_awcache(i_cores_m1_axi_s_awcache[4]),
      .core5_m1_awcache(i_cores_m1_axi_s_awcache[5]),
      .core6_m1_awcache(i_cores_m1_axi_s_awcache[6]),
      .core7_m1_awcache(i_cores_m1_axi_s_awcache[7]),
      .core0_m1_awid(i_cores_m1_axi_s_awid[0]),
      .core1_m1_awid(i_cores_m1_axi_s_awid[1]),
      .core2_m1_awid(i_cores_m1_axi_s_awid[2]),
      .core3_m1_awid(i_cores_m1_axi_s_awid[3]),
      .core4_m1_awid(i_cores_m1_axi_s_awid[4]),
      .core5_m1_awid(i_cores_m1_axi_s_awid[5]),
      .core6_m1_awid(i_cores_m1_axi_s_awid[6]),
      .core7_m1_awid(i_cores_m1_axi_s_awid[7]),
      .core0_m1_awlen(i_cores_m1_axi_s_awlen[0]),
      .core1_m1_awlen(i_cores_m1_axi_s_awlen[1]),
      .core2_m1_awlen(i_cores_m1_axi_s_awlen[2]),
      .core3_m1_awlen(i_cores_m1_axi_s_awlen[3]),
      .core4_m1_awlen(i_cores_m1_axi_s_awlen[4]),
      .core5_m1_awlen(i_cores_m1_axi_s_awlen[5]),
      .core6_m1_awlen(i_cores_m1_axi_s_awlen[6]),
      .core7_m1_awlen(i_cores_m1_axi_s_awlen[7]),
      .core0_m1_awlock(i_cores_m1_axi_s_awlock[0]),
      .core1_m1_awlock(i_cores_m1_axi_s_awlock[1]),
      .core2_m1_awlock(i_cores_m1_axi_s_awlock[2]),
      .core3_m1_awlock(i_cores_m1_axi_s_awlock[3]),
      .core4_m1_awlock(i_cores_m1_axi_s_awlock[4]),
      .core5_m1_awlock(i_cores_m1_axi_s_awlock[5]),
      .core6_m1_awlock(i_cores_m1_axi_s_awlock[6]),
      .core7_m1_awlock(i_cores_m1_axi_s_awlock[7]),
      .core0_m1_awprot(i_cores_m1_axi_s_awprot[0]),
      .core1_m1_awprot(i_cores_m1_axi_s_awprot[1]),
      .core2_m1_awprot(i_cores_m1_axi_s_awprot[2]),
      .core3_m1_awprot(i_cores_m1_axi_s_awprot[3]),
      .core4_m1_awprot(i_cores_m1_axi_s_awprot[4]),
      .core5_m1_awprot(i_cores_m1_axi_s_awprot[5]),
      .core6_m1_awprot(i_cores_m1_axi_s_awprot[6]),
      .core7_m1_awprot(i_cores_m1_axi_s_awprot[7]),
      .core0_m1_awsize(i_cores_m1_axi_s_awsize[0]),
      .core1_m1_awsize(i_cores_m1_axi_s_awsize[1]),
      .core2_m1_awsize(i_cores_m1_axi_s_awsize[2]),
      .core3_m1_awsize(i_cores_m1_axi_s_awsize[3]),
      .core4_m1_awsize(i_cores_m1_axi_s_awsize[4]),
      .core5_m1_awsize(i_cores_m1_axi_s_awsize[5]),
      .core6_m1_awsize(i_cores_m1_axi_s_awsize[6]),
      .core7_m1_awsize(i_cores_m1_axi_s_awsize[7]),
      .core0_m1_awready(o_cores_m1_axi_s_awready[0]),
      .core1_m1_awready(o_cores_m1_axi_s_awready[1]),
      .core2_m1_awready(o_cores_m1_axi_s_awready[2]),
      .core3_m1_awready(o_cores_m1_axi_s_awready[3]),
      .core4_m1_awready(o_cores_m1_axi_s_awready[4]),
      .core5_m1_awready(o_cores_m1_axi_s_awready[5]),
      .core6_m1_awready(o_cores_m1_axi_s_awready[6]),
      .core7_m1_awready(o_cores_m1_axi_s_awready[7]),
      .core0_m1_awvalid(i_cores_m1_axi_s_awvalid[0]),
      .core1_m1_awvalid(i_cores_m1_axi_s_awvalid[1]),
      .core2_m1_awvalid(i_cores_m1_axi_s_awvalid[2]),
      .core3_m1_awvalid(i_cores_m1_axi_s_awvalid[3]),
      .core4_m1_awvalid(i_cores_m1_axi_s_awvalid[4]),
      .core5_m1_awvalid(i_cores_m1_axi_s_awvalid[5]),
      .core6_m1_awvalid(i_cores_m1_axi_s_awvalid[6]),
      .core7_m1_awvalid(i_cores_m1_axi_s_awvalid[7]),
      .core0_m1_bid(o_cores_m1_axi_s_bid[0]),
      .core1_m1_bid(o_cores_m1_axi_s_bid[1]),
      .core2_m1_bid(o_cores_m1_axi_s_bid[2]),
      .core3_m1_bid(o_cores_m1_axi_s_bid[3]),
      .core4_m1_bid(o_cores_m1_axi_s_bid[4]),
      .core5_m1_bid(o_cores_m1_axi_s_bid[5]),
      .core6_m1_bid(o_cores_m1_axi_s_bid[6]),
      .core7_m1_bid(o_cores_m1_axi_s_bid[7]),
      .core0_m1_bresp(o_cores_m1_axi_s_bresp[0]),
      .core1_m1_bresp(o_cores_m1_axi_s_bresp[1]),
      .core2_m1_bresp(o_cores_m1_axi_s_bresp[2]),
      .core3_m1_bresp(o_cores_m1_axi_s_bresp[3]),
      .core4_m1_bresp(o_cores_m1_axi_s_bresp[4]),
      .core5_m1_bresp(o_cores_m1_axi_s_bresp[5]),
      .core6_m1_bresp(o_cores_m1_axi_s_bresp[6]),
      .core7_m1_bresp(o_cores_m1_axi_s_bresp[7]),
      .core0_m1_bready(i_cores_m1_axi_s_bready[0]),
      .core1_m1_bready(i_cores_m1_axi_s_bready[1]),
      .core2_m1_bready(i_cores_m1_axi_s_bready[2]),
      .core3_m1_bready(i_cores_m1_axi_s_bready[3]),
      .core4_m1_bready(i_cores_m1_axi_s_bready[4]),
      .core5_m1_bready(i_cores_m1_axi_s_bready[5]),
      .core6_m1_bready(i_cores_m1_axi_s_bready[6]),
      .core7_m1_bready(i_cores_m1_axi_s_bready[7]),
      .core0_m1_bvalid(o_cores_m1_axi_s_bvalid[0]),
      .core1_m1_bvalid(o_cores_m1_axi_s_bvalid[1]),
      .core2_m1_bvalid(o_cores_m1_axi_s_bvalid[2]),
      .core3_m1_bvalid(o_cores_m1_axi_s_bvalid[3]),
      .core4_m1_bvalid(o_cores_m1_axi_s_bvalid[4]),
      .core5_m1_bvalid(o_cores_m1_axi_s_bvalid[5]),
      .core6_m1_bvalid(o_cores_m1_axi_s_bvalid[6]),
      .core7_m1_bvalid(o_cores_m1_axi_s_bvalid[7]),
      .core0_m1_rdata(o_cores_m1_axi_s_rdata[0]),
      .core1_m1_rdata(o_cores_m1_axi_s_rdata[1]),
      .core2_m1_rdata(o_cores_m1_axi_s_rdata[2]),
      .core3_m1_rdata(o_cores_m1_axi_s_rdata[3]),
      .core4_m1_rdata(o_cores_m1_axi_s_rdata[4]),
      .core5_m1_rdata(o_cores_m1_axi_s_rdata[5]),
      .core6_m1_rdata(o_cores_m1_axi_s_rdata[6]),
      .core7_m1_rdata(o_cores_m1_axi_s_rdata[7]),
      .core0_m1_rid(o_cores_m1_axi_s_rid[0]),
      .core1_m1_rid(o_cores_m1_axi_s_rid[1]),
      .core2_m1_rid(o_cores_m1_axi_s_rid[2]),
      .core3_m1_rid(o_cores_m1_axi_s_rid[3]),
      .core4_m1_rid(o_cores_m1_axi_s_rid[4]),
      .core5_m1_rid(o_cores_m1_axi_s_rid[5]),
      .core6_m1_rid(o_cores_m1_axi_s_rid[6]),
      .core7_m1_rid(o_cores_m1_axi_s_rid[7]),
      .core0_m1_rlast(o_cores_m1_axi_s_rlast[0]),
      .core1_m1_rlast(o_cores_m1_axi_s_rlast[1]),
      .core2_m1_rlast(o_cores_m1_axi_s_rlast[2]),
      .core3_m1_rlast(o_cores_m1_axi_s_rlast[3]),
      .core4_m1_rlast(o_cores_m1_axi_s_rlast[4]),
      .core5_m1_rlast(o_cores_m1_axi_s_rlast[5]),
      .core6_m1_rlast(o_cores_m1_axi_s_rlast[6]),
      .core7_m1_rlast(o_cores_m1_axi_s_rlast[7]),
      .core0_m1_rresp(o_cores_m1_axi_s_rresp[0]),
      .core1_m1_rresp(o_cores_m1_axi_s_rresp[1]),
      .core2_m1_rresp(o_cores_m1_axi_s_rresp[2]),
      .core3_m1_rresp(o_cores_m1_axi_s_rresp[3]),
      .core4_m1_rresp(o_cores_m1_axi_s_rresp[4]),
      .core5_m1_rresp(o_cores_m1_axi_s_rresp[5]),
      .core6_m1_rresp(o_cores_m1_axi_s_rresp[6]),
      .core7_m1_rresp(o_cores_m1_axi_s_rresp[7]),
      .core0_m1_rready(i_cores_m1_axi_s_rready[0]),
      .core1_m1_rready(i_cores_m1_axi_s_rready[1]),
      .core2_m1_rready(i_cores_m1_axi_s_rready[2]),
      .core3_m1_rready(i_cores_m1_axi_s_rready[3]),
      .core4_m1_rready(i_cores_m1_axi_s_rready[4]),
      .core5_m1_rready(i_cores_m1_axi_s_rready[5]),
      .core6_m1_rready(i_cores_m1_axi_s_rready[6]),
      .core7_m1_rready(i_cores_m1_axi_s_rready[7]),
      .core0_m1_rvalid(o_cores_m1_axi_s_rvalid[0]),
      .core1_m1_rvalid(o_cores_m1_axi_s_rvalid[1]),
      .core2_m1_rvalid(o_cores_m1_axi_s_rvalid[2]),
      .core3_m1_rvalid(o_cores_m1_axi_s_rvalid[3]),
      .core4_m1_rvalid(o_cores_m1_axi_s_rvalid[4]),
      .core5_m1_rvalid(o_cores_m1_axi_s_rvalid[5]),
      .core6_m1_rvalid(o_cores_m1_axi_s_rvalid[6]),
      .core7_m1_rvalid(o_cores_m1_axi_s_rvalid[7]),
      .core0_m1_wdata(i_cores_m1_axi_s_wdata[0]),
      .core1_m1_wdata(i_cores_m1_axi_s_wdata[1]),
      .core2_m1_wdata(i_cores_m1_axi_s_wdata[2]),
      .core3_m1_wdata(i_cores_m1_axi_s_wdata[3]),
      .core4_m1_wdata(i_cores_m1_axi_s_wdata[4]),
      .core5_m1_wdata(i_cores_m1_axi_s_wdata[5]),
      .core6_m1_wdata(i_cores_m1_axi_s_wdata[6]),
      .core7_m1_wdata(i_cores_m1_axi_s_wdata[7]),
      .core0_m1_wlast(i_cores_m1_axi_s_wlast[0]),
      .core1_m1_wlast(i_cores_m1_axi_s_wlast[1]),
      .core2_m1_wlast(i_cores_m1_axi_s_wlast[2]),
      .core3_m1_wlast(i_cores_m1_axi_s_wlast[3]),
      .core4_m1_wlast(i_cores_m1_axi_s_wlast[4]),
      .core5_m1_wlast(i_cores_m1_axi_s_wlast[5]),
      .core6_m1_wlast(i_cores_m1_axi_s_wlast[6]),
      .core7_m1_wlast(i_cores_m1_axi_s_wlast[7]),
      .core0_m1_wstrb(i_cores_m1_axi_s_wstrb[0]),
      .core1_m1_wstrb(i_cores_m1_axi_s_wstrb[1]),
      .core2_m1_wstrb(i_cores_m1_axi_s_wstrb[2]),
      .core3_m1_wstrb(i_cores_m1_axi_s_wstrb[3]),
      .core4_m1_wstrb(i_cores_m1_axi_s_wstrb[4]),
      .core5_m1_wstrb(i_cores_m1_axi_s_wstrb[5]),
      .core6_m1_wstrb(i_cores_m1_axi_s_wstrb[6]),
      .core7_m1_wstrb(i_cores_m1_axi_s_wstrb[7]),
      .core0_m1_wready(o_cores_m1_axi_s_wready[0]),
      .core1_m1_wready(o_cores_m1_axi_s_wready[1]),
      .core2_m1_wready(o_cores_m1_axi_s_wready[2]),
      .core3_m1_wready(o_cores_m1_axi_s_wready[3]),
      .core4_m1_wready(o_cores_m1_axi_s_wready[4]),
      .core5_m1_wready(o_cores_m1_axi_s_wready[5]),
      .core6_m1_wready(o_cores_m1_axi_s_wready[6]),
      .core7_m1_wready(o_cores_m1_axi_s_wready[7]),
      .core0_m1_wvalid(i_cores_m1_axi_s_wvalid[0]),
      .core1_m1_wvalid(i_cores_m1_axi_s_wvalid[1]),
      .core2_m1_wvalid(i_cores_m1_axi_s_wvalid[2]),
      .core3_m1_wvalid(i_cores_m1_axi_s_wvalid[3]),
      .core4_m1_wvalid(i_cores_m1_axi_s_wvalid[4]),
      .core5_m1_wvalid(i_cores_m1_axi_s_wvalid[5]),
      .core6_m1_wvalid(i_cores_m1_axi_s_wvalid[6]),
      .core7_m1_wvalid(i_cores_m1_axi_s_wvalid[7]),
      .core0_m2_a_address(i_cores_m2_a_address[0]),
      .core1_m2_a_address(i_cores_m2_a_address[1]),
      .core2_m2_a_address(i_cores_m2_a_address[2]),
      .core3_m2_a_address(i_cores_m2_a_address[3]),
      .core4_m2_a_address(i_cores_m2_a_address[4]),
      .core5_m2_a_address(i_cores_m2_a_address[5]),
      .core6_m2_a_address(i_cores_m2_a_address[6]),
      .core7_m2_a_address(i_cores_m2_a_address[7]),
      .core0_m2_a_corrupt(i_cores_m2_a_corrupt[0]),
      .core1_m2_a_corrupt(i_cores_m2_a_corrupt[1]),
      .core2_m2_a_corrupt(i_cores_m2_a_corrupt[2]),
      .core3_m2_a_corrupt(i_cores_m2_a_corrupt[3]),
      .core4_m2_a_corrupt(i_cores_m2_a_corrupt[4]),
      .core5_m2_a_corrupt(i_cores_m2_a_corrupt[5]),
      .core6_m2_a_corrupt(i_cores_m2_a_corrupt[6]),
      .core7_m2_a_corrupt(i_cores_m2_a_corrupt[7]),
      .core0_m2_a_data(i_cores_m2_a_data[0]),
      .core1_m2_a_data(i_cores_m2_a_data[1]),
      .core2_m2_a_data(i_cores_m2_a_data[2]),
      .core3_m2_a_data(i_cores_m2_a_data[3]),
      .core4_m2_a_data(i_cores_m2_a_data[4]),
      .core5_m2_a_data(i_cores_m2_a_data[5]),
      .core6_m2_a_data(i_cores_m2_a_data[6]),
      .core7_m2_a_data(i_cores_m2_a_data[7]),
      .core0_m2_a_mask(i_cores_m2_a_mask[0]),
      .core1_m2_a_mask(i_cores_m2_a_mask[1]),
      .core2_m2_a_mask(i_cores_m2_a_mask[2]),
      .core3_m2_a_mask(i_cores_m2_a_mask[3]),
      .core4_m2_a_mask(i_cores_m2_a_mask[4]),
      .core5_m2_a_mask(i_cores_m2_a_mask[5]),
      .core6_m2_a_mask(i_cores_m2_a_mask[6]),
      .core7_m2_a_mask(i_cores_m2_a_mask[7]),
      .core0_m2_a_opcode(i_cores_m2_a_opcode[0]),
      .core1_m2_a_opcode(i_cores_m2_a_opcode[1]),
      .core2_m2_a_opcode(i_cores_m2_a_opcode[2]),
      .core3_m2_a_opcode(i_cores_m2_a_opcode[3]),
      .core4_m2_a_opcode(i_cores_m2_a_opcode[4]),
      .core5_m2_a_opcode(i_cores_m2_a_opcode[5]),
      .core6_m2_a_opcode(i_cores_m2_a_opcode[6]),
      .core7_m2_a_opcode(i_cores_m2_a_opcode[7]),
      .core0_m2_a_param(i_cores_m2_a_param[0]),
      .core1_m2_a_param(i_cores_m2_a_param[1]),
      .core2_m2_a_param(i_cores_m2_a_param[2]),
      .core3_m2_a_param(i_cores_m2_a_param[3]),
      .core4_m2_a_param(i_cores_m2_a_param[4]),
      .core5_m2_a_param(i_cores_m2_a_param[5]),
      .core6_m2_a_param(i_cores_m2_a_param[6]),
      .core7_m2_a_param(i_cores_m2_a_param[7]),
      .core0_m2_a_size(i_cores_m2_a_size[0]),
      .core1_m2_a_size(i_cores_m2_a_size[1]),
      .core2_m2_a_size(i_cores_m2_a_size[2]),
      .core3_m2_a_size(i_cores_m2_a_size[3]),
      .core4_m2_a_size(i_cores_m2_a_size[4]),
      .core5_m2_a_size(i_cores_m2_a_size[5]),
      .core6_m2_a_size(i_cores_m2_a_size[6]),
      .core7_m2_a_size(i_cores_m2_a_size[7]),
      .core0_m2_a_source(i_cores_m2_a_source[0]),
      .core1_m2_a_source(i_cores_m2_a_source[1]),
      .core2_m2_a_source(i_cores_m2_a_source[2]),
      .core3_m2_a_source(i_cores_m2_a_source[3]),
      .core4_m2_a_source(i_cores_m2_a_source[4]),
      .core5_m2_a_source(i_cores_m2_a_source[5]),
      .core6_m2_a_source(i_cores_m2_a_source[6]),
      .core7_m2_a_source(i_cores_m2_a_source[7]),
      .core0_m2_a_user(i_cores_m2_a_user[0]),
      .core1_m2_a_user(i_cores_m2_a_user[1]),
      .core2_m2_a_user(i_cores_m2_a_user[2]),
      .core3_m2_a_user(i_cores_m2_a_user[3]),
      .core4_m2_a_user(i_cores_m2_a_user[4]),
      .core5_m2_a_user(i_cores_m2_a_user[5]),
      .core6_m2_a_user(i_cores_m2_a_user[6]),
      .core7_m2_a_user(i_cores_m2_a_user[7]),
      .core0_m2_a_ready(o_cores_m2_a_ready[0]),
      .core1_m2_a_ready(o_cores_m2_a_ready[1]),
      .core2_m2_a_ready(o_cores_m2_a_ready[2]),
      .core3_m2_a_ready(o_cores_m2_a_ready[3]),
      .core4_m2_a_ready(o_cores_m2_a_ready[4]),
      .core5_m2_a_ready(o_cores_m2_a_ready[5]),
      .core6_m2_a_ready(o_cores_m2_a_ready[6]),
      .core7_m2_a_ready(o_cores_m2_a_ready[7]),
      .core0_m2_a_valid(i_cores_m2_a_valid[0]),
      .core1_m2_a_valid(i_cores_m2_a_valid[1]),
      .core2_m2_a_valid(i_cores_m2_a_valid[2]),
      .core3_m2_a_valid(i_cores_m2_a_valid[3]),
      .core4_m2_a_valid(i_cores_m2_a_valid[4]),
      .core5_m2_a_valid(i_cores_m2_a_valid[5]),
      .core6_m2_a_valid(i_cores_m2_a_valid[6]),
      .core7_m2_a_valid(i_cores_m2_a_valid[7]),
      .core0_m2_d_corrupt(o_cores_m2_d_corrupt[0]),
      .core1_m2_d_corrupt(o_cores_m2_d_corrupt[1]),
      .core2_m2_d_corrupt(o_cores_m2_d_corrupt[2]),
      .core3_m2_d_corrupt(o_cores_m2_d_corrupt[3]),
      .core4_m2_d_corrupt(o_cores_m2_d_corrupt[4]),
      .core5_m2_d_corrupt(o_cores_m2_d_corrupt[5]),
      .core6_m2_d_corrupt(o_cores_m2_d_corrupt[6]),
      .core7_m2_d_corrupt(o_cores_m2_d_corrupt[7]),
      .core0_m2_d_data(o_cores_m2_d_data[0]),
      .core1_m2_d_data(o_cores_m2_d_data[1]),
      .core2_m2_d_data(o_cores_m2_d_data[2]),
      .core3_m2_d_data(o_cores_m2_d_data[3]),
      .core4_m2_d_data(o_cores_m2_d_data[4]),
      .core5_m2_d_data(o_cores_m2_d_data[5]),
      .core6_m2_d_data(o_cores_m2_d_data[6]),
      .core7_m2_d_data(o_cores_m2_d_data[7]),
      .core0_m2_d_denied(o_cores_m2_d_denied[0]),
      .core1_m2_d_denied(o_cores_m2_d_denied[1]),
      .core2_m2_d_denied(o_cores_m2_d_denied[2]),
      .core3_m2_d_denied(o_cores_m2_d_denied[3]),
      .core4_m2_d_denied(o_cores_m2_d_denied[4]),
      .core5_m2_d_denied(o_cores_m2_d_denied[5]),
      .core6_m2_d_denied(o_cores_m2_d_denied[6]),
      .core7_m2_d_denied(o_cores_m2_d_denied[7]),
      .core0_m2_d_opcode(o_cores_m2_d_opcode[0]),
      .core1_m2_d_opcode(o_cores_m2_d_opcode[1]),
      .core2_m2_d_opcode(o_cores_m2_d_opcode[2]),
      .core3_m2_d_opcode(o_cores_m2_d_opcode[3]),
      .core4_m2_d_opcode(o_cores_m2_d_opcode[4]),
      .core5_m2_d_opcode(o_cores_m2_d_opcode[5]),
      .core6_m2_d_opcode(o_cores_m2_d_opcode[6]),
      .core7_m2_d_opcode(o_cores_m2_d_opcode[7]),
      .core0_m2_d_param(o_cores_m2_d_param[0]),
      .core1_m2_d_param(o_cores_m2_d_param[1]),
      .core2_m2_d_param(o_cores_m2_d_param[2]),
      .core3_m2_d_param(o_cores_m2_d_param[3]),
      .core4_m2_d_param(o_cores_m2_d_param[4]),
      .core5_m2_d_param(o_cores_m2_d_param[5]),
      .core6_m2_d_param(o_cores_m2_d_param[6]),
      .core7_m2_d_param(o_cores_m2_d_param[7]),
      .core0_m2_d_size(o_cores_m2_d_size[0]),
      .core1_m2_d_size(o_cores_m2_d_size[1]),
      .core2_m2_d_size(o_cores_m2_d_size[2]),
      .core3_m2_d_size(o_cores_m2_d_size[3]),
      .core4_m2_d_size(o_cores_m2_d_size[4]),
      .core5_m2_d_size(o_cores_m2_d_size[5]),
      .core6_m2_d_size(o_cores_m2_d_size[6]),
      .core7_m2_d_size(o_cores_m2_d_size[7]),
      .core0_m2_d_sink(o_cores_m2_d_sink[0]),
      .core1_m2_d_sink(o_cores_m2_d_sink[1]),
      .core2_m2_d_sink(o_cores_m2_d_sink[2]),
      .core3_m2_d_sink(o_cores_m2_d_sink[3]),
      .core4_m2_d_sink(o_cores_m2_d_sink[4]),
      .core5_m2_d_sink(o_cores_m2_d_sink[5]),
      .core6_m2_d_sink(o_cores_m2_d_sink[6]),
      .core7_m2_d_sink(o_cores_m2_d_sink[7]),
      .core0_m2_d_source(o_cores_m2_d_source[0]),
      .core1_m2_d_source(o_cores_m2_d_source[1]),
      .core2_m2_d_source(o_cores_m2_d_source[2]),
      .core3_m2_d_source(o_cores_m2_d_source[3]),
      .core4_m2_d_source(o_cores_m2_d_source[4]),
      .core5_m2_d_source(o_cores_m2_d_source[5]),
      .core6_m2_d_source(o_cores_m2_d_source[6]),
      .core7_m2_d_source(o_cores_m2_d_source[7]),
      .core0_m2_d_user(o_cores_m2_d_user[0]),
      .core1_m2_d_user(o_cores_m2_d_user[1]),
      .core2_m2_d_user(o_cores_m2_d_user[2]),
      .core3_m2_d_user(o_cores_m2_d_user[3]),
      .core4_m2_d_user(o_cores_m2_d_user[4]),
      .core5_m2_d_user(o_cores_m2_d_user[5]),
      .core6_m2_d_user(o_cores_m2_d_user[6]),
      .core7_m2_d_user(o_cores_m2_d_user[7]),
      .core0_m2_d_ready(i_cores_m2_d_ready[0]),
      .core1_m2_d_ready(i_cores_m2_d_ready[1]),
      .core2_m2_d_ready(i_cores_m2_d_ready[2]),
      .core3_m2_d_ready(i_cores_m2_d_ready[3]),
      .core4_m2_d_ready(i_cores_m2_d_ready[4]),
      .core5_m2_d_ready(i_cores_m2_d_ready[5]),
      .core6_m2_d_ready(i_cores_m2_d_ready[6]),
      .core7_m2_d_ready(i_cores_m2_d_ready[7]),
      .core0_m2_d_valid(o_cores_m2_d_valid[0]),
      .core1_m2_d_valid(o_cores_m2_d_valid[1]),
      .core2_m2_d_valid(o_cores_m2_d_valid[2]),
      .core3_m2_d_valid(o_cores_m2_d_valid[3]),
      .core4_m2_d_valid(o_cores_m2_d_valid[4]),
      .core5_m2_d_valid(o_cores_m2_d_valid[5]),
      .core6_m2_d_valid(o_cores_m2_d_valid[6]),
      .core7_m2_d_valid(o_cores_m2_d_valid[7]),
      .iocp_aclk(i_iocp_aclk),
      .iocp_araddr(i_iocp_axi_s_araddr),
      .iocp_arburst(i_iocp_axi_s_arburst),
      .iocp_arcache(i_iocp_axi_s_arcache),
      .iocp_arid(i_iocp_axi_s_arid),
      .iocp_arlen(i_iocp_axi_s_arlen),
      .iocp_arlock(i_iocp_axi_s_arlock),
      .iocp_arprot(i_iocp_axi_s_arprot),
      .iocp_arsize(i_iocp_axi_s_arsize),
      .iocp_arready(o_iocp_axi_s_arready),
      .iocp_arvalid(i_iocp_axi_s_arvalid),
      .iocp_awaddr(i_iocp_axi_s_awaddr),
      .iocp_awburst(i_iocp_axi_s_awburst),
      .iocp_awcache(i_iocp_axi_s_awcache),
      .iocp_awid(i_iocp_axi_s_awid),
      .iocp_awlen(i_iocp_axi_s_awlen),
      .iocp_awlock(i_iocp_axi_s_awlock),
      .iocp_awprot(i_iocp_axi_s_awprot),
      .iocp_awsize(i_iocp_axi_s_awsize),
      .iocp_awready(o_iocp_axi_s_awready),
      .iocp_awvalid(i_iocp_axi_s_awvalid),
      .iocp_bid(o_iocp_axi_s_bid),
      .iocp_bresp(o_iocp_axi_s_bresp),
      .iocp_bready(i_iocp_axi_s_bready),
      .iocp_bvalid(o_iocp_axi_s_bvalid),
      .iocp_rdata(o_iocp_axi_s_rdata),
      .iocp_rid(o_iocp_axi_s_rid),
      .iocp_rlast(o_iocp_axi_s_rlast),
      .iocp_rresp(o_iocp_axi_s_rresp),
      .iocp_rready(i_iocp_axi_s_rready),
      .iocp_rvalid(o_iocp_axi_s_rvalid),
      .iocp_wdata(i_iocp_axi_s_wdata),
      .iocp_wlast(i_iocp_axi_s_wlast),
      .iocp_wstrb(i_iocp_axi_s_wstrb),
      .iocp_wready(o_iocp_axi_s_wready),
      .iocp_wvalid(i_iocp_axi_s_wvalid),
      .mem_aclk(i_mem_aclk),
      .mem_araddr(o_mem_axi_m_araddr),
      .mem_arburst(o_mem_axi_m_arburst),
      .mem_arcache(o_mem_axi_m_arcache),
      .mem_arid(o_mem_axi_m_arid),
      .mem_arlen(o_mem_axi_m_arlen),
      .mem_arlock(o_mem_axi_m_arlock),
      .mem_arprot(o_mem_axi_m_arprot),
      .mem_arsize(o_mem_axi_m_arsize),
      .mem_arready(i_mem_axi_m_arready),
      .mem_arvalid(o_mem_axi_m_arvalid),
      .mem_awaddr(o_mem_axi_m_awaddr),
      .mem_awburst(o_mem_axi_m_awburst),
      .mem_awcache(o_mem_axi_m_awcache),
      .mem_awid(o_mem_axi_m_awid),
      .mem_awlen(o_mem_axi_m_awlen),
      .mem_awlock(o_mem_axi_m_awlock),
      .mem_awprot(o_mem_axi_m_awprot),
      .mem_awsize(o_mem_axi_m_awsize),
      .mem_awready(i_mem_axi_m_awready),
      .mem_awvalid(o_mem_axi_m_awvalid),
      .mem_bid(i_mem_axi_m_bid),
      .mem_bresp(i_mem_axi_m_bresp),
      .mem_bready(o_mem_axi_m_bready),
      .mem_bvalid(i_mem_axi_m_bvalid),
      .mem_rdata(i_mem_axi_m_rdata),
      .mem_rid(i_mem_axi_m_rid),
      .mem_rlast(i_mem_axi_m_rlast),
      .mem_rresp(i_mem_axi_m_rresp),
      .mem_rready(o_mem_axi_m_rready),
      .mem_rvalid(i_mem_axi_m_rvalid),
      .mem_wdata(o_mem_axi_m_wdata),
      .mem_wlast(o_mem_axi_m_wlast),
      .mem_wstrb(o_mem_axi_m_wstrb),
      .mem_wready(i_mem_axi_m_wready),
      .mem_wvalid(o_mem_axi_m_wvalid),
      .mmio_aclk(i_mmio_aclk),
      .mmio_aresetn(i_mmio_arst_n),
      .mmio_araddr(o_mmio_axi_m_araddr),
      .mmio_arburst(o_mmio_axi_m_arburst),
      .mmio_arcache(o_mmio_axi_m_arcache),
      .mmio_arid(o_mmio_axi_m_arid),
      .mmio_arlen(o_mmio_axi_m_arlen),
      .mmio_arlock(o_mmio_axi_m_arlock),
      .mmio_arprot(o_mmio_axi_m_arprot),
      .mmio_arsize(o_mmio_axi_m_arsize),
      .mmio_arready(i_mmio_axi_m_arready),
      .mmio_arvalid(o_mmio_axi_m_arvalid),
      .mmio_awaddr(o_mmio_axi_m_awaddr),
      .mmio_awburst(o_mmio_axi_m_awburst),
      .mmio_awcache(o_mmio_axi_m_awcache),
      .mmio_awid(o_mmio_axi_m_awid),
      .mmio_awlen(o_mmio_axi_m_awlen),
      .mmio_awlock(o_mmio_axi_m_awlock),
      .mmio_awprot(o_mmio_axi_m_awprot),
      .mmio_awsize(o_mmio_axi_m_awsize),
      .mmio_awready(i_mmio_axi_m_awready),
      .mmio_awvalid(o_mmio_axi_m_awvalid),
      .mmio_bid(i_mmio_axi_m_bid),
      .mmio_bresp(i_mmio_axi_m_bresp),
      .mmio_bready(o_mmio_axi_m_bready),
      .mmio_bvalid(i_mmio_axi_m_bvalid),
      .mmio_rdata(i_mmio_axi_m_rdata),
      .mmio_rid(i_mmio_axi_m_rid),
      .mmio_rlast(i_mmio_axi_m_rlast),
      .mmio_rresp(i_mmio_axi_m_rresp),
      .mmio_rready(o_mmio_axi_m_rready),
      .mmio_rvalid(i_mmio_axi_m_rvalid),
      .mmio_wdata(o_mmio_axi_m_wdata),
      .mmio_wlast(o_mmio_axi_m_wlast),
      .mmio_wstrb(o_mmio_axi_m_wstrb),
      .mmio_wready(i_mmio_axi_m_wready),
      .mmio_wvalid(o_mmio_axi_m_wvalid),
      .plmt_araddr(o_plmt_axi_m_araddr),
      .plmt_arburst(o_plmt_axi_m_arburst),
      .plmt_arcache(o_plmt_axi_m_arcache),
      .plmt_arid(o_plmt_axi_m_arid),
      .plmt_arlen(o_plmt_axi_m_arlen),
      .plmt_arlock(o_plmt_axi_m_arlock),
      .plmt_arprot(o_plmt_axi_m_arprot),
      .plmt_arsize(o_plmt_axi_m_arsize),
      .plmt_arready(i_plmt_axi_m_arready),
      .plmt_arvalid(o_plmt_axi_m_arvalid),
      .plmt_awaddr(o_plmt_axi_m_awaddr),
      .plmt_awburst(o_plmt_axi_m_awburst),
      .plmt_awcache(o_plmt_axi_m_awcache),
      .plmt_awid(o_plmt_axi_m_awid),
      .plmt_awlen(o_plmt_axi_m_awlen),
      .plmt_awlock(o_plmt_axi_m_awlock),
      .plmt_awprot(o_plmt_axi_m_awprot),
      .plmt_awsize(o_plmt_axi_m_awsize),
      .plmt_awready(i_plmt_axi_m_awready),
      .plmt_awvalid(o_plmt_axi_m_awvalid),
      .plmt_bid(i_plmt_axi_m_bid),
      .plmt_bresp(i_plmt_axi_m_bresp),
      .plmt_bready(o_plmt_axi_m_bready),
      .plmt_bvalid(i_plmt_axi_m_bvalid),
      .plmt_rdata(i_plmt_axi_m_rdata),
      .plmt_rid(i_plmt_axi_m_rid),
      .plmt_rlast(i_plmt_axi_m_rlast),
      .plmt_rresp(i_plmt_axi_m_rresp),
      .plmt_rready(o_plmt_axi_m_rready),
      .plmt_rvalid(i_plmt_axi_m_rvalid),
      .plmt_wdata(o_plmt_axi_m_wdata),
      .plmt_wlast(o_plmt_axi_m_wlast),
      .plmt_wstrb(o_plmt_axi_m_wstrb),
      .plmt_wready(i_plmt_axi_m_wready),
      .plmt_wvalid(o_plmt_axi_m_wvalid),
      .l2c_disable_init(i_l2c_disable_init),
      .l2c_err_int(o_l2c_err_int)
  );

endmodule
