#add_input_constraints i_thermal_throttle_async -c0
#add_input_constraints i_tok_prod_ocpl_m_scmdaccept -c0
#add_input_constraints i_tok_cons_ocpl_s_mcmd -c0
#add_input_constraints i_msip_async -c0
#add_input_constraints i_mtip_async -c0
#add_input_constraints i_debug_int_async -c0
#add_input_constraints i_resethaltreq_async -c0
#add_input_constraints i_noc_ht_axi_m_awready -c0
#add_input_constraints i_noc_ht_axi_m_wready -c0
#add_input_constraints i_noc_ht_axi_m_bvalid -c0
#add_input_constraints i_noc_ht_axi_m_arready -c0
#add_input_constraints i_noc_ht_axi_m_rvalid -c0
#add_input_constraints i_noc_lt_axi_m_awready -c0
#add_input_constraints i_noc_lt_axi_m_wready -c0
#add_input_constraints i_noc_lt_axi_m_bvalid -c0
#add_input_constraints i_noc_lt_axi_m_arready -c0
#add_input_constraints i_noc_lt_axi_m_rvalid -c0
#add_input_constraints i_noc_lt_axi_s_awvalid -c0
#add_input_constraints i_noc_lt_axi_s_wvalid -c0
#add_input_constraints i_noc_lt_axi_s_bready -c0
#add_input_constraints i_noc_lt_axi_s_arvalid -c0
#add_input_constraints i_noc_lt_axi_s_rready -c0
#add_input_constraints i_cfg_apb4_s_psel -c0
#add_input_constraints i_cfg_apb4_s_penable -c0
#add_input_constraints i_noc_async_idle_ack -c0
#add_input_constraints i_noc_async_idle_val -c0

add_input_constraints test_mode -c1
