#!/usr/bin/env bash

set -e
set -o pipefail

# Directories
workdir=$(pwd)

# save orig filelist created by tessent
cp -rp ${workdir}/tsdb_outdir/modified_files.lst ${workdir}/tsdb_outdir/modified_files.lst.orig

if [[ -d ../memory_test ]];
then
    # Remove _p from mbist modified file list
    # It will be modified by logic_test script
   cat ${workdir}/../memory_test/tsdb_outdir/modified_files.lst ${workdir}/tsdb_outdir/modified_files.lst > modified_files_merged.lst
   rm ${workdir}/tsdb_outdir/modified_files.lst
   awk -F/ '!seen[$NF]++' <(tac modified_files_merged.lst) | tac > ${workdir}/tsdb_outdir/modified_files.lst
   rm modified_files_merged.lst

   if [[ -f ${workdir}/../memory_test/tsdb_outdir/library_files.lst || -f ${workdir}/tsdb_outdir/library_files.lst ]] ; then
       echo "Adding ${workdir}/tsdb_outdir/library_files.lst"
       cat ${workdir}/../memory_test/tsdb_outdir/library_files.lst ${workdir}/tsdb_outdir/library_files.lst > library_files_merged.lst
       rm -f ${workdir}/tsdb_outdir/library_files.lst
       awk -F/ '!seen[$NF]++' <(tac library_files_merged.lst) | tac > ${workdir}/tsdb_outdir/library_files.lst
       rm library_files_merged.lst
   fi
fi

if [[ -d ../../firmware ]] ; then
    mkdir -p ${workdir}/tsdb_outdir/ddr_ate_firmware
    echo "AUTOGENERATED_FILE by postprocess_tsdb.sh" > ${workdir}/tsdb_outdir/ddr_ate_firmware/README
    echo "copied data from hw/impl/europa/blocks/lpddr/dft/firmware/" >> ${workdir}/tsdb_outdir/ddr_ate_firmware/README
    cp -Ru ../../firmware/ddr_ate_* ${workdir}/tsdb_outdir/ddr_ate_firmware/
fi


infile=$(readlink -f ${workdir}/tsdb_outdir/dft_inserted_designs/*.dft_inserted_design/*.sdc)
outfile=${infile/.sdc/.hierfix.sdc}
echo "Processing: $infile -> $outfile"
sed -r \
    -e "s@tessent_persistent_cell_BUF_C_TCK/o_clk@tessent_persistent_cell_BUF_C_TCK/u_tc_lib_clk_inv1/Y@g" \
    -e "s@tessent_persistent_cell_BUF_I_TCK/o_clk@tessent_persistent_cell_BUF_I_TCK/u_tc_lib_clk_inv1/Y@g" \
    -e "s@tessent_persistent_cell_BIST_CLK_OR_TCK/i_sel@tessent_persistent_cell_BIST_CLK_OR_TCK/u_tc_lib_clk_mux/S0@g" \
    -e "s@tessent_persistent_cell_BIST_CLK_INT/i_sel@tessent_persistent_cell_BIST_CLK_INT/u_tc_lib_clk_mux/S0@g" \
    -e "s@tessent_persistent_cell_ltest_clock_mux@tessent_persistent_cell_ltest_clock_mux/u_tc_lib_clk_mux@g" \
    -e "s@tessent_persistent_cell_AND_([^/]*)/o_z@tessent_persistent_cell_AND_\1/u_tc_lib_std_inv/Y@g" \
    -e "s@tessent_persistent_cell_([^/]*)_buf/i_a@tessent_persistent_cell_\1_buf/u_tc_lib_std_buf/A@g" \
    -e "s@tessent_persistent_cell_([^/]*)_buf/o_z@tessent_persistent_cell_\1_buf/u_tc_lib_std_buf/Y@g" \
    $infile > $outfile


sed -ir \
    -e "s@tessent_persistent_cell_edt_update_mux/o_z@tessent_persistent_cell_edt_update_mux/u_tc_lib_std_mux/Y@g" \
    -e "s@tessent_persistent_cell_from_scan_out\*_mux\*/o_z@tessent_persistent_cell_from_scan_out\*_mux\*/u_tc_lib_std_mux/Y@g" \
    -e "s@tessent_persistent_cell_from_scan_out\*_and/o_z@tessent_persistent_cell_from_scan_out\*_and/u_tc_lib_std_inv/Y@g" \
    -e "s@tessent_persistent_cell_from_scan_out\*_and/i_a@tessent_persistent_cell_from_scan_out\*_and/u_tc_lib_std_inv/A@g" \
    -e "s@tessent_persistent_cell_test_clock_buf/i_clk@tessent_persistent_cell_test_clock_buf/u_tc_lib_clk_inv1/A@g" \
    -e "s@tessent_persistent_cell_test_clock_buf/o_clk@tessent_persistent_cell_test_clock_buf/u_tc_lib_clk_inv1/Y@g" \
    -e "s@tessent_persistent_cell_inject_tck_mux@tessent_persistent_cell_inject_tck_mux/u_tc_lib_clk_mux@g" \
    -e "s@tessent_persistent_cell_tck_mux_\*@tessent_persistent_cell_tck_mux_*/u_tc_lib_clk_mux@g" \
    -e "s@tessent_persistent_cell_SHIFT_REG_CLK_mux@tessent_persistent_cell_SHIFT_REG_CLK_mux/u_tc_lib_clk_mux@g" \
    -e "s@u_tc_lib_clk_mux/i_clk1@u_tc_lib_clk_mux/B@g" \
    -e "s@_or2/i_clk1@_or2/u_tc_lib_clk_nor/B@g" \
    -e "s@tessent_persistent_cell_MUX1/i_clk1@tessent_persistent_cell_MUX1/u_tc_lib_clk_mux/B@g" \
    -e "s@tessent_persistent_cell_MUX1/i_sel@tessent_persistent_cell_MUX1/u_tc_lib_clk_mux/S0@g" \
    -e "s@tessent_persistent_cell_GATING_BIST_CLK/o_clk@tessent_persistent_cell_GATING_BIST_CLK/u_tc_lib_clk_en/ECK@g" \
    -e "s@tessent_persistent_cell_ssn_bus_clock_mux/i_sel@tessent_persistent_cell_ssn_bus_clock_mux/u_tc_lib_clk_mux/S0@g" \
    -e "s@tessent_persistent_cell_test_clock_cg/o_clk@tessent_persistent_cell_test_clock_cg/u_tc_lib_clk_en/ECK@g" \
    -e "s@clock_gen/tessent_persistent_cell_edt_update_mux@clock_gen*tessent_persistent_cell_edt_update_mux@g" \
    -e "s@clock_gen/clock_signals/tessent_persistent_cell_test_clock_buf@clock_gen*clock_signals*tessent_persistent_cell_test_clock_buf@g" \
    -e "s@tessent_persistent_cell_\([^/]*\)/o_z@tessent_persistent_cell_\1/u_tc_lib_std_buf/Y@g" \
    $outfile
