auth_enabled: true
api:
  webhook:
    enabled: true
    auth_token: "sdsdsd"
  testing:
    enabled: false
database:
  url: mysql://htz1-mysql01.htz1.axelera.ai
  user: mysql_001
  spaces:
    production: pipewatch
gitlab:
  url: https://git.axelera.ai

tables:

#-------------------------------------------------------
# Global Monitoring
#-------------------------------------------------------
  - name: global:scheduled-pipelines-runtime
    webhook: pipeline
    skip_unfinished: true
    filters:
      - event.object_attributes.source == 'schedule'
    variables:
      - name: project_name
        type: string
        value: event.project.namespace + '/' + event.project.name
      - name: schedule_name
        type: string
        value: api.schedule.description
      - name: schedule_id
        type: integer
        value: api.schedule.id
      - name: pipeline_id
        type: integer
        value: event.object_attributes.id
      - name: pipeline_url
        type: string
        value: event.object_attributes.url
      - name: commit_sha
        type: string
        value: event.object_attributes.sha
      - name: triggerer
        type: string
        value: event.user.username
      - name: created_at
        type: timestamp
        value: event.object_attributes.created_at
      - name: pipeline_duration
        type: float
        value: event.object_attributes.duration
      - name: jobs_count
        type: integer
        value: (api.jobs + api.downstream_jobs) | length
      - name: runtime
        type: float
        value: >
          (api.jobs | map(attribute='duration') | reject('none') | sum) +
          (api.downstream_jobs | map(attribute='duration') | reject('none') | sum)

#-------------------------------------------------------
# Triton Monitoring
#-------------------------------------------------------
  - name: triton:scheduled_pipeline_monitor
    webhook: pipeline
    skip_unfinished: true
    filters:
      - event.project.name == 'triton'
      - event.object_attributes.ref == 'main'
      - event.object_attributes.source == 'schedule'
    variables: &schedule_variables
      - name: schedule_name
        type: string
        value: api.schedule.description
      - name: schedule_id
        type: integer
        value: api.schedule.id
      - name: pipeline_id
        type: integer
        value: event.object_attributes.id
      - name: pipeline_url
        type: string
        value: event.object_attributes.url
      - name: commit_sha
        type: string
        value: event.object_attributes.sha
      - name: triggerer
        type: string
        value: event.user.username
      - name: status
        type: string
        value: event.object_attributes.status
      - name: created_at
        type: timestamp
        value: event.object_attributes.created_at
      - name: duration
        type: float
        value: event.object_attributes.duration
      - name: jobs_count
        type: integer
        value: api.downstream_jobs | list | length
      - name: jobs_passed
        type: integer
        value: api.downstream_jobs | selectattr('status', '==', 'success') | list | length
      - name: jobs_failed
        type: integer
        value: api.downstream_jobs | selectattr('status', '==', 'failed') | list | length
      - name: longest_job_duration
        type: float
        value: api.downstream_jobs | map(attribute='duration') | default(0) | max

  - name: triton:job_monitor
    webhook: job
    skip_unfinished: true
    attach_artifact: false
    filters:
      - event.project.name == 'triton'
      - event.ref == 'main'
    variables: &job_variables
      - name: pipeline_id
        type: integer
        value: event.pipeline_id
      - name: build_id
        type: integer
        value: event.build_id
      - name: schedule_id
        type: integer
        value: api.schedule.id
      - name: schedule_description
        type: string
        value: api.schedule.description
      - name: job_name
        type: string
        value: event.build_name
      - name: job_stage
        type: string
        value: event.build_stage
      - name: job_url
        type: string
        value: event.repository.homepage + '/-/jobs/' + (event.build_id | string)
      - name: job_status
        type: string
        value: event.build_status
      - name: job_failure_reason
        type: string
        value: event.build_failure_reason
      - name: commit_sha
        type: string
        value: event.sha
      - name: build_started_at
        type: timestamp
        value: event.build_started_at
      - name: build_finished_at
        type: timestamp
        value: event.build_finished_at
      - name: build_duration
        type: float
        value: event.build_duration
      - name: queued_duration
        type: float
        value: event.build_queued_duration
      - name: triggerer
        type: string
        value: event.user.username
      - name: runner_id
        type: integer
        value: event.runner.id
      - name: runner_description
        type: string
        value: event.runner.description

  - name: triton:data_monitor
    webhook: job
    skip_unfinished: true
    attach_artifact: true
    filters:
      - event.project.name == 'triton'
      - event.ref == 'main'
    variables: *job_variables

#-------------------------------------------------------
# Europa Monitoring
#-------------------------------------------------------
  - name: europa:scheduled_pipeline_monitor
    webhook: pipeline
    skip_unfinished: true
    filters:
      - event.project.name == 'Europa'
      - event.object_attributes.ref in ['main', 'schedule_main']
      - event.object_attributes.source == 'schedule'
    variables: *schedule_variables

  - name: europa:mr_pipeline_monitor
    webhook: pipeline
    skip_unfinished: true
    filters:
      - event.project.name == 'Europa'
      - event.object_attributes.source == 'merge_request_event'
    variables: &europa_mr_variables
      - name: schedule_name
        type: string
        value: "'MR'"
      - name: schedule_id
        type: integer
        value: api.mr_iid 
      - name: pipeline_id
        type: integer
        value: event.object_attributes.id
      - name: pipeline_url
        type: string
        value: api.pipeline_info.merge_request.web_url if 'merge_request' in api.pipeline_info else None
      - name: commit_sha
        type: string
        value: event.object_attributes.sha
      - name: triggerer
        type: string
        value: event.user.username
      - name: status
        type: string
        value: event.object_attributes.status
      - name: created_at
        type: timestamp
        value: event.object_attributes.created_at
      - name: duration
        type: float
        value: event.object_attributes.duration
      - name: jobs_count
        type: integer
        value: (api.jobs + api.downstream_jobs) | list | length
      - name: jobs_passed
        type: integer
        value: (api.jobs + api.downstream_jobs) | selectattr('status', '==', 'success') | list | length
      - name: jobs_failed
        type: integer
        value: (api.jobs + api.downstream_jobs) | selectattr('status', '==', 'failed') | list | length
      - name: longest_job_duration
        type: float
        value: (api.jobs + api.downstream_jobs) | map(attribute='duration') | default(0) | max
      - name: mr_label
        type: string
        value: api.is_merge_train and 'merge_train' or 'merge_request'

  - name: europa:job_monitor
    webhook: job
    skip_unfinished: true
    attach_artifact: false
    filters:
      - event.project.name == 'Europa'
      - event.ref in ['main', 'schedule_main']
    variables: *job_variables

  - name: europa:data_monitor
    webhook: job
    skip_unfinished: true
    attach_artifact: true
    filters:
      - event.project.name == 'Europa'
      - event.ref in ['main', 'schedule_main']
    variables: *job_variables
