// (C) Copyright Axelera AI 2024
// All Rights Reserved
// *** Axelera AI Confidential ***

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// Use the "blueprint-engine" to regenerate this file.

/* clang-format off */

//==================================================
// INCLUDES
//==================================================

#include "datapath.h"
#include "module.h"
#include "sdk_adapter.h"


//==================================================
// MACROS
//==================================================

//==================================================
// DEFINITIONS
//==================================================

//==================================================
// TYPES
//==================================================

//==================================================
// DATA
//==================================================

//==================================================
// LOCAL FUNCTION DECLARATIONS
//==================================================

//==================================================
// LOCAL FUNCTION DEFINITIONS
//==================================================

//==================================================
// GLOBAL FUNCTION DEFINITIONS
//==================================================

datapath_status_t datapath_init(void) {
  module_init();

  return DATAPATH_STATUS_OK;
}

datapath_status_t datapath_enable_execution(void) {
  for (module_id_t i = 0; i < MODULE_COUNT; i++) {
    module_enable_execution(i);
  }

  return DATAPATH_STATUS_OK;
}

datapath_status_t datapath_disable_execution(void) {
  for (module_id_t i = 0; i < MODULE_COUNT; i++) {
    module_disable_execution(i);
  }

  return DATAPATH_STATUS_OK;
}

datapath_status_t datapath_poll_idle(void) {
  for (module_id_t i = 0; i < MODULE_COUNT; i++) {
    module_poll_idle(i);
  }

  return DATAPATH_STATUS_OK;
}

datapath_status_t datapath_clear_instructions(void) {
  for (module_id_t i = 0; i < MODULE_COUNT; i++) {
    module_clear_instructions(i);
  }

  return DATAPATH_STATUS_OK;
}

