// (C) Copyright Axelera AI 2024
// All Rights Reserved
// *** Axelera AI Confidential ***

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// Use the "blueprint-engine" to regenerate this file.

/* clang-format off */

//==================================================
// INCLUDES
//==================================================

#include "dma.h"

#include "module.h"

//==================================================
// MACROS
//==================================================

//==================================================
// DEFINITIONS
//==================================================

//==================================================
// TYPES
//==================================================

//--------------------------------------------------
// CSRs
//--------------------------------------------------

// Registers
//--------------------------------------------------



// CSR
//--------------------------------------------------

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
} csr_t;

//==================================================
// DATA
//==================================================

//==================================================
// LOCAL FUNCTION DECLARATIONS
//==================================================

//==================================================
// LOCAL FUNCTION DEFINITIONS
//==================================================

//==================================================
// GLOBAL FUNCTION DEFINITIONS
//==================================================

inline dma_status_t dma_init(void) {
  return (dma_status_t) module_init();
}

inline dma_status_t dma_enable_execution(dma_id_t dma_id) {
  return (dma_status_t) module_enable_execution((module_id_t) dma_id);
}

inline dma_status_t dma_disable_execution(dma_id_t dma_id) {
  return (dma_status_t) module_disable_execution((module_id_t) dma_id);
}

inline dma_status_t dma_poll_idle(dma_id_t dma_id) {
  return (dma_status_t) module_poll_idle((module_id_t) dma_id);
}

inline dma_status_t dma_load_command(dma_id_t dma_id, dma_command_t* command) {
  return (dma_status_t) module_load_command((module_id_t) dma_id, (module_command_t*) command);
}
