// (C) Copyright Axelera AI 2024
// All Rights Reserved
// *** Axelera AI Confidential ***

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// Use the "blueprint-engine" to regenerate this file.

/* clang-format off */

#ifndef __DMA_LP_H__
#define __DMA_LP_H__

//==================================================
// INCLUDES
//==================================================

#include <stdint.h>
#include <stddef.h>

//==================================================
// MACROS
//==================================================

//==================================================
// DEFINITIONS
//==================================================

//==================================================
// TYPES
//==================================================

typedef enum {
  DMA_LP_STATUS_OK = 0,
  DMA_LP_STATUS_ERROR,
} dma_lp_status_t;

//==================================================
// GLOBAL FUNCTION PROTOTYPES
//==================================================

dma_lp_status_t dma_lp_init(void);

dma_lp_status_t dma_lp_start(uintptr_t src, uintptr_t dst, size_t size);
dma_lp_status_t dma_lp_poll();

#endif  // __DMA_LP_H__
