// (C) Copyright Axelera AI 2024
// All Rights Reserved
// *** Axelera AI Confidential ***

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// Use the "blueprint-engine" to regenerate this file.

/* clang-format off */

//==================================================
// INCLUDES
//==================================================

#include "ifd.h"

#include "module.h"

//==================================================
// MACROS
//==================================================

//==================================================
// DEFINITIONS
//==================================================

//==================================================
// TYPES
//==================================================

//--------------------------------------------------
// CSRs
//--------------------------------------------------

// Registers
//--------------------------------------------------

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t exec_en : 1;
  uint64_t ptr_rst : 1;
  uint64_t __reserved_2__ : 62;
} csr_register_cmdblk_ctrl_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t state : 2;
  uint64_t wait_token : 1;
  uint64_t __reserved_2__ : 5;
  uint64_t in_word_ptr : 8;
  uint64_t fifo_cnt : 8;
  uint64_t outst_cmds : 8;
  uint64_t pending_tokens : 16;
  uint64_t __reserved_7__ : 16;
} csr_register_cmdblk_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t err_addr_out_of_range : 1;
  uint64_t err_illegal_addr : 1;
  uint64_t __reserved_2__ : 6;
  uint64_t cmdblk_cmd_dropped : 1;
  uint64_t __reserved_4__ : 7;
  uint64_t dp_decomp_access_error : 1;
  uint64_t decomp_invalid_stream_header : 1;
  uint64_t decomp_invalid_scheme_header : 1;
  uint64_t decomp_invalid_compressed_size : 1;
  uint64_t decomp_invalid_uncompressed_size : 1;
  uint64_t __reserved_10__ : 3;
  uint64_t dp_vtrsp_access_error : 1;
  uint64_t err_vtrsp : 1;
  uint64_t __reserved_13__ : 6;
  uint64_t dbg_sw_interrupt : 1;
  uint64_t __reserved_15__ : 31;
} csr_register_irq_en_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t err_addr_out_of_range : 1;
  uint64_t err_illegal_addr : 1;
  uint64_t __reserved_2__ : 6;
  uint64_t cmdblk_cmd_dropped : 1;
  uint64_t __reserved_4__ : 7;
  uint64_t dp_decomp_access_error : 1;
  uint64_t decomp_invalid_stream_header : 1;
  uint64_t decomp_invalid_scheme_header : 1;
  uint64_t decomp_invalid_compressed_size : 1;
  uint64_t decomp_invalid_uncompressed_size : 1;
  uint64_t __reserved_10__ : 3;
  uint64_t dp_vtrsp_access_error : 1;
  uint64_t err_vtrsp : 1;
  uint64_t __reserved_13__ : 6;
  uint64_t dbg_sw_interrupt : 1;
  uint64_t __reserved_15__ : 31;
} csr_register_irq_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t __reserved_0__ : 32;
  uint64_t dbg_sw_irq : 1;
  uint64_t __reserved_2__ : 31;
} csr_register_dp_ctrl_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t __reserved_0__ : 8;
  uint64_t out_vld : 1;
  uint64_t out_rdy : 1;
  uint64_t out_lst : 1;
  uint64_t out_stl : 1;
  uint64_t __reserved_5__ : 4;
  uint64_t dpcmd0_vld : 1;
  uint64_t dpcmd0_rdy : 1;
  uint64_t dpcmd0_lst : 1;
  uint64_t dpcmd0_stl : 1;
  uint64_t __reserved_10__ : 12;
  uint64_t mm_req_vld : 1;
  uint64_t mm_req_rdy : 1;
  uint64_t mm_resp_ack : 1;
  uint64_t __reserved_14__ : 5;
  uint64_t decomp_stream_done : 1;
  uint64_t decomp_scheme_done : 1;
  uint64_t decomp_scheme : 2;
  uint64_t decomp_fsm_state : 4;
  uint64_t vtrsp_fill_state : 3;
  uint64_t vtrsp_drain_state : 2;
  uint64_t vtrsp_in_lst : 1;
  uint64_t vtrsp_in_rdy : 1;
  uint64_t vtrsp_in_vld : 1;
  uint64_t vtrsp_out_lst : 1;
  uint64_t vtrsp_out_rdy : 1;
  uint64_t vtrsp_out_vld : 1;
  uint64_t vtrsp_cmd_lst : 1;
  uint64_t vtrsp_cmd_rdy : 1;
  uint64_t vtrsp_cmd_vld : 1;
  uint64_t __reserved_30__ : 2;
} csr_register_dp_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t __reserved_0__ : 8;
  uint64_t out_vld : 1;
  uint64_t out_rdy : 1;
  uint64_t out_lst : 1;
  uint64_t __reserved_4__ : 5;
  uint64_t dpcmd0_vld : 1;
  uint64_t dpcmd0_rdy : 1;
  uint64_t dpcmd0_lst : 1;
  uint64_t __reserved_8__ : 45;
} csr_register_dbg_observe_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t __reserved_0__ : 48;
  uint64_t fsm_state : 2;
  uint64_t instr_stalled : 1;
  uint64_t out_a_zero : 1;
  uint64_t out_b_zero : 1;
  uint64_t out_c_zero : 1;
  uint64_t out_d_zero : 1;
  uint64_t inner_a_zero : 1;
  uint64_t inner_b_zero : 1;
  uint64_t inner_c_zero : 1;
  uint64_t inner_d_zero : 1;
  uint64_t __reserved_11__ : 5;
} csr_register_cmdgen_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t scratch : 64;
} csr_register_dbg_scratch_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t block_id : 8;
  uint64_t ai_core_id : 8;
  uint64_t hw_revision : 8;
  uint64_t __reserved_3__ : 40;
} csr_register_dbg_id_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t cmd_fifo_depth : 8;
  uint64_t __reserved_1__ : 24;
  uint64_t static_cmd_present : 1;
  uint64_t decomp_present : 1;
  uint64_t vtrsp_present : 1;
  uint64_t __reserved_5__ : 29;
} csr_register_hw_capability_t;

// CSR
//--------------------------------------------------

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  csr_register_cmdblk_ctrl_t cmdblk_ctrl;
  csr_register_cmdblk_status_t cmdblk_status;
  csr_register_irq_en_t irq_en;
  csr_register_irq_status_t irq_status;
  csr_register_dp_ctrl_t dp_ctrl;
  csr_register_dp_status_t dp_status;
  csr_register_dbg_observe_t dbg_observe;
  csr_register_cmdgen_status_t cmdgen_status;
  csr_register_dbg_scratch_t dbg_scratch;
  csr_register_dbg_id_t dbg_id;
  csr_register_hw_capability_t hw_capability;
} csr_t;

//==================================================
// DATA
//==================================================

//==================================================
// LOCAL FUNCTION DECLARATIONS
//==================================================

//==================================================
// LOCAL FUNCTION DEFINITIONS
//==================================================

//==================================================
// GLOBAL FUNCTION DEFINITIONS
//==================================================

inline ifd_status_t ifd_init(void) {
  return (ifd_status_t) module_init();
}

inline ifd_status_t ifd_enable_execution(ifd_id_t ifd_id) {
  return (ifd_status_t) module_enable_execution((module_id_t) ifd_id);
}

inline ifd_status_t ifd_disable_execution(ifd_id_t ifd_id) {
  return (ifd_status_t) module_disable_execution((module_id_t) ifd_id);
}

inline ifd_status_t ifd_poll_idle(ifd_id_t ifd_id) {
  return (ifd_status_t) module_poll_idle((module_id_t) ifd_id);
}

inline ifd_status_t ifd_load_command(ifd_id_t ifd_id, ifd_command_t* command) {
  return (ifd_status_t) module_load_command((module_id_t) ifd_id, (module_command_t*) command);
}

inline ifd_status_t ifd_load_instructions(ifd_id_t ifd_id, ifd_instruction_t instructions[], uint16_t count, uint16_t offset) {
  return (ifd_status_t) module_load_instructions((module_id_t) ifd_id, (void*) instructions, count, offset);
}
