// (C) Copyright Axelera AI 2024
// All Rights Reserved
// *** Axelera AI Confidential ***

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
// Use the "blueprint-engine" to regenerate this file.

/* clang-format off */

//==================================================
// INCLUDES
//==================================================

#include "token_manager.h"

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "sdk_adapter.h"

//==================================================
// MACROS
//==================================================

//==================================================
// DEFINITIONS
//==================================================

#define ADDRESS_OFFSET_TOKEN_MANAGER_CSR                 (0x00030000)
#define REGISTER_ROWS                                             (3)

//==================================================
// TYPES
//==================================================

//--------------------------------------------------
// CSRs
//--------------------------------------------------

// Registers
//--------------------------------------------------

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_0 : 8;
  uint64_t m_ifd_1 : 8;
  uint64_t m_ifd_2 : 8;
  uint64_t m_ifd_w : 8;
  uint64_t m_odr : 8;
  uint64_t d_ifd_0 : 8;
  uint64_t d_ifd_1 : 8;
  uint64_t d_odr : 8;
} csr_register_swep_prod_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_mvmexe : 8;
  uint64_t m_mvmprg : 8;
  uint64_t m_iau : 8;
  uint64_t m_dpu : 8;
  uint64_t d_dwpu : 8;
  uint64_t d_iau : 8;
  uint64_t d_dpu : 8;
  uint64_t hp_dma_0 : 8;
} csr_register_swep_prod_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t hp_dma_1 : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_swep_prod_2_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_0 : 8;
  uint64_t m_ifd_1 : 8;
  uint64_t m_ifd_2 : 8;
  uint64_t m_ifd_w : 8;
  uint64_t m_odr : 8;
  uint64_t d_ifd_0 : 8;
  uint64_t d_ifd_1 : 8;
  uint64_t d_odr : 8;
} csr_register_swep_cons_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_mvmexe : 8;
  uint64_t m_mvmprg : 8;
  uint64_t m_iau : 8;
  uint64_t m_dpu : 8;
  uint64_t d_dwpu : 8;
  uint64_t d_iau : 8;
  uint64_t d_dpu : 8;
  uint64_t hp_dma_0 : 8;
} csr_register_swep_cons_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t hp_dma_1 : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_swep_cons_2_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t swep_prod_m_ifd_0 : 1;
  uint64_t swep_prod_m_ifd_1 : 1;
  uint64_t swep_prod_m_ifd_2 : 1;
  uint64_t swep_prod_m_ifd_w : 1;
  uint64_t swep_prod_m_odr : 1;
  uint64_t swep_prod_d_ifd_0 : 1;
  uint64_t swep_prod_d_ifd_1 : 1;
  uint64_t swep_prod_d_odr : 1;
  uint64_t swep_prod_m_mvmexe : 1;
  uint64_t swep_prod_m_mvmprg : 1;
  uint64_t swep_prod_m_iau : 1;
  uint64_t swep_prod_m_dpu : 1;
  uint64_t swep_prod_d_dwpu : 1;
  uint64_t swep_prod_d_iau : 1;
  uint64_t swep_prod_d_dpu : 1;
  uint64_t swep_prod_hp_dma_0 : 1;
  uint64_t swep_prod_hp_dma_1 : 1;
  uint64_t __reserved_17__ : 47;
} csr_register_irq_swep_prod_sat_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t irq_swep_prod_m_ifd_0_en : 1;
  uint64_t irq_swep_prod_m_ifd_1_en : 1;
  uint64_t irq_swep_prod_m_ifd_2_en : 1;
  uint64_t irq_swep_prod_m_ifd_w_en : 1;
  uint64_t irq_swep_prod_m_odr_en : 1;
  uint64_t irq_swep_prod_d_ifd_0_en : 1;
  uint64_t irq_swep_prod_d_ifd_1_en : 1;
  uint64_t irq_swep_prod_d_odr_en : 1;
  uint64_t irq_swep_prod_m_mvmexe_en : 1;
  uint64_t irq_swep_prod_m_mvmprg_en : 1;
  uint64_t irq_swep_prod_m_iau_en : 1;
  uint64_t irq_swep_prod_m_dpu_en : 1;
  uint64_t irq_swep_prod_d_dwpu_en : 1;
  uint64_t irq_swep_prod_d_iau_en : 1;
  uint64_t irq_swep_prod_d_dpu_en : 1;
  uint64_t irq_swep_prod_hp_dma_0_en : 1;
  uint64_t irq_swep_prod_hp_dma_1_en : 1;
  uint64_t __reserved_17__ : 47;
} csr_register_irq_swep_prod_sat_en_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t swep_cons_m_ifd_0 : 1;
  uint64_t swep_cons_m_ifd_1 : 1;
  uint64_t swep_cons_m_ifd_2 : 1;
  uint64_t swep_cons_m_ifd_w : 1;
  uint64_t swep_cons_m_odr : 1;
  uint64_t swep_cons_d_ifd_0 : 1;
  uint64_t swep_cons_d_ifd_1 : 1;
  uint64_t swep_cons_d_odr : 1;
  uint64_t swep_cons_m_mvmexe : 1;
  uint64_t swep_cons_m_mvmprg : 1;
  uint64_t swep_cons_m_iau : 1;
  uint64_t swep_cons_m_dpu : 1;
  uint64_t swep_cons_d_dwpu : 1;
  uint64_t swep_cons_d_iau : 1;
  uint64_t swep_cons_d_dpu : 1;
  uint64_t swep_cons_hp_dma_0 : 1;
  uint64_t swep_cons_hp_dma_1 : 1;
  uint64_t __reserved_17__ : 47;
} csr_register_irq_swep_cons_sat_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t irq_swep_cons_m_ifd_0_en : 1;
  uint64_t irq_swep_cons_m_ifd_1_en : 1;
  uint64_t irq_swep_cons_m_ifd_2_en : 1;
  uint64_t irq_swep_cons_m_ifd_w_en : 1;
  uint64_t irq_swep_cons_m_odr_en : 1;
  uint64_t irq_swep_cons_d_ifd_0_en : 1;
  uint64_t irq_swep_cons_d_ifd_1_en : 1;
  uint64_t irq_swep_cons_d_odr_en : 1;
  uint64_t irq_swep_cons_m_mvmexe_en : 1;
  uint64_t irq_swep_cons_m_mvmprg_en : 1;
  uint64_t irq_swep_cons_m_iau_en : 1;
  uint64_t irq_swep_cons_m_dpu_en : 1;
  uint64_t irq_swep_cons_d_dwpu_en : 1;
  uint64_t irq_swep_cons_d_iau_en : 1;
  uint64_t irq_swep_cons_d_dpu_en : 1;
  uint64_t irq_swep_cons_hp_dma_0_en : 1;
  uint64_t irq_swep_cons_hp_dma_1_en : 1;
  uint64_t __reserved_17__ : 47;
} csr_register_irq_swep_cons_sat_en_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t swep_cons_m_ifd_0 : 1;
  uint64_t swep_cons_m_ifd_1 : 1;
  uint64_t swep_cons_m_ifd_2 : 1;
  uint64_t swep_cons_m_ifd_w : 1;
  uint64_t swep_cons_m_odr : 1;
  uint64_t swep_cons_d_ifd_0 : 1;
  uint64_t swep_cons_d_ifd_1 : 1;
  uint64_t swep_cons_d_odr : 1;
  uint64_t swep_cons_m_mvmexe : 1;
  uint64_t swep_cons_m_mvmprg : 1;
  uint64_t swep_cons_m_iau : 1;
  uint64_t swep_cons_m_dpu : 1;
  uint64_t swep_cons_d_dwpu : 1;
  uint64_t swep_cons_d_iau : 1;
  uint64_t swep_cons_d_dpu : 1;
  uint64_t swep_cons_hp_dma_0 : 1;
  uint64_t swep_cons_hp_dma_1 : 1;
  uint64_t __reserved_17__ : 47;
} csr_register_irq_swep_cons_non_zero_status_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t irq_swep_cons_m_ifd_0_en : 1;
  uint64_t irq_swep_cons_m_ifd_1_en : 1;
  uint64_t irq_swep_cons_m_ifd_2_en : 1;
  uint64_t irq_swep_cons_m_ifd_w_en : 1;
  uint64_t irq_swep_cons_m_odr_en : 1;
  uint64_t irq_swep_cons_d_ifd_0_en : 1;
  uint64_t irq_swep_cons_d_ifd_1_en : 1;
  uint64_t irq_swep_cons_d_odr_en : 1;
  uint64_t irq_swep_cons_m_mvmexe_en : 1;
  uint64_t irq_swep_cons_m_mvmprg_en : 1;
  uint64_t irq_swep_cons_m_iau_en : 1;
  uint64_t irq_swep_cons_m_dpu_en : 1;
  uint64_t irq_swep_cons_d_dwpu_en : 1;
  uint64_t irq_swep_cons_d_iau_en : 1;
  uint64_t irq_swep_cons_d_dpu_en : 1;
  uint64_t irq_swep_cons_hp_dma_0_en : 1;
  uint64_t irq_swep_cons_hp_dma_1_en : 1;
  uint64_t __reserved_17__ : 47;
} csr_register_irq_swep_cons_non_zero_en_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_0_tok_prod_m_ifd_1 : 1;
  uint64_t m_ifd_0_tok_prod_m_ifd_2 : 1;
  uint64_t m_ifd_0_tok_prod_m_ifd_w : 1;
  uint64_t m_ifd_0_tok_prod_m_odr : 1;
  uint64_t m_ifd_0_tok_prod_d_ifd_0 : 1;
  uint64_t m_ifd_0_tok_prod_d_ifd_1 : 1;
  uint64_t m_ifd_0_tok_prod_d_odr : 1;
  uint64_t m_ifd_0_tok_prod_hp_dma_0 : 1;
  uint64_t m_ifd_0_tok_prod_hp_dma_1 : 1;
  uint64_t m_ifd_1_tok_prod_m_ifd_0 : 1;
  uint64_t m_ifd_1_tok_prod_m_ifd_2 : 1;
  uint64_t m_ifd_1_tok_prod_m_ifd_w : 1;
  uint64_t m_ifd_1_tok_prod_m_odr : 1;
  uint64_t m_ifd_1_tok_prod_d_ifd_0 : 1;
  uint64_t m_ifd_1_tok_prod_d_ifd_1 : 1;
  uint64_t m_ifd_1_tok_prod_d_odr : 1;
  uint64_t m_ifd_1_tok_prod_hp_dma_0 : 1;
  uint64_t m_ifd_1_tok_prod_hp_dma_1 : 1;
  uint64_t m_ifd_2_tok_prod_m_ifd_0 : 1;
  uint64_t m_ifd_2_tok_prod_m_ifd_1 : 1;
  uint64_t m_ifd_2_tok_prod_m_ifd_w : 1;
  uint64_t m_ifd_2_tok_prod_m_odr : 1;
  uint64_t m_ifd_2_tok_prod_d_ifd_0 : 1;
  uint64_t m_ifd_2_tok_prod_d_ifd_1 : 1;
  uint64_t m_ifd_2_tok_prod_d_odr : 1;
  uint64_t m_ifd_2_tok_prod_hp_dma_0 : 1;
  uint64_t m_ifd_2_tok_prod_hp_dma_1 : 1;
  uint64_t m_ifd_w_tok_prod_m_ifd_0 : 1;
  uint64_t m_ifd_w_tok_prod_m_ifd_1 : 1;
  uint64_t m_ifd_w_tok_prod_m_ifd_2 : 1;
  uint64_t m_ifd_w_tok_prod_m_odr : 1;
  uint64_t m_ifd_w_tok_prod_d_ifd_0 : 1;
  uint64_t m_ifd_w_tok_prod_d_ifd_1 : 1;
  uint64_t m_ifd_w_tok_prod_d_odr : 1;
  uint64_t m_ifd_w_tok_prod_hp_dma_0 : 1;
  uint64_t m_ifd_w_tok_prod_hp_dma_1 : 1;
  uint64_t m_odr_tok_prod_m_ifd_0 : 1;
  uint64_t m_odr_tok_prod_m_ifd_1 : 1;
  uint64_t m_odr_tok_prod_m_ifd_2 : 1;
  uint64_t m_odr_tok_prod_m_ifd_w : 1;
  uint64_t m_odr_tok_prod_d_ifd_0 : 1;
  uint64_t m_odr_tok_prod_d_ifd_1 : 1;
  uint64_t m_odr_tok_prod_d_odr : 1;
  uint64_t m_odr_tok_prod_hp_dma_0 : 1;
  uint64_t m_odr_tok_prod_hp_dma_1 : 1;
  uint64_t d_ifd_0_tok_prod_m_ifd_0 : 1;
  uint64_t d_ifd_0_tok_prod_m_ifd_1 : 1;
  uint64_t d_ifd_0_tok_prod_m_ifd_2 : 1;
  uint64_t d_ifd_0_tok_prod_m_ifd_w : 1;
  uint64_t d_ifd_0_tok_prod_m_odr : 1;
  uint64_t d_ifd_0_tok_prod_d_ifd_1 : 1;
  uint64_t d_ifd_0_tok_prod_d_odr : 1;
  uint64_t d_ifd_0_tok_prod_hp_dma_0 : 1;
  uint64_t d_ifd_0_tok_prod_hp_dma_1 : 1;
  uint64_t d_ifd_1_tok_prod_m_ifd_0 : 1;
  uint64_t d_ifd_1_tok_prod_m_ifd_1 : 1;
  uint64_t d_ifd_1_tok_prod_m_ifd_2 : 1;
  uint64_t d_ifd_1_tok_prod_m_ifd_w : 1;
  uint64_t d_ifd_1_tok_prod_m_odr : 1;
  uint64_t d_ifd_1_tok_prod_d_ifd_0 : 1;
  uint64_t d_ifd_1_tok_prod_d_odr : 1;
  uint64_t d_ifd_1_tok_prod_hp_dma_0 : 1;
  uint64_t d_ifd_1_tok_prod_hp_dma_1 : 1;
  uint64_t d_odr_tok_prod_m_ifd_0 : 1;
} csr_register_irq_gen_sat_prod_status_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_odr_tok_prod_m_ifd_1 : 1;
  uint64_t d_odr_tok_prod_m_ifd_2 : 1;
  uint64_t d_odr_tok_prod_m_ifd_w : 1;
  uint64_t d_odr_tok_prod_m_odr : 1;
  uint64_t d_odr_tok_prod_d_ifd_0 : 1;
  uint64_t d_odr_tok_prod_d_ifd_1 : 1;
  uint64_t d_odr_tok_prod_hp_dma_0 : 1;
  uint64_t d_odr_tok_prod_hp_dma_1 : 1;
  uint64_t m_mvmexe_tok_prod_m_mvmprg : 1;
  uint64_t m_mvmprg_tok_prod_m_mvmexe : 1;
  uint64_t hp_dma_0_tok_prod_m_ifd_0 : 1;
  uint64_t hp_dma_0_tok_prod_m_ifd_1 : 1;
  uint64_t hp_dma_0_tok_prod_m_ifd_2 : 1;
  uint64_t hp_dma_0_tok_prod_m_ifd_w : 1;
  uint64_t hp_dma_0_tok_prod_m_odr : 1;
  uint64_t hp_dma_0_tok_prod_d_ifd_0 : 1;
  uint64_t hp_dma_0_tok_prod_d_ifd_1 : 1;
  uint64_t hp_dma_0_tok_prod_d_odr : 1;
  uint64_t hp_dma_0_tok_prod_hp_dma_1 : 1;
  uint64_t hp_dma_1_tok_prod_m_ifd_0 : 1;
  uint64_t hp_dma_1_tok_prod_m_ifd_1 : 1;
  uint64_t hp_dma_1_tok_prod_m_ifd_2 : 1;
  uint64_t hp_dma_1_tok_prod_m_ifd_w : 1;
  uint64_t hp_dma_1_tok_prod_m_odr : 1;
  uint64_t hp_dma_1_tok_prod_d_ifd_0 : 1;
  uint64_t hp_dma_1_tok_prod_d_ifd_1 : 1;
  uint64_t hp_dma_1_tok_prod_d_odr : 1;
  uint64_t hp_dma_1_tok_prod_hp_dma_0 : 1;
  uint64_t __reserved_28__ : 36;
} csr_register_irq_gen_sat_prod_status_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t irq_m_ifd_0_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_m_odr_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_d_odr_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_m_ifd_0_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_m_odr_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_d_odr_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_m_ifd_1_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_m_odr_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_d_odr_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_m_ifd_2_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_m_odr_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_d_odr_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_m_ifd_w_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_m_odr_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_m_odr_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_m_odr_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_m_odr_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_m_odr_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_m_odr_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_m_odr_tok_prod_d_odr_en : 1;
  uint64_t irq_m_odr_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_m_odr_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_m_odr_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_d_odr_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_d_ifd_0_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_m_odr_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_d_odr_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_d_ifd_1_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_d_odr_tok_prod_m_ifd_0_en : 1;
} csr_register_irq_gen_sat_prod_en_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t irq_d_odr_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_d_odr_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_d_odr_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_d_odr_tok_prod_m_odr_en : 1;
  uint64_t irq_d_odr_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_d_odr_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_d_odr_tok_prod_hp_dma_0_en : 1;
  uint64_t irq_d_odr_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_m_mvmexe_tok_prod_m_mvmprg_en : 1;
  uint64_t irq_m_mvmprg_tok_prod_m_mvmexe_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_m_odr_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_d_odr_en : 1;
  uint64_t irq_hp_dma_0_tok_prod_hp_dma_1_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_m_ifd_0_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_m_ifd_1_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_m_ifd_2_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_m_ifd_w_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_m_odr_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_d_ifd_0_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_d_ifd_1_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_d_odr_en : 1;
  uint64_t irq_hp_dma_1_tok_prod_hp_dma_0_en : 1;
  uint64_t __reserved_28__ : 36;
} csr_register_irq_gen_sat_prod_en_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_0_tok_prod_m_ifd_1_cnt : 8;
  uint64_t m_ifd_0_tok_prod_m_ifd_2_cnt : 8;
  uint64_t m_ifd_0_tok_prod_m_ifd_w_cnt : 8;
  uint64_t m_ifd_0_tok_prod_m_odr_cnt : 8;
  uint64_t m_ifd_0_tok_prod_d_ifd_0_cnt : 8;
  uint64_t m_ifd_0_tok_prod_d_ifd_1_cnt : 8;
  uint64_t m_ifd_0_tok_prod_d_odr_cnt : 8;
  uint64_t m_ifd_0_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_m_ifd_0_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_0_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_ifd_0_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_1_tok_prod_m_ifd_0_cnt : 8;
  uint64_t m_ifd_1_tok_prod_m_ifd_2_cnt : 8;
  uint64_t m_ifd_1_tok_prod_m_ifd_w_cnt : 8;
  uint64_t m_ifd_1_tok_prod_m_odr_cnt : 8;
  uint64_t m_ifd_1_tok_prod_d_ifd_0_cnt : 8;
  uint64_t m_ifd_1_tok_prod_d_ifd_1_cnt : 8;
  uint64_t m_ifd_1_tok_prod_d_odr_cnt : 8;
  uint64_t m_ifd_1_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_m_ifd_1_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_1_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_ifd_1_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_2_tok_prod_m_ifd_0_cnt : 8;
  uint64_t m_ifd_2_tok_prod_m_ifd_1_cnt : 8;
  uint64_t m_ifd_2_tok_prod_m_ifd_w_cnt : 8;
  uint64_t m_ifd_2_tok_prod_m_odr_cnt : 8;
  uint64_t m_ifd_2_tok_prod_d_ifd_0_cnt : 8;
  uint64_t m_ifd_2_tok_prod_d_ifd_1_cnt : 8;
  uint64_t m_ifd_2_tok_prod_d_odr_cnt : 8;
  uint64_t m_ifd_2_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_m_ifd_2_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_2_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_ifd_2_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_w_tok_prod_m_ifd_0_cnt : 8;
  uint64_t m_ifd_w_tok_prod_m_ifd_1_cnt : 8;
  uint64_t m_ifd_w_tok_prod_m_ifd_2_cnt : 8;
  uint64_t m_ifd_w_tok_prod_m_odr_cnt : 8;
  uint64_t m_ifd_w_tok_prod_d_ifd_0_cnt : 8;
  uint64_t m_ifd_w_tok_prod_d_ifd_1_cnt : 8;
  uint64_t m_ifd_w_tok_prod_d_odr_cnt : 8;
  uint64_t m_ifd_w_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_m_ifd_w_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_ifd_w_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_ifd_w_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_odr_tok_prod_m_ifd_0_cnt : 8;
  uint64_t m_odr_tok_prod_m_ifd_1_cnt : 8;
  uint64_t m_odr_tok_prod_m_ifd_2_cnt : 8;
  uint64_t m_odr_tok_prod_m_ifd_w_cnt : 8;
  uint64_t m_odr_tok_prod_d_ifd_0_cnt : 8;
  uint64_t m_odr_tok_prod_d_ifd_1_cnt : 8;
  uint64_t m_odr_tok_prod_d_odr_cnt : 8;
  uint64_t m_odr_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_m_odr_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_odr_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_odr_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_ifd_0_tok_prod_m_ifd_0_cnt : 8;
  uint64_t d_ifd_0_tok_prod_m_ifd_1_cnt : 8;
  uint64_t d_ifd_0_tok_prod_m_ifd_2_cnt : 8;
  uint64_t d_ifd_0_tok_prod_m_ifd_w_cnt : 8;
  uint64_t d_ifd_0_tok_prod_m_odr_cnt : 8;
  uint64_t d_ifd_0_tok_prod_d_ifd_1_cnt : 8;
  uint64_t d_ifd_0_tok_prod_d_odr_cnt : 8;
  uint64_t d_ifd_0_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_d_ifd_0_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_ifd_0_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_d_ifd_0_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_ifd_1_tok_prod_m_ifd_0_cnt : 8;
  uint64_t d_ifd_1_tok_prod_m_ifd_1_cnt : 8;
  uint64_t d_ifd_1_tok_prod_m_ifd_2_cnt : 8;
  uint64_t d_ifd_1_tok_prod_m_ifd_w_cnt : 8;
  uint64_t d_ifd_1_tok_prod_m_odr_cnt : 8;
  uint64_t d_ifd_1_tok_prod_d_ifd_0_cnt : 8;
  uint64_t d_ifd_1_tok_prod_d_odr_cnt : 8;
  uint64_t d_ifd_1_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_d_ifd_1_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_ifd_1_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_d_ifd_1_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_odr_tok_prod_m_ifd_0_cnt : 8;
  uint64_t d_odr_tok_prod_m_ifd_1_cnt : 8;
  uint64_t d_odr_tok_prod_m_ifd_2_cnt : 8;
  uint64_t d_odr_tok_prod_m_ifd_w_cnt : 8;
  uint64_t d_odr_tok_prod_m_odr_cnt : 8;
  uint64_t d_odr_tok_prod_d_ifd_0_cnt : 8;
  uint64_t d_odr_tok_prod_d_ifd_1_cnt : 8;
  uint64_t d_odr_tok_prod_hp_dma_0_cnt : 8;
} csr_register_prod_cnt_d_odr_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t d_odr_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_d_odr_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_mvmexe_tok_prod_m_mvmprg_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_mvmexe_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t m_mvmprg_tok_prod_m_mvmexe_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_m_mvmprg_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t hp_dma_0_tok_prod_m_ifd_0_cnt : 8;
  uint64_t hp_dma_0_tok_prod_m_ifd_1_cnt : 8;
  uint64_t hp_dma_0_tok_prod_m_ifd_2_cnt : 8;
  uint64_t hp_dma_0_tok_prod_m_ifd_w_cnt : 8;
  uint64_t hp_dma_0_tok_prod_m_odr_cnt : 8;
  uint64_t hp_dma_0_tok_prod_d_ifd_0_cnt : 8;
  uint64_t hp_dma_0_tok_prod_d_ifd_1_cnt : 8;
  uint64_t hp_dma_0_tok_prod_d_odr_cnt : 8;
} csr_register_prod_cnt_hp_dma_0_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t hp_dma_0_tok_prod_hp_dma_1_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_hp_dma_0_1_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t hp_dma_1_tok_prod_m_ifd_0_cnt : 8;
  uint64_t hp_dma_1_tok_prod_m_ifd_1_cnt : 8;
  uint64_t hp_dma_1_tok_prod_m_ifd_2_cnt : 8;
  uint64_t hp_dma_1_tok_prod_m_ifd_w_cnt : 8;
  uint64_t hp_dma_1_tok_prod_m_odr_cnt : 8;
  uint64_t hp_dma_1_tok_prod_d_ifd_0_cnt : 8;
  uint64_t hp_dma_1_tok_prod_d_ifd_1_cnt : 8;
  uint64_t hp_dma_1_tok_prod_d_odr_cnt : 8;
} csr_register_prod_cnt_hp_dma_1_0_t;

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  uint64_t hp_dma_1_tok_prod_hp_dma_0_cnt : 8;
  uint64_t __reserved_1__ : 56;
} csr_register_prod_cnt_hp_dma_1_1_t;

// CSR
//--------------------------------------------------

typedef __attribute__((aligned(sizeof(uint64_t)))) struct {
  csr_register_swep_prod_0_t swep_prod_0;
  csr_register_swep_prod_1_t swep_prod_1;
  csr_register_swep_prod_2_t swep_prod_2;
  csr_register_swep_cons_0_t swep_cons_0;
  csr_register_swep_cons_1_t swep_cons_1;
  csr_register_swep_cons_2_t swep_cons_2;
  csr_register_irq_swep_prod_sat_status_t irq_swep_prod_sat_status;
  csr_register_irq_swep_prod_sat_en_t irq_swep_prod_sat_en;
  csr_register_irq_swep_cons_sat_status_t irq_swep_cons_sat_status;
  csr_register_irq_swep_cons_sat_en_t irq_swep_cons_sat_en;
  csr_register_irq_swep_cons_non_zero_status_t irq_swep_cons_non_zero_status;
  csr_register_irq_swep_cons_non_zero_en_t irq_swep_cons_non_zero_en;
  csr_register_irq_gen_sat_prod_status_0_t irq_gen_sat_prod_status_0;
  csr_register_irq_gen_sat_prod_status_1_t irq_gen_sat_prod_status_1;
  csr_register_irq_gen_sat_prod_en_0_t irq_gen_sat_prod_en_0;
  csr_register_irq_gen_sat_prod_en_1_t irq_gen_sat_prod_en_1;
  csr_register_prod_cnt_m_ifd_0_0_t prod_cnt_m_ifd_0_0;
  csr_register_prod_cnt_m_ifd_0_1_t prod_cnt_m_ifd_0_1;
  csr_register_prod_cnt_m_ifd_1_0_t prod_cnt_m_ifd_1_0;
  csr_register_prod_cnt_m_ifd_1_1_t prod_cnt_m_ifd_1_1;
  csr_register_prod_cnt_m_ifd_2_0_t prod_cnt_m_ifd_2_0;
  csr_register_prod_cnt_m_ifd_2_1_t prod_cnt_m_ifd_2_1;
  csr_register_prod_cnt_m_ifd_w_0_t prod_cnt_m_ifd_w_0;
  csr_register_prod_cnt_m_ifd_w_1_t prod_cnt_m_ifd_w_1;
  csr_register_prod_cnt_m_odr_0_t prod_cnt_m_odr_0;
  csr_register_prod_cnt_m_odr_1_t prod_cnt_m_odr_1;
  csr_register_prod_cnt_d_ifd_0_0_t prod_cnt_d_ifd_0_0;
  csr_register_prod_cnt_d_ifd_0_1_t prod_cnt_d_ifd_0_1;
  csr_register_prod_cnt_d_ifd_1_0_t prod_cnt_d_ifd_1_0;
  csr_register_prod_cnt_d_ifd_1_1_t prod_cnt_d_ifd_1_1;
  csr_register_prod_cnt_d_odr_0_t prod_cnt_d_odr_0;
  csr_register_prod_cnt_d_odr_1_t prod_cnt_d_odr_1;
  csr_register_prod_cnt_m_mvmexe_t prod_cnt_m_mvmexe;
  csr_register_prod_cnt_m_mvmprg_t prod_cnt_m_mvmprg;
  csr_register_prod_cnt_hp_dma_0_0_t prod_cnt_hp_dma_0_0;
  csr_register_prod_cnt_hp_dma_0_1_t prod_cnt_hp_dma_0_1;
  csr_register_prod_cnt_hp_dma_1_0_t prod_cnt_hp_dma_1_0;
  csr_register_prod_cnt_hp_dma_1_1_t prod_cnt_hp_dma_1_1;
} csr_t;

//--------------------------------------------------
// Other
//--------------------------------------------------

typedef __attribute__((aligned(sizeof(uint64_t)))) union {
  uint64_t words[REGISTER_ROWS];
  uint8_t bytes[REGISTER_ROWS][sizeof(uint64_t)];
  // NOTE(schmuck): these are not actually used, but are here for completeness
  struct {
    csr_register_swep_prod_0_t swep_prod_0;
    csr_register_swep_prod_1_t swep_prod_1;
  } produce_tokens;
  struct {
    csr_register_swep_cons_0_t swep_cons_0;
    csr_register_swep_cons_1_t swep_cons_1;
  } consume_tokens;
} token_access_t;

//==================================================
// DATA
//==================================================

static const uint8_t register_index_map[MODULE_COUNT] = {
  [MODULE_ID_D_DPU] = 1,
  [MODULE_ID_D_DWPU] = 1,
  [MODULE_ID_D_IAU] = 1,
  [MODULE_ID_D_IFD_0] = 0,
  [MODULE_ID_D_IFD_1] = 0,
  [MODULE_ID_D_ODR] = 0,
  [MODULE_ID_HP_DMA_0] = 1,
  [MODULE_ID_HP_DMA_1] = 2,
  [MODULE_ID_M_DPU] = 1,
  [MODULE_ID_M_IAU] = 1,
  [MODULE_ID_M_IFD_0] = 0,
  [MODULE_ID_M_IFD_1] = 0,
  [MODULE_ID_M_IFD_2] = 0,
  [MODULE_ID_M_IFD_W] = 0,
  [MODULE_ID_M_MVMEXE] = 1,
  [MODULE_ID_M_MVMPRG] = 1,
  [MODULE_ID_M_ODR] = 0,
};

static const uint8_t field_index_map[MODULE_COUNT] = {
  [MODULE_ID_D_DPU] = 6,
  [MODULE_ID_D_DWPU] = 4,
  [MODULE_ID_D_IAU] = 5,
  [MODULE_ID_D_IFD_0] = 5,
  [MODULE_ID_D_IFD_1] = 6,
  [MODULE_ID_D_ODR] = 7,
  [MODULE_ID_HP_DMA_0] = 7,
  [MODULE_ID_HP_DMA_1] = 0,
  [MODULE_ID_M_DPU] = 3,
  [MODULE_ID_M_IAU] = 2,
  [MODULE_ID_M_IFD_0] = 0,
  [MODULE_ID_M_IFD_1] = 1,
  [MODULE_ID_M_IFD_2] = 2,
  [MODULE_ID_M_IFD_W] = 3,
  [MODULE_ID_M_MVMEXE] = 0,
  [MODULE_ID_M_MVMPRG] = 1,
  [MODULE_ID_M_ODR] = 4,
};

static volatile csr_t* csr;
static volatile token_access_t* produce_token_csr;
static volatile token_access_t* consume_token_csr;

static uint16_t cached_consume_tokens[MODULE_COUNT] = {0};

//==================================================
// LOCAL FUNCTION DECLARATIONS
//==================================================

//==================================================
// LOCAL FUNCTION DEFINITIONS
//==================================================

//==================================================
// GLOBAL FUNCTION DEFINITIONS
//==================================================

token_manager_status_t token_manager_init(void) {
  static bool pointers_set = false;

  if (!pointers_set) {
    // Get the core's base address
    const uintptr_t core_base_addr = get_core_base_address();

    // Initialize base addresses by patching the offsets with the core's base address
    csr = (volatile csr_t*) ((uint8_t*) core_base_addr + ADDRESS_OFFSET_TOKEN_MANAGER_CSR);
    produce_token_csr = (token_access_t*) &csr->swep_prod_0;
    consume_token_csr = (token_access_t*) &csr->swep_cons_0;

    pointers_set = true;
  }

  return TOKEN_MANAGER_STATUS_OK;
}

token_manager_status_t token_manager_reset(void) {
  // Reset the consume tokens by accessing the CSRs
  // TODO(schmuck): is it dangerous to use memset (non-volatile) here?
  memset((void*) consume_token_csr, 0, sizeof(*consume_token_csr));

  // Reset the cached consume tokens
  memset((void*) cached_consume_tokens, 0, sizeof(cached_consume_tokens));

  return TOKEN_MANAGER_STATUS_OK;
}

token_manager_status_t token_manager_produce_tokens(module_id_t module_id, uint8_t tokens) {
  // NOTE(schmuck): UNTESTED!
  token_access_t token_buffer = {0};
  const uint8_t register_idx = register_index_map[module_id];
  const uint8_t field_idx = field_index_map[module_id];

  // Create the tokens at the correct index
  token_buffer.bytes[register_idx][field_idx] = tokens;

  // Write the entire array in a single transaction
  produce_token_csr->words[register_idx] = token_buffer.words[register_idx];

  return TOKEN_MANAGER_STATUS_OK;
}

token_manager_status_t token_manager_consume_tokens(module_id_t module_id, uint8_t tokens) {
  // NOTE(schmuck): UNTESTED!
  while (cached_consume_tokens[module_id] < tokens) {
    token_access_t token_buffer;
    const uint8_t register_idx = register_index_map[module_id];

    // Clear the buffer
    memset((void*) &token_buffer, 0, sizeof(token_buffer));

    // Read the entire row in a single transaction
    token_buffer.words[register_idx] = consume_token_csr->words[register_idx];

    // Distribute the tokens to the correct index
    // NOTE(schmuck): this is not optimal, as also the unused tokens are copied
    for (module_id_t i = 0; i < MODULE_COUNT; i++) {
      const uint8_t field_idx = field_index_map[i];
      cached_consume_tokens[i] += token_buffer.bytes[register_idx][field_idx];
    }
  }

  // Consume the tokens
  cached_consume_tokens[module_id] -= tokens;

  return TOKEN_MANAGER_STATUS_OK;
}

token_manager_status_t token_manager_produce_multiple_tokens(const uint8_t tokens[MODULE_COUNT]) {
// NOTE(schmuck): UNTESTED!
  token_access_t token_buffer = {0};

  // Create the tokens at the correct index
  for (module_id_t i = 0; i < MODULE_COUNT; i++) {
    if (tokens[i] == 0) continue;

    LOG_INFO("Producing %d tokens for module %s", tokens[i], module_get_name(i));

    const uint8_t register_idx = register_index_map[i];
    const uint8_t field_idx = field_index_map[i];
    token_buffer.bytes[register_idx][field_idx] = tokens[i];
  }

  // Write the entire array in a single transaction
  *produce_token_csr = token_buffer;

  return TOKEN_MANAGER_STATUS_OK;
}

token_manager_status_t token_manager_consume_multiple_tokens(const uint8_t tokens[MODULE_COUNT]) {
  token_access_t token_buffer;

  while (true) {
    // Read the entire consume token array in a single transaction
    token_buffer = *consume_token_csr;

    // Distribute the tokens to the correct index
    for (module_id_t i = 0; i < MODULE_COUNT; i++) {
      const uint8_t register_idx = register_index_map[i];
      const uint8_t field_idx = field_index_map[i];
      cached_consume_tokens[i] += token_buffer.bytes[register_idx][field_idx];
    }

    // Check if all tokens are consumed
    bool all_tokens_produced = true;
    for (module_id_t i = 0; i < MODULE_COUNT; i++) {
      if (!(cached_consume_tokens[i] >= tokens[i])) {
        all_tokens_produced = false;
        break;
      }
    }

    if (all_tokens_produced) {
      break;
    }

    // Clear the buffer
    memset((void*) &token_buffer, 0, sizeof(token_buffer));
  }

  // Consume the tokens
  for (module_id_t i = 0; i < MODULE_COUNT; i++) {
    cached_consume_tokens[i] -= tokens[i];
  }

  return TOKEN_MANAGER_STATUS_OK;
}
